/**
 * İNGİLİZCE ÇEKİRDEK UZMANLIK BANKASI
 *
 * Eski sürümdeki 12 kayıt → 32 kayda çıkarıldı; her kaydın içeriği
 * ortalama iki katına genişletildi. Açıklama dili Türkçedir çünkü
 * hedef kitle Türkçe anadilli öğrencidir.
 */

import type { CoreKnowledgeEntry } from './ruCore';

export const EN_CORE_KNOWLEDGE: CoreKnowledgeEntry[] = [
  {
    id: 'alphabet-phonetics', title: 'İngilizce ses sistemi ve okuma kuralları',
    keywords: ['alfabe', 'harf', 'okunuş', 'telaffuz', 'ses', 'th', 'magic e', 'sessiz harf', 'schwa', 'fonetik'],
    content: 'İngilizce 26 harflidir ama yaklaşık 44 sesi vardır: harf ≠ ses. Bu uyumsuzluk Türkçeden gelen öğrenciyi en çok zorlayan şeydir, çünkü Türkçe neredeyse birebir okunan bir dildir. TH iki ayrı sestir: sedasız θ (think, three, bath) ve sedalı ð (this, that, mother); Türk öğrenci ikisini de "t/d" veya "s/z" yapma eğilimindedir. KAPALI HECE: a→[æ] (cat→ket), o→[ɒ] (hot→hat), u→[ʌ] (cup→kap), i→[ɪ] (sit→sit). MAGIC E: sondaki sessiz "e" önceki ünlüyü kendi harf adıyla okutur — hat→hate (heyt), bit→bite (bayt), not→note (nout), cut→cute (kyut). SESSİZ HARFLER: kn- (know→nou), wr- (write→rayt), -mb (climb→klaym), -gh (light→layt), ps- (psychology), -t (listen, castle). SCHWA [ə] İngilizcenin en sık sesidir ve vurgusuz her hecede çıkabilir: about [əˈbaʊt], teacher [ˈtiːtʃə]. VURGU anlam değiştirir: ˈrecord (isim, kayıt) ↔ reˈcord (fiil, kaydetmek); ˈpresent (hediye) ↔ preˈsent (sunmak). Türk öğrenci tuzağı: her harfi okumak ("komfortable" ✗ → comfortable [ˈkʌmftəbl]).',
  },
  {
    id: 'tense-system', title: 'Zaman sistemi: 3 zaman × 4 görünüş',
    keywords: ['zaman', 'zamanlar', 'tense', 'present', 'past', 'future', 'perfect', 'continuous', '12 zaman'],
    content: 'İngilizcede 12 zaman vardır ve hepsi bir ÇARPIM TABLOSUDUR: 3 zaman (present/past/future) × 4 görünüş (simple/continuous/perfect/perfect continuous). Bu mantığı kavrayan öğrenci 12 kalıbı ezberlemek zorunda kalmaz. GÖRÜNÜŞLERİN ANLAMI: Simple = genel gerçek, alışkanlık, bitmiş olay (I work). Continuous = o anda süren, geçici (I am working). Perfect = önce olmuş, SONUCU şimdi önemli (I have worked). Perfect Continuous = süreç + süre vurgusu (I have been working for two hours). KALIPLAR: V1 / be + V-ing / have + V3 / have been + V-ing — bu dört kalıp zaman değişince yardımcı fiili değiştirerek 12 biçime açılır. Past: worked / was working / had worked / had been working. Future: will work / will be working / will have worked / will have been working. ZAMAN SEÇME TESTİ: "Ne zaman oldu?" diye değil, "Konuşmacı neyi vurguluyor?" diye sor — İngilizcede zaman seçimi takvimle değil BAKIŞ AÇISIYLA yapılır. Türk öğrenci tuzağı: Türkçedeki "-yor" ekini hep Present Continuous sanmak — "Her gün çalışıyorum" → "I work every day" (continuous değil).',
  },
  {
    id: 'present-simple', title: 'Present Simple ve 3. tekil -s',
    keywords: ['present simple', 'şimdiki zaman', 'alışkanlık', 'third person', 's eki', 'geniş zaman'],
    content: 'Present Simple dört işte kullanılır: 1) ALIŞKANLIK — I work every day, She goes to the gym twice a week. 2) GENEL GERÇEK — Water boils at 100 degrees. 3) PROGRAM/TARİFE — The train leaves at 7. 4) DURUM FİİLLERİ — I know, I like, I want (bunlar continuous almaz). 3. TEKİL -s KURALI: he/she/it öznesiyle fiile -s eklenir ve bu kural İngilizcenin en çok unutulan kuralıdır. Yazım: normalde +s (works), -ch/-sh/-ss/-x/-o sonrası +es (watches, goes, misses), ünsüz+y → -ies (study→studies), ünlü+y → +s (play→plays). İSTİSNA: have→has, be→is, do→does. OLUMSUZ/SORU: do/does kullanılır ve ANA FİİL 1. HÂLE DÖNER — She doesn\'t work (doesn\'t works ✗), Does she work? (Does she works? ✗). Bu "yardımcı fiil -s\'i üstlenir" kuralıdır. SIKLIK ZARFLARI özne ile fiil arasına girer: I always work, She never goes — ama "be" fiilinden SONRA gelir: He is always late. Türk öğrenci tuzağı: -s ekini atlamak ve soruda çifte -s koymak.',
  },
  {
    id: 'present-continuous', title: 'Present Continuous — şu an ve geçici durumlar',
    keywords: ['continuous', 'ing', 'şu an', 'progressive', 'am is are', 'şimdi'],
    content: 'Present Continuous (be + V-ing) dört işte kullanılır: 1) TAM ŞU AN — I am studying right now. 2) GEÇİCİ DÖNEM — I am living in Ankara this year (kalıcı değil). 3) KESİNLEŞMİŞ GELECEK PLAN — I am meeting him tomorrow at 5. 4) ŞİKÂYET/ABARTMA — He is always losing his keys (always ile birlikte sinirlilik bildirir). YAZIM KURALLARI: sondaki sessiz -e düşer (make→making), tek heceli CVC yapıda son ünsüz ikilenir (sit→sitting, run→running), -ie → -ying (lie→lying), -y korunur (study→studying). DURUM FİİLLERİ (stative verbs) normalde continuous almaz: know, believe, understand, want, need, like, love, hate, belong, seem, contain, own. "I am knowing" ✗. İSTİSNA: bazı fiiller anlam değiştirerek continuous alabilir — I think it\'s good (fikir) ↔ I am thinking about it (süreç); I have a car (sahiplik) ↔ I am having lunch (yemek yemek); It tastes good ↔ The chef is tasting the soup. Türk öğrenci tuzağı: Türkçedeki "-yor" eki yüzünden alışkanlıkları da continuous yapmak — "I am working every day" ✗ → "I work every day" ✓.',
  },
  {
    id: 'present-perfect', title: 'Present Perfect — bitmiş ama etkisi süren',
    keywords: ['present perfect', 'have has', 'v3', 'just', 'already', 'yet', 'since', 'for', 'ever never'],
    content: 'Present Perfect (have/has + V3) İngilizcenin en çok karıştırılan zamanıdır çünkü Türkçede doğrudan karşılığı yoktur. TEMEL FİKİR: Olay geçmişte oldu ama KONUŞMA ANIYLA bağı var — ya sonucu sürüyor, ya zaman dilimi bitmedi, ya da ne zaman olduğu önemsiz. DÖRT KULLANIM: 1) SONUÇ ŞİMDİ — I have lost my keys (hâlâ bulamadım). 2) DENEYİM — I have been to Paris (hayatım boyunca, tarih önemsiz). 3) BİTMEMİŞ ZAMAN DİLİMİ — I have worked a lot today (bugün hâlâ sürüyor). 4) SÜREN DURUM — I have lived here for 10 years (hâlâ yaşıyorum). SİNYAL KELİMELERİ: just (az önce), already (çoktan), yet (henüz — olumsuz/soru), ever/never, so far, recently, lately, since (başlangıç noktası: since 2020), for (süre: for 3 years). PAST SIMPLE İLE FARK: Belirli geçmiş zaman ifadesi varsa (yesterday, last week, in 2010, ago, when I was young) MUTLAKA Past Simple gelir — "I have seen him yesterday" ✗ → "I saw him yesterday" ✓. BEEN / GONE farkı: He has been to London (gitti ve döndü) ↔ He has gone to London (gitti, hâlâ orada). Türk öğrenci tuzağı: Türkçe "-mış" ekini otomatik Present Perfect sanmak.',
  },
  {
    id: 'past-tenses', title: 'Past Simple ve Past Continuous',
    keywords: ['geçmiş zaman', 'past simple', 'ed', 'düzensiz fiil', 'was were', 'past continuous', 'while when'],
    content: 'PAST SIMPLE bitmiş ve zamanı belli geçmiş olaylar içindir: I worked yesterday, She went home. Düzenli fiiller +ed alır (work→worked); yazım: -e sonrası +d (like→liked), ünsüz+y → -ied (study→studied), CVC yapıda ikileme (stop→stopped). OKUNUŞ: -ed üç farklı okunur — /t/ sedasız sonrası (worked, watched), /d/ sedalı sonrası (played, lived), /ɪd/ sadece -t/-d sonrası (wanted, needed). DÜZENSİZ FİİLLER ezberlenir: go-went-gone, see-saw-seen, take-took-taken, come-came-come, get-got-got(ten), make-made-made, write-wrote-written. OLUMSUZ/SORU: didn\'t + V1, Did + özne + V1 — "didn\'t went" ✗ → "didn\'t go" ✓ (did zaten geçmişi taşır). PAST CONTINUOUS (was/were + V-ing) arka plan ve kesilen eylem içindir: I was sleeping when you called. Klasik ikili: WHILE + continuous (While I was reading…), WHEN + simple (…when the phone rang). İki uzun eylem paralelse ikisi de continuous: While she was cooking, I was cleaning. USED TO geçmiş alışkanlık bildirir ve artık yapılmadığını ima eder: I used to smoke (eskiden içerdim, artık içmiyorum). Türk öğrenci tuzağı: düzensiz fiilin 2. hâli yerine 3. hâlini kullanmak — "I have went" ✗ → "I have gone" ✓.',
  },
  {
    id: 'past-perfect', title: 'Past Perfect — geçmişin geçmişi',
    keywords: ['past perfect', 'had', 'geçmişin geçmişi', 'before after', 'by the time'],
    content: 'Past Perfect (had + V3) geçmişteki iki olaydan ÖNCE olanı işaretler. Mantık: zaman çizgisinde iki nokta varsa, daha eski olan "had + V3" olur. Örnek: When I arrived, the train had already left (ben varmadan önce tren gitmişti). Tek bir geçmiş olay varsa Past Perfect GEREKMEZ — "I had gone to school yesterday" ✗ (sadece "I went"). SİNYALLER: before, after, by the time, already, just, never…before, when. "After I had finished, I went home" — ama sıralama zaten belliyse Past Simple de kabul edilir: "After I finished, I went home". PAST PERFECT CONTINUOUS (had been + V-ing) geçmişteki bir noktaya kadar SÜREN eylemi verir: I had been waiting for an hour when she finally came. DOLAYLI ANLATIMDA zaman bir basamak geri gider: "I saw him" → He said he had seen him. ÜÇÜNCÜ TİP KOŞUL cümlesinde de kullanılır: If I had known, I would have come (bilseydim gelirdim — geçmişe pişmanlık). Türk öğrenci tuzağı: Türkçede "-mıştı" eki olduğu için her geçmişte Past Perfect kullanmak; oysa İngilizcede yalnız SIRALAMA belirsizse gerekir.',
  },
  {
    id: 'future-forms', title: 'Gelecek: will, going to, Present Continuous',
    keywords: ['gelecek', 'will', 'going to', 'future', 'plan', 'tahmin', 'shall'],
    content: 'İngilizcede gelecek için tek bir zaman yoktur; hangi biçimi seçeceğin KONUŞMA ANINDAKİ NİYETİNE bağlıdır. WILL: 1) anlık karar (The phone is ringing — I\'ll get it!), 2) tahmin/öngörü (I think it will rain), 3) söz verme (I will help you), 4) teklif/rica (Will you help me?). BE GOING TO: 1) önceden yapılmış plan (We are going to move next month), 2) KANITA dayalı tahmin (Look at those clouds — it\'s going to rain). Will ile going to farkı tahminde ortaya çıkar: "I think it will rain" (sezgi) ↔ "It\'s going to rain" (bulutları görüyorum). PRESENT CONTINUOUS: kesinleşmiş, ayarlanmış randevu — I am meeting the doctor at 3 tomorrow. PRESENT SIMPLE: tarife/program — The flight departs at 7:30. FUTURE CONTINUOUS (will be + V-ing): gelecekte bir anda sürüyor olacak — This time tomorrow I will be flying. FUTURE PERFECT (will have + V3): gelecekteki bir ana kadar bitmiş olacak — By 2030 I will have finished. ZAMAN BAĞLACINDAN SONRA GELECEK KULLANILMAZ: "When I will arrive" ✗ → "When I arrive, I will call you" ✓ (when, if, as soon as, until, before, after sonrası present). Türk öğrenci tuzağı: tam da bu son kural — "if I will come" ✗.',
  },
  {
    id: 'modals', title: 'Kip fiilleri: can, must, should, might',
    keywords: ['modal', 'kip', 'can', 'must', 'should', 'might', 'izin', 'zorunluluk', 'could would'],
    content: 'Kip fiilleri (modals) üç kuralla çalışır: 1) ardından YALIN mastar gelir (to yok): She can swim. 2) 3. tekilde -s ALMAZ: He can (cans ✗). 3) Olumsuz/soru için do/does kullanılmaz: He can\'t, Can he? ANLAM HARİTASI: can yetenek/izin/olasılık (I can swim, Can I go?), could geçmiş yetenek + kibar rica (Could you help me?), may izin (resmî) + olasılık, might düşük olasılık (It might rain), must güçlü zorunluluk (iç kaynaklı) + kesin çıkarım (He must be tired), have to dış zorunluluk (I have to work — patron öyle istiyor), should/ought to tavsiye, had better güçlü tavsiye/uyarı, would kibar istek + hayalî durum, shall teklif (Shall we go?). OLUMSUZ TUZAĞI: mustn\'t = YASAK (You mustn\'t smoke), don\'t have to = GEREK YOK (You don\'t have to come) — bu ikisi zıt anlamlıdır ve en sık karıştırılan çifttir. ÇIKARIM MERDİVENİ: must be (kesin) > may/might/could be (olabilir) > can\'t be (imkânsız). GEÇMİŞ BİÇİMLER: must have done (yapmış olmalı), should have done (yapmalıydı ama yapmadı), could have done (yapabilirdi). Türk öğrenci tuzağı: "I must to go" ✗ → "I must go" ✓.',
  },
  {
    id: 'conditionals', title: 'Koşul cümleleri (if clauses) — 0, 1, 2, 3',
    keywords: ['if', 'koşul', 'conditional', 'şart cümlesi', 'would', 'unless', 'wish'],
    content: 'Dört temel koşul tipi vardır ve her biri farklı bir GERÇEKLİK derecesini anlatır. TYPE 0 (genel gerçek): If + present, present → If you heat water, it boils. TYPE 1 (gerçek olasılık, gelecek): If + present, will + V1 → If it rains, I will stay home. DİKKAT: if\'ten sonra "will" GELMEZ. TYPE 2 (şu anki hayalî durum): If + past, would + V1 → If I had money, I would travel (ama param yok). "If I were you" kalıbı sabittir (was değil were). TYPE 3 (geçmişe pişmanlık): If + had + V3, would have + V3 → If I had studied, I would have passed (çalışmadım, geçemedim). KARIŞIK TİP: geçmişteki koşul + şimdiki sonuç → If I had studied medicine, I would be a doctor now. UNLESS = if not: Unless you hurry, you will miss the train. DİĞER BAĞLAÇLAR: as long as, provided that, in case, even if. WISH YAPISI koşulun kardeşidir: I wish I had money (şimdiki pişmanlık, past kullanılır), I wish I had studied (geçmiş pişmanlık, past perfect), I wish he would stop (başkasının davranışından şikâyet). Türk öğrenci tuzağı: "If I will have time" ✗ → "If I have time" ✓.',
  },
  {
    id: 'passive-voice', title: 'Edilgen çatı (passive voice)',
    keywords: ['passive', 'edilgen', 'pasif', 'be v3', 'by', 'edilgen yapı'],
    content: 'Edilgen çatı, EYLEMİ YAPAN değil EYLEMDEN ETKİLENEN önemliyse kullanılır. Formül: be (uygun zamanda) + V3. Present: The car is washed. Past: The car was washed. Present Perfect: The car has been washed. Future: The car will be washed. Continuous: The car is being washed. Modal: The car must be washed. NE ZAMAN KULLANILIR: 1) Eylemi yapan bilinmiyorsa (My wallet was stolen), 2) önemsizse (The bridge was built in 1920), 3) açıkça söylenmek istenmiyorsa (Mistakes were made), 4) bilimsel/resmî üslupta (The sample was heated). BY ile eylemi yapan belirtilebilir ama cümlelerin yalnız %20\'sinde kullanılır: The book was written by Orwell. İKİ NESNELİ FİİLLER iki edilgen üretir: They gave me a book → I was given a book / A book was given to me (birincisi daha yaygın). GET-PASSIVE günlük dilde yaygındır: He got fired, I got invited. EDİLGEN OLAMAYANLAR: nesne almayan fiiller (happen, arrive, die, sleep) edilgen yapılamaz — "The accident was happened" ✗ → "The accident happened" ✓. Türk öğrenci tuzağı: Türkçedeki "-il/-ın" ekini her yere taşımak ve geçişsiz fiilleri edilgenleştirmek.',
  },
  {
    id: 'reported-speech', title: 'Dolaylı anlatım (reported speech)',
    keywords: ['reported speech', 'dolaylı anlatım', 'said told', 'aktarma', 'indirect'],
    content: 'Birinin sözünü aktarırken üç şey değişir: ZAMAN, ZAMİR ve ZAMAN/YER BELİRTEÇLERİ. ZAMAN BİR BASAMAK GERİ GİDER: present→past (I work → He said he worked), present continuous→past continuous, past simple→past perfect (I went → He said he had gone), present perfect→past perfect, will→would, can→could, may→might, must→had to. DEĞİŞMEYENLER: would, could, should, might, had better ve genel gerçekler (He said water boils at 100). BELİRTEÇLER: now→then, today→that day, tomorrow→the next day, yesterday→the day before, here→there, this→that, ago→before. SAY / TELL FARKI: say + söz (He said that…), tell + KİŞİ + söz (He told me that…) — "He said me" ✗, "He told that" ✗. SORU AKTARIMI: Wh- sorularda soru sözcüğü kalır ama DÜZ CÜMLE dizilimi olur — He asked where I lived (where did I live ✗). Evet-hayır sorularında if/whether kullanılır: He asked if I was ready. EMİR AKTARIMI: tell/ask + kişi + to + V1 — He told me to wait, She asked me not to go. Türk öğrenci tuzağı: dolaylı soruda soru dizilimini korumak.',
  },
  {
    id: 'prepositions', title: 'Edatlar: in, on, at ve ötesi',
    keywords: ['edat', 'preposition', 'in', 'on', 'at', 'zaman', 'yer', 'in on at farkı'],
    content: 'ZAMAN MERDİVENİ geniyşten dara doğru daralır: IN (uzun süre: ay, yıl, mevsim, yüzyıl, günün bölümü) — in July, in 2025, in summer, in the morning. ON (gün ve tarih) — on Monday, on 5th May, on Christmas Day, on Monday morning (gün belirtilirse on). AT (nokta anlar) — at 7 o\'clock, at noon, at night, at the weekend (BrE), at Christmas (dönem). YER MERDİVENİ aynı mantıkla: IN (kapalı/sınırlı alan) — in the room, in Turkey, in a car. ON (yüzey veya hat) — on the table, on the wall, on the bus, on the second floor. AT (nokta/kurum) — at the bus stop, at school, at work, at the door. HAREKET: to (yöne doğru — go to school), into (içine), onto (üstüne), from (…-den), toward(s) (…-e doğru). "Home" istisnadır: go home (to yok). SABİT EŞDİZİMLER sözlükten öğrenilir ve mantığı yoktur: listen TO, depend ON, interested IN, good AT, afraid OF, married TO, arrive AT/IN (arrive to ✗), look FOR (aramak) / look AFTER (bakmak) / look AT (bakmak) — üç farklı anlam. Türk öğrenci tuzağı: "in Monday" ✗ → "on Monday" ✓; "I am in the bus" yerine "on the bus" ✓.',
  },
  {
    id: 'articles', title: 'Artikeller: a, an, the ve sıfır artikel',
    keywords: ['artikel', 'article', 'a an the', 'belirteç', 'tanımlık', 'the kullanımı'],
    content: 'Türkçede artikel olmadığı için bu konu en zor ve en çok hata yapılan alandır. A/AN (belirsiz): ilk kez bahsedilen, HANGİSİ olduğu önemsiz TEKİL SAYILABİLİR isimle — I saw a dog. Seçim sese göredir, harfe göre değil: a university (yu- sesi), an hour (sessiz h), an MP (em- sesi). THE (belirli): 1) daha önce bahsedilmiş (I saw a dog. The dog was big), 2) bağlamdan belli (Close the door), 3) tek olan şeyler (the sun, the moon, the Internet), 4) üstünlük ve sıra (the best, the first), 5) nehir/deniz/okyanus/sıradağ/çoğul ülke adları (the Nile, the Alps, the USA), 6) müzik aletleri (play the piano). SIFIR ARTİKEL: 1) genel anlamda çoğul (Dogs are loyal), 2) sayılamayan genel (Water is life), 3) ülke/şehir/kişi adları (Turkey, Ankara, Ahmet), 4) öğün/ulaşım/kurum kalıpları (have breakfast, by car, go to school/bed/work — kurumun işlevi kastediliyorsa). KURUM TUZAĞI: go to school (öğrenci olarak) ↔ go to the school (binaya gitmek). Türk öğrenci tuzağı: the\'yi hiç kullanmamak ya da her ismin önüne koymak; kural "önce sayılabilir mi + tekil mi + belirli mi" sırasıyla sorulur.',
  },
  {
    id: 'countable-uncountable', title: 'Sayılabilen / sayılamayan isimler',
    keywords: ['sayılabilir', 'uncountable', 'countable', 'much many', 'information', 'advice'],
    content: 'İngilizcede bazı isimler SAYILAMAZ ve çoğul -s almaz; bu Türkçeden farklıdır. En sık sayılamayanlar: information, advice, furniture, luggage, baggage, equipment, software, homework, knowledge, news (tekil!), money, bread, water, rice, sugar, music, traffic, weather, work, research, progress, accommodation. "Informations" ✗, "advices" ✗, "furnitures" ✗. MİKTAR BELİRTME: a piece of advice, a bit of information, an item of furniture, a slice of bread, a glass of water, two kilos of rice. NİCELEYİCİLER: many/few/a few + sayılabilir çoğul (many books, few friends); much/little/a little + sayılamayan (much time, little money); a lot of / lots of / some / any ikisiyle de kullanılır. A FEW ile FEW farkı: a few = birkaç tane var (olumlu), few = neredeyse hiç yok (olumsuz); aynı şekilde a little ↔ little. ÇİFT KULLANIM: bazı isimler anlam değiştirerek iki gruba da girer — hair (saç, sayılamaz) / a hair (tek tel), paper (kâğıt) / a paper (gazete, makale), glass (cam) / a glass (bardak), experience (deneyim) / an experience (bir olay), time (zaman) / three times (kez). Türk öğrenci tuzağı: "I have many informations" ✗ → "I have a lot of information" ✓.',
  },
  {
    id: 'phrasal-verbs', title: 'Phrasal verbs — fiil + edat öbekleri',
    keywords: ['phrasal verb', 'deyim', 'öbek fiil', 'get up', 'look after', 'put off'],
    content: 'Phrasal verb = fiil + zarf/edat ve anlamı çoğu zaman parçalarından ÇIKARILAMAZ. En sık 30 tanesi günlük İngilizcenin belkemiğidir: get up (kalkmak), get on (binmek/anlaşmak), get off (inmek), get over (atlatmak), give up (vazgeçmek), look for (aramak), look after (bakmak), look forward to (sabırsızlanmak — sonrası V-ing!), put on (giymek), put off (ertelemek), put up with (katlanmak), turn on/off (açmak/kapatmak), turn up (ortaya çıkmak), take off (kalkmak-uçak/çıkarmak-giysi), take after (benzemek), come across (rastlamak), run into (tesadüfen karşılaşmak), run out of (bitmek), figure out (çözmek), find out (öğrenmek), bring up (yetiştirmek/konu açmak), carry on (devam etmek), break down (bozulmak), check in/out, call off (iptal etmek), set up (kurmak), work out (spor yapmak/çözülmek), go on (devam etmek), make up (uydurmak/barışmak). AYRILABİLİRLİK: bazıları nesneyi ortaya alabilir (turn the light on / turn on the light) ama ZAMİR daima ortadadır: turn it on ✓, turn on it ✗. Ayrılamayanlar: look after him ✓, look him after ✗. Türk öğrenci tuzağı: phrasal verb yerine hep Latince kökenli resmî fiil kullanmak (postpone yerine put off daha doğaldır).',
  },
  {
    id: 'collocations-en', title: 'Eşdizimler — hangi kelime hangisiyle gider',
    keywords: ['eşdizim', 'collocation', 'make do', 'heavy rain', 'kalıp', 'doğal kullanım'],
    content: 'Dilbilgisi doğru ama kulağa yanlış gelen cümlelerin sebebi eşdizimdir. MAKE / DO ayrımı en kritik olanıdır. MAKE (üretmek, ortaya çıkarmak): make a mistake, make a decision, make progress, make friends, make money, make noise, make an effort, make a mess, make sense, make a phone call. DO (yapmak, gerçekleştirmek): do homework, do the dishes, do business, do research, do a favour, do exercise, do your best, do damage. GÜÇLÜ SIFATLAR: heavy rain (strong rain ✗), strong coffee (powerful coffee ✗), fast food, quick meal, high speed, deep sleep, bright future, close friend, serious problem. FİİL+İSİM: pay attention, take a photo (make a photo ✗), take a shower, catch a cold, keep a promise, break a promise, meet a deadline, reach an agreement, raise a question, draw a conclusion, save time, waste time, spend money. İSİM+EDAT: reason for, solution to, answer to, increase in, interest in, effect on, difference between. Eşdizim öğrenmenin tek yolu KALIP HÂLİNDE ezberlemektir; tek tek kelime ezberi burada işe yaramaz. Türk öğrenci tuzağı: Türkçe "yapmak" fiilini hep "do" diye çevirmek — "do a mistake" ✗ → "make a mistake" ✓.',
  },
  {
    id: 'word-order', title: 'Söz dizimi: SVO, soru ve sıfat sırası',
    keywords: ['söz dizimi', 'word order', 'svo', 'soru', 'sıfat', 'düzen', 'cümle kurma'],
    content: 'İngilizce KATI bir SVO dilidir ve bu Türkçenin SOV yapısının tam tersidir. Sıra anlamı belirler: The dog bites the man ≠ The man bites the dog. Türkçede ekler görevi gösterdiği için sıra serbesttir; İngilizcede ek yoktur, SIRA görevi gösterir. Bu yüzden Türkçe cümleyi çevirirken önce özne-fiil-nesne iskeletini kurmak gerekir. SORU DİZİLİMİ: (Wh-) + yardımcı + özne + ana fiil → Where do you live? What is she doing? Yardımcı fiil yoksa do/does/did eklenir. DOLAYLI SORUDA ters döner: I don\'t know where he lives (where does he live ✗). SIFAT SIRASI sabit bir hiyerarşi izler: görüş → boyut → yaş → şekil → renk → köken → malzeme → amaç + isim. Örnek: a beautiful big old round red Italian wooden dining table. Pratikte ikiden fazla sıfat nadiren kullanılır. ZARF YERLEŞİMİ: sıklık zarfı özne-fiil arasında (I always work) ama be\'den sonra (He is always late); yer ve zaman zarfı sonda ve sıra "yer + zaman" olur: I went to school yesterday (yesterday to school ✗). ÖZNE ASLA DÜŞMEZ: Türkçede "Geliyorum" denir, İngilizcede "I am coming" — özne zorunludur, hava durumunda bile: It is raining. Türk öğrenci tuzağı: özneyi atlamak ve fiili sona koymak.',
  },
  {
    id: 'relative-clauses', title: 'Sıfat cümlecikleri (relative clauses)',
    keywords: ['relative clause', 'who which that', 'sıfat cümleciği', 'ki', 'whose where'],
    content: 'Relative clause bir ismi tanımlayan yan cümledir ve Türkçedeki "-an/-en, …ki" yapısının karşılığıdır. ZAMİR SEÇİMİ: who (insan), which (nesne/hayvan), that (ikisi de, tanımlayıcı cümlede), whose (aitlik — insan/nesne), where (yer), when (zaman), why (sebep). TANIMLAYICI (defining) cümle ismin HANGİSİ olduğunu söyler, virgülsüzdür ve çıkarılırsa anlam bozulur: The man who lives next door is a doctor. TANIMLAYICI OLMAYAN (non-defining) ek bilgi verir, VİRGÜLLE ayrılır ve "that" KULLANILAMAZ: My father, who is 60, still works. ZAMİR DÜŞÜRME: Tanımlayıcı cümlede zamir NESNE görevindeyse atılabilir — The book (that) I read was great ✓. Özne görevindeyse atılamaz: The man who lives here ✓ (who atılamaz). EDAT YERLEŞİMİ: günlük dilde sona (the man who I talked to), resmî dilde başa (the man to whom I talked). WHOSE: The student whose book I borrowed. Türk öğrenci tuzağı: 1) Türkçedeki "ki"yi "that" diye her yere koymak, 2) zamiri tekrarlamak — "The book that I read it" ✗ → "The book that I read" ✓.',
  },
  {
    id: 'gerund-infinitive', title: 'Gerund mu infinitive mi? (V-ing / to + V)',
    keywords: ['gerund', 'infinitive', 'ing', 'to v1', 'enjoy doing', 'want to do'],
    content: 'Bazı fiiller ardından V-ing, bazıları to + V1 ister; bu liste ezberlenir ama mantıksal ipuçları vardır. GERUND (V-ing) isteyenler — çoğu "deneyim/devam/bitiş" bildirir: enjoy, avoid, finish, keep, mind, suggest, practise, consider, admit, deny, imagine, risk, miss, quit, give up, can\'t help, look forward to, be used to, spend time. Örnek: I enjoy reading, I look forward to seeing you (to burada edattır, mastar değil!). INFINITIVE (to + V1) isteyenler — çoğu "niyet/gelecek" bildirir: want, need, decide, hope, plan, promise, agree, refuse, offer, learn, manage, afford, pretend, seem, expect. Örnek: I want to go, She decided to leave. İKİSİ DE OLANLAR ama ANLAM DEĞİŞENLER: stop doing (o işi bırakmak) ↔ stop to do (başka iş için durmak); remember doing (yaptığını hatırlamak) ↔ remember to do (yapmayı unutmamak); try doing (deneme olarak yapmak) ↔ try to do (yapmaya çalışmak); forget doing ↔ forget to do; regret doing (pişman olmak) ↔ regret to say (üzülerek bildirmek). ANLAM DEĞİŞMEYENLER: begin, start, continue, like, love, hate, prefer. EDATTAN SONRA DAİMA V-ING: good at swimming, interested in learning, instead of going. Türk öğrenci tuzağı: "I look forward to see you" ✗ → "to seeing" ✓.',
  },
  {
    id: 'false-friends', title: 'Türkçe öğrenci tuzakları (yalancı dostlar)',
    keywords: ['yalancı dost', 'false friend', 'sympathetic', 'actually', 'pretend', 'gym', 'karıştırılan'],
    content: 'Kulağa Türkçeye benzeyen ama anlamı farklı kelimeler: actually = ASLINDA (aktüel/güncel değil; güncel = current). sympathetic = ANLAYIŞLI, şefkatli (sempatik değil; sempatik = likeable, nice). sensible = MANTIKLI (hassas değil; hassas = sensitive). pretend = …-MIŞ GİBİ YAPMAK (iddia etmek değil; iddia etmek = claim). gym = SPOR SALONU (jimnastik değil). eventually = SONUNDA (eventüel/olası değil). realize = FARK ETMEK (gerçekleştirmek değil; gerçekleştirmek = carry out). control = KONTROL ETMEK/YÖNETMEK (denetlemek anlamında check kullanılır: "I will control it" ✗ → "I will check it" ✓). fabric = KUMAŞ (fabrika değil; fabrika = factory). magazine = DERGİ (mağaza değil; mağaza = shop/store). smoking = SİGARA İÇME (smokin değil; smokin = tuxedo). serious = CİDDİ ✓ ama "serial" = dizi. lecture = DERS ANLATIMI (lektür/okuma değil). library = KÜTÜPHANE (kitapçı değil; kitapçı = bookstore). apology = ÖZÜR (apoloji/savunma değil). familiar = TANIDIK (ailevi değil). Türk öğrenci tuzağı: "I will control the document" diyerek "belgeyi kontrol edeceğim" demeye çalışmak — doğrusu "I will check the document".',
  },
  {
    id: 'adjective-adverb', title: 'Sıfat / zarf ayrımı ve karşılaştırma',
    keywords: ['sıfat', 'zarf', 'adjective', 'adverb', 'ly', 'comparative', 'superlative', 'karşılaştırma'],
    content: 'SIFAT ismi niteler (a quick car), ZARF fiili niteler (He drives quickly). Çoğu zarf sıfata -ly eklenerek yapılır: quick→quickly, careful→carefully, happy→happily (y→i), simple→simply (-le→-ly). DÜZENSİZ: good→well, fast→fast, hard→hard, late→late, early→early. TUZAK ÇİFTLER: hard (zor/sıkı çalışmak) ↔ hardly (neredeyse hiç); late (geç) ↔ lately (son zamanlarda); near (yakın) ↔ nearly (neredeyse). DUYU FİİLLERİ sıfat alır, zarf değil: It smells good (well ✗), She looks happy, It sounds great, I feel bad. KARŞILAŞTIRMA: tek heceli +er/+est (big→bigger→the biggest, yazımda ikileme), iki heceli -y ile biten → -ier/-iest (happy→happier), diğerleri more/most (more beautiful, the most beautiful). DÜZENSİZ: good→better→best, bad→worse→worst, far→further/farther→furthest, little→less→least, many/much→more→most. YAPILAR: as…as (eşitlik: as tall as me), not as…as, than (karşılaştırma: taller than me), the…the (the more you practise, the better you get), twice as…as. Türk öğrenci tuzağı: 1) çifte karşılaştırma "more better" ✗ → "better" ✓; 2) "than" yerine "from" kullanmak — "bigger from" ✗ → "bigger than" ✓.',
  },
  {
    id: 'question-tags', title: 'Soru ekleri (question tags) ve kısa cevaplar',
    keywords: ['question tag', 'soru eki', 'isn\'t it', 'değil mi', 'kısa cevap'],
    content: 'Question tag, Türkçedeki "değil mi?" ekinin karşılığıdır ve cümlenin sonuna eklenir. KURAL: cümle olumluysa tag OLUMSUZ, cümle olumsuzsa tag OLUMLU olur. You are tired, aren\'t you? / You aren\'t tired, are you? Tag\'de cümlenin YARDIMCI FİİLİ tekrarlanır; yardımcı yoksa do/does/did kullanılır: She works here, doesn\'t she? / He went home, didn\'t he? ÖZEL DURUMLAR: I am → aren\'t I? (amn\'t I ✗); Let\'s go → shall we?; emir cümlesi → will you? (Close the door, will you?); There is → isn\'t there?; nobody/somebody özne ise tag\'de they kullanılır (Somebody called, didn\'t they?); olumsuz anlamlı kelimeler (never, hardly, nothing, nobody) cümleyi olumsuz yapar → tag olumlu olur: He never comes, does he? KISA CEVAPLAR: Yes, I do / No, I don\'t — tam cümle tekrarlanmaz ve yardımcı fiil kullanılır. "Yes, I am" ✓, "Yes, I am tired" gereksiz uzundur. TONLAMA fark yaratır: ses alçalırsa onay bekleniyordur, yükselirse gerçek sorudur. Türk öğrenci tuzağı: Türkçedeki tek biçimli "değil mi?" yüzünden tag\'i hep "isn\'t it?" yapmak — yardımcı fiil cümleye göre değişir.',
  },
  {
    id: 'there-it', title: 'There is/are ve "it" kullanımı',
    keywords: ['there is', 'there are', 'it is', 'var yok', 'dummy subject', 'boş özne'],
    content: 'Türkçedeki "var/yok" yapısı İngilizcede THERE IS / THERE ARE ile kurulur: There is a book on the table (masada bir kitap var), There are two books. Olumsuz: There isn\'t / There aren\'t. Soru: Is there…? / Are there…? Geçmiş: There was / There were. Gelecek: There will be. Perfect: There has been. Modal: There must be. UYUM kurala göre İLK isimle yapılır: There is a book and two pens (konuşma dilinde yaygın). IT ise "boş özne" (dummy subject) olarak kullanılır çünkü İngilizce cümle öznesiz olamaz: hava (It is raining), saat (It is 5 o\'clock), mesafe (It is 10 km to the city), tarih (It is Monday), genel durum (It is difficult to learn Russian). THERE / IT FARKI: there bir şeyin VARLIĞINI tanıtır, it ise zaten bilinen/genel bir duruma gönderme yapar. "There is a problem" (bir sorun var — yeni bilgi) ↔ "It is a problem" (bu bir sorun — zaten bahsedilen şey). IT KALIPLARI: It takes + süre (It takes an hour), It seems that…, It is said that…, It is worth doing. Türk öğrenci tuzağı: "In the table there is a book" yerine "There is a book on the table" doğru dizilimdir; ayrıca "Is have a book?" ✗ → "Is there a book?" ✓.',
  },
  {
    id: 'pronunciation-stress', title: 'Vurgu, ritim ve bağlanma (connected speech)',
    keywords: ['vurgu', 'stress', 'ritim', 'linking', 'connected speech', 'telaffuz', 'anlaşılır konuşma'],
    content: 'İngilizce VURGU ZAMANLI bir dildir: vurgulu heceler düzenli aralıklarla gelir, aradaki heceler sıkışır. Türkçe ise hece zamanlıdır (her hece eşit süre alır) — bu yüzden Türk konuşmacı "robot gibi" duyulur. KELİME VURGUSU anlamı değiştirebilir: ˈrecord (isim) / reˈcord (fiil), ˈpresent / preˈsent, ˈexport / exˈport. Genel eğilim: iki heceli isimlerde vurgu birinci, fiillerde ikinci hecededir. SONEK KURALLARI: -tion/-sion/-ic/-ical öncesindeki hece vurgulanır (eduˈcation, ecoˈnomic); -ity, -ety aynı şekilde (uniˈversity). CÜMLE VURGUSU içerik kelimelerine biner (isim, fiil, sıfat, zarf); yapı kelimeleri (artikel, edat, yardımcı fiil, zamir) zayıflar ve schwa\'ya düşer: "I can do it" → can [kən]. ZAYIF BİÇİMLER anlaşılmayı zorlaştırır: to [tə], of [əv], and [ən], for [fə], you [jə]. BAĞLANMA (linking): ünsüzle biten kelime ünlüyle başlayan kelimeye bağlanır — "an apple" [ənæpl], "pick it up" [pɪkɪtʌp]. YUTULMA: "next day" → [neksdeɪ], "want to" → [wɒnə], "going to" → [ɡənə]. Türk öğrenci tuzağı: her kelimeyi tek tek ve eşit vurguyla söylemek; akıcılık vurgu farkından doğar, hızdan değil.',
  },
  {
    id: 'common-mistakes-en', title: 'Türk öğrencilerin en sık 15 İngilizce hatası',
    keywords: ['hata', 'yanlış', 'sık hata', 'tuzak', 'mistake', 'en çok yapılan hata'],
    content: 'En sık 15 hata ve düzeltmeleri: 1) "I am agree" → "I agree" (agree bir fiildir). 2) "I have 20 years" → "I am 20 years old". 3) "He don\'t" → "He doesn\'t". 4) "I didn\'t went" → "I didn\'t go". 5) "informations/advices" → "information/advice" (sayılamaz). 6) "more better" → "better". 7) "Explain me" → "Explain to me". 8) "depends of" → "depends on". 9) "married with" → "married to". 10) "I am boring" → "I am bored" (-ing yapan, -ed hisseden: the film is boring, I am bored). 11) "in Monday" → "on Monday". 12) "I will come if I will have time" → "…if I have time". 13) "make a photo" → "take a photo". 14) "I am living in Ankara since 2010" → "I have been living in Ankara since 2010". 15) "Although… but…" → ikisinden biri kullanılır: "Although it was late, I went" ✓. BONUS: "actually" aslında demektir, güncel değil; "I am interesting" demek "ben ilginç bir insanım" olur, kastedilen "I am interested". Bu listeyi haftada bir okumak B1 seviyesindeki hataların çoğunu kapatır.',
  },
  {
    id: 'vocabulary-building', title: 'Kelime dağarcığını büyütme stratejisi',
    keywords: ['kelime', 'vocabulary', 'ezber', 'kelime öğrenme', 'word family', 'kök'],
    content: 'Kelime ezberlemenin en verimsiz yolu listedir; en verimlisi AİLE + BAĞLAM + ÜRETİM üçlüsüdür. KELİME AİLESİ: Bir kökü öğrenince türevlerini birlikte al — decide (fiil), decision (isim), decisive (sıfat), decisively (zarf). Bu, tek ezberle dört kelime kazandırır. ÖNEK/SONEK bilgisi tahmin gücü verir: un-/in-/im-/dis- olumsuzluk (unhappy, impossible, disagree), re- yeniden (rewrite), over-/under- aşırı/yetersiz (overwork, underestimate), -ful/-less (helpful/helpless), -able (readable), -ment/-ness/-tion isim yapar. BAĞLAM KURALI: Kelimeyi cümle içinde ezberle; "abandon" tek başına unutulur ama "They abandoned the car" hatırlanır. EŞ/ZIT ANLAM AĞI: Yeni kelimeyi bildiğin bir kelimeye bağla (huge ← big, tiny ← small). ÜRETİM TESTİ: Bir kelimeyi gerçekten biliyorsan onunla KENDİ cümleni kurabilirsin; kuramıyorsan henüz tanıma düzeyindesin. SIKLIK ÖNCELİĞİ: İngilizcenin en sık 2.000 kelimesi günlük metinlerin %80\'ini karşılar — önce onları bitir, sonra alan kelimelerine geç. ARALIKLI TEKRAR: 1-3-7-16-35 gün aralıklarıyla tekrar et; hata yapınca başa dön. Günde 10 yeni kelime + 30 tekrar, günde 50 yeni kelimeden kalıcıdır.',
  },
  {
    id: 'listening-strategy-en', title: 'Dinleme stratejisi — İngilizceyi nasıl duyarım?',
    keywords: ['dinleme', 'listening', 'anlama', 'aksan', 'hızlı konuşma', 'dinleme taktiği'],
    content: 'İngilizceyi anlamamanın üç sebebi ve çözümü: 1) BAĞLANMA (connected speech): Kelimeler konuşmada birleşir — "What do you want to do?" → [wɒdʒəwɒnədu]. Çözüm: tek tek kelime beklemeyi bırak, ÖBEK dinle. 2) ZAYIF BİÇİMLER: Yapı kelimeleri (to, of, and, for, can) vurgusuz kaldığında neredeyse kaybolur. Çözüm: içerik kelimelerine (isim, fiil, sıfat) odaklan — anlam onlarda taşınır. 3) AKSAN FARKI: Amerikan [ˈwɔːtər] ile İngiliz [ˈwɔːtə] farkı, r sesinin telaffuzu, "can\'t" okunuşu [kænt]/[kɑːnt]. Çözüm: önce TEK bir aksana alış, sonra diğerine geç. PRATİK YÖNTEM — ÜÇ TUR TEKNİĞİ: 1. tur altyazısız (genel konu), 2. tur altyazısız ama durdurarak (bilinmeyen 3 kelimeyi not et), 3. tur altyazılı (boşlukları doldur). Son olarak gölgeleme (shadowing): konuşmacıyla aynı anda, aynı tonlamayla tekrar et — bu hem dinlemeyi hem telaffuzu birlikte geliştirir. SÜRE: Her gün 10-15 dakika kesintisiz dinleme, haftada bir 2 saatten çok daha etkilidir. Zorluk seviyesi "%70 anlıyorum" bandında olmalı; %40 anlıyorsan materyal çok zordur.',
  },
  {
    id: 'speaking-strategy-en', title: 'Konuşma stratejisi — akıcılık nasıl kazanılır?',
    keywords: ['konuşma', 'speaking', 'akıcılık', 'fluency', 'pratik', 'konuşamıyorum'],
    content: 'Akıcılık kelime sayısı değil ERİŞİM HIZI meselesidir. Üç teknik: 1) KALIP KONUŞMA: "I was wondering if…", "Would it be possible to…", "What I mean is…", "To be honest…", "The thing is…" gibi 25 kalıp cümleyi sıfırdan kurma yükünü kaldırır. 2) DOLAMBAÇLI ANLATIM (circumlocution): Kelime aklına gelmiyorsa tarif et — "corkscrew" bilmiyorsan "the thing you open wine bottles with" de. Bu, anadili konuşanların da kullandığı bir beceridir ve konuşmayı durdurmaz. 3) ZAMAN KAZANMA İFADELERİ: "Well…", "Let me think…", "That\'s a good question…", "How can I put it…" — sessizliği doldurur ve cümle kurma süresi verir. TELAFFUZ ÖNCELİĞİ: Anlaşılırlığı en çok bozan üç şey — kelime vurgusunun yanlış yerde olması, th sesinin atlanması ve sonsesteki ünsüz kümelerinin düşmesi (asked → [æskt], tek hece). HATA FELSEFESİ: Akıcılık ve doğruluk ters orantılıdır; konuşurken AKICILIĞA, yazarken DOĞRULUĞA öncelik ver. İletişim kurulduysa cümle görevini yapmıştır. GÜNLÜK ALIŞTIRMA: Her gün 2 dakika kendi kendine, yüksek sesle, bir konu hakkında konuş ve kaydet; haftada bir kayıtları dinle — gelişimi görmek motivasyonu korur.',
  },
  {
    id: 'writing-strategy-en', title: 'Yazma stratejisi — paragraf ve e-posta',
    keywords: ['yazma', 'writing', 'essay', 'email', 'paragraf', 'kompozisyon', 'resmi yazı'],
    content: 'PARAGRAF YAPISI: 1) Topic sentence (ana fikir — ilk cümle), 2) Supporting sentences (destek, örnek, veri), 3) Concluding/linking sentence. Bir paragraf = bir fikir kuralı İngilizcede katıdır. BAĞLAYICILAR metni akıtır: ekleme (moreover, in addition, furthermore), karşıtlık (however, on the other hand, nevertheless, although), sebep (because, since, due to, as a result), örnek (for example, for instance, such as), sonuç (therefore, thus, consequently), sıra (first of all, then, finally), özet (in conclusion, to sum up, overall). RESMÎ / SAMİMİ AYRIMI: Resmîde kısaltma yok (do not, cannot), phrasal verb yerine tek kelimeli fiil (postpone > put off), edilgen çatı daha sık. Samimide tersi geçerlidir. E-POSTA KALIPLARI — resmî: "Dear Mr Smith," / "I am writing to enquire about…" / "I would be grateful if you could…" / "I look forward to hearing from you." / "Yours sincerely," (isim biliniyorsa) ya da "Yours faithfully," (bilinmiyorsa). Samimi: "Hi Tom," / "Just a quick note to…" / "Let me know!" / "Best," / "Cheers,". KONTROL LİSTESİ: 1) Her cümlede özne var mı? 2) 3. tekil -s ekleri yerinde mi? 3) Artikeller kontrol edildi mi? 4) Zaman tutarlı mı? 5) Aynı kelime tekrar ediliyor mu? Türk öğrenci tuzağı: Türkçedeki uzun, iç içe cümleleri birebir çevirmek — İngilizcede kısa ve net cümle daha iyi puan alır.',
  },
  {
    id: 'cefr-levels-en', title: 'CEFR seviyeleri — A1\'den C2\'ye İngilizcede ne demek?',
    keywords: ['seviye', 'a1', 'a2', 'b1', 'b2', 'c1', 'c2', 'cefr', 'hangi seviye'],
    content: 'A1 (Başlangıç, ~500 kelime): Alfabe ve ses sistemi, selamlaşma, kendini tanıtma, be fiili, Present Simple, sayılar, temel edatlar. Yavaş ve net konuşulursa anlar, basit kişisel bilgi alışverişi yapar. A2 (Temel, ~1.200 kelime): Past Simple, Future (will/going to), karşılaştırma, countable/uncountable, temel modal fiiller, günlük senaryolar. Tanıdık konularda basit alışveriş ve rutin görevleri yürütür. B1 (Orta, ~2.500 kelime): Present Perfect ile Past Simple ayrımı, koşul cümleleri 1-2, passive giriş, relative clause, phrasal verb\'lerin ilk katmanı, gerund/infinitive. Seyahatte çıkan durumların çoğunu çözer, deneyim ve plan anlatır. B2 (Orta-üstü, ~4.000 kelime): Tüm zamanlar bilinçli kullanılır, reported speech, 3. tip koşul, gelişmiş passive, eşdizim duyarlılığı, tartışma ve görüş savunma. Anadili konuşanla gergin olmadan sohbet eder, karmaşık metinleri anlar. C1 (İleri, ~8.000 kelime): Deyimler, üslup farkları, örtük anlam, akademik ve mesleki dil, ince nüanslar. C2 (Ustalık): Neredeyse anadili düzeyinde; mizah, kültürel gönderme, edebî üslup. TEMPO GERÇEĞİ: Türkçe anadili için A1→B1 düzenli çalışmayla 8-12 ay, B1→B2 ek 8-12 ay sürer; en büyük sıçrama B1 eşiğinde "düşünmeden cümle kurma" kazanıldığında olur.',
  },
  {
    id: 'translation-method-en', title: 'Türkçe-İngilizce çeviri yöntemi',
    keywords: ['çeviri', 'çevir', 'ingilizcesi', 'türkçesi', 'nasıl denir', 'translation'],
    content: 'Çeviri 6 adımlı bir karar zinciridir: 1) ZAMAN VE GÖRÜNÜŞ — olay bitti mi, sürüyor mu, sonucu mu önemli? Bu, 12 zamandan hangisini seçeceğini belirler ve Türkçedeki tek ek (-di, -yor, -mış) yetmez. 2) ÖZNE — İngilizcede özne ASLA gizlenmez; "Geliyorum" → "I am coming", hava durumunda bile "It is raining". 3) SÖZ DİZİMİ — Türkçenin SOV yapısı SVO\'ya çevrilir; fiil sona değil ortaya gelir. 4) ARTİKEL — isim sayılabilir mi, tekil mi, belirli mi? a/an/the/sıfır kararı verilir. 5) EDAT — Türkçe hâl eki İngilizce edatla karşılanır ama birebir değildir: "okula gidiyorum" → "to school", "okulda" → "at school". 6) EŞDİZİM — doğal İngilizce hangi kelime çiftini kullanıyor? "karar vermek" → make a decision, "fotoğraf çekmek" → take a photo. BAĞLAM EKSİKSE en olası nötr seçenek önce verilir, anlamı değiştiren alternatifler kısa notla ayrılır. UYARI: Türkçedeki kibarlık ekleri (-ebilir misiniz) İngilizcede modal seçimiyle karşılanır: Could you…? / Would you mind…? Türk öğrenci tuzağı: kelime kelime çevirip özneyi atlamak ve artikelleri unutmak — bu ikisi tek başına cümleyi "yabancı" gösterir.',
  },
  {
    id: 'exam-strategy-en', title: 'Sınav ve deneme stratejisi',
    keywords: ['sınav', 'deneme', 'exam', 'test', 'hazırlık', 'sınav taktiği', 'yds toefl'],
    content: 'Deneme sınavı bilgi ÖLÇMEZ, bilgiyi PEKİŞTİRİR. ÖNCE: Konuyu %100 bitirmeyi bekleme; %70 hazırken gir, kalan %30\'u sınav sana gösterir. SIRASINDA: Zaman yönetimi puandan önemlidir — takıldığın soruyu işaretle ve geç. Çoktan seçmelide önce KESİN YANLIŞLARI ele; kalan iki şık arasında dilbilgisel ipucu ara (özne-fiil uyumu, zaman tutarlılığı, edat eşdizimi çoğu zaman yanlış şıkkı ele verir). Okuma bölümünde önce SORULARI oku, sonra metni tara — her kelimeyi anlamaya çalışma. Dinleme bölümünde not al ama cümle yazma, anahtar kelime yaz. Yazma bölümünde bilmediğin kelimeyi bildiğinle değiştir; boş bırakmak sıfırdır. SONRA — EN DEĞERLİ KISIM: Yanlışları üç kategoriye ayır: (a) BİLMİYORDUM → yeni öğren, (b) BİLİYORDUM AMA KARIŞTIRDIM → karşılaştırmalı not çıkar, (c) DİKKATSİZLİK → kontrol alışkanlığı geliştir. (b) kategorisi altındır; oradaki her hata kalıcı bir kuralı oturtur. ARALIK: Aynı seviyenin denemesini 10 günden önce tekrarlama. Deneme sonrası yanlışları 24 saat içinde tekrar et — o pencere kapanırsa hata kalıcılaşır.',
  },
  {
    id: 'study-plan-en', title: 'Çalışma planı — günlük/haftalık rutin',
    keywords: ['plan', 'program', 'nasıl çalışmalıyım', 'rutin', 'çalışma planı', 'ne çalışayım'],
    content: 'Etkili bir İngilizce rutini dört kanalı DENGELİ besler. GÜNLÜK 45 DAKİKA ÖNERİSİ: 10 dk SRS tekrarı (vadesi gelen kartlar — pazarlıksız, her gün), 15 dk yeni içerik (bir ünite veya gramer konusu), 10 dk dinleme (kesintisiz, ilk tur altyazısız), 10 dk üretim (yazma veya yüksek sesle konuşma). HAFTALIK EKLER: haftada 1 deneme sınavı, haftada 1 uzun dinleme (15+ dk, film/podcast), haftada 1 yazma (100-150 kelime). ALTIN KURAL: Üretim olmadan girdi tek başına akıcılık üretmez; "anlıyorum ama konuşamıyorum" şikâyetinin tek sebebi üretim eksikliğidir. PLATO KIRMA: İlerleme durduysa seviyeyi değil KANALI değiştir. HATA GÜNLÜĞÜ: Her hatayı tek deftere yaz, haftada bir oku; aynı hatayı üçüncü kez yapmak öğrenmeyi en çok yavaşlatan şeydir. SÜREKLİLİK > YOĞUNLUK: Her gün 30 dakika, haftada bir 4 saatten kesinlikle daha etkilidir. ÖLÇME: Ayda bir kendini test et — ilerleme görünmezse motivasyon düşer, görünürse katlanır.',
  },
];
