/**
 * RUSÇA ÇEKİRDEK UZMANLIK BANKASI
 *
 * Her kayıt tek bir konuyu "öğretmen ağzıyla" ele alır: kural + mantığı +
 * karşılaştırmalı örnek + Türk öğrencinin tam o noktadaki tipik hatası.
 * Eski sürümdeki 23 kayıt → 58 kayda çıkarıldı ve her kaydın içeriği
 * ortalama iki katına genişletildi.
 */

export interface CoreKnowledgeEntry {
  id: string;
  title: string;
  keywords: string[];
  content: string;
}

export const RU_CORE_KNOWLEDGE: CoreKnowledgeEntry[] = [
  {
    id: 'alphabet-pronunciation', title: 'Alfabe, vurgu ve telaffuz',
    keywords: ['alfabe', 'harf', 'okunuş', 'telaffuz', 'vurgu', 'ь', 'ъ', 'ё', 'о', 'akanje', 'akanye', 'kiril', '33 harf'],
    content: 'Rus Kiril alfabesi 33 harftir: 10 ünlü (а, е, ё, и, о, у, ы, э, ю, я), 21 ünsüz ve ses vermeyen 2 işaret (ь, ъ). Ünlüler ikiye ayrılır: sert sıra (а, э, ы, о, у) ve yumuşak sıra (я, е, и, ё, ю) — yumuşak sıradaki ünlü, önündeki ünsüzü inceltir. Vurgu Rusçanın bel kemiğidir: yeri sabit değildir, kelimeden kelimeye ve çekimden çekime kayar (окно́ → о́кна), hatta anlamı değiştirir (замо́к = kilit, за́мок = şato; мука́ = un, му́ка = işkence). ё harfi daima vurguludur ama basılı metinde çoğunlukla е diye yazılır; bu yüzden sözlükte ё gören öğrenci metinde е görünce şaşırır. Türkçe okunuş yazımı yalnızca yaklaşıktır: ы, щ, ь gibi sesler Türkçede birebir yoktur. Tuzak: Türk öğrenci her harfi yazıldığı gibi okumaya çalışır; oysa Rusça okunuşu belirleyen şey vurgudur, harf değil.',
  },
  {
    id: 'vowel-reduction', title: 'Ünlü indirgemesi: akanye ve ikanye',
    keywords: ['akanje', 'akanye', 'ikanye', 'indirgeme', 'vurgusuz', 'o harfi', 'e harfi', 'redüksiyon', 'хорошо', 'молоко'],
    content: 'Vurgusuz ünlüler Rusçada zayıflar. AKANYE: vurgusuz «о» [a] okunur — хорошо́ [haraşó], молоко́ [malakó], Москва́ [maskvá]. Vurgudan iki hece önce ses daha da zayıflar, neredeyse [ı] gibi duyulur. İKANYE: vurgusuz «е» ve «я» [i] yönünde incelir — сестра́ [sistrá], пятёрка [pityórka], язы́к [yizík]. Kural yalnız VURGUSUZ hecelerde çalışır; vurgulu «о» tam [o] kalır: до́м [dom]. Pratik sonuç: bir kelimeyi doğru okumak için önce vurgunun nerede olduğunu bilmek gerekir. Türk öğrenci tuzağı: «молоко» kelimesini üç «o» ile [moloko] diye okumak — Rus kulağı bunu yabancı aksanı olarak anında işaretler; doğrusu [malakó]dır, yalnız son «о» tam telaffuz edilir.',
  },
  {
    id: 'consonant-devoicing', title: 'Ünsüz sedasızlaşma ve benzeşme',
    keywords: ['sedasızlaşma', 'benzeşme', 'kelime sonu', 'хлеб', 'город', 'водка', 'ünsüz', 'asimilasyon'],
    content: 'Rusçada sesli (yumuşak) ünsüzler kelime sonunda sedasızlaşır: б→п, в→ф, г→к, д→т, ж→ш, з→с. Örnek: хлеб [hlep], город [górat], муж [muş], нож [noş], друг [druk]. Aynı şey sedasız bir ünsüzden ÖNCE de olur (gerileyici benzeşme): водка [vótka], ложка [loşka], всё [fsyo]. Tersi de geçerlidir: sedalı ünsüzden önce sedasız olan seslenir — сделать [zdélat\']. Önemli ayrıntı: ses değişir ama YAZIM değişmez; bu yüzden «город» yazılır, [górat] okunur. Türk öğrenci tuzağı: yazıldığı gibi [gorod] demek. İkinci tuzak: «друг» → [druk] okunur ama çekimde ses geri gelir: дру́га [drúga].',
  },
  {
    id: 'gender-number', title: 'İsimlerde cinsiyet ve çoğul',
    keywords: ['cinsiyet', 'eril', 'dişil', 'nötr', 'çoğul', 'isim', 'род', 'множественное'],
    content: 'Rusçada her ismin cinsiyeti vardır ve bu cinsiyet sıfatı, zamiri ve geçmiş zaman fiilini yönetir. Kural: ünsüz veya -й ile bitenler ERİL (стол, музей), -а/-я ile bitenler DİŞİL (книга, неделя), -о/-е ile bitenler NÖTR (окно, море). -ь ile bitenler ikiye ayrılır ve sözlükten öğrenilir: дверь, ночь, жизнь dişil; словарь, день, учитель erildir. Anlamca eril ama biçimce dişil isimler vardır: папа, дядя, мужчина — bunlar dişil gibi çekilir ama sıfat eril gelir: мой папа. Çoğul: eril/dişil çoğunlukla -ы/-и (столы, книги), nötr -а/-я (окна, моря). Düzensizler ezberlenir: человек→люди, ребёнок→дети, друг→друзья, брат→братья, город→города, дом→дома. Yazım kuralı: к, г, х, ж, ч, ш, щ sonrası «ы» yazılmaz, «и» gelir — книга→книги (книгы değil). Türk öğrenci tuzağı: Türkçede cinsiyet olmadığı için sıfat uyumu unutulur — «новый книга» ✗, «новая книга» ✓.',
  },
  {
    id: 'case-overview', title: 'Hâl sistemine genel bakış — 6 hâl birden',
    keywords: ['hal', 'hâl', 'падеж', '6 hal', 'hal sistemi', 'çekim', 'kaç hal', 'hangi hal'],
    content: 'Rusçada 6 hâl vardır ve her biri cümlede bir "görev" dağıtır: 1) Именительный / YALIN (кто? что?) — özne ve sözlük biçimi. 2) Родительный / İLGİ (кого? чего?) — aitlik, yokluk, miktar, без/для/из/от/у edatları. 3) Дательный / YÖNELME (кому? чему?) — alıcı, к ve по edatları, «мне нужно» gibi kişisiz yapılar. 4) Винительный / BELİRTME (кого? что?) — doğrudan nesne, в/на + hedef (куда?). 5) Творительный / ARAÇ (кем? чем?) — araç, eşlik (с), meslek (работаю врачом). 6) Предложный / BULUNMA (о ком? где?) — daima edatla: в/на (где?), о/об (hakkında). Zihin haritası: Türkçede ekler kelime sonuna eklenir ve değişmez; Rusçada ek kelimenin sonunu YENİDEN YAZAR ve cinsiyete göre farklıdır. Doğru hâli bulmanın en hızlı yolu: önce fiilin veya edatın hangi hâli istediğini sor, sonra ismin cinsiyetine göre eki seç. Türk öğrenci tuzağı: hâli Türkçe eke göre seçmek — Türkçe «-de» her zaman предложный değildir; «в пять часов» zamanda belirtme hâli ister.',
  },
  {
    id: 'nominative', title: 'Yalın hâl — именительный',
    keywords: ['yalın', 'именительный', 'özne', 'kim', 'ne', 'nominatif'],
    content: 'Yalın hâl sözlük biçimidir ve üç yerde görünür: 1) Öznede — Маша читает. 2) Ad yükleminde — Это мой брат. 3) Adlandırmada — Меня зовут Анна (ad yalın). Şimdiki zamanda быть kullanılmaz: «Я студент» doğrudur, «Я есть студент» standart dilde yanlıştır (есть yalnız varlık vurgulanınca kalır: «У меня есть брат»). Geçmiş ve gelecekte быть geri gelir ve araç hâli isteyebilir: «Он был врачом» (meslek araç hâlinde). Yalın hâl ayrıca «Это…» kalıbında sabittir: «Это новая книга». Türk öğrenci tuzağı: Türkçedeki «-dir» ekini быть ile karşılamaya çalışmak ve her cümleye «есть» koymak.',
  },
  {
    id: 'genitive', title: 'İlgi hâli — родительный',
    keywords: ['ilgi hâli', 'ilgi hali', 'родительный', 'yokluk', 'aitlik', 'нет', 'miktar', 'у меня', 'genitif', 'sahiplik'],
    content: 'Родительный en çok iş yapan hâldir. Beş ana görevi: 1) AİTLİK — книга брата (kardeşin kitabı); Rusçada iyelik, sahibin ilgi hâline girmesiyle kurulur, sondaki ek sahibe takılır. 2) YOKLUK — У меня нет книги (kitabım yok); нет / не было / не будет daima ilgi hâli ister. 3) SAHİPLİK KALIBI — У меня есть книга (bende kitap var); у + ilgi hâli. 4) MİKTAR — 2, 3, 4 sonrası tekil ilgi (две книги), 5 ve üzeri çoğul ilgi (пять книг); много/мало/несколько de ilgi ister. 5) EDATLAR — без, для, до, из, от, с (…-den), у, около, после, кроме, вместо. Olumlu/olumsuz çifti ezberle: «У меня есть время» ↔ «У меня нет времени». Türk öğrenci tuzağı: «benim kitabım yok» derken ismi yalın bırakmak — «нет книга» ✗, «нет книги» ✓. İkinci tuzak: 5 ve üzeri sayıdan sonra çoğul yalın kullanmak — «пять книги» ✗, «пять книг» ✓.',
  },
  {
    id: 'dative', title: 'Yönelme hâli — дательный',
    keywords: ['yönelme', 'дательный', 'kime', 'мне', 'нужно', 'надо', 'yaş', 'datif', 'нравится'],
    content: 'Дательный "kime / neye" sorusunu yanıtlar ve Rusçanın en Türkçe-dostu hâlidir. Görevleri: 1) ALICI — Я дал книгу Анне (Anna\'ya verdim). 2) KİŞİSİZ DURUM — Мне холодно, Мне скучно, Мне плохо (bana soğuk geliyor). 3) YAŞ — Мне двадцать лет (Rusçada yaş "sahiplik" değil, "kişiye düşen" olarak kurulur). 4) GEREKLİLİK — Мне нужно работать, Мне надо идти, Мне можно войти? 5) HOŞLANMA — Мне нравится эта книга (dikkat: hoşlanan kişi yönelmede, hoşlanılan şey YALIN hâlde ve fiil ona uyar: Мне нравятся эти книги). 6) EDATLAR — к (…-e doğru, birinin yanına) ve по (üzerinde/boyunca, telefonla: по телефону). Türk öğrenci tuzağı: «Я нравлюсь книгу» ✗ — yapı tersine kurulur: «Мне нравится книга» ✓. İkinci tuzak: yaşı «Я имею 20 лет» diye söylemek (Fransızca/Türkçe mantığı) — doğrusu «Мне 20 лет».',
  },
  {
    id: 'accusative', title: 'Belirtme hâli — винительный',
    keywords: ['belirtme', 'винительный', 'nesne', 'kimi', 'neyi', 'куда', 'akuzatif', 'canlılık'],
    content: 'Винительный doğrudan nesneyi gösterir: Я читаю книгу. Biçimi CANLILIĞA bağlıdır — bu Rusçanın en kritik kurallarından biridir. Cansız eril: belirtme = yalın (вижу стол). Canlı eril: belirtme = ilgi (вижу брата). Dişil -а: -у olur (книга→книгу). Çoğulda canlılar yine ilgi biçimini alır (вижу друзей), cansızlar yalın biçimini (вижу столы). İkinci büyük görev: HEDEF. в/на + belirtme "nereye?" sorusuna cevap verir — Я иду в школу (okula gidiyorum), Я кладу книгу на стол. Karşılaştır: в/на + bulunma "nerede?" demektir — Я в школе (okuldayım). Üçüncü görev: saat ve gün — в два часа, в среду. Türk öğrenci tuzağı: «куда» ile «где» yapısını karıştırmak — «Я иду в школе» ✗ (bu "okulda yürüyorum" olur), «Я иду в школу» ✓.',
  },
  {
    id: 'instrumental', title: 'Araç hâli — творительный',
    keywords: ['araç hâli', 'araç hali', 'творительный', 'ile', 'с кем', 'чем', 'enstrümental', 'meslek'],
    content: 'Творительный "kiminle / neyle" hâlidir. Görevleri: 1) ARAÇ — Я пишу ручкой (kalemle yazıyorum); dikkat, burada edat YOKTUR, ek tek başına "ile" anlamını taşır. 2) EŞLİK — Я иду с другом (arkadaşımla); burada с edatı gerekir. Bu ikisi Türkçede aynı "-le" ekiyle karşılandığı için sürekli karışır: ручкой (araç, edatsız) ↔ с другом (eşlik, edatlı). 3) MESLEK/ROL — Он работает врачом, Она стала учителем (fiil "olmak/çalışmak" ise meslek araç hâline girer). 4) İLGİ ALANI — Я интересуюсь музыкой, Я занимаюсь спортом. 5) EDATLAR — с (ile), над (üstünde), под (altında), перед (önünde), за (arkasında), между (arasında). 6) быть geçmiş/gelecekte meslekle: Он был студентом. Türk öğrenci tuzağı: «Я пишу с ручкой» ✗ (bu "kalemle birlikte yürüyorum" gibi duyulur) → «Я пишу ручкой» ✓.',
  },
  {
    id: 'prepositional', title: 'Bulunma hâli — предложный',
    keywords: ['bulunma', 'предложный', 'nerede', 'где', 'hakkında', 'о ком', 'о чём', 'prepozisyonel'],
    content: 'Предложный tek başına asla kullanılmaz — daima bir edata yaslanır, adı da buradan gelir. İki ana kullanım: 1) YER (где?) — в/на + bulunma: живу в Москве, книга на столе, работаю в офисе. в "içinde", на "üstünde/açık alanda" demektir ama kullanım gelenekseldir: на почте, на работе, на вокзале, на Украине/в Украине tartışmalıdır; в театре ama на концерте. 2) KONU — о/об + bulunma: говорим о фильме, думаю о тебе (об ünlüyle başlayan kelimeden önce: об Анне). Eski yer biçimi: bazı eril isimler в/на ile -у/-ю alır — в лесу, на мосту, в саду, на полу, в году. Bu biçim yalnız yer anlamında çıkar; konu anlamında normal ek gelir: о лесе. Türk öğrenci tuzağı: "hakkında" için ilgi hâli kullanmak («о книги» ✗ → «о книге» ✓) ve «где/куда» ayrımını kaçırmak.',
  },
  {
    id: 'case-after-prepositions', title: 'Hangi edat hangi hâli ister?',
    keywords: ['edat', 'предлог', 'в', 'на', 'к', 'у', 'с', 'из', 'по', 'за', 'hangi hal', 'edat tablosu'],
    content: 'Edat-hâl eşleşmesi Rusçada ezberlenmesi ŞART olan tek listedir. İLGİ isteyenler: без, для, до, из, от, с (…-den), у, около, после, кроме, вместо, против, вокруг. YÖNELME isteyenler: к (…-e doğru), по (üzerinde, …-e göre, telefonla), благодаря, вопреки. BELİRTME isteyenler: в/на (nereye?), за (…-in arkasına, …için/karşılığında), под (…-in altına), через (…-den sonra/arasından), про (hakkında, konuşma dili). ARAÇ isteyenler: с (ile), над, под (altında — konum), перед, за (arkasında — konum), между. BULUNMA isteyenler: в/на (nerede?), о/об (hakkında), при (…-in yanında/döneminde). Çift çalışan edatlar hareket/konum ayrımı yapar: «иду в школу» (belirtme, hedef) ↔ «я в школе» (bulunma, konum); «кладу книгу под стол» (belirtme, hareket) ↔ «книга под столом» (araç, konum). Türk öğrenci tuzağı: с edatını hep araç hâliyle kullanmak — «с работы» (işten) ilgi hâlidir, «с другом» (arkadaşla) araç hâlidir; anlamı edat değil, hâl ayırır.',
  },
  {
    id: 'adjective-agreement', title: 'Sıfat ve zamir uyumu',
    keywords: ['sıfat', 'uyum', 'zamir', 'какой', 'benim', 'мой', 'прилагательное', 'kısa sıfat'],
    content: 'Sıfatlar, iyelik ve işaret zamirleri bağlı oldukları ismin CİNSİYET + SAYI + HÂLİNE uyar. Yalın hâl: новый дом, новая книга, новое окно, новые дома. Çekimde ek hâli gösterir: с новым другом (araç), о новой книге (bulunma), нового студента (ilgi). İyelik zamirleri de aynı şekilde çekilir: мой/моя/моё/мои, твой, наш, ваш — ама его, её, их DEĞİŞMEZ (его книга, его книги). Yazım: к/г/х ve ж/ч/ш/щ gövdeli sıfatlarda «ы» yerine «и» yazılır — русский, большие. Okunuş tuzağı: ilgi/belirtme hâlindeki -ого/-его eki [-ava]/[-eva] okunur: нового [nóvava]. Kısa sıfat yüklem görevindedir ve geçici durum bildirir: Он готов (hazır, şu an) ↔ готовый ужин (hazır yemek, nitelik). Kısa biçim cinsiyete uyar: готов, готова, готово, готовы. Türk öğrenci tuzağı: sıfatı sözlük biçiminde bırakmak — «я люблю новый книга» ✗, «я люблю новую книгу» ✓ (hem sıfat hem isim belirtmeye girer).',
  },
  {
    id: 'pronouns', title: 'Zamirler ve çekimleri',
    keywords: ['zamir', 'я', 'ты', 'он', 'она', 'мы', 'вы', 'они', 'меня', 'тебя', 'местоимение', 'себя'],
    content: 'Şahıs zamirleri de hâllere göre çekilir ve tamamen düzensizdir — ezberlenir. я: меня (ilgi/belirtme), мне (yönelme), мной (araç), обо мне (bulunma). ты: тебя, тебе, тобой, о тебе. он/оно: его, ему, им, о нём. она: её, ей, ей/ею, о ней. мы: нас, нам, нами, о нас. вы: вас, вам, вами, о вас. они: их, им, ими, о них. Kritik ayrıntı: edattan sonra 3. şahıs zamirleri başına «н-» alır — у него, к ней, с ними, о них (ama «его книга» edatsız olduğu için н- almaz). Dönüşlü zamir себя tüm şahıslar için kullanılır ve yalın hâli yoktur: Я купил себе книгу. İyelik свой "öznenin kendi" anlamını verir ve karışıklığı önler: Он взял свою книгу (kendi kitabını) ↔ Он взял его книгу (başkasının kitabını). Türk öğrenci tuzağı: «у его» demek — doğrusu «у него».',
  },
  {
    id: 'present-conjugation', title: 'Şimdiki zaman ve fiil çekimi',
    keywords: ['şimdiki', 'çekim', '1. çekim', '2. çekim', 'настоящее', 'читать', 'говорить', 'спряжение'],
    content: 'Bitmemiş fiiller şimdiki zamanda altı şahsa göre çekilir ve iki sınıfa ayrılır. 1. ÇEKİM (çoğunlukla -ать, -ять, -еть): -ю/-у, -ешь, -ет, -ем, -ете, -ют/-ут → читать: читаю, читаешь, читает, читаем, читаете, читают. 2. ÇEKİM (çoğunlukla -ить): -ю/-у, -ишь, -ит, -им, -ите, -ят/-ат → говорить: говорю, говоришь, говорит, говорим, говорите, говорят. İSTİSNA LİSTESİ ezberlenir: -еть ile bitip 2. çekim olanlar (смотреть, видеть, терпеть, обидеть, зависеть, ненавидеть, вертеть) ve -ать ile bitip 2. çekim olanlar (слышать, дышать, держать, гнать). Tersine, -ить ile bitip 1. çekim olanlar: брить, стелить, пить, бить, жить. 2. çekimde 1. TEKİL ŞAHISTA ünsüz değişir: д→ж (ходить→хожу), т→ч (платить→плачу), с→ш (просить→прошу), з→ж (возить→вожу), ст→щ (простить→прощу), б→бл (любить→люблю), в→вл (готовить→готовлю), п→пл (купить→куплю), м→мл (кормить→кормлю). Bu değişim YALNIZ «я» biçiminde olur, diğer beş şahısta gövde normale döner. Türk öğrenci tuzağı: mastardan mekanik tahmin yürütmek — писать 1. çekimdir ama gövdesi değişir: пишу, пишешь.',
  },
  {
    id: 'past-future', title: 'Geçmiş ve gelecek zaman',
    keywords: ['geçmiş', 'gelecek', 'был', 'буду', 'прошедшее', 'будущее', 'л eki'],
    content: 'GEÇMİŞ ZAMAN Rusçada şahsa göre değil, CİNSİYET ve SAYIYA göre çekilir — bu Türkçeden en farklı noktadır. Mastardan -ть atılır, -л/-ла/-ло/-ли eklenir: он читал, она читала, оно читало, они читали. «Я читал» diyen erkektir, «Я читала» diyen kadındır; yani cümle konuşanın cinsiyetini ele verir. быть geçmişi: был, была, было, были; olumsuzu не был (vurgu kayar: не́ был). GELECEK ikiye ayrılır: 1) BİLEŞİK GELECEK (bitmemiş) = буду/будешь/будет/будем/будете/будут + bitmemiş MASTAR → Я буду читать (okuyacağım, süreç). 2) BASİT GELECEK (bitmiş) = bitmiş fiilin şimdiki zaman çekimi → Я прочитаю (okuyup bitireceğim). Kritik kural: «буду» yanına ASLA bitmiş mastar gelmez — «буду прочитать» ✗. Ayrıca «буду» yanına çekimli fiil de gelmez — «буду читаю» ✗. Türk öğrenci tuzağı: Türkçede «okuyacağım» tek biçim olduğu için iki geleceği ayırmamak; sonuç vurgulanıyorsa bitmiş, süreç vurgulanıyorsa bileşik gelecek seçilir.',
  },
  {
    id: 'aspect', title: 'Fiil görünüşü — вид (bitmiş / bitmemiş)',
    keywords: ['görünüş', 'aspect', 'вид', 'bitmiş', 'bitmemiş', 'совершенный', 'несовершенный', 'yapmak', 'делать сделать'],
    content: 'Görünüş Rusçanın kalbidir ve Türkçede doğrudan karşılığı yoktur. НЕСОВЕРШЕННЫЙ (bitmemiş): süreç, süre, tekrar, alışkanlık, eylemin kendisi — Я читал книгу (kitap okuyordum / okudum, sonuç belirsiz). СОВЕРШЕННЫЙ (bitmiş): tek seferlik, sonuçlanmış, sınırlanmış eylem — Я прочитал книгу (kitabı okudum ve bitirdim). Çiftler çoğunlukla önekle kurulur: делать→сделать, читать→прочитать, писать→написать, смотреть→посмотреть; bazen sonekle: покупать→купить, давать→дать; bazen tamamen farklı köktür: говорить→сказать, брать→взять. SEÇİM KURALLARI: Tekrar/alışkanlık → bitmemiş (Я каждый день читаю). Tek sonuç → bitmiş (Я вчера прочитал). Olumsuzlukta çoğunlukla bitmemiş (Я не читал эту книгу). «начать, продолжать, кончить» sonrası DAİMA bitmemiş mastar (начал читать ✓, начал прочитать ✗). Süre belirteçleriyle (долго, весь день, два часа) bitmemiş; sonuç belirteçleriyle (вдруг, наконец, уже) bitmiş. En önemli kural: BİTMİŞ FİİLİN ŞİMDİKİ ZAMANI YOKTUR — прочитаю biçimi gelecek anlamındadır. Türk öğrenci tuzağı: Türkçedeki «-di» ekini hep bitmiş sanmak; «dün çalıştım» süreç ise работал, sonuç ise поработал/сделал olur.',
  },
  {
    id: 'motion-verbs', title: 'Hareket fiilleri ve önekleri',
    keywords: ['hareket', 'gitmek', 'gelmek', 'идти', 'ходить', 'ехать', 'ездить', 'нести', 'носить', 'глаголы движения'],
    content: 'Rusçada "gitmek" tek fiil değildir; ikili sistem vardır. YÜRÜYEREK: идти (tek yön, şu an, belirli sefer) ↔ ходить (alışkanlık, çok yön, gidip gelme). ARAÇLA: ехать ↔ ездить. Örnek fark: «Я иду в школу» = şu anda okula gidiyorum; «Я хожу в школу» = okula giderim (öğrenciyim). «Вчера я ходил в кино» = sinemaya gittim VE geri döndüm; «Вчера я шёл в кино» = sinemaya gidiyordum (yolda bir şey oldu). Benzer çiftler: нести/носить (taşımak), везти/возить (araçla taşımak), вести/водить (götürmek), бежать/бегать (koşmak), лететь/летать (uçmak), плыть/плавать (yüzmek). ÖNEKLER yön ve görünüş katar: при- varış (пришёл = geldi), у- ayrılış (ушёл = gitti), в-/во- giriş (вошёл), вы- çıkış (вышел), под- yaklaşma (подошёл), от- uzaklaşma (отошёл), пере- geçiş (перешёл), до- hedefe ulaşma (дошёл), про- geçip gitme (прошёл), за- uğrama (зашёл). Önek alan tek yönlü fiil bitmiş görünüş olur: идти → прийти (bitmiş), приходить (bitmemiş). Türk öğrenci tuzağı: Türkçede «gidiyorum/giderim» ayrımı zaman ekiyle yapıldığından, Rusçada bunun FİİL SEÇİMİYLE yapıldığını atlamak.',
  },
  {
    id: 'reflexive-passive', title: '-ся dönüşlü fiiller ve edilgen yapı',
    keywords: ['-ся', 'ся', 'dönüşlü', 'edilgen', 'возвратный', 'пассив', 'мыться', 'нравиться'],
    content: '-ся/-сь eki altı farklı iş yapar, hepsi "kendi" demek değildir: 1) GERÇEK DÖNÜŞLÜLÜK — мыться (yıkanmak), одеваться (giyinmek); özne eylemi kendine yapar. 2) KARŞILIKLILIK — встречаться (buluşmak), обниматься (sarılmak); iki taraf birbirine. 3) EDİLGEN/ORTA YAPI — Дом строится (ev inşa ediliyor), Книга читается легко. 4) KİŞİSİZ EĞİLİM — Мне не спится (uykum gelmiyor), Мне хочется (canım istiyor). 5) SÜREKLİ ÖZELLİK — Собака кусается (bu köpek ısırır). 6) SÖZLÜKSEL — боятся, смеяться, улыбаться, надеяться: bunların -ся\'sız biçimi yoktur veya tamamen başka anlamdadır. Biçim kuralı: ünlüden sonra -сь, ünsüzden sonra -ся (я учусь, ты учишься, он учится — yazımda hep -ся/-сь ama okunuşta [-ца]). ÇOK ÖNEMLİ: -ся fiilleri doğrudan nesne ALMAZ; «Я учусь русский» ✗, «Я учу русский» ✓ veya «Я учусь русскому языку» ✓. Türk öğrenci tuzağı: нравиться yapısını ters kurmak — «Я нравлюсь книгу» ✗, «Мне нравится книга» ✓.',
  },
  {
    id: 'negation', title: 'Olumsuzluk ve çifte olumsuzluk',
    keywords: ['olumsuzluk', 'не', 'ни', 'нет', 'никто', 'hiç', 'никогда', 'ничего', 'отрицание'],
    content: 'Rusçada olumsuzluk ÜST ÜSTE binerek güçlenir; İngilizcedeki "double negative yanlıştır" kuralı burada TERSİNE işler. не kelimeyi/fiili olumsuzlar: Я не читаю. нет varlık yokluğudur ve ilgi hâli ister: У меня нет времени. ÇİFTE OLUMSUZLUK ZORUNLUDUR: Я никого не вижу (kimseyi görmüyorum — hem никого hem не), Никто не пришёл (kimse gelmedi), Я никогда не был в Москве, Он ничего не сказал. Yani olumsuz zamir varsa fiilin önünde не mutlaka bulunur. Olumsuzlukta nesne ilgi hâline kayabilir ve bu anlamı değiştirir: Я не вижу книгу (belirli bir kitabı görmüyorum) ↔ Я не вижу книги (hiç kitap görmüyorum, genel). ни- öneki olumsuzluğu dağıtır: никто, ничто, никогда, нигде, никуда, никакой. Edat araya girer: ни у кого, ни с кем. Türk öğrenci tuzağı: İngilizce mantığıyla «Я никого вижу» demek — не atlanamaz, çünkü Rusçada olumsuzluk fiilde taşınır.',
  },
  {
    id: 'questions-word-order', title: 'Sorular, ли ve kelime sırası',
    keywords: ['soru', 'kelime sırası', 'кто', 'что', 'где', 'куда', 'ли', 'почему', 'вопрос', 'tonlama'],
    content: 'EVET-HAYIR sorusu Rusçada yardımcı fiille değil, TONLAMAYLA kurulur: «Ты дома.» (düz) → «Ты дома?» (tonlama yükselir). Yazıda fark yalnız soru işaretidir; konuşmada vurgu sorulan öğenin üzerine biner: «ТЫ дома?» (sen mi?) ↔ «Ты ДОМА?» (evde mi?). SORU SÖZCÜKLERİ: кто (kim), что (ne), где (nerede), куда (nereye), откуда (nereden), когда (ne zaman), почему (neden), зачем (ne amaçla), как (nasıl), какой (hangi/nasıl bir), который (hangisi), сколько (kaç), чей (kimin). ли "…-ıp olmadığı" anlamını verir ve vurgulanan kelimeden hemen sonra, cümlenin ikinci konumuna gelir: «Знаешь ли ты…?», «Не знаю, придёт ли он». KELİME SIRASI esnektir çünkü hâl ekleri görevi zaten belirtir; ama sıra VURGU taşır. Nötr sıra özne-fiil-nesne: «Маша читает книгу». Sona taşınan öğe yeni bilgidir: «Книгу читает Маша» (kitabı okuyan Maşa\'dır). Türk öğrenci tuzağı: Türkçedeki «mi» soru ekini ли ile birebir eşlemek — «Ты ли дома?» garip olur; günlük Rusçada tonlama yeterlidir.',
  },
  {
    id: 'numbers-time', title: 'Sayılar, yaş, saat ve tarih',
    keywords: ['sayı', 'yaş', 'saat', 'tarih', 'kaç', 'сколько', 'год', 'лет', 'числительное', 'kaç yaşında'],
    content: 'SAYI-İSİM UYUMU Rusçanın en mekanik ama en çok hata yapılan kuralıdır. 1 (ve 21, 31, 101…) → tekil YALIN: один год, двадцать один год. 2-3-4 (ve 22, 23, 24…) → tekil İLGİ: два года, двадцать два года. 5-20 ve 0, ayrıca 11-14 → çoğul İLGİ: пять лет, одиннадцать лет. 11-14 İSTİSNADIR: son rakam kuralı burada çalışmaz — 12 лет (не 12 года), 113 лет. Kural son İKİ haneye bakılarak uygulanır. YAŞ yönelme hâliyle söylenir: Мне 21 год, Тебе 22 года, Ему 25 лет. «Я имею 20 лет» ✗ (Fransızca kalıbı). SAAT: «Сколько времени?» / «Который час?» — Сейчас два часа, пять часов. Saatte в + belirtme: в два часа, в пять часов. GÜN: в понедельник, в среду (belirtme). AY/YIL: в январе, в 2025 году (bulunma). TARİH söylerken sıra sayısı + ay ilgi hâlinde: первое января, но «первого января» (tarihte olan olay için). Türk öğrenci tuzağı: 11-14 istisnasını kaçırıp «одиннадцать года» demek.',
  },
  {
    id: 'imperative-modals', title: 'Emir, gereklilik ve yeterlilik',
    keywords: ['emir', 'gereklilik', 'можно', 'нельзя', 'нужно', 'надо', 'должен', 'мочь', 'повелительное'],
    content: 'EMİR KİPİ iki biçimlidir: samimi tekil (читай, скажи, иди) ve nezaket/çoğul (читайте, скажите, идите). Üretim: şimdiki zaman 3. çoğul gövdesine ünlü sonrası -й, ünsüz sonrası -и eklenir: читают→читай, говорят→говори. пожалуйста tonu yumuşatır; давай(те) birlikte yapma önerir: Давайте пойдём! Olumsuz emir çoğunlukla bitmemiş fiille kurulur: Не читай! (okuma) — bitmiş fiille uyarı anlamı doğar: Не упади! (düşme sakın). MODAL YAPILAR kişiyi yönelme hâline alır: Мне можно войти? (girebilir miyim), Мне нужно/надо работать (çalışmam gerek), Мне нельзя курить (sigara içmem yasak). можно izin/imkân, нельзя yasak/imkânsızlık, надо/нужно gereklilik. должен KISA SIFAT gibi davranır ve özneyle uyar: Я должен (erkek), Я должна (kadın), Мы должны. мочь yetenek/fiziksel imkân verir ve çekilir: могу, можешь, может, можем, можете, могут. уметь ise öğrenilmiş beceridir: Я умею плавать (yüzmeyi bilirim) ↔ Я могу плавать (şu an yüzebilirim). Türk öğrenci tuzağı: «Я нужно» ✗ — doğrusu «Мне нужно» ✓, çünkü gereklilik kişiye "düşer".',
  },
  {
    id: 'participles-gerunds', title: 'Ortaç ve ulaçlar',
    keywords: ['ortaç', 'ulaç', 'причастие', 'деепричастие', 'который', 'sıfat fiil', 'zarf fiil'],
    content: 'ПРИЧАСТИЕ (ortaç/sıfat-fiil) fiili sıfata çevirir ve isimle uyum gösterir — Türkçedeki «-an/-en, -mış» eklerinin karşılığıdır. Etken şimdiki: читающий студент (okuyan öğrenci). Etken geçmiş: прочитавший студент (okumuş öğrenci). Edilgen geçmiş: написанная книга (yazılmış kitap). Kısa edilgen ortaç yüklem olur: Книга написана (kitap yazılmıştır), Магазин закрыт. ДЕЕПРИЧАСТИЕ (ulaç/zarf-fiil) eş zamanlı veya önce olan yan eylemi verir — Türkçedeki «-arak, -ıp, -ınca» karşılığıdır. Bitmemişten: читая (okuyarak), Читая книгу, он делал заметки. Bitmişten: прочитав (okuyup), Прочитав письмо, она заплакала. ALTIN KURAL: ulacın öznesi ana cümlenin öznesiyle AYNI olmalıdır. «Подъезжая к станции, у меня слетела шляпа» ünlü bir hata örneğidir (şapka istasyona yaklaşmıyor). Konuşma dilinde ortaç/ulaç yerine который kullanılır: «студент, который читает». Türk öğrenci tuzağı: ortacı çekmeden bırakmak — «я вижу читающий студента» ✗, «я вижу читающего студента» ✓.',
  },
  {
    id: 'conditionals-subjunctive', title: 'Koşul, dilek ve бы yapısı',
    keywords: ['koşul', 'şart', 'бы', 'если', 'keşke', 'условное', 'чтобы', 'dilek kipi'],
    content: 'GERÇEK KOŞUL если ile kurulur ve normal zaman çekimleri kullanılır: Если будет время, я приду (vakit olursa gelirim). Dikkat: Rusçada şart cümlesinde de gelecek zaman kullanılır — Türkçedeki «olursa» geniş zaman gibi görünse de Rusçada «будет» denir. VARSAYIMSAL/OLMAYAN KOŞUL geçmiş biçim + бы ister ve zamanı belirtmez: Я бы пошёл, если бы было время (vaktim olsaydı giderdim). Burada «пошёл» geçmiş biçimdir ama anlam şimdiki/gelecek olabilir; bağlam karar verir. бы vurgulanan öğeden sonra gelir ve cinsiyet geçmiş biçimde görünür: Она бы пришла. DİLEK: Я хотел бы… (isterdim, kibar), Хорошо бы… (keşke olsa). ÇТОБЫ amaç veya istek bildirir ve ardından geçmiş biçim ya da mastar gelir: Я хочу, чтобы ты пришёл (gelmeni istiyorum — iki özne farklı), Я пришёл, чтобы помочь (yardım etmek için geldim — tek özne, mastar). Türk öğrenci tuzağı: «чтобы» sonrası şimdiki zaman kullanmak — «чтобы ты приходишь» ✗, «чтобы ты пришёл» ✓.',
  },
  {
    id: 'prefixes-word-formation', title: 'Önekler, sonekler ve sözcük yapımı',
    keywords: ['önek', 'sonek', 'kelime yapımı', 'приставка', 'суффикс', 'kök', 'словообразование'],
    content: 'Rusça kelime dağarcığını ezberle değil, KÖK + ÖNEK + SONEK mantığıyla büyütmek gerekir. Fiil önekleri hem yön hem görünüş katar: по- başlama/kısa süre (поговорить = biraz konuşmak), про- baştan sona (прочитать), пере- yeniden/karşıya (переписать = yeniden yazmak), за- başlama/uğrama (заговорить = konuşmaya başlamak), вы- dışarı (выйти), в- içeri (войти), при- varış (прийти), у- ayrılış (уйти), до- hedefe kadar (дойти), раз- dağılma (разойтись), с- bir araya/aşağı (сойти). Aynı önek her fiilde aynı Türkçe karşılığı vermez — kalıp olarak öğrenilir. İsim sonekleri anlam ve cinsiyet ipucu verir: -тель kişi/araç ve eril (учитель, выключатель), -ость soyut ve dişil (радость, скорость), -ник kişi/nesne eril (работник), -ство soyut nötr (государство), -ция/-сия dişil ve çoğu uluslararası (информация), -ка dişil küçültme veya meslek (студентка). Sıfat sonekleri: -ск- ilişkisel (русский, городской), -н- genel nitelik (интересный), -лив- eğilim (счастливый). Küçültme ekleri sıcaklık katar: дом→домик, мама→мамочка, Анна→Аня→Анечка. Türk öğrenci tuzağı: öneki atıp kökü tek başına kullanmak — «Я читал книгу вчера и кончил» yerine «прочитал» demek daha doğaldır.',
  },
  {
    id: 'register-naturalness', title: 'Doğallık, resmiyet ve konuşma dili',
    keywords: ['doğal', 'resmî', 'resmi', 'samimi', 'argo', 'konuşma dili', 'ты', 'вы', 'nezaket'],
    content: 'ты / вы ayrımı Rusçada sosyal bir karardır, dilbilgisi değil. ты: yaşıt, arkadaş, aile, çocuk. вы: yeni tanışılan kişi, yaşça büyük, resmî ortam, müşteri-satıcı ilişkisi ve çoğul. Yanlış seçim kaba ya da mesafeli algılanır; emin değilsen вы ile başla, karşı taraf «давай на ты» derse geç. SELAMLAMA MERDİVENİ: Здравствуйте (resmî/nötr) > Добрый день (resmî, sıcak) > Привет (samimi) > Здорово/Хай (çok samimi, genç). VEDA: До свидания (resmî) > Всего доброго (kibar) > Пока (samimi) > Давай (çok samimi). İSİM KULLANIMI: resmî ortamda ad + baba adı (имя-отчество) kullanılır — Иван Петрович. Bu Türkçede karşılığı olmayan bir nezaket katmanıdır. Rusçada özne Türkçedeki kadar sık düşmez: «Иду домой» mümkündür ama «Я иду домой» nötr biçimdir. Çeviride kelime kelime doğruluk yetmez; eşdizim ve ton kontrol edilmelidir: «сделать фотографию» yerine «сфотографировать» daha doğaldır. Türk öğrenci tuzağı: herkese «Привет» demek ve resmî ortamda samimi düşmek.',
  },
  {
    id: 'translation-method', title: 'Türkçe-Rusça çeviri yöntemi',
    keywords: ['çeviri', 'çevir', 'rusçası', 'türkçesi', 'nasıl denir', 'перевод'],
    content: 'Çeviri 6 adımlı bir karar zinciridir: 1) İLETİŞİM AMACI — rica mı, bilgi mi, şikâyet mi? Bu, kibarlık düzeyini ve fiil seçimini belirler. 2) MUHATAP — ты mı вы mu? 3) ÖZNE CİNSİYETİ — geçmiş zaman kullanılacaksa cinsiyet şart (я читал / я читала). 4) GÖRÜNÜŞ — süreç mi sonuç mu? «Dün kitap okudum» süreçse читал, bitirdiyse прочитал. 5) HÂL — fiilin ve edatın istediği hâl seçilir; Türkçe eki birebir taşımak güvenli değildir. 6) EŞDİZİM — doğal Rusça hangi kelime çiftini kullanıyor? «karar vermek» = принять решение, «fotoğraf çekmek» = сфотографировать. Bağlam yoksa en olası NÖTR seçenek önce verilir, anlamı değiştiren alternatifler kısa notla ayrılır. Türkçenin SOV dizilimi Rusçanın esnek SVO dizilimine çevrilirken vurgulanan öğe sona bırakılır. Türk öğrenci tuzağı: Türkçe cümleyi kelime kelime çevirip hâl eklerini atlamak; sonuç dilbilgisel olarak doğru görünse de Rus kulağına "robot" gelir.',
  },
  {
    id: 'byt-possession', title: 'быть, есть ve sahiplik yapısı',
    keywords: ['быть', 'есть', 'var', 'yok', 'sahiplik', 'у меня есть', 'нет', 'olmak fiili'],
    content: 'Rusçada "olmak" ve "sahip olmak" Türkçeden tamamen farklı kurulur. ŞİMDİKİ ZAMAN: быть kullanılmaz — Я студент, Он дома, Это хорошо. GEÇMİŞ/GELECEK: быть geri gelir — Я был студентом (araç hâli!), Я буду дома. SAHİPLİK: "benim X\'im var" = У меня есть X. Burada sahip у + ilgi hâline girer, sahip olunan şey YALIN kalır: У меня есть брат, У неё есть машина. есть yalnız varlık vurgulanınca kullanılır; nitelik vurgulanıyorsa düşer: «У меня есть машина» (arabam var) ↔ «У меня красная машина» (arabam kırmızı). YOKLUK: нет + ilgi hâli — У меня нет брата, У нас нет времени. Geçmişte не было, gelecekte не будет, hepsi ilgi hâliyle: Вчера не было времени. иметь fiili vardır ama günlük dilde neredeyse kullanılmaz; soyut/resmî bağlamda görülür: иметь право, иметь значение. Türk öğrenci tuzağı: «Я имею машину» demek — dilbilgisel olarak kurulabilir ama doğal değildir; «У меня есть машина» ✓.',
  },
  {
    id: 'word-order-focus', title: 'Kelime sırası ve bilgi yapısı',
    keywords: ['kelime sırası', 'vurgu', 'tema', 'rema', 'порядок слов', 'dizilim', 'odak'],
    content: 'Rusçada kelime sırası dilbilgisi değil, BİLGİ YÖNETİMİ aracıdır. Hâl ekleri "kim kime ne yaptı"yı zaten belirlediği için sıra serbesttir; serbestlik de vurgu için kullanılır. Genel ilke: bilinen bilgi (tema) başta, yeni bilgi (rema) SONDA. «Маша читает книгу» = nötr, kim ne yapıyor. «Книгу читает Маша» = kitabı okuyan Maşa\'dır (yeni bilgi: Maşa). «Маша книгу читает» = Maşa kitabı okuyor (okumak eylemi vurgulu). Soru-cevap testi bunu kanıtlar: «Что делает Маша?» → «Маша читает КНИГУ». «Кто читает книгу?» → «Книгу читает МАША». Konuşmada ayrıca ses vurgusu kullanılır ve yazıdaki sırayı bozmadan odağı değiştirebilir. Sıfat normalde isimden önce gelir (новая книга); sonra gelirse şiirsel/vurgulu olur. Edat öbekleri yer değiştirebilir ama edat kendi isminden ayrılmaz. Türk öğrenci tuzağı: Türkçenin SOV alışkanlığıyla fiili hep sona atmak — «Я книгу читаю» yanlış değildir ama nötr değildir, sürekli kullanılırsa tuhaf durur.',
  },
  {
    id: 'common-mistakes', title: 'Türk öğrencilerin en sık 15 hatası',
    keywords: ['hata', 'yanlış', 'sık hata', 'tuzak', 'ошибка', 'en çok yapılan hata'],
    content: 'Yıllara dayanan gözlemle en sık 15 hata: 1) «Я есть студент» → «Я студент» (şimdiki zamanda быть yok). 2) «Я имею 20 лет» → «Мне 20 лет». 3) «Я нравлюсь книгу» → «Мне нравится книга». 4) «Я иду в школе» → «Я иду в школу» (hedef belirtme ister). 5) «У меня нет книга» → «нет книги» (ilgi hâli). 6) «пять книги» → «пять книг». 7) «одиннадцать года» → «одиннадцать лет» (11-14 istisnası). 8) «буду прочитать» → «буду читать» veya «прочитаю». 9) «новый книга» → «новая книга» (cinsiyet uyumu). 10) «Я пишу с ручкой» → «Я пишу ручкой» (araç hâli edatsız). 11) «Я учусь русский» → «Я учу русский» (-ся nesne almaz). 12) «у его» → «у него» (edat sonrası н-). 13) «Я никого вижу» → «Я никого не вижу» (çifte olumsuzluk zorunlu). 14) «Я хочу что ты придёшь» → «Я хочу, чтобы ты пришёл». 15) «Спасибо тебя» → «Спасибо тебе» (спасибо yönelme ister). Bu listeyi haftada bir okumak, A2 seviyesindeki hataların yarısını kapatır.',
  },
  {
    id: 'verbs-government', title: 'Fiil yönetimi — hangi fiil hangi hâli ister?',
    keywords: ['fiil yönetimi', 'управление', 'hangi hal', 'помогать', 'звонить', 'заниматься', 'интересоваться'],
    content: 'Her fiil belli bir hâl ister ve bu Türkçeden tahmin edilemez — sözlükle birlikte öğrenilir. YÖNELME isteyenler: помогать кому (yardım etmek), звонить кому (aramak), отвечать кому (cevap vermek), верить кому, мешать кому (rahatsız etmek), советовать кому, радоваться чему, учиться чему. ARAÇ isteyenler: заниматься чем (ile uğraşmak), интересоваться чем, пользоваться чем (kullanmak), гордиться кем (gurur duymak), становиться кем (olmak), работать кем (meslek). İLGİ isteyenler: бояться кого/чего (korkmak), ждать кого/чего (beklemek — belirsizse), достигать чего, желать чего. BELİRTME isteyenler (düz nesne): читать что, видеть кого, любить кого, ждать кого (belirliyse). EDATLI yönetimler: думать о ком (düşünmek), говорить о чём (hakkında konuşmak), смотреть на что (bakmak), слушать что (dinlemek — edatsız!), спрашивать у кого (sormak), просить кого о чём. Türk öğrenci tuzağı: «звонить кого» ✗ → «звонить кому» ✓; «слушать музыке» ✗ → «слушать музыку» ✓.',
  },
  {
    id: 'comparative-superlative', title: 'Karşılaştırma ve üstünlük dereceleri',
    keywords: ['karşılaştırma', 'üstünlük', 'больше', 'лучше', 'самый', 'сравнительная', 'daha', 'en'],
    content: 'KARŞILAŞTIRMA iki yolla kurulur. 1) BASİT BİÇİM: sıfat gövdesi + -ее → красивый→красивее, интересный→интереснее. Bu biçim çekilmez, yüklem olur. Düzensizler ezberlenir: хороший→лучше, плохой→хуже, большой→больше, маленький→меньше, высокий→выше, низкий→ниже, дорогой→дороже, молодой→моложе, старый→старше. 2) BİLEŞİK BİÇİM: более + sıfat → более интересный; çekilebilir, isimden önce kullanılır. Karşılaştırılan taraf iki şekilde verilir: ilgi hâliyle edatsız (Он старше меня) veya чем ile yalın hâlde (Он старше, чем я). İkisi de doğrudur; чем daha açıktır. ÜSTÜNLÜK: самый + sıfat (самый интересный фильм) en yaygın biçimdir; наиболее resmîdir; -ейший/-айший kitabi ve güçlüdür (интереснейший). «En iyi» = самый лучший veya kısaca лучший. Zarf karşılaştırması aynı biçimi kullanır: Он говорит быстрее. «Gittikçe daha…» = всё + karşılaştırma: всё лучше и лучше. Türk öğrenci tuzağı: «более лучше» ✗ (çifte karşılaştırma) → «лучше» ✓.',
  },
  {
    id: 'time-expressions', title: 'Zaman ifadeleri ve hangi hâli alır',
    keywords: ['zaman', 'когда', 'ne zaman', 'сегодня', 'вчера', 'через', 'назад', 'время'],
    content: 'Zaman ifadeleri hangi hâle gireceğini süre birimine göre seçer. SAAT: в + belirtme → в два часа, в полдень. GÜN: в + belirtme → в понедельник, в субботу. HAFTA: на + bulunma → на этой неделе, на прошлой неделе. AY/YIL/YÜZYIL: в + bulunma → в январе, в 2025 году, в XXI веке. MEVSİM: araç hâli edatsız → зимой, летом, весной, осенью. GÜNÜN BÖLÜMLERİ: araç hâli edatsız → утром, днём, вечером, ночью. SÜRE (ne kadar sürdü): belirtme edatsız → Я читал два часа. SÜRE SINIRI (ne kadar zamanda): за + belirtme → Я прочитал книгу за два часа. GELECEKTE (…sonra): через + belirtme → через час, через неделю. GEÇMİŞTE (…önce): tam tersi dizilim, назад SONA gelir → два часа назад, неделю назад. SIKLIK: каждый день, раз в неделю, два раза в месяц. Türk öğrenci tuzağı: «назад два часа» ✗ → «два часа назад» ✓; ayrıca «в этой неделе» ✗ → «на этой неделе» ✓.',
  },
  {
    id: 'v-na-choice', title: 'в mi на mı? — yer edatı seçimi',
    keywords: ['в', 'на', 'edat seçimi', 'nerede', 'в школе', 'на работе', 'yer'],
    content: 'в "kapalı/sınırlı alanın içinde", на "yüzeyde veya açık alanda" demektir — ama Rusçada bu ayrım büyük ölçüde GELENEKSELDİR, mantıkla çözülmez, liste olarak öğrenilir. в alanlar: в доме, в комнате, в школе, в университете, в магазине, в театре, в музее, в больнице, в городе, в стране, в машине, в офисе, в парке. на alanlar: на работе, на почте, на вокзале, на станции, на остановке, на уроке, на лекции, на концерте, на стадионе, на заводе, на фабрике, на рынке, на улице, на этаже, на севере/юге, на Кавказе, на острове. ULAŞIM: на + bulunma (araçla) → на автобусе, на машине, на поезде; ama içinde olma vurgulanırsa в автобусе. ANLAM FARKI yaratan çiftler: в столе (masanın çekmecesinde) ↔ на столе (masanın üstünde); в кухне ↔ на кухне (ikisi de kullanılır, на daha yaygın). ÇIKIŞ EDATI eşleşir: в → из (из школы), на → с (с работы). Bu eşleşme kuralı sağlamadır: «на работе» diyorsan «с работы» dersin, «из работы» ✗. Türk öğrenci tuzağı: «я иду из работы» ✗ → «я иду с работы» ✓.',
  },
  {
    id: 'etiquette-phrases', title: 'Günlük nezaket kalıpları',
    keywords: ['nezaket', 'teşekkür', 'спасибо', 'пожалуйста', 'извините', 'rica', 'özür', 'kibarlık'],
    content: 'Rusça nezaket kalıpları sabittir ve değiştirilmeden kullanılır. TEŞEKKÜR: Спасибо (teşekkürler), Большое спасибо (çok teşekkürler), Спасибо большое (aynı, daha sıcak), Благодарю (resmî). Kime teşekkür edildiği YÖNELME hâlindedir: Спасибо тебе / вам / Анне — «спасибо тебя» ✗. CEVAP: Пожалуйста, Не за что (bir şey değil), На здоровье (yemek için). RİCA: Пожалуйста, передайте… / Будьте добры… / Вы не могли бы…? (en kibar). ÖZÜR: Извините (resmî, dikkat çekmek için de), Простите (daha güçlü), Прошу прощения (çok resmî). Извините ile Простите farkı incedir: ilki "affedersiniz" (küçük rahatsızlık), ikincisi "beni bağışlayın" (gerçek özür). İYİ DİLEKLER: Удачи! (bol şans), Приятного аппетита!, Будьте здоровы! (hapşırana), С днём рождения!, Счастливого пути! TANIŞMA: Очень приятно / Приятно познакомиться. Türk öğrenci tuzağı: «Спасибо за…» yapısında belirtme hâli kullanmayı unutmak — «Спасибо за помощь» ✓ (за + belirtme).',
  },
  {
    id: 'questions-practice', title: 'Soru sorma kalıpları ve cevaplama',
    keywords: ['soru sorma', 'nasıl sorulur', 'как спросить', 'что это', 'сколько стоит', 'где находится'],
    content: 'Günlük hayatta en çok işe yarayan soru kalıpları: KİMLİK — Как тебя/вас зовут? (adın ne), Откуда ты? (nerelisin), Кем ты работаешь? (ne iş yaparsın, araç hâli!). YER — Где находится…? (nerede), Как пройти к…? (nasıl giderim), Это далеко? (uzak mı). FİYAT — Сколько это стоит? (bu kaça), Сколько с меня? (ne kadar ödeyeceğim). ZAMAN — Сколько времени? / Который час? (saat kaç), Когда открывается? (ne zaman açılıyor), Во сколько? (saat kaçta). ANLAMA — Что это значит? (ne demek), Как это по-русски? (Rusçası nasıl), Повторите, пожалуйста (tekrar edin), Говорите медленнее, пожалуйста (yavaş konuşun), Я не понимаю (anlamıyorum), Вы говорите по-английски? CEVAPLAMA kalıpları: Да, конечно / Нет, к сожалению / Я не знаю / Может быть / Думаю, да. Önemli: Rusçada "evet/hayır" sorusuna cevap verirken fiili tekrarlamak doğaldır: «Ты читаешь?» → «Читаю.» Türk öğrenci tuzağı: «Как это по-русски?» yerine «Как это русский?» demek — по- öneki şart.',
  },
  {
    id: 'verb-pairs-confusing', title: 'Karıştırılan fiil çiftleri',
    keywords: ['karışan fiil', 'учить учиться', 'знать уметь', 'говорить сказать', 'слушать слышать', 'смотреть видеть'],
    content: 'Rusçada Türkçede tek kelimeyle karşılanan birçok ikili vardır: УЧИТЬ / УЧИТЬСЯ / ИЗУЧАТЬ — учить + belirtme = ezberlemek/öğretmek (учу слова), учиться = öğrenci olmak (учусь в университете), изучать = sistemli incelemek (изучаю русский язык). ЗНАТЬ / УМЕТЬ — знать bilgi (Я знаю ответ), уметь beceri (Я умею плавать). ГОВОРИТЬ / СКАЗАТЬ / РАЗГОВАРИВАТЬ — говорить süreç/dil konuşmak (Я говорю по-русски), сказать tek seferlik söylemek (Он сказал правду), разговаривать sohbet etmek (Мы разговаривали час). СЛУШАТЬ / СЛЫШАТЬ — слушать bilinçli dinlemek (слушаю музыку), слышать duymak (слышу шум). СМОТРЕТЬ / ВИДЕТЬ — смотреть bakmak (смотрю фильм), видеть görmek (вижу дом). ДЕЛАТЬ / ЗАНИМАТЬСЯ — делать yapmak (делаю домашнее задание), заниматься + araç = uğraşmak (занимаюсь спортом). ЖИТЬ / ЖИВАТЬ yoktur ama ПРОЖИВАТЬ resmîdir (ikametgâh). ПОМНИТЬ / ВСПОМНИТЬ — помнить hafızada tutmak, вспомнить hatırlamak (anımsamak anı). Türk öğrenci tuzağı: «Я учу в университете» ✗ → «Я учусь в университете» ✓.',
  },
  {
    id: 'alphabet-writing', title: 'El yazısı ve Kiril yazım tuzakları',
    keywords: ['el yazısı', 'yazma', 'прописи', 'курсив', 'kiril yazma', 'harf karışıklığı'],
    content: 'Kiril alfabesinde Latin harflerine BENZEYEN ama farklı okunan harfler en büyük başlangıç tuzağıdır: В = [v] (B değil), Н = [n] (H değil), Р = [r] (P değil), С = [s] (C değil), У = [u] (Y değil), Х = [h] (X değil), Р ve П karışır. Hiç benzemeyen ama öğrenilmesi gerekenler: Б [b], Г [g], Д [d], Ж [j], З [z], И [i], Л [l], П [p], Ф [f], Ц [ts], Ч [ç], Ш [ş], Щ [şç], Ы [ı], Э [e], Ю [yu], Я [ya]. EL YAZISI ayrı bir sistemdir ve matbu harflere benzemez: küçük «т» el yazısında «m» gibi, küçük «д» ise «g» gibi görünür; «и, ш, щ, л, м» art arda gelince ayırt etmek zordur, bu yüzden Ruslar bazen «ш» altına veya «т» üstüne çizgi çeker. Yazarken dikkat: ь ve ъ asla büyük yazılmaz ve kelime başında bulunmaz; ы de kelime başında bulunmaz. Türk öğrenci tuzağı: «Ресторан» kelimesini [pestopan] diye okumak — Р ve С Latin P ve C değildir.',
  },
  {
    id: 'food-restaurant', title: 'Kafe, restoran ve sipariş dili',
    keywords: ['restoran', 'kafe', 'sipariş', 'yemek', 'меню', 'счёт', 'заказать', 'eating out'],
    content: 'Restoran senaryosunun sabit cümleleri: GİRİŞ — Столик на двоих, пожалуйста (iki kişilik masa), У вас есть свободный столик? SİPARİŞ — Меню, пожалуйста / Я буду… (… alacağım) / Мне, пожалуйста, … / Что вы посоветуете? (ne tavsiye edersiniz) / Что у вас есть из…? SORULAR — Это острое? (acı mı), Есть вегетарианские блюда?, Сколько это стоит? HESAP — Счёт, пожалуйста / Можно картой? (kartla olur mu) / Сдачи не надо (üstü kalsın). TEMEL SÖZCÜKLER: завтрак (kahvaltı), обед (öğle yemeği), ужин (akşam yemeği), первое (çorba), второе (ana yemek), десерт, напитки (içecekler), вода (su), чай, кофе, сок (meyve suyu), хлеб, суп, салат, мясо (et), курица (tavuk), рыба (balık), овощи (sebze), сыр (peynir), сахар (şeker), соль (tuz). ÖNEMLİ YAPI: «Я буду» + belirtme hâli = sipariş kalıbıdır ve gelecek zaman gibi görünse de "alıyorum" demektir. Türk öğrenci tuzağı: «Я хочу» ile sipariş vermek — dilbilgisel ama kaba durur; «Я буду…» veya «Мне, пожалуйста…» daha kibardır.',
  },
  {
    id: 'transport-directions', title: 'Ulaşım ve yön sorma',
    keywords: ['ulaşım', 'yön', 'метро', 'автобус', 'такси', 'как пройти', 'направление', 'adres'],
    content: 'YÖN SORMA: Как пройти к…? (yürüyerek nasıl giderim), Как проехать до…? (araçla), Где находится…? (nerede), Это далеко отсюда? (buradan uzak mı), Покажите на карте, пожалуйста. YÖN TARİFİ: прямо (düz), налево (sola), направо (sağa), назад (geri), до угла (köşeye kadar), через дорогу (yolun karşısına), рядом с… (…-in yanında), напротив (karşısında), за углом (köşeyi dönünce), в двух минутах отсюда. ULAŞIM ARAÇLARI ve edatı: на метро, на автобусе, на машине, на такси, пешком (yürüyerek — edatsız!). METRO: станция (istasyon), вход/выход (giriş/çıkış), переход (aktarma), следующая станция (sonraki durak), Осторожно, двери закрываются! (kapılar kapanıyor). BİLET: билет, проездной (abonman), Один билет до…, Сколько стоит проезд? TAKSİ: Отвезите меня, пожалуйста, на/в… (beni …-e götürün), Остановите здесь (burada durun). Hareket fiili seçimi kritiktir: hedefe в/на + belirtme (еду в центр), bulunulan yer в/на + bulunma (я в центре). Türk öğrenci tuzağı: «Я еду на пешком» ✗ → «Я иду пешком» ✓.',
  },
  {
    id: 'shopping-money', title: 'Alışveriş, fiyat ve pazarlık',
    keywords: ['alışveriş', 'fiyat', 'магазин', 'сколько стоит', 'скидка', 'размер', 'para'],
    content: 'ALIŞVERİŞ CÜMLELERİ: Сколько это стоит? (kaç para), У вас есть…? (… var mı), Можно посмотреть? (bakabilir miyim), Я ищу… (… arıyorum), Покажите, пожалуйста (gösterin lütfen), Есть другой размер/цвет? (başka beden/renk var mı), Можно примерить? (deneyebilir miyim), Это слишком дорого (çok pahalı), Есть скидка? (indirim var mı), Я возьму это (bunu alıyorum), Можно картой? (kartla olur mu), Дайте чек, пожалуйста (fiş verin). SÖZCÜKLER: магазин (dükkân), рынок (pazar), супермаркет, касса (kasa), продавец (satıcı), покупатель (müşteri), цена (fiyat), скидка (indirim), размер (beden), дёшево (ucuz), дорого (pahalı), бесплатно (ücretsiz), деньги (para), рубль/рубля/рублей, сдача (para üstü). PARA BİRİMİ SAYI UYUMU: 1 рубль, 2-4 рубля, 5+ рублей — tam da sayı kuralı burada çalışır. «Стоит» fiili tekil, «стоят» çoğul: Книга стоит 500 рублей / Книги стоят дорого. Türk öğrenci tuzağı: «Сколько стоят это?» ✗ → «Сколько стоит это?» ✓ (özne tekil).',
  },
  {
    id: 'health-doctor', title: 'Sağlık, doktor ve eczane',
    keywords: ['sağlık', 'doktor', 'hasta', 'больница', 'аптека', 'болит', 'врач', 'ilaç'],
    content: 'AĞRI BİLDİRME: Rusçada ağrı "bana ait" değil, "organ ağrıyor" biçiminde kurulur — У меня болит голова (başım ağrıyor), У меня болит горло, У меня болят зубы (çoğul: болят). Yapı: у + ilgi hâli + болит/болят + YALIN organ. DURUM: Я плохо себя чувствую (kendimi kötü hissediyorum), У меня температура (ateşim var), У меня насморк (burnum akıyor), Меня тошнит (midem bulanıyor), Я простудился/простудилась (üşüttüm — cinsiyet!). DOKTORDA: Мне нужен врач (doktora ihtiyacım var), Запишите меня к врачу (randevu alın), Что у меня? (nedir bu), Это серьёзно? (ciddi mi). ECZANE: Дайте что-нибудь от головной боли (baş ağrısı için bir şey verin), У вас есть это без рецепта? (reçetesiz var mı), Как принимать? (nasıl kullanılır), три раза в день (günde üç kez), после еды / до еды (yemekten sonra/önce). SÖZCÜKLER: врач/доктор, больница (hastane), поликлиника, аптека (eczane), лекарство (ilaç), таблетки (hap), рецепт (reçete), скорая помощь (ambulans), температура (ateş), кашель (öksürük), боль (ağrı). Türk öğrenci tuzağı: «Я болею голову» ✗ → «У меня болит голова» ✓.',
  },
  {
    id: 'family-relations', title: 'Aile, akrabalık ve ilişkiler',
    keywords: ['aile', 'akraba', 'семья', 'мама', 'папа', 'брат', 'сестра', 'жена', 'муж'],
    content: 'ÇEKİRDEK AİLE: мама/мать (anne), папа/отец (baba), родители (ebeveynler), брат (erkek kardeş), сестра (kız kardeş), сын (oğul), дочь (kız evlat), дети (çocuklar), ребёнок (çocuk, tekil). EŞLER: муж (koca), жена (eş/karı), супруг/супруга (resmî). BÜYÜKLER: бабушка (babaanne/anneanne — Rusçada ayrım yok), дедушка (dede), прабабушка (büyük büyükanne). GENİŞ AİLE: дядя (amca/dayı), тётя (hala/teyze), племянник (yeğen-erkek), племянница (yeğen-kız), двоюродный брат (kuzen-erkek), двоюродная сестра (kuzen-kız), внук (torun-erkek), внучка (torun-kız), свекровь (kayınvalide-kocanın annesi), тёща (kayınvalide-karının annesi). Dikkat: Türkçedeki ince akrabalık ayrımları (amca/dayı, hala/teyze) Rusçada YOKTUR; gerekirse «дядя по отцу» denir. MEDENİ DURUM: Я женат (evliyim — erkek), Я замужем (evliyim — kadın), Я не женат / Я не замужем, Я в разводе (boşandım), Мы встречаемся (çıkıyoruz). TANITMA: Это мой брат, Это моя жена, У меня двое детей (iki çocuğum var — двое toplu sayı). Türk öğrenci tuzağı: kadın için «Я женат» demek — doğrusu «Я замужем».',
  },
  {
    id: 'weather-seasons', title: 'Hava durumu ve mevsimler',
    keywords: ['hava', 'mevsim', 'погода', 'зима', 'лето', 'дождь', 'снег', 'холодно'],
    content: 'HAVA DURUMU kişisiz yapıyla kurulur — özne yoktur: Сегодня холодно (bugün soğuk), Жарко, Тепло, Прохладно, Ветрено, Солнечно, Пасмурно (kapalı). KİŞİSEL HİS yönelme hâliyle: Мне холодно (üşüyorum), Мне жарко (sıcakladım). Bu ikisini karıştırmamak önemlidir: «Холодно» hava soğuk, «Мне холодно» ben üşüyorum. YAĞIŞ: Идёт дождь (yağmur yağıyor — "yürüyor" fiiliyle!), Идёт снег (kar yağıyor), Был дождь (yağmur yağdı), Дождь кончился. SORU: Какая сегодня погода? (hava nasıl), Какая погода будет завтра? MEVSİMLER ve araç hâli: зима→зимой (kışın), весна→весной (ilkbaharda), лето→летом (yazın), осень→осенью (sonbaharda). Bu ekler edatsızdır. SICAKLIK: Сколько градусов? (kaç derece), Плюс пять / Минус десять, Ноль градусов. SÖZCÜKLER: небо (gökyüzü), облако (bulut), ветер (rüzgâr), гроза (fırtına), туман (sis), лёд (buz), жара (sıcak hava), мороз (ayaz). Türk öğrenci tuzağı: «Дождь падает» ✗ — Rusçada yağmur "yürür": «Идёт дождь» ✓.',
  },
  {
    id: 'work-office', title: 'İş hayatı, ofis ve meslekler',
    keywords: ['iş', 'meslek', 'работа', 'офис', 'профессия', 'коллега', 'начальник'],
    content: 'MESLEK SÖYLEME araç hâliyle: Я работаю врачом / учителем / инженером (doktor olarak çalışıyorum). Meslek yalın söyleniyorsa быть düşer: Я врач. Soru: Кем вы работаете? (ne iş yaparsınız — КЕМ araç hâli!) ya da Чем вы занимаетесь? MESLEKLER: врач (doktor), учитель (öğretmen), инженер, программист, юрист (hukukçu), бухгалтер (muhasebeci), менеджер, продавец (satıcı), водитель (şoför), повар (aşçı), официант (garson), парикмахер (kuaför), строитель (inşaatçı), переводчик (çevirmen). İŞYERİ: офис, компания, фирма, завод (fabrika), начальник/шеф (patron), коллега (meslektaş), сотрудник (çalışan), отдел (departman), зарплата (maaş), отпуск (izin), командировка (iş seyahati), совещание (toplantı), договор (sözleşme), резюме (CV), собеседование (mülakat). CÜMLELER: Я работаю с девяти до шести (dokuzdan altıya), У меня много работы, Я в отпуске, Давайте назначим встречу (bir toplantı ayarlayalım), Отправьте мне на почту (mail atın). Türk öğrenci tuzağı: «Я работаю врач» ✗ → «Я работаю врачом» ✓ (araç hâli şart).',
  },
  {
    id: 'phone-communication', title: 'Telefon ve dijital iletişim',
    keywords: ['telefon', 'arama', 'телефон', 'алло', 'звонить', 'сообщение', 'mesaj'],
    content: 'TELEFON AÇMA: Алло? / Да, слушаю (buyurun) / Слушаю вас. KENDİNİ TANITMA: Это Иван / Иван беспокоит (resmî, "rahatsız ediyorum"). İSTEME: Можно Анну? (Anna\'yı alabilir miyim), Позовите, пожалуйста, Анну, Я бы хотел поговорить с… (с + araç hâli). CEVAPLAR: Минуточку (bir dakika), Подождите, пожалуйста, Его/Её нет (yok), Перезвоните позже (sonra arayın), Он занят (meşgul), Вы ошиблись номером (yanlış numara). SORUNLAR: Плохо слышно (iyi duyulmuyor), Вас плохо слышно, Связь прерывается (bağlantı kopuyor), Я вам перезвоню (sizi geri ararım). FİİL YÖNETİMİ: звонить КОМУ (yönelme) — Я звоню маме; «звонить маму» ✗. Ayrıca «по телефону» (telefonla) — по + bulunma. DİJİTAL: сообщение (mesaj), написать в мессенджер, отправить (göndermek), получить (almak), ссылка (link), файл, электронная почта/почта (e-posta), скинь мне (at bana — çok samimi), я тебе наберу (seni ararım — konuşma dili). Türk öğrenci tuzağı: «Я звоню тебя» ✗ → «Я звоню тебе» ✓.',
  },
  {
    id: 'home-household', title: 'Ev, eşyalar ve ev işleri',
    keywords: ['ev', 'eşya', 'дом', 'квартира', 'комната', 'мебель', 'kira'],
    content: 'MEKÂNLAR: дом (ev/bina), квартира (daire), комната (oda), кухня (mutfak), спальня (yatak odası), гостиная (oturma odası), ванная (banyo), туалет, прихожая (antre), балкон, коридор, подъезд (apartman girişi), этаж (kat), лифт (asansör). EŞYALAR: мебель (mobilya — TEKİL ve dişil, çoğul kullanılmaz!), стол, стул, кровать (yatak), диван, шкаф (dolap), полка (raf), зеркало (ayna), ковёр (halı), окно, дверь, лампа, холодильник (buzdolabı), плита (ocak), микроволновка, стиральная машина (çamaşır makinesi), посудомойка. EV İŞLERİ: убирать/убрать (toplamak), мыть посуду (bulaşık yıkamak), стирать (çamaşır yıkamak), гладить (ütülemek), пылесосить (süpürmek), выносить мусор (çöp atmak), готовить (yemek yapmak), поливать цветы (çiçek sulamak). KİRA: снимать квартиру (kiralamak), сдавать (kiraya vermek), арендная плата / квартплата (kira), хозяин/хозяйка (ev sahibi), коммунальные услуги (aidat/faturalar), залог (depozito), ремонт (tadilat). «Мебель» uyarısı: Türkçede "mobilyalar" çoğul kurulabilir, Rusçada мебель daima tekildir — «мебели» ✗ (yalın çoğul olarak). Türk öğrenci tuzağı: «Я живу в третьем этаже» ✗ → «на третьем этаже» ✓.',
  },
  {
    id: 'emotions-opinions', title: 'Duygular ve fikir belirtme',
    keywords: ['duygu', 'fikir', 'думаю', 'по-моему', 'мне кажется', 'согласен', 'görüş'],
    content: 'FİKİR BELİRTME: Я думаю, что… (bence/düşünüyorum ki), По-моему… (bana göre), Мне кажется, что… (bana öyle geliyor ki), На мой взгляд… (benim görüşüme göre, resmî), Я уверен(а), что… (eminim). KATILMA: Я согласен (erkek) / Я согласна (kadın) / Согласен с тобой (с + araç hâli), Точно! (kesinlikle), Конечно (tabii), Вы правы (haklısınız). KATILMAMA: Я не согласен, Я так не думаю (ben öyle düşünmüyorum), Не совсем (tam olarak değil), Наоборот (tam tersine), Может быть, но… DUYGULAR: Я рад(а) (sevindim), Мне грустно (üzgünüm), Я устал(а) (yoruldum), Я злюсь (kızıyorum), Я боюсь (korkuyorum), Мне скучно (sıkıldım), Мне интересно (ilgimi çekiyor), Я волнуюсь (endişeliyim), Я горжусь (gurur duyuyorum + araç hâli). BEĞENİ: Мне нравится (hoşuma gidiyor) — yapı terstir: beğenen kişi yönelmede, beğenilen şey yalında ve fiil ona uyar. Мне нравятся эти книги. Daha güçlü: Я люблю (seviyorum), Я обожаю (bayılıyorum), Мне не нравится, Я терпеть не могу (katlanamıyorum). Türk öğrenci tuzağı: «Я согласен тебя» ✗ → «Я согласен с тобой» ✓.',
  },
  {
    id: 'education-study', title: 'Eğitim, okul ve öğrenme dili',
    keywords: ['eğitim', 'okul', 'школа', 'университет', 'урок', 'экзамен', 'öğrenmek'],
    content: 'KURUMLAR: школа (okul), университет, институт, колледж, детский сад (anaokulu), курсы (kurs), факультет, кафедра (bölüm). KİŞİLER: ученик/ученица (öğrenci-okul), студент/студентка (üniversite), учитель/учительница (öğretmen), преподаватель (öğretim görevlisi), профессор, декан, одноклассник (sınıf arkadaşı), однокурсник. DERS: урок (ders saati), занятие, лекция (ders anlatımı), семинар, пара (üniversitede çift ders saati), расписание (program), перемена (teneffüs), домашнее задание (ödev), контрольная (yazılı), экзамен (sınav), зачёт (geçme notu), оценка (not), пятёрка (5, en yüksek not), двойка (2, kalır). FİİLLER: учиться (öğrenci olmak), учить (ezberlemek/öğretmek), изучать (sistemli incelemek), заниматься (çalışmak + araç hâli: заниматься русским), готовиться к экзамену (sınava hazırlanmak, к + yönelme), сдавать экзамен (sınava girmek), сдать экзамен (sınavı geçmek — görünüş farkı kritik!), поступить в университет (üniversiteye girmek), окончить (bitirmek). «Сдавать» ile «сдать» farkı tam bir görünüş dersidir: «Вчера я сдавал экзамен» (sınava girdim, sonuç belirsiz) ↔ «Вчера я сдал экзамен» (sınavı geçtim). Türk öğrenci tuzağı: «Я учу в школе» ✗ → «Я учусь в школе» ✓.',
  },
  {
    id: 'collocations', title: 'Eşdizimler — hangi kelime hangisiyle gider?',
    keywords: ['eşdizim', 'collocation', 'kalıp', 'birlikte kullanım', 'doğal', 'принять решение'],
    content: 'Rusçada kelimeler rastgele birleşmez; "doğru ama doğal olmayan" cümlelerin sebebi eşdizim hatasıdır. KARAR: принять решение (karar vermek) — «дать решение» ✗. SORU: задать вопрос (soru sormak) — «спросить вопрос» ✗. HATA: сделать ошибку / допустить ошибку. FOTOĞRAF: сфотографировать veya сделать фото — «делать фотографию» zayıftır. DUŞ: принять душ (duş almak). KAHVALTI: завтракать veya позавтракать — «делать завтрак» yemek pişirmek demektir. İLGİ: обращать внимание (dikkat etmek, на + belirtme). SÖZ: дать слово (söz vermek), сдержать слово (sözünü tutmak). YARDIM: оказать помощь (resmî), помочь (günlük). ROL: играть роль (rol oynamak), иметь значение (önemi olmak). YAĞMUR: идёт дождь. YAŞ: исполняется (…yaşına basmak) — Мне исполняется 30. ZAMAN: проводить время (vakit geçirmek), терять время (vakit kaybetmek). GÜÇLÜ YAĞMUR: сильный дождь — «тяжёлый дождь» ✗. KOYU ÇAY: крепкий чай — «тёмный чай» ✗. Eşdizim listeleri tek tek öğrenilir; çeviri sözlüğü burada yardımcı olmaz. Türk öğrenci tuzağı: Türkçe "yapmak/etmek" fiilini Rusçaya hep делать diye taşımak.',
  },
  {
    id: 'idioms-expressions', title: 'Deyimler ve günlük ifadeler',
    keywords: ['deyim', 'ifade', 'идиома', 'выражение', 'konuşma dili', 'günlük konuşma'],
    content: 'Doğal Rusça konuşmanın anahtarı deyimlerdir: Как дела? — Нормально / Так себе (şöyle böyle) / Отлично / Ничего (fena değil). Ни пуха ни пера! (bol şans — cevabı «К чёрту!»). Всё в порядке (her şey yolunda). Не за что (bir şey değil). Да ладно! (yapma ya!). Ну и что? (ne olmuş yani?). В чём дело? (sorun ne?). Дело в том, что… (olay şu ki). Кстати (bu arada). Короче (kısacası — çok yaygın dolgu sözcüğü). На самом деле (aslında). Честно говоря (açıkçası). К сожалению (maalesef). К счастью (neyse ki). Между прочим (bu arada, laf aramızda). Так и быть (peki madem). Ещё бы! (tabii ki!). Я тебя понял (anladım seni). Без проблем (sorun değil). Как-нибудь (bir ara). Давай! (hadi! ayrıca vedalaşma). DOLGU SÖZCÜKLER: ну, вот, это самое, типа, как бы — bunlar aşırı kullanılırsa özensiz durur ama hiç kullanılmazsa konuşma robotik olur. Türk öğrenci tuzağı: deyimleri birebir çevirmek — «Ни пуха ни пера» harfi harfine "ne tüy ne kuş tüyü" demektir ama anlamı "bol şans"tır.',
  },
  {
    id: 'listening-strategy', title: 'Dinleme stratejisi — Rusçayı nasıl duyarım?',
    keywords: ['dinleme', 'anlama', 'аудирование', 'duymak', 'hızlı konuşma', 'dinleme taktiği'],
    content: 'Rusçayı anlamamanın üç teknik sebebi vardır ve üçünün de çözümü farklıdır. 1) SES İNDİRGEMESİ: Yazıda gördüğün kelime konuşmada başka duyulur (здравствуйте → [zdrástvuyte] hatta [zdrás\'te]; сейчас → [şiçás]; что → [şto]; тысяча → [tışça]). Çözüm: sık kelimelerin KONUŞMA biçimini ayrıca ezberle. 2) KELİME SINIRI KAYBI: Rusça akıcı konuşmada kelimeler birleşir, özellikle tek heceli edatlar önündeki kelimeye yapışır (в школе → [fşkóle], с ним → [snim]). Çözüm: edat + isim öbeklerini TEK parça olarak dinle. 3) HÂL EKLERİNİ KAÇIRMA: Anlamı taşıyan ek kelimenin SONUNDADIR ve hızlı konuşmada zayıflar. Çözüm: kelime sonlarına bilinçli odaklan. PRATİK YÖNTEM: aynı kaydı üç kez dinle — birincide genel konuyu yakala, ikincide bilmediğin 3 kelimeyi not et, üçüncüde metinle birlikte dinle. 0.75× hız ile başlayıp 1.0×\'e çıkmak işe yarar ama 0.5× fazla yavaştır ve doğal ritmi bozar. Her gün 10 dakika kesintisiz dinleme, haftada bir 1 saatlik dinlemeden daha etkilidir.',
  },
  {
    id: 'speaking-strategy', title: 'Konuşma stratejisi — nasıl akıcı olunur?',
    keywords: ['konuşma', 'akıcılık', 'говорение', 'pratik', 'konuşamıyorum', 'akıcı konuşma'],
    content: 'Akıcılık kelime sayısıyla değil, ERİŞİM HIZIYLA ilgilidir. Üç kural: 1) KALIPLA KONUŞ, kelimeyle değil. «Я хотел бы…», «Можно мне…», «Мне нужно…», «Как сказать…?» gibi 20 kalıp, 500 kelimeden daha çok iş görür çünkü cümleyi sıfırdan kurmazsın. 2) BASİTLEŞTİR. Bilmediğin kelimeyi bildiğinle anlat: «холодильник» aklına gelmiyorsa «шкаф, где холодно» de. Bu "dolambaçlı anlatım" (circumlocution) gerçek konuşmacıların da kullandığı bir beceridir. 3) ZAMAN KAZANMA SÖZCÜKLERİ kullan: «Ну…», «Как сказать…», «Дайте подумать…», «Это сложный вопрос…». Bunlar sessizliği doldurur ve beynine cümle kurma süresi verir. TELAFFUZ ÖNCELİĞİ: Rusçada en çok anlaşılırlığı bozan üç şey — vurgu yanlışlığı, ы sesinin i\'ye kaçması ve ь yumuşatmasının atlanması. Kelime ezberlerken vurguyu da ezberle; vurgusuz ezber yarım ezberdir. GÜNLÜK ALIŞTIRMA: Aynı cümleyi üç farklı hızda (yavaş-normal-hızlı) üç kez söyle; ağız kası hafızası böyle oluşur. Hata yapmaktan korkma — iletişim kurulduysa cümle işe yaramıştır.',
  },
  {
    id: 'memory-srs', title: 'Kalıcı öğrenme ve tekrar aralıkları',
    keywords: ['ezber', 'tekrar', 'srs', 'hafıza', 'unutma', 'leitner', 'nasıl ezberlerim'],
    content: 'Unutma eğrisi (Ebbinghaus) acımasızdır: yeni öğrenilen bir kelimenin %50\'si 1 günde, %70\'i 1 haftada kaybolur — TEKRAR EDİLMEZSE. Çözüm aralıklı tekrardır (SRS): 1. gün → 3. gün → 7. gün → 16. gün → 35. gün. Her başarılı tekrarda aralık uzar, hata yapınca kutu 1\'e döner. ÜRETİM > TANIMA: Kelimeyi görüp anlamını hatırlamak (tanıma) kolaydır; Türkçesini görüp Rusçasını YAZMAK (üretim) 3 kat güçlü iz bırakır. Bu yüzden kart çalışırken ters yönü de çalış. BAĞLAM KURALI: Tek kelime ezberi zayıftır; kelimeyi bir CÜMLE içinde ezberle. «стол» yerine «Книга на столе» ezberlersen hem kelimeyi hem hâl ekini hem edatı birlikte öğrenirsin. KÜMELEME: Birbirine benzeyen kelimeleri AYNI ANDA öğrenme (лево/право, завтра/вчера karışır); arada en az bir gün bırak. UYKU: Ezber uykudan önce yapılırsa pekişme daha güçlüdür; uyku sırasında bellek konsolidasyonu olur. TEST ETKİSİ: Okumak değil, kendini TEST ETMEK öğretir. Kartı çevirmeden önce 3 saniye düşün — o 3 saniyelik zorlanma, 10 dakikalık pasif okumadan değerlidir.',
  },
  {
    id: 'cefr-levels', title: 'CEFR seviyeleri — A1\'den C2\'ye Rusçada ne demek?',
    keywords: ['seviye', 'a1', 'a2', 'b1', 'b2', 'c1', 'c2', 'cefr', 'hangi seviye'],
    content: 'A1 (Başlangıç, ~500 kelime): Alfabe, selamlaşma, kendini tanıtma, sayılar, basit şimdiki zaman, yalın + belirtme + bulunma hâllerinin temeli. Çok yavaş ve net konuşulursa anlar. A2 (Temel, ~1.200 kelime): Altı hâlin tamamına giriş, geçmiş/gelecek zaman, görünüş farkının ilk sezgisi, hareket fiilleri, günlük senaryolar (alışveriş, restoran, yol sorma). Tanıdık konularda basit alışveriş yapabilir. B1 (Orta, ~2.500 kelime): Görünüş seçimi bilinçli hâle gelir, hareket fiili önekleri, koşul cümleleri, который ile yan cümle. Seyahatte çıkan durumların çoğunu çözer, deneyim ve plan anlatabilir. B2 (Orta-üstü, ~4.000 kelime): Ortaç ve ulaçlar, edilgen yapı, soyut konular, tartışma, resmî-samimi ayrımını bilinçli kullanma. Anadili konuşanla gergin olmadan sohbet edebilir. C1 (İleri, ~8.000 kelime): Deyimler, üslup farkları, uzun metinleri örtük anlamıyla kavrama, akademik/mesleki dil. C2 (Ustalık): Neredeyse anadili düzeyinde; nüans, mizah, kültürel gönderme ve edebî üslup. TEMPO GERÇEĞİ: Türkçe anadili için Rusça A1→B1 yolculuğu düzenli çalışmayla 10-14 ay sürer; hâl sistemi en çok B1 eşiğinde oturur.',
  },
  {
    id: 'exam-strategy', title: 'Sınav ve deneme stratejisi',
    keywords: ['sınav', 'deneme', 'экзамен', 'test', 'hazırlık', 'sınav taktiği'],
    content: 'Deneme sınavı bilgi ÖLÇMEZ, bilgiyi PEKİŞTİRİR — doğru kullanılırsa en güçlü çalışma aracıdır. ÖNCE: Sınava girmeden önce konuyu "bitirmiş" olmayı bekleme; %70 hazırken gir, kalan %30\'u sınav sana gösterir. SIRASINDA: Bilmediğin soruda takılma, işaretle geç — zaman yönetimi puandan önemlidir. Çoktan seçmelide önce KESİN YANLIŞLARI ele, kalan iki şık arasında dilbilgisel ipucu ara (hâl eki uyumu, cinsiyet uyumu çoğu zaman yanlış şıkkı ele verir). Yazma bölümünde bilmediğin kelimeyi bildiğinle değiştir; boş bırakmak sıfır puandır. SONRA — EN ÖNEMLİ KISIM: Yanlışları tek tek analiz et ve üç kategoriye ayır: (a) BİLMİYORDUM → yeni öğren, (b) BİLİYORDUM AMA KARIŞTIRDIM → karşılaştırmalı not çıkar, (c) DİKKATSİZLİK → kontrol alışkanlığı geliştir. (b) kategorisi en değerlisidir; oradaki her hata, kalıcı bir kuralı oturtur. ARALIK: Aynı seviyenin denemesini 10 günden önce tekrarlama; hafıza değil, anlama ölçülmelidir. Deneme sonrası yanlışları 24 saat içinde tekrar et — o pencere kapanırsa hata kalıcılaşır.',
  },
  {
    id: 'false-friends-ru', title: 'Rusça-Türkçe yalancı dostlar',
    keywords: ['yalancı dost', 'benzer kelime', 'ложные друзья', 'karıştırılan', 'tuzak kelime'],
    content: 'Türkçe ile Rusça arasında kulağa tanıdık gelen ama anlamı farklı kelimeler: «магазин» = dükkân (dergi değil; dergi «журнал»). «кабинет» = çalışma odası/muayene odası (mobilya değil). «фабрика» = fabrika ✓ (bu doğru dost). «акция» = hisse senedi veya kampanya (aksiyon filmi değil). «карта» = harita veya banka kartı (oyun kâğıdı «карты» çoğul). «кефир» = ayran benzeri içecek ✓. «диван» = koltuk/kanepe ✓. «балкон» ✓. «стакан» = bardak ✓ (Türkçeye de geçmiştir). «чай» ✓. «пара» = çift veya üniversitede çift ders saati. «интеллигент» = aydın/entelektüel (zeki demek değil; zeki «умный»). «симпатичный» = güzel/yakışıklı görünüşlü (sempatik değil; sempatik «приятный»). «артист» = oyuncu/sanatçı (ressam değil; ressam «художник»). «фамилия» = SOYADI (aile değil! aile «семья») — bu en sık karışandır. «конкурс» = yarışma. «репетиция» = prova (tekrar değil). Türk öğrenci tuzağı: «Моя фамилия большая» demek — "soyadım büyük" olur; aile demek istiyorsan «Моя семья большая» ✓.',
  },
  {
    id: 'writing-strategy', title: 'Yazma stratejisi — Rusça metin nasıl kurulur?',
    keywords: ['yazma', 'yazı', 'kompozisyon', 'письмо', 'metin', 'paragraf'],
    content: 'Rusça yazarken en sık görülen sorun "Türkçe düşünüp Rusça yazmak"tır. Çözüm: KALIPTAN CÜMLEYE yöntemi. 1) Cümleyi kurmadan önce FİİLİ seç — fiil hangi hâli istiyor, hangi görünüşte olmalı? Bu iki karar cümlenin iskeletini belirler. 2) Özneyi ve cinsiyetini sabitle (geçmiş zaman yazacaksan şart). 3) Nesneyi ve hâlini yerleştir. 4) Zaman/yer öbeklerini ekle, edat-hâl eşleşmesini kontrol et. 5) Son okuma: her ismin eki fiilin istediğiyle uyuşuyor mu? BAĞLAÇLAR metni birbirine bağlar: и (ve), а (ama/oysa — karşıtlık), но (ama), потому что (çünkü), поэтому (bu yüzden), хотя (-mesine rağmen), если (eğer), когда (-dığında), чтобы (için), который (ki o). «а» ile «но» farkı önemlidir: «а» karşılaştırma (Я читаю, а он пишет), «но» beklenti kırılması (Я хотел прийти, но не смог). RESMİ MEKTUP: Уважаемый Иван Петрович! … С уважением, (ad). SAMİMİ: Привет, Аня! … Пока!/Целую! Paragraf başına bir fikir kuralı Rusçada da geçerlidir. Türk öğrenci tuzağı: uzun ve iç içe cümle kurmaya çalışmak — B1\'e kadar kısa, net cümleler daha yüksek puan getirir.',
  },
  {
    id: 'culture-context', title: 'Kültürel bağlam ve iletişim âdetleri',
    keywords: ['kültür', 'adet', 'культура', 'görgü', 'davranış', 'rus kültürü'],
    content: 'Dil kültürle gelir; bu kalıplar bilinmezse dilbilgisi doğru olsa da iletişim tökezler. İSİM-BABA ADI (отчество): Resmî ortamda kişiye ad + baba adıyla hitap edilir — Иван Петрович, Анна Сергеевна. Bu, Türkçedeki "Bey/Hanım"ın yerini tutar ve saygının temel işaretidir. GÜLÜMSEME: Ruslar yabancılara refleks olarak gülümsemez; bu soğukluk değil, kültürel normdur — samimiyet tanıştıktan sonra gelir. MİSAFİRLİK: Eve giderken küçük bir hediye (çiçek, tatlı) götürülür; çiçek TEK sayıda olur, çift sayı cenazeye aittir. Evde ayakkabı çıkarılır ve genellikle terlik (тапочки) verilir. KADEH KALDIRMA: «тост» uzun ve içtendir; «За здоровье!» en bilinenidir ama Ruslar genellikle daha kişisel bir temenni söyler. İLETİŞİM TARZI: Rusça doğrudan konuşmaya yatkındır; Türkçedeki dolaylı kibarlık (örtük rica) bazen anlaşılmaz. «Дайте, пожалуйста» kaba değildir. TABULAR: Eşikte el sıkışılmaz, boş şişe masada bırakılmaz, doğum gününü erken kutlamak uğursuz sayılır. Bu detaylar sınavda çıkmaz ama gerçek iletişimde fark yaratır.',
  },
  {
    id: 'study-plan', title: 'Çalışma planı — günlük/haftalık rutin',
    keywords: ['plan', 'program', 'nasıl çalışmalıyım', 'rutin', 'çalışma planı', 'ne çalışayım'],
    content: 'Etkili bir Rusça rutini dört kanalı DENGELİ besler; tek kanala yüklenmek plato yaratır. GÜNLÜK 45 DAKİKA ÖNERİSİ: 10 dk SRS tekrarı (vadesi gelen kartlar — pazarlıksız, her gün), 15 dk yeni içerik (bir ünite veya gramer konusu), 10 dk dinleme (kesintisiz, altyazısız ilk tur), 10 dk üretim (yazma veya yüksek sesle konuşma). HAFTALIK EKLER: haftada 1 deneme sınavı (yalnız öğrendiklerinden), haftada 1 uzun dinleme (15+ dk), haftada 1 yazma (80-120 kelime). ALTIN KURAL: Üretim (yazma/konuşma) olmadan girdi tek başına akıcılık üretmez; pasif anlama ile aktif kullanım arasındaki fark burada kapanır. PLATO KIRMA: İlerleme durduysa seviyeyi değil KANALI değiştir — hep okuyorsan dinlemeye, hep dinliyorsan yazmaya geç. HATA GÜNLÜĞÜ: Yaptığın her hatayı tek bir deftere yaz ve haftada bir oku; aynı hatayı üçüncü kez yapmak öğrenmeyi en çok yavaşlatan şeydir. SÜREKLİLİK > YOĞUNLUK: Her gün 30 dakika, haftada bir 4 saatten kesinlikle daha etkilidir; dil beyinde aralıklı tekrarla yerleşir, tek seferlik yüklemeyle değil.',
  },
  {
    id: 'verbs-top100', title: 'En sık 60 fiil ve yönetimleri',
    keywords: ['sık fiil', 'temel fiil', 'глагол', 'en çok kullanılan fiil', 'fiil listesi'],
    content: 'Rusçanın en sık 60 fiili (bitmemiş/bitmiş çiftiyle ve istediği hâlle): быть (olmak), иметь (sahip olmak, resmî), делать/сделать что (yapmak), говорить/сказать что, кому (söylemek), знать что (bilmek), хотеть что/мастар (istemek), мочь (yapabilmek), идти/пойти (gitmek-yaya), ехать/поехать (gitmek-araçla), видеть/увидеть кого (görmek), смотреть/посмотреть на что (bakmak), слышать/услышать что (duymak), слушать что (dinlemek), читать/прочитать что, писать/написать что, кому, думать о чём (düşünmek), понимать/понять что (anlamak), работать кем (çalışmak), жить где (yaşamak), любить кого (sevmek), нравиться кому (hoşa gitmek), есть/съесть что (yemek), пить/выпить что, спать (uyumak), вставать/встать (kalkmak), ложиться/лечь (yatmak), покупать/купить что (satın almak), платить/заплатить за что (ödemek), давать/дать что, кому (vermek), брать/взять что (almak), получать/получить что, начинать/начать что (başlamak), кончать/кончить что, помогать/помочь кому (yardım etmek), звонить/позвонить кому (aramak), спрашивать/спросить у кого (sormak), отвечать/ответить кому (cevaplamak), учить/выучить что, учиться где (öğrenci olmak), изучать что, забывать/забыть что (unutmak), помнить что (hatırlamak), искать что (aramak), находить/найти что (bulmak), терять/потерять что (kaybetmek), открывать/открыть что, закрывать/закрыть что, ждать кого (beklemek), встречать/встретить кого (karşılamak), встречаться с кем (buluşmak), приходить/прийти (gelmek), уходить/уйти (gitmek), приезжать/приехать (varmak), возвращаться/вернуться (dönmek), становиться/стать кем (olmak), казаться кому (görünmek), чувствовать себя как (hissetmek), заниматься чем (uğraşmak), интересоваться чем, пользоваться чем (kullanmak). Bu 60 fiil günlük Rusçanın yaklaşık %60\'ını karşılar.',
  },
  {
    id: 'adverbs-connectors', title: 'Zarflar ve cümle bağlayıcıları',
    keywords: ['zarf', 'bağlaç', 'наречие', 'союз', 'bağlayıcı', 'tоже', 'также'],
    content: 'ZAMAN ZARFLARI: сейчас (şimdi), сегодня (bugün), вчера (dün), завтра (yarın), послезавтра, позавчера, рано (erken), поздно (geç), всегда (her zaman), часто (sık sık), иногда (bazen), редко (nadiren), никогда (asla — не ile), уже (artık/çoktan), ещё (hâlâ/daha), ещё не (henüz değil), скоро (yakında), давно (uzun zamandır), недавно (geçenlerde), сразу (hemen), потом (sonra), сначала (önce). YER: здесь/тут (burada), там (orada), везде (her yerde), нигде (hiçbir yerde), дома (evde), домой (eve — hareket!), справа/слева, впереди/сзади. MİKTAR: очень (çok), слишком (fazla), немного (biraz), совсем (tamamen), достаточно (yeterince), почти (neredeyse), только (yalnız), тоже / также (de/da). «Тоже» ile «также» farkı: тоже olumlu benzerlik (Я тоже студент), также ek bilgi (Я также читаю). Olumsuzda «тоже не» kullanılır. BAĞLAÇLAR: и (ve), а (oysa/ama — karşılaştırma), но (ama — karşıtlık), или (veya), потому что (çünkü), поэтому (bu yüzden), хотя (rağmen), если (eğer), когда (-dığında), пока (… iken), чтобы (için), что (ki), который (ki o). Türk öğrenci tuzağı: «а» ile «но»yu ayırmamak — «Я читаю, но он пишет» ✗ (karşıtlık yok) → «Я читаю, а он пишет» ✓.',
  },
  {
    id: 'numbers-full', title: 'Sayı sistemi — asal, sıra ve toplu sayılar',
    keywords: ['sayı', 'rakam', 'числительное', 'birinci', 'ikinci', 'sıra sayısı', 'двое'],
    content: 'ASAL SAYILAR: один/одна/одно (cinsiyete uyar!), два/две (eril-nötr два, dişil две — tek istisna budur), три, четыре, пять, шесть, семь, восемь, девять, десять, одиннадцать…двадцать, тридцать, сорок (kırk — kuraldışı), пятьдесят, шестьдесят, семьдесят, восемьдесят, девяносто (doksan — kuraldışı), сто, двести, триста, четыреста, пятьсот, тысяча, миллион. SIRA SAYILARI sıfat gibi çekilir: первый, второй, третий (düzensiz çekilir), четвёртый, пятый, шестой, седьмой, восьмой, девятый, десятый, одиннадцатый… Tarih ve kat numaralarında sıra sayısı kullanılır: пятый этаж, первое сентября. TOPLU SAYILAR (собирательные): двое, трое, четверо, пятеро — insan gruplarıyla ve çoğul-only isimlerle kullanılır: двое детей (iki çocuk), трое друзей, двое суток. «Два ребёнка» da doğrudur ama «двое детей» daha doğaldır. KESİRLER: половина (yarım), полтора (bir buçuk), четверть (çeyrek), треть (üçte bir). TELEFON/NUMARA okuma ikişerli gruplanır. SAYI UYUMU en kritik kuraldır: 1 → yalın tekil, 2-4 → ilgi tekil, 5+ → ilgi çoğul, 11-14 → istisna olarak ilgi çoğul. Türk öğrenci tuzağı: «два книги» ✗ → «две книги» ✓ (dişil isimle две).',
  },
  {
    id: 'ortography-rules', title: 'Yazım kuralları — ы/и, о/е, ь ne zaman?',
    keywords: ['yazım', 'imla', 'орфография', 'ы и', 'о е', 'yumuşak işaret', 'yazım kuralı'],
    content: 'Rusçanın üç temel yazım kuralı bütün çekimleri yönetir ve ezberlenmesi zorunludur. KURAL 1 (ы/и): к, г, х, ж, ч, ш, щ harflerinden sonra «ы» YAZILMAZ, yerine «и» gelir. Bu yüzden книга→книги (книгы ✗), нога→ноги, карандаш→карандаши, русский (русскый ✗). KURAL 2 (о/е): ж, ч, ш, щ, ц harflerinden sonra VURGUSUZ «о» yazılmaz, yerine «е» gelir. Vurguluysa «о» kalır: муж→мужем (vurgusuz), но большой→большого (vurgulu). Örnek: товарищем, сердцем, хорошее. KURAL 3 (я/ю → а/у): ж, ч, ш, щ harflerinden sonra «я, ю» yazılmaz, «а, у» gelir: слышать→слышу (слышю ✗), кричать→кричат. YUMUŞAK İŞARET (ь): a) ünsüzü inceltir: соль, день; b) dişil isimlerin -ь ile bittiğini gösterir: ночь, дочь; c) ж, ш, ч, щ sonrası dişillik işareti olarak yazılır ama ses vermez: мышь (dişil) ↔ нож (eril, ь yok); d) fiil mastarında ve 2. tekil şahısta: читать, читаешь. AYIRMA İŞARETİ (ъ): yalnız önek + jotlu ünlü sınırında: объявление, съезд, подъезд. Türk öğrenci tuzağı: 2. tekil şahıs ekinde ь\'yi unutmak — «читаеш» ✗ → «читаешь» ✓.',
  },
];
