// DilKoç © 2026 — Bu kaynak kod telif hakkıyla korunur. İzinsiz kopyalama,
// dağıtma ve türev çalışma üretme yasaktır (bkz. LICENSE).
// ============================================================================
// 🛂 VİZE & PASAPORT / VATANDAŞLIK / GÖÇ PAKETİ — RUSÇA (2/2: ünite 26-50)
// ============================================================================

import type { UnitModule } from '../../curriculumData';
import { makeCitUnit, type CitWord, type CitSent, type CitLine } from './makeCitUnit';

const U = (
  id: string, n: number, lv: UnitModule['levelGroup'], icon: string,
  title: string, desc: string, cat: string, color: string, grammar: string,
  words: CitWord[], sents: CitSent[], dlg: CitLine[],
): UnitModule => makeCitUnit({ id, unitNumber: n, level: lv, icon, title, desc, category: cat, color, grammar, words, sents, dlg });

const VAT = "Vatandaşlık";
const GOC = "Göç & Uyum";
const DOGUM = "Doğum & Vatandaşlık";
const RESMI = "Resmî İşlemler";

export const CIT_RU_B: UnitModule[] = [
  U("cit_26", 625, "B2", "⚖️", "Çift Vatandaşlık",
    "İkinci vatandaşlık: izin, bildirim yükümlülüğü",
    VAT, "#8b5cf6",
    "📌 Kısmi olumsuzluk: «не во всех странах» — her ülkede değil.\nKısa passive sıfatlar: разрешено — izinli, запрещено — yasak.",
    [
      ["двойное гражданство", "dvóynaye grajdánstva", "çift vatandaşlık", "İki ülkenin vatandaşı olmak."],
      ["второе гражданство", "ftaróye grajdánstva", "ikinci vatandaşlık", "Sonradan kazanılır."],
      ["уведомить органы", "uyedyamít' órganı", "makamlara bildirmek", "Yasal yükümlülüktür."],
      ["обязанность", "abyázannast'", "yükümlülük", "Vatandaşlıkla gelir."],
      ["разрешено", "razyşyénа", "izinli/mümkün", "Ülkeye göre değişir."],
      ["запрещено", "zapryşyénа", "yasak", "Bazı ülkelerde geçerli."],
    ],
    [
      ["Двойное гражданство разрешено не во всех странах.", "Çift vatandaşlık her ülkede mümkün değil."],
      ["О втором гражданстве нужно уведомить органы.", "İkinci vatandaşlık makamlara bildirilmeli."],
      ["У гражданина двойные права и обязанности.", "Vatandaşın çifte hak ve yükümlülükleri olur."],
    ],
    [
      ["Юрист", "У вас есть второе гражданство?", "U vas yest' ftaróye grajdánstva", "İkinci vatandaşlığınız var mı?"],
      ["Клиент", "Да, я должен уведомить органы?", "Da, ya dóljin uyedyamít' órganı", "Evet, makamlara bildirmem mi gerekir?"],
      ["Юрист", "Да, это обязанность по закону.", "Da, éta abyázannast' pa zakónу", "Evet, kanunen bir yükümlülük."],
    ]),

  U("cit_27", 626, "B2", "🧑‍⚖️", "Vatandaşlık Hukuku ve Avukat",
    "Mevzuat, avukat, dava ve hukuki yardım",
    VAT, "#8b5cf6",
    "📌 «специализироваться на + önerme» — ...uzmanı olmak.\n«рассматривать дело/иск» — davayı görmek.",
    [
      ["законодательство", "zakadayélatyel'stva", "mevzuat (kanunlar)", "Tüm yasaların bütünü."],
      ["адвокат", "advakát", "avukat", "Hukuki temsilcidir."],
      ["консультация", "kansultátsiya", "hukuki danışma", "İlk adım olmalıdır."],
      ["иск", "isk", "dava", "Mahkemeye taşınır."],
      ["суд", "sut", "mahkeme", "Kararı veren organdır."],
      ["правовая помощь", "pravóvaya pómaşch'", "hukuki yardım", "Ücretsiz olanı da vardır."],
    ],
    [
      ["Адвокат специализируется на гражданстве.", "Avukat vatandaşlık hukuku uzmanı."],
      ["Первая консультация бесплатная.", "İlk görüşme ücretsiz."],
      ["Суд рассматривает иски об отказе.", "Mahkeme ret davalarını görür."],
    ],
    [
      ["Клиент", "Мне нужна правовая помощь.", "Mnye nujná pravóvaya pómaşch'", "Hukuki yardıma ihtiyacım var."],
      ["Адвокат", "Расскажите вашу ситуацию.", "Raskajítye váşu sitüátsiyu", "Durumunuzu anlatın."],
      ["Клиент", "Мне отказали в гражданстве.", "Mnye atkazáli f grajdánstvye", "Vatandaşlıktan ret aldım."],
    ]),

  U("cit_28", 627, "C1", "🔄", "Başvuru Reddi ve İtiraz Süreci",
    "Gerekçeli ret, itiraz yolları ve süreler",
    VAT, "#8b5cf6",
    "📌 Passive geçmiş: отклонено — reddedilmiş, принято — kabul edilmiş.\n«можно + fiil» — ...ebilir: можно обжаловать.",
    [
      ["отклонить заявление", "atklanít' zayavlyéniye", "başvuruyu reddetmek", "Olumsuz karardır."],
      ["мотивированный отказ", "mativíravannıy atkáz", "gerekçeli ret", "Nedeni yazılıdır."],
      ["досудебное обжалование", "dasudyébnaye abjalávaniye", "dava öncesi itiraz", "Önce idareye yapılır."],
      ["сроки подачи", "sróki padáchi", "başvuru süreleri", "Kaçırılmamalıdır."],
      ["восстановить срок", "vastanavít' srak", "süreyi iade ettirmek", "Mahkeme yoluyla olur."],
      ["надзорная инстанция", "nadzórnaya instánsiya", "denetim mercii", "Üst itiraz yeridir."],
    ],
    [
      ["Немотивированный отказ можно обжаловать.", "Gerekçesiz ret itiraza açıktır."],
      ["Пропущенный срок можно восстановить через суд.", "Kaçırılan süre mahkemeyle iade ettirilebilir."],
      ["Досудебное обжалование ускоряет процесс.", "Dava öncesi itiraz süreci hızlandırır."],
    ],
    [
      ["Адвокат", "Вы получили мотивированный отказ?", "Vy paluchíli mativíravannıy atkáz", "Gerekçeli ret aldınız mı?"],
      ["Заявитель", "Да, причина — ошибка в документах.", "Da, prichína — ashíbka f dakumyéntah", "Evet, neden belgelerdeki hata."],
      ["Адвокат", "Исправим и подадим жалобу.", "Isprávim i padádim jalóbu", "Düzeltip itiraz dilekçesi veririz."],
    ]),

  U("cit_29", 628, "A2", "🧳", "Göç ve Göçmen Kelimeleri",
    "Göçmen, yabancı, yerel halk: temel göç kelimeleri",
    GOC, "#f59e0b",
    "📌 «откуда» — nereden; «здесь недавно» — yeni burada.\nGeçmiş cinsiyet: приехал / приехала.",
    [
      ["иммигрант", "imigránt", "göçmen (gelen)", "Ülkeye yerleşmek için gelen."],
      ["эмигрант", "yemigránt", "göçmen (giden)", "Ülkeden ayrılan kişidir."],
      ["переезд", "piryeézd", "taşınma", "Yeni yere yerleşmedir."],
      ["родной язык", "radnóy yazyk", "ana dili", "Çocuklukta öğrenilen dil."],
      ["иностранец", "inastrányeц", "yabancı (uyruklu)", "Başka ülke vatandaşı."],
      ["местные жители", "myéstnıyye zhíteli", "yerel halk", "O bölgede yaşayanlar."],
    ],
    [
      ["Он иммигрант: приехал из другой страны.", "O göçmen: başka ülkeden geldi."],
      ["Родной язык у меня турецкий.", "Ana dilim Türkçe."],
      ["Местные жители очень добрые.", "Yerel halk çok iyi kalpli."],
    ],
    [
      ["Сосед", "Откуда вы приехали?", "Atkúda vy priyéхali", "Nereden geldiniz?"],
      ["Иммигрант", "Из Турции. Я здесь недавно.", "Is Turtsíi. Ya zdyés' nyevdávna", "Türkiye'den. Yeni buradayım."],
      ["Сосед", "Добро пожаловать в наш город!", "Dabró pajálavat' v naş górad", "Şehrimize hoş geldiniz!"],
    ]),

  U("cit_30", 629, "B2", "🕊️", "Sığınma Başvurusu",
    "Sığınma isteme, zulüm ve mülakat",
    GOC, "#f59e0b",
    "📌 «из-за + ilgi hâli» — ...nedeniyle (olumsuz neden): из-за преследования.\nBelirtisiz nesne → eril geçmiş: Меня преследовали.",
    [
      ["убежище", "ubyéjisch'ye", "sığınma", "Korunma hakkıdır."],
      ["просить убежище", "prasít' ubyéjisch'ye", "sığınma istemek", "Resmî başvurudur."],
      ["преследование", "pryeslyédavaniye", "zulüm/takip", "Başvuru nedenidir."],
      ["беженец", "byejyéneц", "mülteci", "Zorunlu göçmendir."],
      ["гуманитарный статус", "gumanitárnıy státus", "insani statü", "Koruma biçimidir."],
      ["интервью с офицером", "intyrvyú s afítsyeram", "memurla görüşme", "Başvurunun ana adımı."],
    ],
    [
      ["Он попросил убежище из-за преследования.", "Zulüm nedeniyle sığınma istedi."],
      ["Заявление подают на границе или внутри страны.", "Başvuru sınırda veya ülke içinde yapılır."],
      ["Офицер проводит подробное интервью.", "Memur ayrıntılı görüşme yapar."],
    ],
    [
      ["Офицер", "Почему вы просите убежище?", "Pachimú vy prósitye ubyéjisch'ye", "Neden sığınma istiyorsunuz?"],
      ["Заявитель", "Меня преследовали на родине.", "Minya pryeslyédavali na radínye", "Vatanımda zulüm gördüm."],
      ["Офицер", "Расскажите всё подробно.", "Raskajítye fsyo padróbna", "Her şeyi ayrıntılı anlatın."],
    ]),

  U("cit_31", 630, "B2", "🛡️", "Mülteci Statüsü ve Haklar",
    "Mülteci statüsü: korunma, konut, sağlık ve yardım",
    GOC, "#f59e0b",
    "📌 «право на + önerme» — ...hakkı: право на защиту.\n«после + ilgi hâli» — ...sonra.",
    [
      ["статус беженца", "státus byejyénцa", "mülteci statüsü", "Uluslararası korumadır."],
      ["защита", "zaştchíta", "korunma", "Temel haktır."],
      ["жильё", "jilyó", "konut/barınak", "İlk ihtiyaçtır."],
      ["пособие", "pasóbiye", "sosyal yardım", "Devlet desteğidir."],
      ["медицинская помощь", "miditsínskaya pómaşch'", "sağlık yardımı", "Acil durumlarda zorunlu."],
      ["временное размещение", "vryéminnaye razmyeschchyéniye", "geçici barındırma", "İlk aşamada verilir."],
    ],
    [
      ["Статус беженца даёт право на защиту.", "Mülteci statüsü korunma hakkı verir."],
      ["Семья получила жильё и пособие.", "Aile konut ve yardım aldı."],
      ["Медицинская помощь бесплатна для беженцев.", "Sağlık yardımı mültecilere ücretsizdir."],
    ],
    [
      ["Социальный работник", "Вот ваше временное размещение.", "Vot váşye vryéminnaye razmyeschchyéniye", "İşte geçici barındırmanız."],
      ["Беженец", "Спасибо. А работать можно?", "Spasíba. A rabótat' mójna", "Teşekkürler. Çalışmak mümkün mü?"],
      ["Социальный работник", "Да, после получения статуса.", "Da, póslye paluchyéniya státusa", "Evet, statü alındıktan sonra."],
    ]),

  U("cit_32", 631, "C1", "⚖️", "Sınır Dışı ve Yasal Duruş",
    "Sınır dışı etme, giriş yasağı ve hukuki mücadele",
    GOC, "#f59e0b",
    "📌 Zincirleme ilgi hâli: из-за нарушения срока — süre ihlalinden.\nFiil–isim çifti: решение → решить.",
    [
      ["депортация", "dipartátsiya", "sınır dışı etme", "Zorla çıkarılmadır."],
      ["выдворение", "vyдварyéniye", "idari sınır dışı", "Mahkeme kararıyla olur."],
      ["запрет на въезд", "zapryét na vyezd", "giriş yasağı", "Yıllarca sürebilir."],
      ["решение суда", "ryshyéniye sudá", "mahkeme kararı", "İtiraz edilebilir."],
      ["адвокат по миграции", "advakát pa migrátsii", "göç hukuku avukatı", "Uzman desteğidir."],
      ["основания", "asnávaniya", "gerekçeler", "Kararın dayanağıdır."],
    ],
    [
      ["Депортацию можно обжаловать в суде.", "Sınır dışı karara mahkemede itiraz edilebilir."],
      ["Запрет на въезд действует пять лет.", "Giriş yasağı beş yıl geçerli."],
      ["Суд изучит основания для выдворения.", "Mahkeme sınır dışı gerekçelerini inceleyecek."],
    ],
    [
      ["Адвокат", "Вам грозит депортация?", "Vam grozít dipartátsiya", "Sınır dışı riski mi var?"],
      ["Клиент", "Да, из-за нарушения срока.", "Da, is-za narushyéniya sróka", "Evet, süre ihlali nedeniyle."],
      ["Адвокат", "Подадим апелляционную жалобу.", "Padádim apyellyatsiónnuу jалóbu", "İtiraz dilekçesi vereceğiz."],
    ]),

  U("cit_33", 632, "A2", "👣", "Yeni Ülkeye İlk Adımlar",
    "Yeni ülkede ilk günler: yol sorma, komşular, market",
    GOC, "#f59e0b",
    "📌 Yön zarfları: прямо — düz, направо — sağa, налево — sola.\n«показать кому что» — birine bir şeyi göstermek.",
    [
      ["первые шаги", "pyérvıyye şági", "ilk adımlar", "Yeni başlangıçtır."],
      ["город", "górad", "şehir", "Yeni yaşam alanı."],
      ["соседи", "sasyédi", "komşular", "İlk tanışılan kişiler."],
      ["продукты", "pradúkty", "market/erzak", "Günlük ihtiyaçtır."],
      ["дорога", "daróga", "yol", "Şehri öğrenmekle başlar."],
      ["спросить дорогу", "sprasít' darógu", "yol sormak", "Yabancıdan istenir."],
    ],
    [
      ["Первые шаги в новой стране — самые трудные.", "Yeni ülkede ilk adımlar en zor olanlardır."],
      ["Я спросил дорогу у прохожего.", "Bir yayaya yol sordum."],
      ["Соседи показали мне магазин.", "Komşular bana marketi gösterdi."],
    ],
    [
      ["Новичок", "Извините, где магазин продуктов?", "Izvinítye, gdye magazín pradúktav", "Affedersiniz, market nerede?"],
      ["Прохожий", "Идите прямо, потом направо.", "Idítye pryáma, patóm napráva", "Düz gidin, sonra sağa dönün."],
      ["Новичок", "Большое спасибо!", "Bal'shóye spasíba", "Çok teşekkür ederim!"],
    ]),

  U("cit_34", 633, "B1", "🌉", "Kültür Şoku ve Entegrasyon",
    "Kültür şoku, gelenekler ve uyum süreci",
    GOC, "#f59e0b",
    "📌 Reflexive: «чувствовать себя + hâl» — kendini ... hissetmek: чувствовать себя чужим.\n«сначала... но...» — önce... ama...",
    [
      ["культурный шок", "kul'túrnyy şok", "kültür şoku", "Yeni kültürde yaşanır."],
      ["традиции", "tradítsii", "gelenekler", "Küçükten öğrenilir."],
      ["обычаи", "abы́чai", "örf ve adetler", "Toplum kurallarıdır."],
      ["адаптация", "adaptátsiya", "uyum", "Zamanla gerçekleşir."],
      ["чувствовать себя чужим", "чuvstvavat' syebyá чujim", "kendini yabancı hissetmek", "Şokun belirtisidir."],
      ["со временем", "sa vryéminem", "zamanla", "Her şey düzelir."],
    ],
    [
      ["Культурный шок проходит со временем.", "Kültür şoku zamanla geçer."],
      ["Я изучаю местные традиции и обычаи.", "Yerel gelenekleri ve adetleri öğreniyorum."],
      ["Сначала я чувствовал себя чужим.", "Başta kendimi yabancı hissettim."],
    ],
    [
      ["Друг", "Тебе трудно здесь?", "Tibyé trúdna zdyés'", "Burada zorlanıyor musun?"],
      ["Иммигрант", "Сначала да, но сейчас лучше.", "Snachála da, no ichás lúчшye", "Başta evet ama şimdi daha iyi."],
      ["Друг", "Всё будет хорошо, со временем.", "Fsyo búdit harashó, sa vryéminem", "Her şey zamanla iyi olacak."],
    ]),

  U("cit_35", 634, "B1", "🗒️", "İlk Günler: Kayıt İşlemleri",
    "Yeni gelenin listesi: kayıt, banka, SIM kart, sigorta",
    GOC, "#f59e0b",
    "📌 «с чего начать?» — nereden başlamalı?\nGeçmiş çift fiiller: открыл и купил — açtım ve aldım.",
    [
      ["зарегистрироваться", "zaryegistríravatsa", "kayıt olmak", "İlk resmî adımdır."],
      ["идентификационный номер", "idyentifikatsiónnыy nómyer", "kimlik numarası", "Vergi/kimlik için verilir."],
      ["открыть счёт в банке", "atkrýt' şchót f bánkye", "banka hesabı açmak", "Maaş/ödeme için gerekir."],
      ["сим-карта", "sim-kárta", "SIM kart", "İletişim ilk ihtiyaçtır."],
      ["медицинская страховка", "miditsínskaya strahófka", "sağlık sigortası", "Devlet veya özel."],
      ["документы в порядке", "dakumyéntу f paryádkye", "evraklar tamam", "Her şey hazır demektir."],
    ],
    [
      ["Сначала нужно зарегистрироваться по адресу.", "Önce adrese kayıt olmak gerekir."],
      ["Я открыл счёт и купил сим-карту.", "Banka hesabı açtım ve SIM kart aldım."],
      ["Теперь все документы в порядке.", "Artık tüm evraklar tamam."],
    ],
    [
      ["Консультант", "Вы уже зарегистрировались?", "Vy ujye zaryegistríravalis'", "Kayıt oldunuz mu?"],
      ["Приезжий", "Да, вчера. Что дальше?", "Da, vchyerá. Shtó dál'şye", "Evet, dün. Sıradaki ne?"],
      ["Консультант", "Откройте счёт и оформите страховку.", "Atkrýtye şchót i afrmítye strahófku", "Hesap açın ve sigorta yaptırın."],
    ]),

  U("cit_36", 635, "B1", "🏫", "Dil Kursları ve Uyum Programları",
    "Ücretsiz dil kursları, seviye testi ve dersler",
    GOC, "#f59e0b",
    "📌 «три раза в неделю» — haftada üç kez (tekrar kalıbı).\n«записаться на + önerme» — ...a kaydolmak.",
    [
      ["языковые курсы", "yazykóvыyye kúrsı", "dil kursları", "Belediye/devlet verir."],
      ["занятия", "zanyátiya", "dersler", "Haftalık programı vardır."],
      ["бесплатно", "byesplatna", "ücretsiz", "Uyum kurslarında olur."],
      ["уровень", "úryivin'", "seviye", "A1'den başlar."],
      ["тест на уровень", "tyest na úryivin'", "seviye testi", "Kayıt öncesi yapılır."],
      ["практика", "práktika", "pratik/uygulama", "Konuşma geliştirir."],
    ],
    [
      ["Город предлагает бесплатные языковые курсы.", "Belediye ücretsiz dil kursları sunuyor."],
      ["Сначала вы проходите тест на уровень.", "Önce seviye testine girersiniz."],
      ["Занятия идут три раза в неделю.", "Dersler haftada üç kez."],
    ],
    [
      ["Администратор", "Вы хотите записаться на курсы?", "Vy khatítye zapissátsa na kúrsı", "Kursa yazılmak ister misiniz?"],
      ["Студент", "Да. Есть вечерние занятия?", "Da. Yest' vyechyérniyye zanyátiya", "Evet. Akşam dersleri var mı?"],
      ["Администратор", "Да, в семь часов, бесплатно.", "Da, f syem' чasóf, byesplatna", "Evet, yedide, ücretsiz."],
    ]),

  U("cit_37", 636, "B2", "👪", "Eş ve Çocuklar için İşlemler",
    "Aile belgeleri: apostil, çeviri, vasilik",
    GOC, "#f59e0b",
    "📌 «понадобиться» — gerekmek: Понадобится апостиль.\nPassive çoğul: легализуются — yasallaştırılır.",
    [
      ["семейное положение", "syeмyéynaye palajyéniye", "medeni hâl", "Evli/bekâr bilgisidir."],
      ["апостиль", "apastíl'", "apostil", "Uluslararası onaydır."],
      ["легализация", "lyegalizátsiya", "yasallaştırma", "Yabancı belge onayı."],
      ["перевод документов", "piryevót dakumyéntav", "belge çevirisi", "Yetkili çevirmen yapar."],
      ["опекун", "apyekáun", "vasi", "Çocuk için atanır."],
      ["несовершеннолетние дети", "nyisavyrshennalyétniyye dyéti", "reşit olmayan çocuklar", "18 yaş altıdır."],
    ],
    [
      ["Свидетельства легализуются через апостиль.", "Belgeler apostille ile yasallaştırılır."],
      ["Перевод документов делает нотариус.", "Belge çevirisini noter yapar."],
      ["Для детей нужны копии свидетельств о рождении.", "Çocuklar için doğum belgesi kopyaları gerekir."],
    ],
    [
      ["Сотрудник", "Дети поедут с вами?", "Dyéti poyédut s vámi", "Çocuklar sizinle mi gelecek?"],
      ["Родитель", "Да, вот их документы и переводы.", "Da, vot ih dakumyéntу i piryevódy", "Evet, işte belgeleri ve çevirileri."],
      ["Сотрудник", "Понадобится апостиль на каждый документ.", "Panadóbitsa apastíl' na kájdyy dakumyént", "Her belge için apostil gerekecek."],
    ]),

  U("cit_38", 637, "B2", "💠", "Nitelikli Göçmen ve Mavi Kart",
    "Mavi kart, diploma denkliği ve nitelikli uzmanlık",
    GOC, "#f59e0b",
    "📌 Kısa passive: выдана — verilmiş, признан — tanınmış.\n«значит» — demek ki.",
    [
      ["квалифицированный специалист", "kvalifitsíravannыy spyetsialíst", "nitelikli uzman", "Meslek sahibi göçmen."],
      ["голубая карта", "galubáya kárta", "mavi kart", "AB nitelikli göçmen kartı."],
      ["подтверждение диплома", "padtvyerjdyéniye diplóma", "diploma denkliği", "Eşdeğerlik tanınması."],
      ["признание", "priznániye", "tanınma/kabul", "Denklik sonucudur."],
      ["профессия", "prafyéssiya", "meslek", "Uzmanlık alanıdır."],
      ["зарплата", "zarpláta", "maaş", "Eşik alt sınırı vardır."],
    ],
    [
      ["Голубая карта выдаётся квалифицированным специалистам.", "Mavi kart nitelikli uzmanlara verilir."],
      ["Диплом должен пройти признание.", "Diplomanın denklik işleminden geçmesi gerekir."],
      ["Для карты нужна высокая зарплата.", "Kart için yüksek maaş gerekir."],
    ],
    [
      ["Работник", "Мой диплом признали?", "Moy diplóm priznali", "Diplomam tanındı mı?"],
      ["Служащий", "Да, вы квалифицированный специалист.", "Da, vy kvalifitsíravannыy spyetsialíst", "Evet, nitelikli bir uzmansınız."],
      ["Работник", "Значит, я могу получить голубую карту.", "Znachit, ya magú paluchít' galubúyu kártу", "Demek mavi kart alabilirim."],
    ]),

  U("cit_39", 638, "B1", "🗺️", "Vatandaşlığa Giden Yol",
    "Yol haritası: aşamalar, sabır ve hedef",
    GOC, "#f59e0b",
    "📌 «путь к + önerme» — ...yolu: путь к гражданству.\n«занимать + süre» — sürmek: занимает годы.",
    [
      ["путь", "put'", "yol", "Uzun bir süreçtir."],
      ["этап", "etáp", "aşama", "Her adım bir etaptır."],
      ["шаг за шагом", "şag za šágam", "adım adım", "Sabırla ilerlemektir."],
      ["подготовка", "padgatófka", "hazırlık", "Belgelerle başlar."],
      ["терпение", "tirpéniye", "sabır", "En gerekli şeydir."],
      ["цель", "tsél'", "hedef", "Vatandaşlıktır."],
    ],
    [
      ["Путь к гражданству занимает несколько лет.", "Vatandaşlık yolu birkaç yıl sürer."],
      ["Идите к цели шаг за шагом.", "Hedefe adım adım ilerleyin."],
      ["Главное — терпение и подготовка.", "En önemlisi sabır ve hazırlık."],
    ],
    [
      ["Консультант", "Какая ваша цель?", "Kakáya váşa tsél'", "Hedefiniz ne?"],
      ["Мигрант", "Получить гражданство этой страны.", "Paluchít' grajdánstva étoy stranı", "Bu ülkenin vatandaşlığını almak."],
      ["Консультант", "Отличная цель. Начнём с этапа проживания.", "Atlíčnaya tsél'. Nachnyóm s etápa prajıvániya", "Harika bir hedef. İkamet aşamasıyla başlayalım."],
    ]),

  U("cit_40", 639, "B2", "⏳", "Uzun Süreli İkamet Yolu",
    "İkamet süresi: kesintisizlik ve yurt dışı çıkışları",
    GOC, "#f59e0b",
    "📌 «влиять на + önerme» — ...etkilemek: влияет на срок.\nSayı çekimi: два месяца — iki ay.",
    [
      ["длительное проживание", "dlítel'naye prajıvániye", "uzun süreli ikamet", "Statünün temelidir."],
      ["считать срок", "şchitát' srak", "süreyi saymak", "Gün gün hesaplanır."],
      ["отсутствие", "atsútstviye", "yokluk/dışarıda kalma", "Süreyi etkileyebilir."],
      ["прерывать срок", "pryervát' srak", "süreyi bölmek", "Uzun ayrılık yapar."],
      ["долгосрочная виза", "dalgasróčnaya víza", "uzun süreli vize", "İlk adımdır."],
      ["статус", "státus", "statü", "Hakları belirler."],
    ],
    [
      ["Длительное проживание даёт право на статус.", "Uzun süreli ikamet statü hakkı verir."],
      ["Долгое отсутствие прерывает срок.", "Uzun süre ülkede olmamak süreyi böler."],
      ["Долгосрочная виза — первый шаг.", "Uzun süreli vize ilk adımdır."],
    ],
    [
      ["Инспектор", "Вы выезжали за последние пять лет?", "Vy выyejjáli za póslyedniye pyat' lyeт", "Son beş yılda yurt dışına çıktınız mı?"],
      ["Заявитель", "Да, на два месяца.", "Da, na dva myésyatsa", "Evet, iki aylığına."],
      ["Инспектор", "Это не прерывает срок.", "Éta nye pryerváyvayet srak", "Bu süreyi bölemez."],
    ]),

  U("cit_41", 640, "B1", "👶", "Doğum Yoluyla Vatandaşlık",
    "Doğumla vatandaşlık kazanımı ve işleyişi",
    DOGUM, "#ec4899",
    "📌 «по + önerme» — yolla anlamı: по рождению — doğum yoluyla.\n«родился / родилась / родились» — doğdu (cinsiyet/çoğul).",
    [
      ["по рождению", "pa rajdyéniyu", "doğum yoluyla", "Kazanım türüdür."],
      ["новорождённый", "navarajdyónnыy", "yenidoğan", "Kayıtla başlar."],
      ["приобретать гражданство", "priabryetat' grajdánstva", "vatandaşlık kazanmak", "Doğumla otomatiktir."],
      ["автоматически", "avtamatíçyеski", "otomatik olarak", "Başvuru gerektirmez."],
      ["родители", "radítyeli", "ebeveynler", "Statüyü belirler."],
      ["место рождения", "myésto rajdyéniya", "doğum yeri", "Kuralarda önemlidir."],
    ],
    [
      ["Ребёнок приобретает гражданство по рождению.", "Çocuk doğumla vatandaşlık kazanır."],
      ["Это право работает автоматически.", "Bu hak otomatik işler."],
      ["Место рождения влияет на гражданство.", "Doğum yeri vatandaşlığı etkiler."],
    ],
    [
      ["Родитель", "Наш ребёнок родился здесь.", "Nash ryebyónak radílsa zdyés'", "Çocuğumuz burada doğdu."],
      ["Сотрудник", "Он получает гражданство по рождению.", "On palucháyет grajdánstva pa rajdyéniyu", "Doğum yoluyla vatandaşlık alır."],
      ["Родитель", "Какие документы нужны?", "Kakíyye dakumyéntу nujnı", "Hangi belgeler gerekli?"],
    ]),

  U("cit_42", 641, "A2", "📜", "Doğum Belgesi ve Kayıt",
    "Doğum kaydı: hastane belgesi, nüfus müdürlüğü, isim",
    DOGUM, "#ec4899",
    "📌 «регистрировать в + önerme» — ...da kaydetmek.\nKısaltmalar da çekilir: в ЗАГСе — nüfus müdürlüğünde.",
    [
      ["справка из роддома", "spráfka iz roddóма", "hastane doğum belgesi", "Kayıt için gerekir."],
      ["роддом", "roddóm", "doğum hastanesi", "Belgeyi verir."],
      ["ЗАГС", "zaks", "nüfus müdürlüğü", "Kayıt burada yapılır."],
      ["имя", "ímya", "ad", "Aile seçer."],
      ["фамилия", "famíliya", "soyad", "Ebeveynden alınır."],
      ["зарегистрировать рождение", "zaryegistríravat' rajdyéniye", "doğumu kaydetmek", "İlk yasal adımdır."],
    ],
    [
      ["Рождение регистрируют в ЗАГСе.", "Doğum nüfus müdürlüğünde kaydedilir."],
      ["Справка из роддома нужна для регистрации.", "Kayıt için hastane belgesi gerekir."],
      ["Мы выбрали имя для ребёнка.", "Çocuk için isim seçtik."],
    ],
    [
      ["Мать", "Где зарегистрировать рождение?", "Gdye zaryegistríravat' rajdyéniye", "Doğumu nerede kaydederiz?"],
      ["Работник ЗАГСа", "В нашем отделе, возьмите талон.", "V našem atdyélye, vaz'mítye talón", "Bizim birimde, sıra numarası alın."],
      ["Мать", "Спасибо, мы принесли справку из роддома.", "Spasíba, my prinyeslí spráfku iz roddóма", "Teşekkürler, hastane belgesini getirdik."],
    ]),

  U("cit_43", 642, "B1", "👨‍👩‍👦", "Ana-Baba Vatandaşlığı ve Çocuk",
    "Ebeveyn statüsünün çocuğa etkisi",
    DOGUM, "#ec4899",
    "📌 «оба / обе» — her ikisi (eril / dişil): оба родителя.\n«ставить отметку» — damga/kayıt basmak.",
    [
      ["оба родителя", "óba radítyelya", "her iki ebeveyn", "Statü birlikte değerlendirilir."],
      ["по матери", "pa mátyeri", "anneden (taraf)", "Kan bağı yoludur."],
      ["по отцу", "pa atsú", "babadan (taraf)", "Diğer kan yoludur."],
      ["гражданство родителей", "grajdánstva radítyelеy", "ebeveynlerin vatandaşlığı", "Çocuğu belirler."],
      ["вкладыш", "vkládыş", "belge ek yaprağı", "Vatandaşlık kanıtıdır."],
      ["отметка", "atmyétka", "kayıt (şerh)", "Belgeye basılır."],
    ],
    [
      ["Ребёнок получает гражданство по матери или по отцу.", "Çocuk vatandaşlığı anneden veya babadan alır."],
      ["Гражданство родителей подтверждается паспортами.", "Ebeveyn vatandaşlığı pasaportlarla kanıtlanır."],
      ["В свидетельстве ставят отметку.", "Belgeye kayıt damgası basılır."],
    ],
    [
      ["Сотрудник", "Кто гражданин — мать или отец?", "Kto grajdanín — máт' ili átyeц", "Vatandaş kim — anne mi baba mı?"],
      ["Отец", "Оба родителя — граждане.", "Óba radítyelya — grajdánye", "Her iki ebeveyn de vatandaş."],
      ["Сотрудник", "Тогда ребёнок гражданин по рождению.", "Tagdá ryebyónak grajdanín pa rajdyéniyu", "O zaman çocuk doğumla vatandaş."],
    ]),

  U("cit_44", 643, "B2", "🌍", "Toprakta Doğma Hakkı (Jus Soli)",
    "Doğum yerine göre vatandaşlık ilkesi",
    DOGUM, "#ec4899",
    "📌 Kısmi olumsuzluk: «не каждое государство» — her devlet değil.\nFiil çifti: признавать → признать — tanımak.",
    [
      ["право почвы", "práva póčvy", "toprak hakkı (jus soli)", "Doğum yerine dayanır."],
      ["уроженец", "urajdyéneц", "doğumlu (yerli)", "O ülkede doğandır."],
      ["территория", "tyerritóriya", "ülke toprağı", "İlkenin kapsamıdır."],
      ["принцип", "printsíp", "ilke", "Her ülkeninki farklıdır."],
      ["исключение", "ysklyuchyéniye", "istisna", "Kurallarda vardır."],
      ["государство", "gasudárstva", "devlet", "İlkeyi belirler."],
    ],
    [
      ["Право почвы означает гражданство по месту рождения.", "Toprak hakkı, doğum yerine göre vatandaşlık demektir."],
      ["Не каждое государство признаёт этот принцип.", "Her devlet bu ilkeyi tanımaz."],
      ["Уроженец страны — её гражданин.", "Ülkenin doğumlusu onun vatandaşıdır."],
    ],
    [
      ["Студент", "Что такое право почвы?", "Shtó takóye práva póčvy", "Toprak hakkı nedir?"],
      ["Преподаватель", "Гражданство по месту рождения.", "Grajdánstva pa myéstу rajdyéniya", "Doğum yerine göre vatandaşlık."],
      ["Студент", "А есть исключения?", "A yest' ysklyuchyéniya", "İstisnalar var mı?"],
    ]),

  U("cit_45", 644, "B2", "🩸", "Kan Bağı Hakkı (Jus Sanguinis)",
    "Soy bağıyla vatandaşlık: köken ve atalar",
    DOGUM, "#ec4899",
    "📌 «передаваться через + önerme» — ...ile geçmek.\nSayı çekimi: сто лет — yüz yıl.",
    [
      ["право крови", "práva króvi", "kan bağı hakkı (jus sanguinis)", "Soyla geçer."],
      ["происхождение", "praisxajdyéniye", "köken/soy", "Belgelerle gösterilir."],
      ["предки", "pryatkí", "atalar", "Aile geçmişidir."],
      ["наследство", "nastyyédstva", "miras", "Kültürel bağdır."],
      ["поколение", "pakalyéniye", "kuşak", "Soy zinciridir."],
      ["этнические корни", "etníçyеskiyye kórni", "etnik kökler", "Köken statüsüdür."],
    ],
    [
      ["Право крови передаётся через происхождение.", "Kan hakkı soyla geçer."],
      ["Мои предки жили здесь сто лет назад.", "Atalarım yüz yıl önce burada yaşıyordu."],
      ["Каждое поколение сохраняет корни.", "Her kuşak köklerini korur."],
    ],
    [
      ["Заявитель", "Мои предки были гражданами.", "Móи pryatkí býchí grajdánami", "Atalarım vatandaştı."],
      ["Юрист", "Тогда действует право крови.", "Tagdá dyéystvuyet práva króvi", "O zaman kan hakkı geçerli."],
      ["Заявитель", "Какие документы подтвердят происхождение?", "Kakíyye dakumyéntу padtvyérdyat praisxajdyéniye", "Hangi belgeler kökeni kanıtlar?"],
    ]),

  U("cit_46", 645, "B2", "🤝", "Evlat Edinme ve Vatandaşlık",
    "Evlat edinme: mahkeme, çıkarın gözetilmesi, aile",
    DOGUM, "#ec4899",
    "📌 «в интересах + ilgi hâli» — ...yararına: в интересах ребёнка.\nPassive: оформляется — yapılır/düzenlenir.",
    [
      ["усыновление", "usыnavlyéniye", "evlat edinme", "Mahkemeyle gerçekleşir."],
      ["усыновитель", "usыnavítyel'", "evlat edinen", "Başvuran taraftır."],
      ["приёмные родители", "priyómnыyyе radítyeli", "koruyucu ebeveyn", "Çocuğa aile verir."],
      ["судебное решение", "sudyébnaye ryshyéniye", "mahkeme kararı", "Sürecin sonucudur."],
      ["интересы ребёнка", "intyérésу ryebyónka", "çocuğun yararı", "En üst unsurdur."],
      ["семья", "seм'yá", "aile", "Çocuğun hakkıdır."],
    ],
    [
      ["Усыновление оформляется через суд.", "Evlat edinme mahkemeyle yapılır."],
      ["Суд защищает интересы ребёнка.", "Mahkeme çocuğun yararını korur."],
      ["Приёмные родители дают ребёнку семью.", "Koruyucu ebeveynler çocuğa aile verir."],
    ],
    [
      ["Судья", "Вы понимаете ответственность усыновления?", "Vy панimáyitye atvyétstvyennast' usыnavlyéniya", "Evlat edinmenin sorumluluğunu anlıyor musunuz?"],
      ["Приёмный родитель", "Да, мы готовы.", "Da, my gatóvy", "Evet, hazırız."],
      ["Судья", "Решение принято в интересах ребёнка.", "Ryshyéniye prínyato v intyérésah ryebyónka", "Karar çocuğun yararına alındı."],
    ]),

  U("cit_47", 646, "B1", "📋", "Resmî Formlar ve Beyan Dili",
    "Form doldurma: alan, imza, zorunlu bölümler",
    RESMI, "#10b981",
    "📌 Emir kipi (kibar çoğul): заполните — doldurun, укажите — belirtin, поставьте — koyun.",
    [
      ["бланк", "blank", "form (kağıdı)", "Resmî evrakın kendisidir."],
      ["поле", "pólye", "form alanı", "Her kutucuk bir alandır."],
      ["заполнить", "zapólnit'", "doldurmak", "Blok harflerle yapılır."],
      ["указать", "ukazát'", "belirtmek", "Bilgiyi yazmaktır."],
      ["подпись", "pódpis'", "imza", "Formun sonunda atılır."],
      ["дата заполнения", "dáta zapolnyéniya", "doldurma tarihi", "Zorunlu alandır."],
    ],
    [
      ["Заполните бланк печатными буквами.", "Formu blok harflerle doldurun."],
      ["Укажите дату и поставьте подпись.", "Tarihi belirtin ve imzayı atın."],
      ["Поля, отмеченные звёздочкой, обязательны.", "Yıldızlı alanlar zorunludur."],
    ],
    [
      ["Сотрудник", "Почему не заполнено это поле?", "Pachimú nye zapólnyna eta pólye", "Bu alan neden boş?"],
      ["Клиент", "Я не понял, что туда писать.", "Ya nye панyal, shtо tudá písat'", "Oraya ne yazacağımı anlamadım."],
      ["Сотрудник", "Укажите адрес и дату.", "Ukajítye ádryes i dátu", "Adresi ve tarihi yazın."],
    ]),

  U("cit_48", 647, "A2", "☎️", "Randevu, Sıra ve Telefon Görüşmesi",
    "Telefonla randevu: meşgul hat, geri arama",
    RESMI, "#10b981",
    "📌 «была занята» — meşguldü (dişil kısa sıfat, «линия» dişildir).\nGeri-önek: перезвонить — geri aramak.",
    [
      ["позвонить", "pazvanít'", "telefon etmek", "İlk iletişim yoludur."],
      ["назначить встречу", "naznáčit' vstryéчu", "randevu belirlemek", "Telefonla yapılır."],
      ["одну минуту", "adnú minútu", "bir dakika", "Bekletme ifadesidir."],
      ["линия занята", "líniya zanyatá", "hat meşgul", "Tekrar aramak gerekir."],
      ["перезвонить", "piryezvanít'", "geri aramak", "Sık yaşanır."],
      ["свободное время", "svabódnaye vryémya", "müsait zaman", "Randevu buna alınır."],
    ],
    [
      ["Я позвонил в визовый центр.", "Başvuru merkezini aradım."],
      ["Линия была занята, я перезвонил.", "Hat meşguldü, geri aradım."],
      ["Назначьте встречу на свободное время.", "Randevuyu müsait bir zamana koyun."],
    ],
    [
      ["Оператор", "Здравствуйте, визовый центр.", "Zdrástvuytye, vízavыy tséntr", "Merhaba, başvuru merkezi."],
      ["Клиент", "Здравствуйте. Хочу назначить встречу.", "Zdrástvuytye. Khachú naznáčit' vstryéчu", "Merhaba. Randevu almak istiyorum."],
      ["Оператор", "Подождите минуту... Есть место в пятницу.", "Padajdítye minútu... Yest' myésta v pyátnitsu", "Bir dakika bekleyin... Cuma günü uygun var."],
    ]),

  U("cit_49", 648, "A2", "📖", "Belge ve Terimler Sözlüğü",
    "Kopya, onay, çeviri, arşiv: resmî terimler",
    RESMI, "#10b981",
    "📌 «нужен / нужна / нужно» — gereken (cinsiyete göre): нужна выписка.\n«из + ilgi hâli» — ...den: выписка из архива.",
    [
      ["копия", "kópiya", "kopya", "Aslın ikizidir."],
      ["заверить", "zavyérit'", "onaylatmak", "Noter yapar."],
      ["переводчик", "piryevóçik", "çevirmen", "Yetkili olmalıdır."],
      ["выписка", "vыpiska", "resmî belge örneği", "Kayıttan çıkarılır."],
      ["архив", "arhíf", "arşiv", "Eski kayıtlar buradadır."],
      ["срок действия", "srak dyéystviya", "geçerlilik süresi", "Belgede yazar."],
    ],
    [
      ["Мне нужна выписка из архива.", "Arşivten resmî belge örneği gerekiyor."],
      ["Копию нужно заверить у нотариуса.", "Kopya notere onaylatılmalı."],
      ["Проверьте срок действия документа.", "Belgenin geçerlilik süresini kontrol edin."],
    ],
    [
      ["Клиент", "Можно заверить копию?", "Mójna zavyérit' kópiyu", "Kopya onaylanabilir mi?"],
      ["Нотариус", "Да, покажите оригинал.", "Da, păjíjitye ariginal", "Evet, aslını gösterin."],
      ["Клиент", "Вот, и проверьте срок действия.", "Vot, i pravyér'tye srak dyéystviya", "İşte, geçerlilik süresini de kontrol edin."],
    ]),

  U("cit_50", 649, "C1", "🎓", "Vatandaşlık Yolculuğu: Tüm Süreç",
    "Naturalizasyon: baştan sona tüm süreç bir arada",
    RESMI, "#10b981",
    "📌 «до + ilgi hâli» — ...e kadar: от начала до конца — baştan sona.\nFiil isimleri: соблюдение — uyum, получение — alma.",
    [
      ["натурализация", "naturalizátsiya", "naturalizasyon", "Vatandaşlığa kabul süreci."],
      ["от начала до конца", "at načála da kantsá", "baştan sona", "Tüm yolculuğu anlatır."],
      ["соблюдение сроков", "sablyudyéniye srókav", "sürelere uyum", "Başarının anahtarıdır."],
      ["финальный этап", "final'nыy etáp", "son aşama", "Yemin törenidir."],
      ["долгожданный", "dalgajdánпый", "uzun zamân beklenen", "Gün sonunda gelir."],
      ["гордость", "górdast'", "gurur", "Yeni vatandaşın hissi."],
    ],
    [
      ["Натурализация — это путь от начала до конца.", "Naturalizasyon baştan sona bir yoldur."],
      ["Ключ к успеху — соблюдение сроков.", "Başarının anahtarı sürelere uymaktır."],
      ["Долгожданный финальный этап — присяга.", "Uzun beklenen son aşama yemindir."],
    ],
    [
      ["Репортёр", "Как вы дошли до конца процесса?", "Kak vy daşlí da kantsá pratsyéssa", "Sürecin sonuna nasıl geldiniz?"],
      ["Гражданин", "Терпение, документы и соблюдение сроков.", "Tirpéniye, dakumyéntу i sablyudyéniye srókav", "Sabır, belgeler ve sürelere uyum."],
      ["Репортёр", "Что вы чувствуете сейчас?", "Shtо vy чuvstvuyetye ichás", "Şimdi ne hissediyorsunuz?"],
      ["Гражданин", "Гордость. Теперь я гражданин!", "Górdast'. Tipyér' ya grajdanín", "Gurur. Artık vatandaşım!"],
    ]),
];
