// DilKoç © 2026 — Bu kaynak kod telif hakkıyla korunur. İzinsiz kopyalama,
// dağıtma ve türev çalışma üretme yasaktır (bkz. LICENSE).
// ============================================================================
// 🛂 VATANDAŞLIK PAKETİ — RUSÇA (3/4: ünite 51-75)
// Mülakat soruları (10) + vize-pasaport derinleşme (8) + göç-uyum (7)
// ============================================================================

import type { UnitModule } from '../../curriculumData';
import { makeCitUnit, type CitWord, type CitSent, type CitLine } from './makeCitUnit';

const U = (
  id: string, n: number, lv: UnitModule['levelGroup'], icon: string,
  title: string, desc: string, cat: string, color: string, grammar: string,
  words: CitWord[], sents: CitSent[], dlg: CitLine[],
): UnitModule => makeCitUnit({ id, unitNumber: n, level: lv, icon, title, desc, category: cat, color, grammar, words, sents, dlg });

const MUL = "Vatandaşlık Mülakatı";
const VIZE = "Vize & Pasaport";
const GOC = "Göç & Uyum";

export const CIT_RU_C: UnitModule[] = [
  U("cit_51", 650, "B1", "🎤", "Mülakat 1: Kişisel Sorular",
    "Ad, doğum yeri, adres: mülakatın ilk soruları",
    MUL, "#ef4444",
    "📌 Mülakatta «меня зовут» yerine resmî «моя фамилия…» da kullanılır.\n«родился / родилась» — doğdum (cinsiyete göre).",
    [
      ["как вас зовут?", "kak vas zavút", "adınız nedir?", "İlk soru her zaman budur."],
      ["фамилия", "famíliya", "soyad", "Resmî değil «фамилия» sorulur."],
      ["дата рождения", "dáta rajdyéniya", "doğum tarihi", "Tam olarak söylenir."],
      ["место рождения", "myésto rajdyéniya", "doğum yeri", "Şehir/ülke olarak cevaplanır."],
      ["ваш адрес", "vaş ádryes", "adresiniz", "Kayıtlı adres sorulur."],
      ["семейное положение", "syeмyéynaye palajyéniye", "medeni hâl", "Evli/bekâr/boşanmış."],
    ],
    [
      ["— Как вас зовут? — Меня зовут Ахмет Кайа.", "— Adınız nedir? — Adım Ahmet Kaya."],
      ["— Где вы родились? — Я родился в Бурсе.", "— Nerede doğdunuz? — Bursa'da doğdum."],
      ["— Ваш адрес? — Улица Ленина, дом десять.", "— Adresiniz? — Lenin Caddesi, numara on."],
    ],
    [
      ["Инспектор", "Здравствуйте! Как вас зовут?", "Zdrástvuytye! Kak vas zavút", "Merhaba! Adınız nedir?"],
      ["Кандидат", "Меня зовут Ахмет Кайа.", "Minyá zavút Ahyét Káya", "Adım Ahmet Kaya."],
      ["Инспектор", "Где и когда вы родились?", "Gdye i kagdá vy radílis'", "Nerede ve ne zaman doğdunuz?"],
      ["Кандидат", "Я родился в Бурсе в тысяча девятьсот девяносто пятом году.", "Ya radílsa f Búrsye f týsyaça dyevit'sót dyevinóstа pyátom gadú", "1995 yılında Bursa'da doğdum."],
    ]),

  U("cit_52", 651, "B1", "👨‍👩‍👧", "Mülakat 2: Aile ve Çocuklar",
    "Aile bireyleri, çocuk sayısı, eş mesleği soruları",
    MUL, "#ef4444",
    "📌 «сколько у вас детей?» — kaç çocuğunuz var?\nSayı + «лет»: двое детей — iki çocuk (özel biçim).",
    [
      ["сколько у вас детей?", "skól'ka u vas dyétey", "kaç çocuğunuz var?", "Aile sorusunun merkezidir."],
      ["супруга", "suprúga", "eş (karı)", "Erkek için: супруг."],
      ["профессия мужа", "prafyéssiya mújа", "kocanın mesleği", "Eş bilgisi istenir."],
      ["дети школьного возраста", "dyéti shkól'nava vózrasta", "okul çağındaki çocuklar", "Kayıt sorusu yöneltir."],
      ["родственники здесь", "rastvyénniki zdyés'", "akrabalar burada", "Aile bağları sorulur."],
      ["внуки", "vnúki", "torunlar", "Sorular geniş aileyi kapsar."],
    ],
    [
      ["— Сколько у вас детей? — У меня двое детей.", "— Kaç çocuğunuz var? — İki çocuğum var."],
      ["Мой супруг тоже работает здесь.", "Eşim de burada çalışıyor."],
      ["Мои родители живут в Турции.", "Ailem Türkiye'de yaşıyor."],
    ],
    [
      ["Инспектор", "Вы женаты?", "Vy jináty", "Evli misiniz?"],
      ["Кандидат", "Да, у меня двое детей школьного возраста.", "Da, u manyá dvóye dyétey shkól'nava vózrasta", "Evet, okul çağında iki çocuğum var."],
      ["Инспектор", "Кем работает ваша супруга?", "Kyem rabótayet váşa suprúga", "Eşiniz ne iş yapıyor?"],
      ["Кандидат", "Она учительница в школе.", "Aná uchítel'nitsa f şkórye", "O okulda öğretmen."],
    ]),

  U("cit_53", 652, "B2", "❓", "Mülakat 3: Neden Vatandaşlık?",
    "«Neden vatandaşlık istiyorsunuz?» sorusuna hazırlık",
    MUL, "#ef4444",
    "📌 «потому что» — çünkü (neden açıklama kalıbı).\nInfinitive amaç: «хочу жить и работать здесь».",
    [
      ["почему вы хотите гражданство?", "pachimú vy khatítye grajdánstva", "neden vatandaşlık istiyorsunuz?", "Ana sorudur; samimi cevap gerekir."],
      ["постоянно жить", "pastóyanna jít'", "kalıcı olarak yaşamak", "En kabul görür neden."],
      ["планы на будущее", "plánı na budúşcheye", "gelecek planları", "Soru sonrası gelir."],
      ["чувствовать себя дома", "чuvstvavat' syebyá dóма", "kendini evinde hissetmek", "Güçlü bir ifadedir."],
      ["связь со страной", "svyáz' sa stranóy", "ülkeyle bağ", "Köklülük vurgulanır."],
      ["вложить силы", "vlójit' sílı", "emek vermek", "Katkı anlamındadır."],
    ],
    [
      ["Я хочу постоянно жить и работать здесь.", "Kalıcı olarak burada yaşamak ve çalışmak istiyorum."],
      ["Эта страна стала мне вторым домом.", "Bu ülke bana ikinci yurt oldu."],
      ["У меня здесь работа, дом и друзья.", "Burada işim, evim ve arkadaşlarım var."],
    ],
    [
      ["Инспектор", "Почему вы хотите получить гражданство?", "Pachimú vy khatítye paluchít' grajdánstva", "Neden vatandaşlık almak istiyorsunuz?"],
      ["Кандидат", "Я живу здесь давно, у меня работа и семья.", "Ya jivú zdyés' davнó, u manyá rabóta i seм'yá", "Uzun süredir burada yaşıyorum, işim ve ailem burada."],
      ["Инспектор", "Какие у вас планы на будущее?", "Kakíyye u vas plánу na budúşcheye", "Gelecek planlarınız neler?"],
      ["Кандидат", "Хочу вложить силы в эту страну.", "Khachú vlójit' sílı f étu stranú", "Bu ülkeye emek vermek istiyorum."],
    ]),

  U("cit_54", 653, "B2", "💼", "Mülakat 4: İkamet ve Çalışma",
    "Nerede çalışıyorsun, gelirin ne: mali sorular",
    MUL, "#ef4444",
    "📌 «заниматься чем» — ile meşgul olmak: Чем вы занимаетесь?\n«официально» — resmî olarak (kayıtlı çalışma vurgusu).",
    [
      ["чем вы занимаетесь?", "chyem vy zanimáyetyes'", "ne iş yapıyorsunuz?", "Klasik mülakat sorusu."],
      ["место работы", "myésto rabótı", "iş yeri", "Adresiyle sorulur."],
      ["официальный доход", "afitsiál'nıy dakhót", "resmî gelir", "Kayıt dışı olmamalı."],
      ["стаж", "staж", "kıdem (çalışma süresi)", "Süreyi kanıtlar."],
      ["работать легально", "rabótat' lyegál'na", "yasal çalışmak", "Önemli şarttır."],
      ["подтверждающий документ", "padtverjdáyüşchiy dakumyént", "kanıtlama belgesi", "Gelir için istenir."],
    ],
    [
      ["— Чем вы занимаетесь? — Я инженер на заводе.", "— Ne iş yapıyorsunuz? — Fabrikada mühendisim."],
      ["Я работаю легально уже пять лет.", "Beş yıldır yasal olarak çalışıyorum."],
      ["Доход подтверждается справкой.", "Gelir belgeyle kanıtlanır."],
    ],
    [
      ["Инспектор", "Чем вы занимаетесь?", "Chyem vy zanimáyetyes'", "Ne iş yapıyorsunuz?"],
      ["Кандидат", "Я инженер, работаю на заводе официально.", "Ya injinýér, rabótayu na zavódye afitsiál'na", "Mühendisim, fabrikada resmî olarak çalışıyorum."],
      ["Инспектор", "Ваш доход подтверждён документами?", "Vash dakhót padtvyerjdyón dakumyéntami", "Geliriniz belgelerle kanıtlanmış mı?"],
      ["Кандидат", "Да, вот справка о доходах за год.", "Da, vot spráfka a dakhódah za got", "Evet, işte yıllık gelir belgesi."],
    ]),

  U("cit_55", 654, "B2", "🏛️", "Mülakat 5: Ülke Bilgisi",
    "Başkent, bayrak, yönetim biçimi: bilgi soruları",
    MUL, "#ef4444",
    "📌 «какой / какая / какое» — hangi (cinsiyete göre seçilir).\n«столица» — başkent; «президент» — cumhurbaşkanı.",
    [
      ["столица", "stalítsa", "başkent", "En klasik sorudur."],
      ["государственный язык", "gasudárstvyennıy yazyk", "resmî dil", "Ülkenin dilidir."],
      ["президент", "prizidyént", "cumhurbaşkanı", "Yöneticidir."],
      ["парламент", "parlamyént", "parlamento", "Yasama organıdır."],
      ["государственное устройство", "gasudárstvyennoye ustróystva", "devlet yapısı", "Yönetim biçimidir."],
      ["население", "nasélyéniye", "nüfus", "Temel bilgidir."],
    ],
    [
      ["— Какая столица этой страны? — Столица — Москва.", "— Bu ülkenin başkenti neresi? — Başkent Moskova."],
      ["Какой государственный язык в стране?", "Ülkenin resmî dili nedir?"],
      ["Парламент принимает законы.", "Parlamento yasaları kabul eder."],
    ],
    [
      ["Экзаменатор", "Какая столица этой страны?", "Kakáya stalítsa étay stranı", "Bu ülkenin başkenti neresi?"],
      ["Кандидат", "Столица — Москва.", "Stalítsa — Maskvá", "Başkent Moskova."],
      ["Экзаменатор", "Кто принимает законы?", "Kto primimáyет zakónı", "Yasaları kim kabul eder?"],
      ["Кандидат", "Парламент принимает законы.", "Parlamyént primimáyет zakónı", "Parlamento yasaları kabul eder."],
    ]),

  U("cit_56", 655, "B2", "📜", "Mülakat 6: Tarih Soruları",
    "Temel tarih bilgisi ve millî günler",
    MUL, "#ef4444",
    "📌 Tarih kalıbı: «в каком году» — hangi yılda; «в тысяча девятьсот…» — bin dokuzyüz…\n«праздновать» — kutlamak.",
    [
      ["в каком году", "f kakóm gadú", "hangi yılda", "Tarih sorusu kalıbı."],
      ["важное событие", "vájnaye sобы́tiye", "önemli olay", "Tarihte dönüm noktası."],
      ["независимость", "nyezavisímast'", "bağımsızlık", "Millî tarihin ana teması."],
      ["национальный праздник", "natsiyal'nıy prazdnik", "ulusal bayram", "Sorulması olasıdır."],
      ["основатель", "asnavadítyel'", "kurucu", "Tarihî kişiliktir."],
      ["прошлое", "próshlaye", "geçmiş", "Tarihin kendisidir."],
    ],
    [
      ["— Когда этот национальный праздник? — Девятого мая.", "— Bu ulusal bayram ne zaman? — Dokuz Mayıs."],
      ["Страна получила независимость давно.", "Ülke bağımsızlığına uzun zaman önce kavuştu."],
      ["Это было важное событие в истории.", "Bu tarihte önemli bir olaydı."],
    ],
    [
      ["Экзаменатор", "Когда главный национальный праздник?", "Kagdá gláv nıy natsiyal'nıy prazdnik", "Ana ulusal bayram ne zaman?"],
      ["Кандидат", "Двенадцатого июня.", "Dvinátsatava yúnya", "On İki Haziran."],
      ["Экзаменатор", "Что произошло в этот день?", "Shtо praisizashló f état dyen'", "O gün ne oldu?"],
      ["Кандидат", "Страна провозгласила независимость.", "Straná pravazglasíla nyezavisímast'", "Ülke bağımsızlığını ilan etti."],
    ]),

  U("cit_57", 656, "B2", "⚖️", "Mülakat 7: Yasalar ve Yükümlülükler",
    "Vergi, seçme hakkı, yasalara uyum soruları",
    MUL, "#ef4444",
    "📌 Modal yapı: «обязан + fiil» — ...mekle yükümlü.\n«платить налоги» — vergi ödemek (belirtisiz nesne).",
    [
      ["платить налоги", "platít' nalógi", "vergi ödemek", "Vatandaşın birinci görevi."],
      ["соблюдать закон", "sablyudát' zakón", "yasaya uymak", "Mülakatta vurgulanır."],
      ["право голоса", "práva gólasa", "oy hakkı", "Seçme hakkıdır."],
      ["воинская обязанность", "vaínskaya abyázannast'", "askerlik hizmeti", "Bazı ülkelerde vardır."],
      ["присяжный", "prisyaжnıy", "jurü (heyet üyesi)", "Yurttaş görevidir."],
      ["гражданский долг", "grajdánstvıy dolk", "yurttaşlık borcu", "Genel kavramdır."],
    ],
    [
      ["Граждане обязаны платить налоги.", "Vatandaşlar vergi ödemekle yükümlüdür."],
      ["Каждый имеет право голоса.", "Herkesin oy hakkı vardır."],
      ["Соблюдать закон — гражданский долг.", " yasaya uymak yurttaşlık borcudur."],
    ],
    [
      ["Экзаменатор", "Какие обязанности у гражданина?", "Kakíyye abyázannastí u grajdanína", "Vatandaşın görevleri nelerdir?"],
      ["Кандидат", "Платить налоги и соблюдать закон.", "Platít' nalógi i sablyudát' zakón", "Vergi ödemek ve yasaya uymak."],
      ["Экзаменатор", "Что такое право голоса?", "Shtо takóye práva gólasa", "Oy hakkı nedir?"],
      ["Кандидат", "Это право выбирать власть.", "Eta práva vıbírат' vlast'", "Yönetimi seçme hakkıdır."],
    ]),

  U("cit_58", 657, "B1", "👂", "Mülakat 8: Anlamadım, Tekrar Eder misiniz?",
    "Mülakatta yardım isteme kalıpları",
    MUL, "#ef4444",
    "📌 Kibar rica: «повторите, пожалуйста» — lütfen tekrar eder misiniz.\n«медленнее» — daha yavaş (zarf biçimi).",
    [
      ["повторите, пожалуйста", "paftarítye, pajálusta", "tekrar eder misiniz, lütfen", "En güvenli kalıptır."],
      ["говорите медленнее", "gavarítye myédlennyе", "daha yavaş konuşun", " Rica kalıbıdır."],
      ["я не понял", "ya nye panyál", "anlamadım", "Durumu bildirir."],
      ["что это значит?", "shtо eta znáçit", "bu ne demek?", "Kelime sorma cesareti."],
      ["можно вопрос?", "mójna vaprós", "soru sorabilir miyim?", "İzin isteme kibarlığı."],
      ["как это произносится?", "kak eta priznósitsa", "bu nasıl telaffuz edilir?", "Telaffuz yardımı ister."],
    ],
    [
      ["Повторите, пожалуйста, вопрос.", "Soruyu lütfen tekrar edin."],
      ["Говорите, пожалуйста, медленнее.", "Lütfen daha yavaş konuşun."],
      ["Извините, я не понял вопрос.", "Affedersiniz, soruyu anlamadım."],
    ],
    [
      ["Кандидат", "Извините, повторите, пожалуйста.", "Izvinítye, paftarítye, pajálusta", "Affedersiniz, lütfen tekrar edin."],
      ["Инспектор", "Конечно. Где вы работали раньше?", "Kanyéshna. Gdye vy rabótali rán'şye", "Elbette. Daha önce nerede çalıştınız?"],
      ["Кандидат", "Спасибо! Я работала в больнице.", "Spasíba! Ya rabótala f bal'nítsye", "Teşekkürler! Hastanede çalıştım."],
    ]),

  U("cit_59", 658, "B2", "💬", "Mülakat 9: Cevap Kalıpları",
    "Tam cümle cevap verme ve net ifade teknikleri",
    MUL, "#ef4444",
    "📌 Tam cümle: sorudaki fiili cevapta tekrarla.\n«да / нет, + kısa açıklama» — netlik kuralı.",
    [
      ["отвечать полностью", "atvyéчat' palnast'yu", "tam cevap vermek", "Mülakat tekniğidir."],
      ["уверенный ответ", "uvyérennıy atvyet", "kendinden emin cevap", "Ses tonuyla desteklenir."],
      ["кратко и ясно", "krátkа i yásna", "kısa ve net", "Mülakatın altın kuralı."],
      ["не уклоняться", "ni uklanyát'sa", "kaçamak cevap vermemek", "Güven oluşturur."],
      ["пример из жизни", "primyér iz jízni", "yaşamdan örnek", "Cevabı güçlendirir."],
      ["честный ответ", "чyéstnıy atvyet", "dürüst cevap", "En doğru strateji."],
    ],
    [
      ["Отвечайте кратко, но полностью.", "Kısa ama tam cevap verin."],
      ["Не уклоняйтесь от вопроса.", "Sorudan kaçamak cevap vermeyin."],
      ["Честный ответ лучше длинного.", "Dürüst cevap, uzun açıklamadan iyidir."],
    ],
    [
      ["Экзаменатор", "Вы когда-нибудь нарушали закон?", "Vy kagdá-nibud' narusháli zakón", "Hiç yasa ihlali yaptınız mı?"],
      ["Кандидат", "Нет, никогда. Я всегда соблюдаю правила.", "Nyét, nikagdá. Ya fsygdá sablyudáyu právila", "Hayır, asla. Kurallara her zaman uyarım."],
      ["Экзаменатор", "Спасибо за честный ответ.", "Spasíba za чyéstnıy atvyet", "Dürüst cevabınız için teşekkürler."],
    ]),

  U("cit_60", 659, "B1", "🎭", "Mülakat 10: Tam Simülasyon",
    "Uçtan uca örnek mülakat diyaloğu",
    MUL, "#ef4444",
    "📌 Simülasyonda BÜTÜN kalıplar birlikte kullanılır.\nSıra: selam → kişisel bilgiler → neden → kapanış.",
    [
      ["проходите", "prahadítye", "buyurun geçin", "Mülakat davetidir."],
      ["присядьте", "prisyádt'ye", "oturun", "Kibar yönlendirmedir."],
      ["документы при вас?", "dakumyéntı pri vas", "belgeleriniz yanınızda mı?", "Başlangıç kontrolüdür."],
      ["это всё", "eta fsyo", "hepsi bu kadar", "Bitiş ifadesidir."],
      ["ждите решения", "jdítye ryshyéniya", "kararı bekleyin", "Kapanış cümlesidir."],
      ["спасибо за время", "spasíba za vryémya", "zamanınız için teşekkürler", "Nazik vedadır."],
    ],
    [
      ["— Проходите, присядьте. — Спасибо.", "— Buyurun, oturun. — Teşekkürler."],
      ["Документы при вас? Покажите паспорт.", "Belgeleriniz yanınızda mı? Pasaportunuzu gösterin."],
      ["Ждите решения по почте.", "Kararı postayla bekleyin."],
    ],
    [
      ["Инспектор", "Здравствуйте! Проходите, присядьте.", "Zdrástvuytye! Prahadítye, prisyádt'ye", "Merhaba! Buyurun, oturun."],
      ["Кандидат", "Здравствуйте! Спасибо. Документы при мне.", "Zdrástvuytye! Spasíba. Dakumyéntı pri mnyé", "Merhaba! Teşekkürler. Belgelerim yanımda."],
      ["Инспектор", "Как вас зовут и где вы работаете?", "Kak vas zavút i gdye vy rabótayetye", "Adınız nedir ve nerede çalışıyorsunuz?"],
      ["Кандидат", "Меня зовут Ахмет. Я работаю инженером.", "Minyá zavút Ahyét. Ya rabótayu injinýeram", "Adım Ahmet. Mühendis olarak çalışıyorum."],
      ["Инспектор", "Спасибо за время. Ждите решения.", "Spasíba za vryémya. Jdítye ryshyéniya", "Zamanınız için teşekkürler. Kararı bekleyin."],
    ]),

  U("cit_61", 660, "A2", "🛫", "Havalimanı ve Uçuş Kelimeleri",
    "Check-in, kapı, uçuş ve bagaj kelimeleri",
    VIZE, "#0ea5e9",
    "📌 «регистрация на рейс» — uçuşa check-in (belirtisiz nesne).\n«за сколько часов» — kaç saat önce.",
    [
      ["аэропорт", "aerapórt", "havalimanı", "Yolculuğun başlangıcıdır."],
      ["рейс", "reys", "uçuş (sefer)", "Biletin kimliğidir."],
      ["посадочный талон", "pasádoçnıy talón", "biniş kartı", "Check-in'de verilir."],
      ["выход на посадку", "výkhad na pásadku", "kapı (gate)", "Tabela takip edilir."],
      ["посадка", "pásadka", "biniş/uçuşa kabul", "Duyurularla başlar."],
      ["вещи на борт", "vyéşchi na bort", "kabin bagajı", "Sınırlı sayıda olur."],
    ],
    [
      ["Регистрация на рейс начинается за два часа.", "Check-in uçuştan iki saat önce başlar."],
      ["Вот мой посадочный талон и паспорт.", "İşte biniş kartım ve pasaportum."],
      ["Посадка на выход номер пять.", "Beş numaralı kapıdan biniş var."],
    ],
    [
      ["Сотрудник", "Ваш паспорт и билет, пожалуйста.", "Vash pásport i bilét, pajálusta", "Pasaportunuzu ve biletinizi lütfen."],
      ["Пассажир", "Вот, пожалуйста. Одна вещь на борт.", "Vot, pajálusta. Adná vyеşch' na bort", "Buyurun. Bir kabin bagajım var."],
      ["Сотрудник", "Вот ваш посадочный талон. Выход пять.", "Vot vaş pasádoçnıy talón. Výkhad pyat'", "İşte biniş kartınız. Kapı beş."],
    ]),

  U("cit_62", 661, "B1", "💻", "E-Vize ve Online Başvuru",
    "İnternetten vize başvurusu: formül doldurma, yükleme, onay",
    VIZE, "#0ea5e9",
    "📌 «загрузить» — yüklemek (download KARŞITI: upload anlamında da kullanılır).\n«подтверждение по электронной почте» — e-posta onayı.",
    [
      ["электронная виза", "yiktróнная víza", "e-vize", "Başvurusu tamamen onlinedır."],
      ["заполнить онлайн-форму", "zapólnit' anlayn-fórmu", "online formu doldurmak", "Kağıt yoktur."],
      ["загрузить фото", "zagruzít' fóto", "fotoğraf yüklemek", "Formatına dikkat edilir."],
      ["подтверждение на почту", "padtveryedyéniye na póчtu", "e-posta onayı", "Yazılı kanıttır."],
      ["статус заявления", "státus zayavlyéniya", "başvuru durumu", "Siteden takip edilir."],
      ["распечатать", "raspyečátat'", "yazdırmak (çıktı)", "Sınırda istenebilir."],
    ],
    [
      ["Я заполнил онлайн-форму и загрузил фото.", "Online formu doldurdum ve fotoğrafı yükledim."],
      ["Подтверждение пришло на почту.", "Onay e-postama geldi."],
      ["Статус заявления можно проверить онлайн.", "Başvuru durumu internetten kontrol edilebilir."],
    ],
    [
      ["Клиент", "Я заполнил форму. Что дальше?", "Ya zapólnil fórmu. Shtó dál'şye", "Formu doldurdum. Sıra ne?"],
      ["Оператор", "Загрузите фото и оплатите сбор онлайн.", "Zagruzítye fóto i aplatítye sbor anlayn", "Fotoğrafı yükleyin ve ücreti online ödeyin."],
      ["Клиент", "Готово. Подтверждение придёт на почту?", "Gatóva. Padtveryedyéniye pridyót na póčtu", "Tamam. Onay e-postaya mı gelecek?"],
    ]),

  U("cit_63", 662, "B1", "💱", "Vize Ücretleri ve Para Birimleri",
    "Döviz, kur ve ödeme kelimeleri",
    VIZE, "#0ea5e9",
    "📌 «обменять что на что» — ...ı ...ye değiştirmek: обменять доллары на рубли.\n«курс» — kur (döviz kuru).",
    [
      ["сбор в валюте", "sbor f valyútye", "döviz cinsinden ücret", "Konsolosluk belirler."],
      ["обмен валюты", "abmyén valyútı", "döviz bozdurma", "Ofisten yapılır."],
      ["курс", "kurs", "kur", "Günlük değişir."],
      ["наличные", "nalíчnıyyе", "nakit", "Bazı yerlerde istenir."],
      ["банковская карта", "bankóvskaya kárta", "banka kartı", "En yaygın ödeme."],
      ["чек", "chyek", "fiş (dekont)", "Ödeme kanıtıdır."],
    ],
    [
      ["Сбор оплачивается в местной валюте.", "Ücret yerel para birimiyle ödenir."],
      ["Я обменял доллары на рубли.", "Doları rublaya çevirdim."],
      ["Сохраните чек об оплате.", "Ödeme fişini saklayın."],
    ],
    [
      ["Клиент", "Можно оплатить картой?", "Mójna aplatít' kártay", "Kartla ödeme mümkün mü?"],
      ["Кассир", "Нет, только наличные в местной валюте.", "Nyét, tól'ka nalíçnıyyе f myéstnay valyútye", "Hayır, yalnız yerel para ile nakit."],
      ["Клиент", "Хорошо, я сначала обменяю валюту.", "Harashó, ya snachála abminyáyу valyútu", "Peki, önce döviz bozduracağım."],
    ]),

  U("cit_64", 663, "B2", "⏰", "Vize Süresi Aşımı",
    "Overstay: ceza, çıkış yasağı ve çözümler",
    VIZE, "#0ea5e9",
    "📌 «просрочить» — süreyi aşmak; «наказание» — yaptırım.\n«заплатить штраф» — ceza ödemek.",
    [
      ["просрочить визу", "prasróчit' vízu", "vize süresini aşmak", "Ciddi sonuçları vardır."],
      ["штраф", "ştraf", "ceza (para)", "Sınırda ödenir."],
      ["запрет на въезд", "zapryét na vyezd", "giriş yasağı", "Uzun süreli olur."],
      ["добровольно выехать", "dabról'na výyeхat'", "kendi isteğiyle çıkmak", "Cezayı hafifletir."],
      ["уважительная причина", "uvajítel'naya prichína", "haklı neden", "Belgelenirse kabul edilir."],
      ["пограничная служба", "pagraníčnaya slújba", "sınır idaresi", "Kararı veren makamdır."],
    ],
    [
      ["Я просрочил визу на пять дней.", "Vize süremi beş gün aştım."],
      ["За просрочку нужно заплатить штраф.", "Süre aşımı için ceza ödemek gerekir."],
      ["Он выехал добровольно, без запрета.", "Giriş yasağı olmadan kendi isteğiyle çıktı."],
    ],
    [
      ["Офицер", "Вы просрочили визу на десять дней.", "Vy prasróчili vízu na dyésit' dnyéy", "Vize sürenizi on gün aştınız."],
      ["Путешественник", "У меня была уважительная причина — болезнь.", "U manyá býcha uvajítel'naya prichína — balyézn'", "Haklı nedenim vardı — hastalık."],
      ["Офицер", "Покажите справку от врача и заплатите штраф.", "Pajíjité spráfku at vračá i zaplatítye ştraf", "Doktor belgesini gösterin ve cezayı ödeyin."],
    ]),

  U("cit_65", 664, "B1", "🎖️", "Pasaport Türleri",
    "Umuma mahsus, diplomatik ve hizmet pasaportları",
    VIZE, "#0ea5e9",
    "📌 Sıfat uyumu: дипломатическИЙ паспорт (eril).\n«предназначен для» — ...için tasarlanmıştır.",
    [
      ["обычный паспорт", "abы́чnıy pásport", "umuma mahsus pasaport", "Standart pasaporttur."],
      ["дипломатический паспорт", "diplamatíçyеskiй pásport", "diplomatik pasaport", "Diplomatlara verilir."],
      ["служебный паспорт", "slújybnyй pásport", "hizmet pasaportu", "Görevlilere verilir."],
      ["загранпаспорт", "zagranpásport", "yurt dışı pasaportu", "Seyahat belgesidir."],
      ["внутренний паспорт", "vnutryénniy pásport", "iç pasaport (kimlik)", "Ülke içi kimliktir."],
      ["срок действия", "srak dyéystviya", "geçerlilik süresi", "Tür başına değişir."],
    ],
    [
      ["У меня обычный загранпаспорт.", "Umuma mahsus yurt dışı pasaportum var."],
      ["Дипломатический паспорт даёт привилегии.", "Diplomatik pasaport ayrıcalık verir."],
      ["Срок действия паспорта — десять лет.", "Pasaportun geçerlilik süresi on yıl."],
    ],
    [
      ["Пассажир", "Это обычный паспорт или служебный?", "Eta abы́čnıy pásport ili slújybnyй", "Bu umuma mahsus mu hizmet pasaportu mu?"],
      ["Офицер", "Обычный, для всех граждан.", "Abы́čnıy, dlya fsyh grajdán", "Umuma mahsus, tüm vatandaşlar için."],
      ["Пассажир", "Понял, спасибо за объяснение.", "Panyál, spasíba za abyyasnyéniye", "Anladım, açıklama için teşekkürler."],
    ]),

  U("cit_66", 665, "A2", "🚨", "Pasaport Kaybı ve Çalınma",
    "Kayıp pasaport: polis, tutanak, yeniden çıkarma",
    VIZE, "#0ea5e9",
    "📌 «у меня украли» — benden çaldılar (belirtisiz nesne, geçmiş çoğul).\n«заявление в полицию» — polise başvuru.",
    [
      ["потерять паспорт", "patyéryat' pásport", "pasaportu kaybetmek", "Hemen bildirilir."],
      ["украли паспорт", "ukráli pásport", "pasaport çalındı", "Polis tutanağı gerekir."],
      ["заявление в полицию", "zayavlyéniye f palítsiyu", "polis başvurusu", "Kanıt belgesidir."],
      ["справка о краже", "spráfka a krayé", "hırsızlık belgesi", "Konsolosluğa verilir."],
      ["консульство", "kansúl'stva", "konsolosluk", "Yeni belgeyi verir."],
      ["временный документ", "vryéminnıy dakumyént", "geçici belge", "Dönüş için yeterlidir."],
    ],
    [
      ["Я потерял паспорт — что делать?", "Pasaportumu kaybettim — ne yapmalıyım?"],
      ["Сначала заявление в полицию.", "Önce polise başvuru."],
      ["Консульство выдаст временный документ.", "Konsolosluk geçici belge verir."],
    ],
    [
      ["Турист", "У меня украли паспорт!", "U manyá ukráli pásport", "Pasaportum çalındı!"],
      ["Полицейский", "Напишите заявление — я дам справку.", "Napíşitye zayavlyéniye — ya dam spráfku", "Başvuru yazın — size belge vereceğim."],
      ["Турист", "Спасибо! Потом я пойду в консульство.", "Spasíba! Patóm ya paydu f kansúl'stva", "Teşekkürler! Sonra konsolosluğa gideceğim."],
    ]),

  U("cit_67", 666, "B1", "🧒", "Çocuklar için Pasaport ve Vize",
    "Çocuk belgeleri: veli izni ve ortak başvuru",
    VIZE, "#0ea5e9",
    "📌 «вписать ребёнка» — çocuğu kaydettirmek (pasaporta).\n«согласие второго родителя» — diğer ebeveynin onayı.",
    [
      ["паспорт для ребёнка", "pásport dlya ryebyónka", "çocuk pasaportu", "Ayrı belgedir."],
      ["свидетельство о рождении", "svidyétel'stva a rajdyéniya", "doğum belgesi", "Her işlemde istenir."],
      ["согласие родителя", "saglásiye radítyelya", "ebeveyn onayı", "Noter onaylıdır."],
      ["вписать в паспорт", "fipísat' f pásport", "pasaporta yazdırmak", "Bazı ülkelerde geçerlidir."],
      ["несовершеннолетний", "nyisavyrshennalyétniy", "reşit olmayan", "Özel kurallara tabidir."],
      ["сопровождение", "sapravajdyéniye", "refakat", "Yalnız seyahatte kuraldır."],
    ],
    [
      ["Ребёнку нужен отдельный паспорт.", "Çocuğa ayrı pasaport gerekir."],
      ["Нужно согласие второго родителя на выезд.", "Yurt dışına çıkış için diğer ebeveynin onayı gerekir."],
      ["Мы оформили документы вместе.", "Belgeleri birlikte düzenledik."],
    ],
    [
      ["Мать", "Как оформить паспорт ребёнку?", "Kak aformít' pásport ryebyónku", "Çocuğa pasaport nasıl çıkarılır?"],
      ["Сотрудник", "Нужно свидетельство о рождении и ваше согласие.", "Nujná svidyétel'stva a rajdyéniya i vášye saglásiye", "Doğum belgesi ve sizin onayınız gerekli."],
      ["Мать", "Хорошо, мы принесли всё.", "Harashó, my prinyeslí fsyo", "Tamam, hepsini getirdik."],
    ]),

  U("cit_68", 667, "B2", "👪", "Özel Durumlar: Boşanma ve Velayet",
    "Boşanmış ailelerde çocuk vizesi ve velayet",
    VIZE, "#0ea5e9",
    "📌 «после развода» — boşanmadan sonra (önerme).\n«решение о воспитании» — velayet kararı.",
    [
      ["развод", "razvót", "boşanma", "Belgeyle kanıtlanır."],
      ["свидетельство о разводе", "svidyétel'stva a razvódye", "boşanma belgesi", "Dosyada istenir."],
      ["опека", "apyéka", "velayet", "Mahkeme verir."],
      ["с кем живёт ребёнок", "s kyem jivyót ryebyónak", "çocuk kimle yaşıyor", "Temel sorudur."],
      ["право на выезд ребёнка", "práva na vyezd ryebyónka", "çocuğu yurt dışına çıkarma hakkı", "Onaya bağlıdır."],
      ["решение суда", "ryshyéniye sudá", "mahkeme kararı", "Velayeti belirler."],
    ],
    [
      ["После развода опека у матери.", "Boşanmadan sonra velayet annede."],
      ["Для выезда ребёнка нужно согласие отца.", "Çocuğun çıkışı için babanın onayı gerekir."],
      ["Решение суда определяет опеку.", "Mahkeme kararı velayeti belirler."],
    ],
    [
      ["Мать", "Я в разводе, ребёнок живёт со мной.", "Ya f razvódye, ryebyónak jivyót sa mnóy", "Boşanmışım, çocuk benimle yaşıyor."],
      ["Сотрудник", "Покажите решение суда об опеке.", "Pajíjité ryshyéniye sudá ab apyékye", "Velayet kararını gösterin."],
      ["Мать", "Вот оно, и согласие отца на выезд.", "Vot anó, i saglásiye atsá na vyezd", "İşte, ve babanın çıkış onayı."],
    ]),

  U("cit_69", 668, "A2", "🏠", "Konut Kiralama ve Depozito",
    "Yeni ülkede ev tutma: depozito, komisyon, sözleşme",
    GOC, "#f59e0b",
    "📌 «снимать квартиру» — daire kiralamak (kiracı tarafı).\n«залог» — depozito (teminat).",
    [
      ["снимать квартиру", "snimát' kvartíru", "daire kiralamak", "İlk ihtiyaçtır."],
      ["залог", "zalók", "depozito (teminat)", "Genelde bir kira bedelidir."],
      ["комиссия", "kamísiya", "komisyon (emlak)", "Emlakçıya ödenir."],
      ["договор найма", "dagavór náyma", "kira sözleşmesi", "İmzalanmadan ödeme yapılmaz."],
      ["коммунальные платежи", "kamunál'nыyye platyejí", "aidat/faturalar", "Kiraya eklenebilir."],
      ["хозяин квартиры", "hazyáin kvartírı", "ev sahibi", "Anlaşmanın diğer tarafı."],
    ],
    [
      ["Я снимаю квартиру рядом с работой.", "İş yerimin yanında daire kiralıyorum."],
      ["Залог — одна месячная плата.", "Depozito bir aylık kiradır."],
      ["Договор найма подписали на год.", "Kira sözleşmesini bir yıllık imzaladık."],
    ],
    [
      ["Арендатор", "Сколько залог и комиссия?", "Skól'ka zalók i kamísiya", "Depozito ve komisyon ne kadar?"],
      ["Агент", "Залог — одна плата, комиссия — половина.", "Zalók — adná platá, kamísiya — palavína", "Depozito bir kira, komisyon yarım."],
      ["Арендатор", "Хорошо, покажите договор.", "Harashó, păjíjityе dagavór", "Peki, sözleşmeyi gösterin."],
    ]),

  U("cit_70", 669, "A2", "🩺", "Aile Hekimi ve Sağlık Sistemi",
    "Sağlık kaydı, aile hekimi ve randevu",
    GOC, "#f59e0b",
    "📌 «записаться к врачу» — hekime randevu almak (kimin yanına).\n«полис» — poliçe (sigorta belgesi).",
    [
      ["полис ОМС", "pólis om-yés", "genel sağlık poliçesi", "Devlet sigortasıdır."],
      ["участковый врач", "učastkóvıy vrač", "aile hekimi", "İlk başvuru noktasıdır."],
      ["записаться к врачу", "zapissátsa k vračú", "hekime randevu almak", "Telefonla veya online olur."],
      ["медицинская карта", "miditsínskaya kárta", "sağlık kartı/dosyası", "Kayıtla açılır."],
      ["направление", "napravlyéniye", "sevk", "Uzman için gereklidir."],
      ["скорая помощь", "skóraya pómaşch'", "acil servis", "112 numarasıdır."],
    ],
    [
      ["Сначала получите полис.", "Önce poliçe alın."],
      ["Я записался к участковому врачу.", "Aile hekimine randevu aldım."],
      ["Для специалиста нужно направление.", "Uzman için sevk gerekiyor."],
    ],
    [
      ["Пациент", "Как получить полис?", "Kak paluchít' pólis", "Poliçe nasıl alınır?"],
      ["Администратор", "С паспортом и регистрацией — в страховую.", "S pásportam i ragistrátsiyey — f strahóvuyu", "Pasaport ve kayıtla sigorta kurumuna."],
      ["Пациент", "Спасибо, завтра пойду.", "Spasíba, záftra paydú", "Teşekkürler, yarın gideceğim."],
    ]),

  U("cit_71", 670, "B1", "🔍", "İş Bulma Yolları",
    "İş arama: ilan, CV, başvuru ve ön görüşme",
    GOC, "#f59e0b",
    "📌 «откликнуться на вакансию» — ilana başvurmak.\n«опыт работы» — iş deneyimi (kıdem).",
    [
      ["искать работу", "iskát' rabótu", "iş aramak", "İlk adımdır."],
      ["откликнуться на вакансию", "atkliknútsa na vakánsiyu", "ilana başvurmak", "Online yapılır."],
      ["резюме", "rizyumé", "CV (özgeçmiş)", "Güncel tutulur."],
      ["опыт работы", "opıt rabótı", "iş deneyimi", "İlanda şart olarak yazar."],
      ["собеседование", "sabyédavaniye", "iş görüşmesi", "Davetle gelir."],
      ["испытательный срок", "ispыtátel'nıy srak", "deneme süresi", "Genelde 3 aydır."],
    ],
    [
      ["Я ищу работу по специальности.", "Uzmanlık alanımda iş arıyorum."],
      ["Отправьте резюме на эту вакансию.", "Bu ilana CV'nizi gönderin."],
      ["Испытательный срок — три месяца.", "Deneme süresi üç ay."],
    ],
    [
      ["Соискатель", "Я откликнулся на вакансию повара.", "Ya atkliknúlsa na vakánsiyu pavára", "Aşçı ilanına başvurdum."],
      ["Работодатель", "Какой у вас опыт работы?", "Kakóy u vas opıt rabótı", "Ne kadar deneyiminiz var?"],
      ["Соискатель", "Пять лет в ресторане.", "Pyat' lyet f rystaránye", "Restoranda beş yıl."],
    ]),

  U("cit_72", 671, "A2", "🚌", "Toplu Taşıma ve Ulaşım Kartı",
    "Metro, otobüs ve ulaşım kartı dolumu",
    GOC, "#f59e0b",
    "📌 «пополнить карту» — kart yüklemek (para eklemek).\n«проезд» — yolculuk (biniş).",
    [
      ["транспортная карта", "transpórтnaya kárta", "ulaşım kartı", "Dolumla çalışır."],
      ["пополнить карту", "papólnit' kártu", "kart yüklemek",      "Kasada veya uygulamada."],
      ["поездка", "poyézdka", "yolculuk (biniş)", "Tek biniştir."],
      ["метро", "myetró", "metro", "En hızlı yoldur."],
      ["остановка", "astanófka", "durak", "Biniş noktasıdır."],
      ["конечная", "kanyéčnaya", "son durak", "Hattın bitişidir."],
    ],
    [
      ["Пополните карту в кассе или приложении.", "Kartı gişede veya uygulamada doldurun."],
      ["Одна поездка стоит пятьдесят рублей.", "Bir yolculuk elli ruble."],
      ["Эта остановка не конечная.", "Bu durak son durak değil."],
    ],
    [
      ["Пассажир", "Как пополнить транспортную карту?", "Kak papólnit' transpórтnuyu kártu", "Ulaşım kartı nasıl yüklenir?"],
      ["Кассир", "В кассе или в мобильном приложении.", "F kassye i f máyil'nam prilojyéniyi", "Gişede veya mobil uygulamada."],
      ["Пассажир", "Спасибо, пополню на десять поездок.", "Spasíba, papólnyu na dyésit' poyézdak", "Teşekkürler, on yolculuk yükleyeceğim."],
    ]),

  U("cit_73", 672, "B1", "🏫", "Okul ve Çocukların Eğitimi",
    "Okul kaydı, dil desteği ve veli toplantıları",
    GOC, "#f59e0b",
    "📌 «записать ребёнка в школу» — çocuğu okula kaydettirmek.\n«адаптационные занятия» — uyum dersleri.",
    [
      ["запись в школу", "zápis' f şkólu", "okul kaydı", "Belgeyle yapılır."],
      ["необходимые документы", "nyeabhodímыyyе dakumyéntы", "gerekli belgeler", "Listesi okulda asılıdır."],
      ["адаптационные занятия", "adaptatsiónnыyyе zanyátiya", "uyum dersleri", "Yeni gelenler içindir."],
      ["родительское собрание", "radítyel'skaye sabrániye", "veli toplantısı", "Düzenli yapılır."],
      ["оценки", "atsyénki", "notlar (karne)", "Dönem sonunda verilir."],
      ["учитель", "uchítel'", "öğretmen", "İlk iletişim kişisidir."],
    ],
    [
      ["Мы записали сына в первый класс.", "Oğlumuzu birinci sınıfa kaydettirdik."],
      ["Для записи нужны документы о регистрации.", "Kayıt için ikamet belgeleri gerekli."],
      ["Родительское собрание — в четверг.", "Veli toplantısı Perşembe günü."],
    ],
    [
      ["Родитель", "Как записать ребёнка в школу?", "Kak zapisát' ryebyónka f şkólu", "Çocuk okula nasıl kaydedilir?"],
      ["Директор", "Принесите документы: паспорт, регистрацию, свидетельство.", "Prinyesítyе dakumyéntы: pásport, ragistrátsiyu, svidyétel'stva", "Pasaport, kayıt ve doğum belgesini getirin."],
      ["Родитель", "Спасибо, всё приготовим.", "Spasíba, fsyo prigatóvim", "Teşekkürler, hepsini hazırlayacağız."],
    ]),

  U("cit_74", 673, "B1", "🧾", "Vergi Numarası ve Vergiler",
    "Vergi kimlik numarası alma ve temel vergi kelimeleri",
    GOC, "#f59e0b",
    "📌 «платить налог с чего» — ...den vergi ödemek: налог с зарплаты.\n«ИНН» — vergi numarası kısaltması.",
    [
      ["ИНН", "i-yen-yen", "vergi kimlik numarası", "Her işlemde istenir."],
      ["получить ИНН", "paluchít' INN", "vergi numarası almak", "Vergi dairesinden alınır."],
      ["налог", "nalók", "vergi", "Yurttaş görevidir."],
      ["налоговая декларация", "nalagóvaya dyeklarátsiya", "vergi beyannamesi", "Yılda bir verilir."],
      ["вычет", "výçyет", "vergi indirimi", "Bazı giderler için olur."],
      ["подоходный налог", "padakhódnyй nalók", "gelir vergisi", "Maaştan kesilir."],
    ],
    [
      ["ИНН нужен для работы и банка.", "Vergi numarası iş ve banka için gerekir."],
      ["Подоходный налог удерживают с зарплаты.", "Gelir vergisi maaştan kesilir."],
      ["Декларацию подают раз в год.", "Beyanname yılda bir verilir."],
    ],
    [
      ["Мигрант", "Где получить ИНН?", "Gdye paluchít' INN", "Vergi numarası nereden alınır?"],
      ["Инспектор", "В налоговой инспекции, с паспортом.", "F nalagóvay inspyéktsii, s pásportam", "Vergi dairesinden, pasaportla."],
      ["Мигрант", "Спасибо, завтра получу.", "Spasíba, záftra paluchú", "Teşekkürler, yarın alacağım."],
    ]),

  U("cit_75", 674, "A2", "🛒", "Market Alışverişi ve Fiyatlar",
    "Market kelimeleri: fiyat sorusu, ödeme, poşet",
    GOC, "#f59e0b",
    "📌 «сколько стоит / сколько стоят» — tekil / çoğul fiyat sorusu.\n«без пакета» — poşetsiz (çevre kuralı).",
    [
      ["продуктовый магазин", "pradúktavıy magazín", "market", "Günlük alışveriş yeridir."],
      ["сколько стоит?", "skól'ka stóit", "ne kadar (fiyat)?", "Temel soru kalıbı."],
      ["скидка", "skítka", "indirim", "Etikette yazılıdır."],
      ["на кассе", "na kassyé", "kasada", "Ödeme noktasıdır."],
      ["пакет", "pakyét", "poşet", "Ücretlidir."],
      ["наличными или картой?", "nalíčnımi ili kártay", "nakit mi kart mı?", "Kasa sorusudur."],
    ],
    [
      ["Сколько стоит этот сыр?", "Bu peynir ne kadar?"],
      ["На кассе спросили: наличными или картой?", "Kasada sordular: nakit mi kart mı?"],
      ["Пакет платный, без пакета — бесплатно.", "Poşet ücretli, poşetsiz — ücretsiz."],
    ],
    [
      ["Покупатель", "Сколько стоит этот хлеб?", "Skól'ka stóit état hlyeb", "Bu ekmek ne kadar?"],
      ["Продавец", "Тридцать рублей. С вас тридцать.", "Trítsat' rublyéy. S vas trítsat'", "Otuz ruble. Otuz lütfen."],
      ["Покупатель", "Заплачу картой, без пакета.", "Zaplačú kártay, byez pakyéta", "Kartla ödeyeceğim, poşet istemiyorum."],
    ]),
];
