// ============================================================
// 100 ÜNİTELİK YENİ KARIŞIK PAKET + 30 ÜNİTELİK AŞÇILIK PAKETİ
// Bu dosya mevcut müfredatın dışına eklenen bağımsız ünitelerdir.
// Her ünite aynı akışı kullanır: kelime kartları, cümle kurma ve diyalog.
// ============================================================
import type { UnitModule, WordDetail } from '../curriculumData';

type Spec = {
  title: string; description: string; category: string; level: WordDetail['level']; icon: string;
  words: [string, string, string][]; sentences: [string, string][];
};

const colors = ['#0ea5e9', '#8b5cf6', '#10b981', '#f59e0b', '#f43f5e', '#14b8a6', '#a855f7'];
const sentence = (ru: string, tr: string) => ({ ru, tr, scrambled: ru.split(' ').reverse(), correct: ru.split(' ') });

function build(start: number, prefix: string, specs: Spec[]): UnitModule[] {
  return specs.map((s, i) => {
    const n = start + i;
    const words = s.words.map(([ru, reading, tr], j) => ({
      id: `${prefix}_${n}_${j}`, ru, reading, tr, level: s.level,
      usageNote: `${s.title} bağlamında kullanılan kelime; cümle içinde tekrar ederek öğren.`
    }));
    return {
      id: `mod_plus_${prefix}_${n}`, unitNumber: n, levelGroup: s.level, title: s.title,
      description: s.description, category: s.category, color: colors[i % colors.length], icon: s.icon,
      grammarExplain: `📌 ${s.title.toUpperCase()}:\nBu ünitede ${s.description.toLowerCase()}. Kelimeleri cümle içinde kullan; Rusçada vurgu ve hâl eklerine dikkat et.\n\n🧠 Anlam ipucu: Önce Rusça cümlenin ana fikrini bul, sonra ayrıntıları çöz.`,
      words, sentences: s.sentences.map(([ru, tr]) => sentence(ru, tr)),
      sceneTitle: `${s.title} — kısa sahne`, sceneContext: `${s.description}. Günlük hayattan özgün bir Rusça konuşma.`,
      dialogue: [
        { speaker: 'Анна', ru: s.sentences[0][0], reading: '', tr: s.sentences[0][1] },
        { speaker: 'Иван', ru: s.sentences[1][0], reading: '', tr: s.sentences[1][1] },
        { speaker: 'Анна', ru: 'Понятно. Давай повторим ещё раз.', reading: '', tr: 'Anladım. Bir kez daha tekrarlayalım.' }
      ]
    };
  });
}

const W = (a: string, b: string, c: string, d: string, e: string, f: string, g: string, h: string): [string,string,string][] =>
  [[a, a, b], [c, c, d], [e, e, f], [g, g, h]];

// 224–323: 60 gündelik/akademik + 20 cümlede anlam/gramer + 20 kültürel/dinî ünite.
const mixed: Spec[] = [
  {title:'Komşuluk ve Apartman Hayatı',description:'komşuya ricada bulunma, gürültü ve ortak alanları konuş',category:'Gündelik Yaşam',level:'A2',icon:'🏢',words:W('сосед','komşu','подъезд','apartman girişi','шум','gürültü','лестница','merdiven'),sentences:[['Сосед попросил говорить тише.','Komşu daha sessiz konuşmamı istedi.'],['В подъезде нельзя оставлять вещи.','Apartman girişinde eşya bırakılmaz.']]},
  {title:'Evde Onarım',description:'bozuk eşyayı tarif et ve usta çağır',category:'Ev ve Yaşam',level:'A2',icon:'🔧',words:W('ремонт','onarım','краска','boya','стена','duvar','инструмент','alet'),sentences:[['Кран течёт, нужен ремонт.','Musluk akıtıyor, onarım gerekiyor.'],['Мастер придёт утром.','Usta sabah gelecek.']]},
  {title:'Çamaşır ve Temizlik',description:'ev işlerini, deterjanı ve temizlik sırasını anlat',category:'Ev ve Yaşam',level:'A2',icon:'🧺',words:W('стирка','çamaşır yıkama','порошок','deterjan','убирать','temizlemek','полотенце','havlu'),sentences:[['Я стираю белые вещи отдельно.','Beyazları ayrı yıkıyorum.'],['После уборки открой окно.','Temizlikten sonra pencereyi aç.']]},
  {title:'Kişisel Bakım',description:'kuaförde ve berberde isteklerini açıkla',category:'Sağlık ve Bakım',level:'A2',icon:'💇',words:W('стрижка','saç kesimi','волосы','saç','шампунь','şampuan','зеркало','ayna'),sentences:[['Я хочу короткую стрижку.','Kısa saç kesimi istiyorum.'],['Пожалуйста, не слишком коротко.','Lütfen çok kısa olmasın.']]},
  {title:'Duyguları Anlatma',description:'mutluluk, kaygı ve hayal kırıklığını cümlelerle anlat',category:'Duygular',level:'B1',icon:'🙂',words:W('радость','sevinç','тревога','kaygı','обида','gücenme','надежда','umut'),sentences:[['Я рад, что ты пришёл.','Geldiğine sevindim.'],['Не скрывай свои чувства.','Duygularını gizleme.']]},
  {title:'Plan ve Öncelik',description:'günün işlerini sıraya koy ve öncelik belirt',category:'Gündelik Yaşam',level:'B1',icon:'🗓️',words:W('план','plan','срочный','acil','сначала','önce','успеть','yetişmek'),sentences:[['Сначала закончим важную задачу.','Önce önemli işi bitirelim.'],['Я постараюсь всё успеть.','Her şeye yetişmeye çalışacağım.']]},
  {title:'İş Görüşmesi',description:'özgeçmiş, deneyim ve güçlü yönlerden söz et',category:'İş Hayatı',level:'B1',icon:'💼',words:W('собеседование','iş görüşmesi','опыт','deneyim','навык','beceri','должность','pozisyon'),sentences:[['У меня три года опыта.','Üç yıllık deneyimim var.'],['Я готов учиться новому.','Yeni şeyler öğrenmeye hazırım.']]},
  {title:'Toplantı Yönetimi',description:'gündem, öneri ve kararları profesyonelce ifade et',category:'İş Hayatı',level:'B2',icon:'📊',words:W('повестка','gündem','предложение','öneri','решение','karar','протокол','tutanak'),sentences:[['Давайте обсудим этот вопрос позже.','Bu konuyu daha sonra tartışalım.'],['Решение принято единогласно.','Karar oy birliğiyle alındı.']]},
  {title:'E-posta Nezaketi',description:'resmî e-postaya başla, rica et ve kibarca bitir',category:'İş Hayatı',level:'B1',icon:'✉️',words:W('уважаемый','sayın','приложение','ek','уточнить','netleştirmek','заранее','önceden'),sentences:[['Прикрепляю необходимые документы.','Gerekli belgeleri ekliyorum.'],['Заранее благодарю за ответ.','Yanıtınız için şimdiden teşekkür ederim.']]},
  {title:'Telefon ve Sesli Mesaj',description:'ulaşılamadığında mesaj bırak ve geri arama iste',category:'İletişim',level:'A1',icon:'📱',words:W('звонок','arama','сообщение','mesaj','перезвонить','geri aramak','занят','meşgul'),sentences:[['Я не могу сейчас говорить.','Şu an konuşamam.'],['Перезвони мне вечером.','Beni akşam geri ara.']]},
  {title:'Sosyal Medyada Güvenlik',description:'gizlilik, şifre ve şüpheli bağlantılar hakkında konuş',category:'Teknoloji',level:'B1',icon:'🔐',words:W('пароль','şifre','приватность','gizlilik','ссылка','bağlantı','мошенник','dolandırıcı'),sentences:[['Не открывай подозрительную ссылку.','Şüpheli bağlantıyı açma.'],['Сложный пароль защищает аккаунт.','Güçlü şifre hesabı korur.']]},
  {title:'Harita ve Konum',description:'bir yeri tarif et, uzaklık ve yön bildiren ifadeler kullan',category:'Seyahat',level:'A1',icon:'🗺️',words:W('карта','harita','перекрёсток','kavşak','прямо','düz','далеко','uzak'),sentences:[['Идите прямо до перекрёстка.','Kavşağa kadar düz gidin.'],['Музей находится недалеко.','Müze uzakta değil.']]},
  {title:'Tren Yolculuğu',description:'peron, aktarma ve gecikme bilgilerini anla',category:'Seyahat',level:'A2',icon:'🚆',words:W('платформа','peron','билет','bilet','пересадка','aktarma','задержка','gecikme'),sentences:[['Поезд отправляется с третьей платформы.','Tren üçüncü perondan kalkıyor.'],['Из-за задержки будет пересадка.','Gecikme yüzünden aktarma olacak.']]},
  {title:'Otel Sorunları',description:'rezervasyon, oda ve hizmet sorunlarını resepsiyona bildir',category:'Seyahat',level:'B1',icon:'🏨',words:W('бронирование','rezervasyon','ресепшен','resepsiyon','полотенце','havlu','жалоба','şikâyet'),sentences:[['В моей комнате не работает кондиционер.','Odamdaki klima çalışmıyor.'],['Можно поменять номер?','Odayı değiştirebilir misiniz?']]},
  {title:'Müze ve Sergi',description:'eser, sanatçı ve izlenimlerini anlat',category:'Kültür',level:'B1',icon:'🖼️',words:W('выставка','sergi','картина','tablo','художник','ressam','впечатление','izlenim'),sentences:[['Эта картина произвела на меня впечатление.','Bu tablo beni etkiledi.'],['Выставка открыта до воскресенья.','Sergi pazara kadar açık.']]},
  {title:'Müzik ve Konser',description:'müzik türleri, prova ve konser deneyimini konuş',category:'Kültür',level:'B1',icon:'🎵',words:W('концерт','konser','мелодия','melodi','сцена','sahne','репетиция','prova'),sentences:[['Музыканты долго репетировали.','Müzisyenler uzun süre prova yaptı.'],['Зал был полон зрителей.','Salon izleyicilerle doluydu.']]},
  {title:'Kitap ve Okuma',description:'kitabın konusu, karakteri ve yazarın üslubunu anlat',category:'Kültür',level:'B2',icon:'📚',words:W('сюжет','konu/olay örgüsü','герой','karakter','автор','yazar','стиль','üslup'),sentences:[['Главный герой меняется к концу романа.','Baş karakter romanın sonunda değişiyor.'],['Мне нравится стиль этого автора.','Bu yazarın üslubunu beğeniyorum.']]},
  {title:'Sinema Eleştirisi',description:'bir filmi öv, eleştir ve gerekçe göster',category:'Kültür',level:'B2',icon:'🎬',words:W('режиссёр','yönetmen','сцена','sahne','правдоподобный','inandırıcı','разочарование','hayal kırıklığı'),sentences:[['Фильм интересный, но финал слабый.','Film ilginç ama finali zayıf.'],['Я рекомендую его из-за актёров.','Oyuncular nedeniyle tavsiye ederim.']]},
  {title:'Fotoğraf ve Anı',description:'fotoğraf betimle, geçmişteki bir anıyı paylaş',category:'Kültür',level:'B1',icon:'📷',words:W('снимок','fotoğraf','воспоминание','anı','пейзаж','manzara','улыбка','gülümseme'),sentences:[['На снимке мы стоим у моря.','Fotoğrafta denizin yanında duruyoruz.'],['Это воспоминание мне особенно дорого.','Bu anı benim için özellikle değerli.']]},
  {title:'Spor ve Takım Ruhu',description:'antrenman, skor ve fair play hakkında konuş',category:'Spor',level:'A2',icon:'⚽',words:W('матч','maç','команда','takım','счёт','skor','тренировка','antrenman'),sentences:[['Наша команда выиграла матч.','Takımımız maçı kazandı.'],['После тренировки я устал.','Antrenmandan sonra yoruldum.']]},
  {title:'Doğada Yürüyüş',description:'patika, hava ve doğa gözlemlerini anlat',category:'Doğa',level:'A2',icon:'🥾',words:W('тропа','patika','лес','orman','вершина','zirve','рюкзак','sırt çantası'),sentences:[['Тропа ведёт к вершине.','Patika zirveye gidiyor.'],['Возьми воду и рюкзак.','Su ve sırt çantası al.']]},
  {title:'Hava Olayları',description:'fırtına, sis ve hava tahminini yorumla',category:'Doğa',level:'B1',icon:'⛈️',words:W('гроза','fırtına','туман','sis','прогноз','tahmin','молния','şimşek'),sentences:[['По прогнозу вечером будет гроза.','Tahmine göre akşam fırtına olacak.'],['Из-за тумана дорога опасна.','Sis yüzünden yol tehlikeli.']]},
  {title:'Çevre ve Geri Dönüşüm',description:'atık, enerji ve çevre sorumluluğunu tartış',category:'Çevre',level:'B1',icon:'♻️',words:W('отходы','atıklar','переработка','geri dönüşüm','энергия','enerji','загрязнение','kirlilik'),sentences:[['Отходы нужно сортировать.','Atıkları ayırmak gerekir.'],['Экономия энергии полезна для природы.','Enerji tasarrufu doğa için yararlıdır.']]},
  {title:'Hayvanlarla İletişim',description:'evcil hayvan bakımı ve hayvan davranışlarını anlat',category:'Doğa',level:'A2',icon:'🐾',words:W('питомец','evcil hayvan','корм','mama','поводок','tasma','ласковый','sevecen'),sentences:[['Собака ждёт хозяина у двери.','Köpek kapıda sahibini bekliyor.'],['Не забудь покормить кота.','Kediyi beslemeyi unutma.']]},
  {title:'Sağlıklı Uyku',description:'uyku düzeni, dinlenme ve ekran alışkanlıklarını konuş',category:'Sağlık',level:'B1',icon:'🌙',words:W('сон','uyku','режим','düzen','отдых','dinlenme','усталость','yorgunluk'),sentences:[['Мне нужен спокойный режим сна.','Sakin bir uyku düzenine ihtiyacım var.'],['Перед сном я не смотрю телефон.','Uyumadan önce telefona bakmıyorum.']]},
  {title:'Beslenme Etiketleri',description:'içindekiler, alerjen ve son kullanma tarihini oku',category:'Sağlık',level:'B1',icon:'🏷️',words:W('состав','içindekiler','аллерген','alerjen','срок','süre/tarih','калория','kalori'),sentences:[['Проверь состав продукта.','Ürünün içindekilerini kontrol et.'],['В составе нет орехов.','İçinde kuruyemiş yok.']]},
  {title:'İlk Yardım',description:'küçük yaralanmayı tarif et ve yardım iste',category:'Sağlık',level:'B1',icon:'🩹',words:W('рана','yara','бинт','bandaj','кровь','kan','обморок','bayılma'),sentences:[['Нужно промыть рану водой.','Yarayı suyla yıkamak gerekir.'],['Позвоните в скорую помощь.','Ambulansı arayın.']]},
  {title:'Doktora Belirti Anlatma',description:'ağrı, ateş ve belirtilerin ne zamandır sürdüğünü söyle',category:'Sağlık',level:'B1',icon:'🩺',words:W('симптом','belirti','температура','ateş','кашель','öksürük','лекарство','ilaç'),sentences:[['У меня болит горло второй день.','İki gündür boğazım ağrıyor.'],['Принимайте лекарство после еды.','İlacı yemekten sonra alın.']]},
  {title:'Para Transferi',description:'havale, ücret ve hesap bilgilerini bankada kullan',category:'Finans',level:'B1',icon:'💳',words:W('перевод','transfer','комиссия','komisyon','счёт','hesap','получатель','alıcı'),sentences:[['Сколько стоит перевод?','Transfer ne kadar?'],['Укажите имя получателя.','Alıcının adını belirtin.']]},
  {title:'Bütçe Planlama',description:'gelir, gider ve tasarruf hedefinden söz et',category:'Finans',level:'B2',icon:'💰',words:W('бюджет','bütçe','расход','gider','доход','gelir','сбережения','birikim'),sentences:[['Я веду учёт расходов.','Giderlerin kaydını tutuyorum.'],['Нужно увеличить сбережения.','Birikimleri artırmak gerekiyor.']]},
  {title:'Sigorta ve Hasar',description:'poliçe, kaza ve tazminat sürecini açıkla',category:'Finans',level:'B2',icon:'📄',words:W('страховка','sigorta','полис','poliçe','ущерб','hasar','компенсация','tazminat'),sentences:[['Страховая компания рассматривает заявление.','Sigorta şirketi başvuruyu inceliyor.'],['Документы нужны для компенсации.','Tazminat için belgeler gerekli.']]},
  {title:'Kira Sözleşmesi',description:'ev kiralarken depozito, süre ve koşulları sor',category:'Gündelik Yaşam',level:'B2',icon:'🔑',words:W('аренда','kira','залог','depozito','условие','koşul','срок','süre'),sentences:[['Какой срок аренды указан в договоре?','Sözleşmede kira süresi ne yazıyor?'],['Залог возвращается при выезде.','Depozito çıkarken iade edilir.']]},
  {title:'Müzakere ve Uzlaşma',description:'itiraz et, taviz ver ve ortak çözüm öner',category:'İletişim',level:'B2',icon:'🤝',words:W('переговоры','müzakere','компромисс','uzlaşma','уступка','taviz','условие','koşul'),sentences:[['Нам нужен разумный компромисс.','Makul bir uzlaşmaya ihtiyacımız var.'],['Я готов пойти навстречу.','Uzlaşmaya hazırım.']]},
  {title:'İstatistik Yorumlama',description:'grafik, artış, düşüş ve oranları anlat',category:'Akademik Rusça',level:'B2',icon:'📈',words:W('данные','veriler','рост','artış','снижение','azalma','доля','oran/pay'),sentences:[['Данные показывают стабильный рост.','Veriler istikrarlı artış gösteriyor.'],['Доля молодых участников увеличилась.','Genç katılımcıların oranı arttı.']]},
  {title:'Bilimsel Yöntem',description:'varsayım, kanıt ve sonucu akademik biçimde ifade et',category:'Akademik Rusça',level:'C1/C2',icon:'🔬',words:W('гипотеза','varsayım','доказательство','kanıt','метод','yöntem','вывод','sonuç'),sentences:[['Гипотеза требует дополнительной проверки.','Varsayım ek doğrulama gerektiriyor.'],['На основании данных сделан вывод.','Verilere dayanarak sonuç çıkarıldı.']]},
  {title:'Sunumda Geçişler',description:'sunum bölümlerini bağla, örnek ver ve özetle',category:'Akademik Rusça',level:'B2',icon:'🎤',words:W('во-первых','birincisi','далее','devamında','пример','örnek','итак','öyleyse/özetle'),sentences:[['Перейдём к следующему примеру.','Bir sonraki örneğe geçelim.'],['Итак, главный вывод такой.','Özetle, ana sonuç şöyle.']]},
  {title:'Cümlede Anlam: Neden-Sonuç',description:'çünkü, bu yüzden ve -dığı için ile neden-sonuç kur',category:'Cümlede Anlam',level:'B1',icon:'🔗',words:W('потому что','çünkü','поэтому','bu yüzden','причина','neden','результат','sonuç'),sentences:[['Я остался дома, потому что шёл дождь.','Yağmur yağdığı için evde kaldım.'],['Было поздно, поэтому мы ушли.','Geç olmuştu, bu yüzden ayrıldık.']]},
  {title:'Cümlede Anlam: Amaç',description:'için, amacıyla ve -mek üzere ile amaç bildir',category:'Cümlede Anlam',level:'B1',icon:'🎯',words:W('чтобы','-mek için','цель','amaç','ради','uğruna','для','için'),sentences:[['Я пришёл, чтобы помочь тебе.','Sana yardım etmek için geldim.'],['Мы учимся ради будущего.','Gelecek uğruna öğreniyoruz.']]},
  {title:'Cümlede Anlam: Koşul',description:'eğer, -se/-sa ve aksi hâlde ile şart kur',category:'Cümlede Anlam',level:'B1',icon:'❓',words:W('если','eğer','условие','şart','иначе','aksi hâlde','в случае','durumunda'),sentences:[['Если будет время, позвони мне.','Vaktin olursa beni ara.'],['Поторопись, иначе опоздаешь.','Acele et, yoksa geç kalırsın.']]},
  {title:'Cümlede Anlam: Karşılaştırma',description:'daha, kadar, aksine ve buna rağmen anlamlarını ayırt et',category:'Cümlede Anlam',level:'B1',icon:'⚖️',words:W('чем','-den/-dan','так же','aynı şekilde','однако','ancak','несмотря на','-e rağmen'),sentences:[['Сегодня теплее, чем вчера.','Bugün dünden daha sıcak.'],['Несмотря на дождь, мы гуляли.','Yağmura rağmen yürüdük.']]},
  {title:'Cümlede Anlam: Tahmin',description:'olasılık, kesinlik ve şüphe derecesini ifade et',category:'Cümlede Anlam',level:'B2',icon:'🔮',words:W('возможно','mümkün','вероятно','muhtemelen','точно','kesinlikle','сомнение','şüphe'),sentences:[['Возможно, поезд задержится.','Tren muhtemelen gecikecek.'],['Я точно не знаю ответа.','Cevabı kesin olarak bilmiyorum.']]},
  {title:'Cümlede Anlam: Vurgu',description:'özellikle, yalnızca, bile ve artık gibi anlam parçacıklarını kullan',category:'Cümlede Anlam',level:'B2',icon:'✨',words:W('только','sadece','даже','bile','особенно','özellikle','уже','artık/şimdiden'),sentences:[['Даже дети поняли правило.','Çocuklar bile kuralı anladı.'],['Особенно важен первый шаг.','İlk adım özellikle önemlidir.']]},
  {title:'Cümlede Anlam: Dolaylı Anlatım',description:'başkasının sözünü aktarmayı ve anlam değişimini öğren',category:'Cümlede Anlam',level:'B2',icon:'💬',words:W('сказать','söylemek','передать','aktarmak','сообщить','bildirmek','по словам','sözlerine göre'),sentences:[['Она сказала, что придёт завтра.','Yarın geleceğini söyledi.'],['По его словам, встреча отменена.','Onun sözlerine göre toplantı iptal edildi.']]},
  {title:'Cümlede Anlam: Zaman İlişkisi',description:'önce, sonra, o sırada ve beri ile olayları sırala',category:'Cümlede Anlam',level:'B1',icon:'⏳',words:W('до того как','-meden önce','после того как','-dikten sonra','пока','-iken','с тех пор','-den beri'),sentences:[['Позвони мне после того, как приедешь.','Geldikten sonra beni ara.'],['Пока я готовлю, накрой на стол.','Ben yemek yaparken sofrayı kur.']]},
  {title:'Cümlede Anlam: Tutum ve Değerlendirme',description:'memnuniyet, pişmanlık ve eleştiriyi yumuşak biçimde söyle',category:'Cümlede Anlam',level:'B2',icon:'🗣️',words:W('к сожалению','ne yazık ki','к счастью','neyse ki','жаль','yazık','согласен','katılıyorum'),sentences:[['К сожалению, мы не успели.','Ne yazık ki yetişemedik.'],['К счастью, всё закончилось хорошо.','Neyse ki her şey iyi bitti.']]},
  {title:'Cümlede Anlam: Özetleme',description:'kısacası, başka bir deyişle ve sonuç olarak kullan',category:'Akademik Rusça',level:'C1/C2',icon:'📝',words:W('короче','kısacası','иначе говоря','başka deyişle','в итоге','sonuç olarak','суть','öz'),sentences:[['Иными словами, план слишком дорогой.','Başka bir deyişle plan çok pahalı.'],['В итоге мы нашли решение.','Sonuç olarak çözümü bulduk.']]},
  {title:'Dini Hayatlar: İbadet ve Niyet',description:'ibadet, niyet, dua ve manevi pratikler hakkında saygılı konuş',category:'Din ve Maneviyat',level:'B1',icon:'🕊️',words:W('молитва','dua','намерение','niyet','поклонение','ibadet','духовный','manevi'),sentences:[['Намерение важно в духовной практике.','Niyet manevi uygulamada önemlidir.'],['Люди молятся по-разному.','İnsanlar farklı şekillerde dua eder.']]},
  {title:'Dini Hayatlar: Cami ve Ramazan',description:'Ramazan, oruç, iftar ve bayram geleneklerini anlat',category:'Din ve Maneviyat',level:'A2',icon:'🌙',words:W('Рамадан','Ramazan','пост','oruç','ифтар','iftar','праздник','bayram'),sentences:[['Во время Рамадана люди постятся.','Ramazan sırasında insanlar oruç tutar.'],['После поста семья собирается на ифтар.','Oruçtan sonra aile iftarda toplanır.']]},
  {title:'Dini Hayatlar: Bayram Ziyareti',description:'bayramlaşma, misafirlik ve büyükleri ziyaret etmeyi konuş',category:'Din ve Maneviyat',level:'A2',icon:'🎁',words:W('праздничный','bayrama ait','гость','misafir','пожелание','dilek','уважение','saygı'),sentences:[['В праздник мы навещаем старших.','Bayramda büyükleri ziyaret ederiz.'],['Желаю вашей семье мира и здоровья.','Ailenize huzur ve sağlık dilerim.']]},
  {title:'Dini Hayatlar: Farklı İnançlara Saygı',description:'inanç çeşitliliği, hoşgörü ve mahremiyet hakkında konuş',category:'Din ve Maneviyat',level:'B2',icon:'🤲',words:W('вера','inanç','терпимость','hoşgörü','разнообразие','çeşitlilik','уважать','saygı göstermek'),sentences:[['Мы уважаем разные убеждения.','Farklı inançlara saygı duyarız.'],['О вере нужно говорить бережно.','İnanç hakkında dikkatli konuşmak gerekir.']]},
  {title:'Dini Hayatlar: Kilise ve Gelenek',description:'kilise, mum, dua ve geleneksel günleri kültürel bağlamda tanı',category:'Kültür ve Din',level:'B1',icon:'⛪',words:W('церковь','kilise','свеча','mum','традиция','gelenek','святой','kutsal/aziz'),sentences:[['В церкви люди зажигают свечи.','Kilisede insanlar mum yakar.'],['Традиции передаются в семье.','Gelenekler ailede aktarılır.']]},
  {title:'Dini Hayatlar: Sinagog ve Topluluk',description:'sinagog, cemaat, bayram ve ortak yaşamı kültürel olarak anlat',category:'Kültür ve Din',level:'B1',icon:'🕍',words:W('синагога','sinagog','община','cemaat','память','hafıza','обычай','görenek'),sentences:[['Община собирается в праздник.','Cemaat bayramda toplanır.'],['Обычаи помогают сохранять память.','Görenekler hafızayı korumaya yardımcı olur.']]},
  {title:'Dini Hayatlar: Kutsal Metinler',description:'metin, yorum, anlam ve okuma geleneğini tarafsız biçimde konuş',category:'Kültür ve Din',level:'B2',icon:'📖',words:W('священный текст','kutsal metin','толкование','yorum','прочитать','okumak','смысл','anlam'),sentences:[['Каждый читатель ищет свой смысл.','Her okur kendi anlamını arar.'],['Текст можно толковать по-разному.','Metin farklı şekillerde yorumlanabilir.']]},
  {title:'Dini Hayatlar: Ahlak ve Sorumluluk',description:'iyilik, adalet, sorumluluk ve vicdan üzerine düşünce belirt',category:'Din ve Etik',level:'B2',icon:'⚖️',words:W('добро','iyilik','справедливость','adalet','ответственность','sorumluluk','совесть','vicdan'),sentences:[['Ответственность начинается с честности.','Sorumluluk dürüstlükle başlar.'],['Справедливость требует внимания к другим.','Adalet başkalarına dikkat etmeyi gerektirir.']]},
  {title:'Dini Hayatlar: Hac ve Ziyaret',description:'hac, ziyaret, yolculuk ve ortak dayanışma kavramlarını öğren',category:'Din ve Kültür',level:'B2',icon:'🧳',words:W('паломничество','hac/ziyaret','паломник','hac yolcusu','путь','yol','единство','birlik'),sentences:[['Паломничество требует подготовки.','Hac yolculuğu hazırlık gerektirir.'],['Общий путь создаёт чувство единства.','Ortak yolculuk birlik duygusu oluşturur.']]},
  {title:'Dini Hayatlar: Oruç ve Sabır',description:'oruç, sabır, dayanışma ve paylaşma temalarını karşılaştır',category:'Din ve Etik',level:'B1',icon:'🌅',words:W('терпение','sabır','самодисциплина','öz disiplin','делиться','paylaşmak','милосердие','merhamet'),sentences:[['Пост учит терпению и самодисциплине.','Oruç sabır ve öz disiplin öğretir.'],['Милосердие проявляется в помощи другим.','Merhamet başkalarına yardımda görülür.']]},
  {title:'Dini Hayatlar: Ortak Sofra',description:'farklı toplumlarda şükür, paylaşma ve misafirperverliği konuş',category:'Din ve Kültür',level:'A2',icon:'🍞',words:W('благодарность','şükran','угощение','ikram','гостеприимство','misafirperverlik','стол','sofra'),sentences:[['Общая трапеза объединяет людей.','Ortak sofra insanları birleştirir.'],['Гостю предлагают чай и угощение.','Misafire çay ve ikram sunulur.']]},
  {title:'Kültürel Bayramlar',description:'takvim, geleneksel yemek ve kutlama biçimlerini karşılaştır',category:'Kültür',level:'A2',icon:'🎊',words:W('календарь','takvim','обычай','gelenek','подарок','hediye','поздравлять','tebrik etmek'),sentences:[['В каждой культуре есть свои праздники.','Her kültürün kendi bayramları vardır.'],['Мы поздравляем друзей с праздником.','Arkadaşlarımızı bayramda tebrik ederiz.']]},
  {title:'Misafirperverlik Kültürü',description:'misafir karşılama, ikram ve nazik reddetme kalıplarını kullan',category:'Kültür',level:'A2',icon:'☕',words:W('принимать','ağırlamak','гостеприимный','misafirperver','угощать','ikram etmek','отказаться','reddetmek'),sentences:[['Хозяева тепло принимают гостей.','Ev sahipleri misafirleri sıcak karşılıyor.'],['Спасибо, но я пока откажусь.','Teşekkürler ama şimdilik almayayım.']]},
  {title:'Kültürlerarası Yanlış Anlama',description:'niyet, jest ve bağlam farklarını açıklayarak özür dile',category:'Kültürlerarası İletişim',level:'B2',icon:'🌍',words:W('недоразумение','yanlış anlama','жест','jest','намерение','niyet','контекст','bağlam'),sentences:[['Это было недоразумение, я не хотел обидеть.','Bu bir yanlış anlamaydı, kırmak istemedim.'],['Жесты зависят от культуры.','Jestler kültüre bağlıdır.']]},
  {title:'Gelenek ve Modernlik',description:'geleneklerin değişimini ve kuşaklar arası farkları tartış',category:'Kültür',level:'C1/C2',icon:'🔄',words:W('наследие','miras','современность','modernlik','поколение','kuşak','сохранять','korumak'),sentences:[['Молодое поколение переосмысливает традиции.','Genç kuşak gelenekleri yeniden düşünüyor.'],['Культурное наследие нужно сохранять.','Kültürel mirası korumak gerekir.']]},
  {title:'Etik Tartışma: Mahremiyet',description:'kişisel alan, rıza ve saygı hakkında gerekçeli görüş bildir',category:'Din ve Etik',level:'C1/C2',icon:'🛡️',words:W('граница','sınır','согласие','rıza','личный','kişisel','достоинство','onur'),sentences:[['Личные границы нужно уважать.','Kişisel sınırlara saygı göstermek gerekir.'],['Согласие должно быть свободным.','Rıza özgür iradeyle olmalıdır.']]},
  {title:'Haber ve Dezenformasyon',description:'kaynak, iddia ve doğrulama yaparak haberi değerlendir',category:'Medya Okuryazarlığı',level:'C1/C2',icon:'📰',words:W('источник','kaynak','утверждение','iddia','проверка','doğrulama','достоверный','güvenilir'),sentences:[['Проверь источник перед публикацией.','Yayınlamadan önce kaynağı kontrol et.'],['Это утверждение пока не подтверждено.','Bu iddia henüz doğrulanmadı.']]},
  {title:'Krizde İletişim',description:'sakinleştir, öncelik belirle ve açık talimat ver',category:'İletişim',level:'B2',icon:'🚨',words:W('кризис','kriz','инструкция','talimat','опасность','tehlike','спокойно','sakin'),sentences:[['Сохраняйте спокойствие и следуйте инструкции.','Sakin olun ve talimatı izleyin.'],['Сначала оценим опасность.','Önce tehlikeyi değerlendirelim.']]},
  {title:'Liderlik ve Geri Bildirim',description:'yapıcı eleştiri, hedef ve gelişim planı oluştur',category:'İş Hayatı',level:'C1/C2',icon:'🌟',words:W('лидерство','liderlik','обратная связь','geri bildirim','цель','hedef','развитие','gelişim'),sentences:[['Обратная связь помогает команде расти.','Geri bildirim ekibin gelişmesine yardım eder.'],['Нам нужно уточнить общую цель.','Ortak hedefi netleştirmemiz gerekiyor.']]},
  {title:'İş Kültürleri Karşılaştırması',description:'resmiyet, hiyerarşi ve doğrudan iletişim farklarını anlat',category:'Kültürlerarası İletişim',level:'C1/C2',icon:'🌐',words:W('иерархия','hiyerarşi','формальность','resmiyet','прямой','doğrudan','коллега','iş arkadaşı'),sentences:[['Стиль общения зависит от рабочей культуры.','İletişim tarzı çalışma kültürüne bağlıdır.'],['Коллеги договорились говорить прямо.','İş arkadaşları doğrudan konuşmaya karar verdi.']]},
  {title:'Hukukta Hak ve Yükümlülük',description:'sözleşme, hak, yükümlülük ve istisnayı akademik dille anlat',category:'İleri Rusça',level:'C1/C2',icon:'⚖️',words:W('право','hak','обязанность','yükümlülük','договор','sözleşme','исключение','istisna'),sentences:[['Договор определяет права сторон.','Sözleşme tarafların haklarını belirler.'],['Это правило имеет одно исключение.','Bu kuralın bir istisnası var.']]},
  {title:'Ekonomi ve Enflasyon',description:'fiyat, talep, arz ve ekonomik değişimleri yorumla',category:'İleri Rusça',level:'C1/C2',icon:'📉',words:W('инфляция','enflasyon','спрос','talep','предложение','arz','цена','fiyat'),sentences:[['Инфляция влияет на покупательную способность.','Enflasyon satın alma gücünü etkiler.'],['Спрос на продукт вырос.','Ürüne talep arttı.']]},
  {title:'Felsefi Görüş Bildirme',description:'soru sor, karşı görüşü tanı ve soyut düşünceyi savun',category:'İleri Rusça',level:'C1/C2',icon:'🧠',words:W('смысл','anlam','свобода','özgürlük','сомнение','şüphe','аргумент','argüman'),sentences:[['Свобода предполагает ответственность.','Özgürlük sorumluluk gerektirir.'],['Это сильный аргумент, но есть сомнения.','Bu güçlü bir argüman ama şüpheler var.']]},
  {title:'Araştırma Mülakatı',description:'soruları derinleştir, alıntı yap ve görüşleri karşılaştır',category:'Akademik Rusça',level:'C1/C2',icon:'🎙️',words:W('интервью','mülakat','респондент','katılımcı','цитата','alıntı','наблюдение','gözlem'),sentences:[['Респондент описал свой опыт подробно.','Katılımcı deneyimini ayrıntılı anlattı.'],['Цитата подтверждает наше наблюдение.','Alıntı gözlemimizi doğruluyor.']]},
  {title:'Kişisel Değerler',description:'dürüstlük, empati ve sınırlarını açıklayarak kendini tanıt',category:'Kişisel Gelişim',level:'B1',icon:'💎',words:W('ценность','değer','честность','dürüstlük','эмпатия','empati','выбор','seçim'),sentences:[['Честность для меня очень важна.','Dürüstlük benim için çok önemli.'],['Я стараюсь уважать чужой выбор.','Başkalarının seçimine saygı göstermeye çalışırım.']]},
  {title:'Karar Verme',description:'seçenekleri tart, riskleri belirt ve kararını gerekçelendir',category:'Kişisel Gelişim',level:'B2',icon:'🧭',words:W('вариант','seçenek','риск','risk','преимущество','avantaj','решить','karar vermek'),sentences:[['Нужно сравнить все варианты.','Tüm seçenekleri karşılaştırmak gerekir.'],['Я выбрал этот путь из-за преимуществ.','Avantajları nedeniyle bu yolu seçtim.']]},
  {title:'Hedef ve Alışkanlık',description:'alışkanlık oluştur, ilerlemeyi ölç ve ertelemeyi bırak',category:'Kişisel Gelişim',level:'B1',icon:'✅',words:W('привычка','alışkanlık','прогресс','ilerleme','откладывать','ertelemek','достичь','ulaşmak'),sentences:[['Маленькие шаги создают привычку.','Küçük adımlar alışkanlık oluşturur.'],['Не откладывай важное дело.','Önemli işi erteleme.']]},
  {title:'Dostluk ve Güven',description:'güven kazanma, sır saklama ve destek olmayı anlat',category:'İlişkiler',level:'B1',icon:'🫶',words:W('дружба','dostluk','доверие','güven','поддержка','destek','секрет','sır'),sentences:[['Доверие строится постепенно.','Güven yavaş yavaş kurulur.'],['Настоящий друг поддержит тебя.','Gerçek arkadaşın seni destekler.']]},
  {title:'Çatışma Çözümü',description:'özür dile, duyguyu adlandır ve ortak çözüm öner',category:'İlişkiler',level:'B2',icon:'🕊️',words:W('конфликт','çatışma','извинение','özür','обсудить','tartışmak','согласие','anlaşma'),sentences:[['Давай обсудим проблему спокойно.','Sorunu sakin biçimde konuşalım.'],['Извинение помогло восстановить доверие.','Özür güveni yeniden kurmaya yardımcı oldu.']]},
  {title:'Kutlama Planı',description:'davetiye, program, hediye ve ev sahibi ifadelerini kullan',category:'Gündelik Yaşam',level:'A2',icon:'🎉',words:W('приглашение','davetiye','праздник','kutlama','подарок','hediye','хозяин','ev sahibi'),sentences:[['Спасибо за приглашение на праздник.','Kutlama daveti için teşekkürler.'],['Что подарить хозяину?','Ev sahibine ne hediye edelim?']]},
  {title:'Bebek ve Çocuk Bakımı',description:'beslenme, uyku ve güvenli oyun alanını anlat',category:'Aile',level:'A2',icon:'🧸',words:W('ребёнок','çocuk','игрушка','oyuncak','коляска','bebek arabası','безопасный','güvenli'),sentences:[['Ребёнку нужна безопасная игрушка.','Çocuğun güvenli bir oyuncağa ihtiyacı var.'],['Малыш заснул в коляске.','Bebek arabasında uyudu.']]},
  {title:'Yaşlılara Destek',description:'yardım teklif et, randevu ve ilaç düzenini konuş',category:'Aile',level:'B1',icon:'🤍',words:W('помощь','yardım','пожилой','yaşlı','лекарство','ilaç','забота','özen'),sentences:[['Я помогу пожилому соседу.','Yaşlı komşuma yardım edeceğim.'],['Забота должна быть регулярной.','Özen düzenli olmalıdır.']]},
  {title:'Okul ve Öğretmen',description:'ders, ödev, sınav ve öğretmenden yardım istemeyi öğren',category:'Eğitim',level:'A2',icon:'🏫',words:W('урок','ders','домашнее задание','ödev','экзамен','sınav','учитель','öğretmen'),sentences:[['Я не понял домашнее задание.','Ödevi anlamadım.'],['Можно задать вопрос учителю?','Öğretmene soru sorabilir miyim?']]},
  {title:'Üniversite ve Bölüm',description:'bölüm, kampüs, araştırma ve mezuniyet hakkında konuş',category:'Eğitim',level:'B1',icon:'🎓',words:W('факультет','fakülte','кампус','kampüs','исследование','araştırma','выпуск','mezuniyet'),sentences:[['Я учусь на медицинском факультете.','Tıp fakültesinde okuyorum.'],['После выпуска я продолжу исследование.','Mezuniyetten sonra araştırmaya devam edeceğim.']]},
  {title:'Dil Öğrenme Stratejileri',description:'tekrar, bağlam, hata ve akıcılık hakkında öğrenme planı kur',category:'Eğitim',level:'B1',icon:'🗣️',words:W('повторение','tekrar','контекст','bağlam','ошибка','hata','беглость','akıcılık'),sentences:[['Повторение помогает запомнить слова.','Tekrar kelimeleri hatırlamaya yardım eder.'],['Ошибки — часть обучения.','Hatalar öğrenmenin bir parçasıdır.']]},
  {title:'Yaratıcı Yazma',description:'karakter, mekân ve olay örgüsüyle kısa hikâye kur',category:'Yazma',level:'B2',icon:'✍️',words:W('персонаж','karakter','описание','betimleme','сюжет','olay örgüsü','воображение','hayal gücü'),sentences:[['Воображение помогает создать героя.','Hayal gücü bir karakter yaratmaya yardım eder.'],['Описание места задаёт настроение.','Mekân betimlemesi atmosfer oluşturur.']]},
  {title:'Resmî Başvuru',description:'form, belge, imza ve son başvuru tarihini kullan',category:'Resmî Dil',level:'B1',icon:'🗂️',words:W('заявление','başvuru/dilekçe','документ','belge','подпись','imza','срок','son tarih'),sentences:[['Заполните заявление и поставьте подпись.','Başvuruyu doldurup imzalayın.'],['Срок подачи документов истекает завтра.','Belgelerin teslim süresi yarın bitiyor.']]},
  {title:'Büyük Şehirde Yaşam',description:'kalabalık, kira, ulaşım ve şehir ritmini karşılaştır',category:'Şehir Yaşamı',level:'B1',icon:'🏙️',words:W('мегаполис','metropol','пробка','trafik sıkışıklığı','арендная плата','kira bedeli','ритм','ritim'),sentences:[['В мегаполисе быстрый ритм жизни.','Metropolde hayatın ritmi hızlıdır.'],['Пробки увеличивают время в пути.','Trafik sıkışıklığı yolculuk süresini artırır.']]},
  {title:'Kırsal Hayat',description:'köy, tarım, mevsim ve sakin yaşamı betimle',category:'Şehir Yaşamı',level:'B1',icon:'🌾',words:W('деревня','köy','урожай','hasat','поле','tarla','спокойствие','sakinlik'),sentences:[['В деревне люди ближе к природе.','Köyde insanlar doğaya daha yakındır.'],['Урожай зависит от погоды.','Hasat havaya bağlıdır.']]},
  {title:'Göç ve Yeni Başlangıç',description:'taşınma, uyum, dil ve yeni çevreyi anlat',category:'Toplum',level:'B2',icon:'🧳',words:W('переезд','taşınma','адаптация','uyum','среда','çevre','начало','başlangıç'),sentences:[['Адаптация требует времени.','Uyum sağlamak zaman alır.'],['Новый язык открывает новую среду.','Yeni dil yeni bir çevre açar.']]},
  {title:'Gönüllülük',description:'gönüllü çalışma, dayanışma ve toplumsal faydayı konuş',category:'Toplum',level:'B1',icon:'🙌',words:W('волонтёр','gönüllü','помощь','yardım','сообщество','topluluk','польза','fayda'),sentences:[['Волонтёры помогают сообществу.','Gönüllüler topluluğa yardım eder.'],['Даже маленькая помощь приносит пользу.','Küçük bir yardım bile fayda sağlar.']]},
  {title:'Toplumsal Eşitlik',description:'fırsat, ayrımcılık ve kapsayıcı dil hakkında tartış',category:'Toplum',level:'C1/C2',icon:'⚖️',words:W('равенство','eşitlik','дискриминация','ayrımcılık','доступ','erişim','возможность','fırsat'),sentences:[['Равенство требует равного доступа.','Eşitlik eşit erişim gerektirir.'],['Дискриминацию нельзя игнорировать.','Ayrımcılık görmezden gelinemez.']]},
  {title:'Kamu Hizmeti',description:'belediye, başvuru, sıra ve vatandaşlık hizmetlerini kullan',category:'Toplum',level:'B1',icon:'🏛️',words:W('муниципалитет','belediye','услуга','hizmet','очередь','sıra','гражданин','vatandaş'),sentences:[['Гражданин подал заявление в муниципалитет.','Vatandaş belediyeye başvuru yaptı.'],['Эта услуга доступна онлайн.','Bu hizmet çevrim içi kullanılabilir.']]},
  {title:'Trafik ve Sürüş',description:'ehliyet, hız, kavşak ve güvenli sürüş ifadelerini öğren',category:'Ulaşım',level:'A2',icon:'🚗',words:W('водитель','sürücü','скорость','hız','светофор','trafik ışığı','поворот','dönüş'),sentences:[['Водитель остановился у светофора.','Sürücü trafik ışığında durdu.'],['Снизь скорость перед поворотом.','Dönüşten önce hızı azalt.']]},
  {title:'Bisiklet ve Scooter',description:'kask, bisiklet yolu ve kiralama şartlarını konuş',category:'Ulaşım',level:'A2',icon:'🚲',words:W('велосипед','bisiklet','шлем','kask','дорожка','yol/şerit','арендовать','kiralamak'),sentences:[['Надень шлем перед поездкой.','Sürüşten önce kask tak.'],['Велосипед можно арендовать на час.','Bisiklet bir saat kiralanabilir.']]},
  {title:'Havalimanında Kontrol',description:'bagaj, pasaport ve güvenlik sorularını anla',category:'Seyahat',level:'B1',icon:'🛫',words:W('багаж','bagaj','паспорт','pasaport','досмотр','kontrol','рейс','uçuş'),sentences:[['Покажите паспорт и посадочный талон.','Pasaportu ve biniş kartını gösterin.'],['Ваш багаж проходит досмотр.','Bagajınız kontrolden geçiyor.']]},
  {title:'Kamp ve Konaklama',description:'çadır kur, ateş yakma kurallarını ve ihtiyaçları anlat',category:'Doğa',level:'B1',icon:'⛺',words:W('палатка','çadır','костёр','kamp ateşi','спальный мешок','uyku tulumu','разрешение','izin'),sentences:[['Поставим палатку до темноты.','Çadırı hava kararmadan kuralım.'],['Для костра нужно разрешение.','Ateş için izin gerekiyor.']]},
  {title:'Deniz Kenarında Güvenlik',description:'dalga, cankurtaran, güneş ve yüzme uyarılarını anla',category:'Seyahat',level:'A2',icon:'🏖️',words:W('волна','dalga','спасатель','cankurtaran','берег','sahil','солнцезащитный','güneş koruyucu'),sentences:[['Не заплывай далеко от берега.','Kıyıdan uzağa yüzme.'],['Спасатель следит за безопасностью.','Cankurtaran güvenliği gözetiyor.']]},
  {title:'Dilbilgisi: Edilgen Yapı',description:'eylemi yapan değil yapılan işi öne çıkaran cümleleri anla',category:'Dilbilgisi',level:'B2',icon:'🔤',words:W('построить','inşa etmek','открыть','açmak','изменить','değiştirmek','решение','karar'),sentences:[['Мост был построен в прошлом году.','Köprü geçen yıl inşa edildi.'],['Решение было принято вчера.','Karar dün alındı.']]},
  {title:'Dilbilgisi: Hareket Fiilleri',description:'gitmek, gelmek, düzenli hareket ve tek seferlik hareket ayrımını öğren',category:'Dilbilgisi',level:'B1',icon:'🚶',words:W('идти','gitmek (şimdi)','ходить','gidip gelmek','ехать','araçla gitmek','ездить','araçla gidip gelmek'),sentences:[['Я иду в магазин сейчас.','Şimdi markete gidiyorum.'],['По выходным мы ходим в парк.','Hafta sonları parka gideriz.']]},
  {title:'Dilbilgisi: Görünüş',description:'tamamlanmış ve süreç hâlindeki eylemi ayırt et',category:'Dilbilgisi',level:'B2',icon:'🔁',words:W('делать','yapmak/süreç','сделать','yapıp bitirmek','читать','okumak/süreç','прочитать','okuyup bitirmek'),sentences:[['Я читал книгу весь вечер.','Bütün akşam kitap okuyordum.'],['Я прочитал книгу за два дня.','Kitabı iki günde bitirdim.']]},
  {title:'Dilbilgisi: Koşul ve Varsayım',description:'keşke, olsaydı ve varsayımsal sonuçları ifade et',category:'Dilbilgisi',level:'B2',icon:'💭',words:W('если бы','keşke/eğer olsaydı','мечта','hayal','возможность','olasılık','иначе','aksi hâlde'),sentences:[['Если бы я знал, я бы помог.','Bilseydim yardım ederdim.'],['На твоём месте я бы подождал.','Senin yerinde olsam beklerdim.']]},
  {title:'Dilbilgisi: Bağlaçlar',description:'ancak, oysa, hem...hem ve ne...ne bağlaçlarını karşılaştır',category:'Dilbilgisi',level:'B2',icon:'🧩',words:W('зато','buna karşılık','хотя','-e rağmen/gerçi','либо','ya...ya','ни','ne...ne'),sentences:[['Хотя было поздно, он продолжил работу.','Geç olmasına rağmen çalışmaya devam etti.'],['Он не пьёт ни чай, ни кофе.','Ne çay ne kahve içiyor.']]},
  {title:'Dilbilgisi: Hâllerle Anlam',description:'hâl değişiminin cümledeki anlamı nasıl değiştirdiğini gör',category:'Dilbilgisi',level:'B1',icon:'🧱',words:W('помогать','yardım etmek','ждать','beklemek','интересоваться','ilgilenmek','гордиться','gurur duymak'),sentences:[['Я помогаю другу.','Arkadaşıma yardım ediyorum.'],['Я жду друга.','Arkadaşımı bekliyorum.']]},
  {title:'Dilbilgisi: Sıfatların Derecesi',description:'daha, en ve aşırı dereceleriyle karşılaştırma yap',category:'Dilbilgisi',level:'B1',icon:'📐',words:W('быстрый','hızlı','быстрее','daha hızlı','самый','en','слишком','fazla/aşırı'),sentences:[['Этот путь быстрее.','Bu yol daha hızlı.'],['Это самый удобный вариант.','Bu en uygun seçenek.']]},
  {title:'Dilbilgisi: Belirsizlik',description:'birisi, herhangi biri ve hiç kimse gibi belirsiz zamirleri kullan',category:'Dilbilgisi',level:'B1',icon:'❔',words:W('кто-то','birisi','кто-нибудь','herhangi biri','никто','hiç kimse','что-то','bir şey'),sentences:[['Кто-то оставил сообщение.','Birisi mesaj bırakmış.'],['Никто не знает ответа.','Cevabı hiç kimse bilmiyor.']]},
  {title:'Dilbilgisi: Dolaylı Soru',description:'nerede, ne zaman ve neden olduğunu soran yan cümleleri kur',category:'Dilbilgisi',level:'B2',icon:'❓',words:W('ли','mi (dolaylı)','где','nerede','почему','neden','когда','ne zaman'),sentences:[['Я не знаю, где он живёт.','Onun nerede yaşadığını bilmiyorum.'],['Спроси, когда начинается урок.','Dersin ne zaman başladığını sor.']]},
  {title:'Dilbilgisi: Rica ve Kibarlık',description:'rica, öneri ve nazik ret cümlelerini resmî biçimde kullan',category:'İletişim',level:'A2',icon:'🙏',words:W('не могли бы','yapabilir miydiniz','будьте добры','lütfen','разрешите','izin verin','извините','affedersiniz'),sentences:[['Не могли бы вы повторить?','Tekrar eder misiniz?'],['Будьте добры, подождите минуту.','Lütfen bir dakika bekleyin.']]},
  {title:'Gelecek Planları',description:'kesin plan, niyet ve tahmini gelecek hakkında konuş',category:'Gündelik Yaşam',level:'A2',icon:'🔭',words:W('планировать','planlamak','собраться','niyet etmek','будущий','gelecek','возможно','belki'),sentences:[['Я собираюсь начать завтра.','Yarın başlamayı düşünüyorum.'],['В будущем мы будем работать вместе.','Gelecekte birlikte çalışacağız.']]},
  {title:'Geçmişi Anlatma',description:'olayları sıraya koy, süre ve arka plan bilgisi ver',category:'Cümlede Anlam',level:'B1',icon:'📜',words:W('вчера','dün','сначала','önce','потом','sonra','вдруг','birden'),sentences:[['Сначала мы позвонили, потом приехали.','Önce aradık, sonra geldik.'],['Вдруг начался сильный дождь.','Birden şiddetli yağmur başladı.']]},
  {title:'İhtiyaç ve Zorunluluk',description:'gerekli, yasak ve izin verilen şeyleri ifade et',category:'Cümlede Anlam',level:'A2',icon:'📌',words:W('нужно','gerekir','нельзя','yasak','можно','olur/izinli','обязательно','mutlaka'),sentences:[['Здесь нельзя парковаться.','Buraya park etmek yasak.'],['Нужно обязательно взять паспорт.','Pasaportu mutlaka almak gerekir.']]},
  {title:'Kibar İtiraz',description:'katılmadığını kırmadan söyle, gerekçe ve alternatif sun',category:'İletişim',level:'B2',icon:'💡',words:W('не совсем','tam olarak değil','позвольте не согласиться','katılmama izin verin','возможно','belki','альтернатива','alternatif'),sentences:[['Позвольте не согласиться с этим выводом.','Bu sonuca katılmadığımı belirtmek isterim.'],['Возможно, есть другая альтернатива.','Belki başka bir alternatif vardır.']]},
  {title:'Dijital Toplantı',description:'mikrofon, ekran paylaşımı ve bağlantı sorunlarını yönet',category:'Teknoloji',level:'B1',icon:'💻',words:W('микрофон','mikrofon','экран','ekran','подключение','bağlantı','включить','açmak'),sentences:[['Включите микрофон, пожалуйста.','Lütfen mikrofonu açın.'],['У меня пропало подключение.','Bağlantım kesildi.']]},
  {title:'Yapay Zekâ Hakkında Konuşma',description:'veri, model, yarar ve riskleri dengeli biçimde tartış',category:'Teknoloji',level:'C1/C2',icon:'🤖',words:W('искусственный интеллект','yapay zekâ','модель','model','данные','veri','риск','risk'),sentences:[['Модель обучается на больших данных.','Model büyük verilerle eğitiliyor.'],['Технология приносит пользу, но есть риски.','Teknoloji fayda sağlıyor ama riskleri var.']]},
  {title:'Enerji ve İklim',description:'emisyon, yenilenebilir enerji ve iklim hedeflerini anlat',category:'Çevre',level:'C1/C2',icon:'🌱',words:W('выбросы','emisyonlar','возобновляемый','yenilenebilir','климат','iklim','сократить','azaltmak'),sentences:[['Нужно сократить выбросы углерода.','Karbon emisyonlarını azaltmak gerekir.'],['Возобновляемая энергия развивается быстро.','Yenilenebilir enerji hızla gelişiyor.']]},
  {title:'Kültürel Miras Alanı',description:'anıt, restorasyon ve koruma kurallarını ziyaretçiye açıkla',category:'Kültür',level:'B1',icon:'🏛️',words:W('памятник','anıt','реставрация','restorasyon','наследие','miras','посетитель','ziyaretçi'),sentences:[['Памятник находится под охраной.','Anıt koruma altındadır.'],['Посетители не должны трогать экспонаты.','Ziyaretçiler sergilere dokunmamalı.']]},
  {title:'Bölgesel Yemek Kültürü',description:'yöresel tat, tarif ve sofra geleneğini kültürel bağlamda anlat',category:'Kültür ve Mutfak',level:'B1',icon:'🍲',words:W('региональный','bölgesel','рецепт','tarif','вкус','tat','традиционный','geleneksel'),sentences:[['У каждого региона есть традиционные блюда.','Her bölgenin geleneksel yemekleri vardır.'],['Рецепт передаётся из поколения в поколение.','Tarif kuşaktan kuşağa aktarılır.']]},
  {title:'Kültürlerarası Sofra',description:'sofrada alerji, tercih ve farklı yemek görgüsü kurallarını konuş',category:'Kültürlerarası İletişim',level:'B2',icon:'🍽️',words:W('предпочтение','tercih','аллергия','alerji','этикет','görgü','порция','porsiyon'),sentences:[['Пожалуйста, учтите мою аллергию.','Lütfen alerjimi dikkate alın.'],['В разных странах разный этикет.','Farklı ülkelerde farklı sofra adabı vardır.']]},
  {title:'Hafıza ve Öğrenme',description:'hatırlama, unutma ve tekrar yöntemlerini açıklayarak öneri ver',category:'Eğitim',level:'B1',icon:'🧠',words:W('память','hafıza','запомнить','ezberlemek','забыть','unutmak','повторять','tekrarlamak'),sentences:[['Повторяй слова через интервалы.','Kelimeleri aralıklarla tekrarla.'],['Я запомнил выражение в контексте.','İfadeyi bağlam içinde ezberledim.']]},
  {title:'Sonuç ve Değerlendirme',description:'performans, ölçüt ve gelişim sonucunu raporla',category:'Akademik Rusça',level:'C1/C2',icon:'📋',words:W('результат','sonuç','критерий','ölçüt','оценка','değerlendirme','эффективность','etkililik'),sentences:[['Результат соответствует критериям.','Sonuç ölçütlere uyuyor.'],['Нужно оценить эффективность метода.','Yöntemin etkililiğini değerlendirmek gerekir.']]}
];

// 324–353: yalnızca yemek yapma, baharat, malzeme ve profesyonel mutfak.
const cookingRaw = [
  ['Baharat Temelleri','baharatların adını, kokusunu ve ölçüsünü öğren','Aşçılık','A2','🌶️',[['корица','tarçın'],['тмин','kimyon'],['куркума','zerdeçal'],['паприка','paprika']],[['Добавь щепотку паприки.','Bir tutam paprika ekle.'],['Корица подходит к яблокам.','Tarçın elmaya yakışır.']]],
  ['Taze Otlar','dereotu, maydanoz ve fesleğeni tarifte kullan','Aşçılık','A2','🌿',[['укроп','dereotu'],['петрушка','maydanoz'],['базилик','fesleğen'],['мята','nane']],[['Нарежь зелень мелко.','Yeşillikleri ince doğra.'],['Мята освежает соус.','Nane sosu ferahlatır.']]],
  ['Sarımsak ve Soğan','soğanı kavurmayı ve sarımsağı doğru zamanda eklemeyi öğren','Aşçılık','A2','🧄',[['лук','soğan'],['чеснок','sarımsak'],['обжарить','kavurmak'],['аромат','aroma']],[['Сначала обжарь лук.','Önce soğanı kavur.'],['Чеснок добавляют в конце.','Sarımsak sona doğru eklenir.']]],
  ['Sirke ve Turşu','sirke, salamura ve turşu dengesini kur','Aşçılık','B1','🥒',[['уксус','sirke'],['маринад','marine/salamura'],['рассол','turşu suyu'],['мариновать','marine etmek']],[['Овощи маринуются ночь.','Sebzeler bir gece marine edilir.'],['В рассоле достаточно соли.','Turşu suyunda yeterince tuz var.']]],
  ['Yağlar ve Isı','zeytinyağı, ayçiçek yağı ve dumanlanma noktasını ayırt et','Aşçılık','B1','🫒',[['оливковое масло','zeytinyağı'],['подсолнечное масло','ayçiçek yağı'],['нагревать','ısıtmak'],['дым','duman']],[['Не перегревай масло.','Yağı fazla ısıtma.'],['Оливковое масло добавляют в салат.','Salataya zeytinyağı eklenir.']]],
  ['Et Kesimleri','et parçalarını, yağ oranını ve kesme yönünü anlat','Aşçılık','B1','🥩',[['вырезка','bonfile'],['фарш','kıyma'],['жир','yağ'],['нарезать','dilimlemek']],[['Нарежь мясо поперёк волокон.','Eti liflerin tersine kes.'],['Фарш готовится быстро.','Kıyma çabuk pişer.']]],
  ['Tavuk Hazırlığı','tavuğu temizleme, marine etme ve güvenli pişirmeyi öğren','Aşçılık','B1','🍗',[['курица','tavuk'],['грудка','göğüs eti'],['бедро','but'],['мариновать','marine etmek']],[['Курицу нужно полностью прожарить.','Tavuğu tamamen pişirmek gerekir.'],['Грудка готовится быстрее бедра.','Göğüs eti buttan daha çabuk pişer.']]],
  ['Balık ve Deniz Ürünleri','balığı ayıklama, kılçık ve tazelik kontrolünü konuş','Aşçılık','B1','🐟',[['рыба','balık'],['креветка','karides'],['кость','kılçık/kemik'],['свежий','taze']],[['Проверь, нет ли костей.','Kılçık olup olmadığını kontrol et.'],['Свежая рыба пахнет морем.','Taze balık deniz kokar.']]],
  ['Pişirme Dereceleri','az, orta ve iyi pişmiş et isteklerini söyle','Aşçılık','B1','🔥',[['сырой','çiğ'],['средней прожарки','orta pişmiş'],['хорошо прожаренный','iyi pişmiş'],['степень','derece']],[['Мне нужен стейк средней прожарки.','Bana orta pişmiş biftek lazım.'],['Проверь степень готовности.','Pişme derecesini kontrol et.']]],
  ['Fırın Sıcaklığı','fırını önceden ısıt, derece ve süreyi tarif et','Aşçılık','A2','♨️',[['духовка','fırın'],['температура','sıcaklık'],['разогреть','önceden ısıtmak'],['выпекать','fırında pişirmek']],[['Разогрей духовку до ста восьмидесяти градусов.','Fırını 180 dereceye ısıt.'],['Выпекай пирог тридцать минут.','Keki otuz dakika pişir.']]],
  ['Hamur Yoğurma','maya, yoğurma ve dinlendirme adımlarını anlat','Aşçılık','B1','🍞',[['дрожжи','maya'],['тесто','hamur'],['замешивать','yoğurmak'],['подниматься','kabarmak']],[['Оставь тесто подниматься.','Hamuru kabarmaya bırak.'],['Замешивай тесто десять минут.','Hamuru on dakika yoğur.']]],
  ['Kremalar ve Dolgular','krema, dolgu ve kıvamı tatlı tarifinde kullan','Aşçılık','B1','🍰',[['крем','krema'],['начинка','dolgu'],['взбивать','çırpmak'],['густой','koyu']],[['Взбей крем до густоты.','Kremayı koyulaşana kadar çırp.'],['Начинку добавляют после охлаждения.','Dolgu soğuduktan sonra eklenir.']]],
  ['Çorba Stokları','et suyu, sebze suyu ve köpük alma tekniğini öğren','Aşçılık','B1','🍲',[['бульон','et/sebze suyu'],['пенка','köpük'],['варить','kaynatmak/pişirmek'],['наваристый','yoğun']],[['Сними пенку с бульона.','Et suyunun köpüğünü al.'],['Наваристый бульон готовится долго.','Yoğun et suyu uzun pişer.']]],
  ['Sosların Temeli','roux, krema, kıvam ve sosu bağlamayı öğren','Aşçılık','B2','🥣',[['соус','sos'],['загуститель','kıvam artırıcı'],['сливки','krema'],['смешивать','karıştırmak']],[['Добавь сливки и перемешай.','Krema ekle ve karıştır.'],['Соус должен быть однородным.','Sos homojen olmalı.']]],
  ['Emülsiyon Soslar','mayonez, vinaigrette ve yağ-su dengesini kur','Aşçılık','B2','🫙',[['эмульсия','emülsiyon'],['горчица','hardal'],['взбивать','çırpmak'],['однородный','homojen']],[['Масло вводи тонкой струйкой.','Yağı ince bir akışla ekle.'],['Горчица помогает связать соус.','Hardal sosu bağlamaya yardım eder.']]],
  ['Sebze Pişirme Teknikleri','blanch, buharda pişirme ve soteyi karşılaştır','Aşçılık','B1','🥦',[['бланшировать','blanch etmek'],['на пару','buharda'],['тушить','kısık ateşte pişirmek'],['соте','sote']],[['Бланшируй овощи две минуты.','Sebzeleri iki dakika blanch et.'],['На пару вкус daha iyi korunur.','Buharda tat daha iyi korunur.']]],
  ['Bakliyat ve Tahıllar','mercimek, nohut, bulgur ve pişirme sürelerini anlat','Aşçılık','A2','🫘',[['чечевица','mercimek'],['нут','nohut'],['булгур','bulgur'],['крупа','tahıl/yarma']],[['Нут нужно замочить заранее.','Nohudu önceden ıslatmak gerekir.'],['Чечевица варится быстро.','Mercimek çabuk pişer.']]],
  ['Pirinç ve Risotto','pirinci yıkama, kavurma ve kıvamını kontrol et','Aşçılık','B1','🍚',[['рис','pirinç'],['ризотто','risotto'],['крахмал','nişasta'],['кремовый','kremamsı']],[['Рис впитывает бульон постепенно.','Pirinç et suyunu yavaş yavaş çeker.'],['Ризотто должно быть кремовым.','Risotto kremamsı olmalı.']]],
  ['Makarna ve Erişte','hamur, al dente, süzme ve sosla birleştirmeyi öğren','Aşçılık','A2','🍝',[['макароны','makarna'],['лапша','erişte'],['аль денте','al dente'],['сливать','süzmek']],[['Свари макароны аль денте.','Makarnayı al dente pişir.'],['Не промывай пасту после варки.','Makarnayı haşladıktan sonra yıkama.']]],
  ['Mantı ve Pelmeni','hamur açma, iç doldurma ve kapatma fiillerini kullan','Aşçılık','B1','🥟',[['пельмени','pelmeni'],['начинка','iç harç'],['защипывать','kenar kapatmak'],['раскатывать','hamur açmak']],[['Раскатай тесто тонко.','Hamuru ince aç.'],['Хорошо защипни края.','Kenarları iyice kapat.']]],
  ['Salata Sosu','sirke, limon, yağ ve tuzla denge kur','Aşçılık','A2','🥗',[['салат','salata'],['лимон','limon'],['кислый','ekşi'],['заправка','salata sosu']],[['Добавь лимонный сок в заправку.','Sosa limon suyu ekle.'],['Салат должен быть свежим.','Salata taze olmalı.']]],
  ['Ekmek ve Kabuk','ekmek kabuğu, iç doku ve buharı tarif et','Aşçılık','B2','🥖',[['корка','kabuk'],['мякиш','ekmek içi'],['плотный','yoğun'],['хрустящий','çıtır']],[['Корка должна быть хрустящей.','Kabuk çıtır olmalı.'],['Дай хлебу остыть.','Ekmeği soğumaya bırak.']]],
  ['Kahve Demleme','öğütme, filtre, aroma ve demleme süresini anlat','Aşçılık','A2','☕',[['кофе','kahve'],['помол','öğütme'],['фильтр','filtre'],['заваривать','demlemek']],[['Сделай помол мельче.','Öğütmeyi daha ince yap.'],['Кофе заваривается четыре минуты.','Kahve dört dakika demlenir.']]],
  ['Çay Kültürü','çaydanlık, dem, sıcaklık ve ikramı öğren','Aşçılık','A2','🫖',[['чайник','çaydanlık'],['заварка','dem'],['кипяток','kaynar su'],['наливать','dökmek']],[['Не лей кипяток на зелёный чай.','Yeşil çayın üzerine kaynar su dökme.'],['Налей чай гостю.','Misafire çay doldur.']]],
  ['Fermente Ürünler','yoğurt, kefir, maya ve fermantasyon sürecini anlat','Aşçılık','B2','🥛',[['ферментация','fermantasyon'],['кефир','kefir'],['йогурт','yoğurt'],['кислый','ekşi']],[['Ферментация меняет вкус продукта.','Fermantasyon ürünün tadını değiştirir.'],['Йогурт должен быть густым.','Yoğurt koyu olmalı.']]],
  ['Dondurma ve Soğuk Tatlı','şeker şurubu, dondurma ve kristalleşmeyi konuş','Aşçılık','B2','🍨',[['мороженое','dondurma'],['сироп','şurup'],['замораживать','dondurmak'],['кристалл','kristal']],[['Охлади смесь перед заморозкой.','Karışımı dondurmadan önce soğut.'],['Сироп добавляет сладость.','Şurup tatlılık katar.']]],
  ['Çikolata Teknikleri','benmari, kakao, temperleme ve parlaklığı öğren','Aşçılık','B2','🍫',[['шоколад','çikolata'],['какао','kakao'],['темперировать','temperlemek'],['блестящий','parlak']],[['Темперируй шоколад аккуратно.','Çikolatayı dikkatle temperle.'],['Какао усиливает вкус.','Kakao tadı güçlendirir.']]],
  ['Profesyonel Bıçak Kullanımı','şef bıçağı, kesim güvenliği ve doğrama hızını öğren','Aşçılık','B1','🔪',[['шефский нож','şef bıçağı'],['нарезка','doğrama'],['острый','keskin'],['доска','kesme tahtası']],[['Нож должен быть острым.','Bıçak keskin olmalı.'],['Пальцы держи согнутыми.','Parmaklarını kıvrık tut.']]],
  ['Mutfak Hijyeni','el yıkama, çiğ-pişmiş ayrımı ve yüzey temizliğini uygula','Aşçılık','A2','🧼',[['гигиена','hijyen'],['перчатка','eldiven'],['сырой','çiğ'],['дезинфицировать','dezenfekte etmek']],[['Разделяй сырые и готовые продукты.','Çiğ ve hazır ürünleri ayır.'],['Мой руки перед готовкой.','Yemek yapmadan önce ellerini yıka.']]],
  ['Mutfak Maliyeti ve İsraf','porsiyon, maliyet, stok ve gıda israfını yönet','Aşçılık','C1/C2','📦',[['себестоимость','maliyet'],['порция','porsiyon'],['запасы','stoklar'],['отходы','atıklar']],[['Рассчитай себестоимость порции.','Bir porsiyonun maliyetini hesapla.'],['Планирование уменьшает отходы.','Planlama israfı azaltır.']]],
  ['Menü Tasarımı','menü dengesi, mevsimsellik ve yemek açıklaması yaz','Aşçılık','C1/C2','📜',[['меню','menü'],['сезонный','mevsimlik'],['описание','açıklama'],['сочетание','eşleşme']],[['Меню должно быть сбалансированным.','Menü dengeli olmalı.'],['Опиши блюдо коротко и ясно.','Yemeği kısa ve açık tarif et.']]],
  ['Şef ve Mutfak Ekibi','istasyon, vardiya, komut ve servis koordinasyonunu öğren','Aşçılık','C1/C2','👨‍🍳',[['шеф','şef'],['бригада','ekip'],['смена','vardiya'],['выдача','servis çıkışı']],[['Команда должна работать слаженно.','Ekip uyumlu çalışmalı.'],['Шеф проверяет выдачу блюд.','Şef yemeklerin çıkışını kontrol eder.']]],
  ['Degüstasyon Notu','aroma, doku, asidite ve bitiş hakkında profesyonel not yaz','Aşçılık','C1/C2','🍷',[['дегустация','degüstasyon'],['аромат','aroma'],['текстура','doku'],['послевкусие','bitiş/son tat']],[['Текстура блюда мягкая и гладкая.','Yemeğin dokusu yumuşak ve pürüzsüz.'],['Послевкусие долгое и пряное.','Son tat uzun ve baharatlı.']]],
  ['Sürdürülebilir Mutfak','yerel ürün, mevsim ve sıfır atık yaklaşımını tartış','Aşçılık','C1/C2','🌍',[['локальный','yerel'],['сезонность','mevsimsellik'],['нулевые отходы','sıfır atık'],['фермер','çiftçi']],[['Сезонность улучшает вкус и снижает расходы.','Mevsimsellik tadı iyileştirir ve masrafı azaltır.'],['Ресторан сотрудничает с местным фермером.','Restoran yerel çiftçiyle çalışıyor.']]]
].map(([title,description,category,level,icon,raw,sents]) => ({title,description,category,level: level as WordDetail['level'],icon,words:(raw as string[][]).map(x=>[x[0],x[0],x[1]] as [string,string,string]),sentences:sents as [string,string][]})) as Spec[];

// Kesin kapsam: tam 100 karışık ünite ve bunların dışında tam 30 aşçılık ünitesi.
const CEFR_ORDER: WordDetail['level'][] = ['A1', 'A2', 'B1', 'B2', 'C1/C2'];

// Yeni karışık pakette seviye sırası korunur: A1-A2 → B1-B2 → C1/C2.
// "Karışık" yalnızca konu çeşitliliğidir; öğrenme yolu seviye olarak karışmaz.
function buildByLevel(start: number, prefix: string, specs: Spec[]): UnitModule[] {
  const ordered = CEFR_ORDER.flatMap((level) => specs.filter((s) => s.level === level));
  return build(start, prefix, ordered);
}

export const EXPANSION_MIXED_100 = buildByLevel(224, 'mix', mixed.slice(0, 100));
export const EXPANSION_COOKING_30 = build(324, 'cook', cookingRaw.slice(0, 30));
export const EXPANSION_100_PLUS_30 = [...EXPANSION_MIXED_100, ...EXPANSION_COOKING_30];
