D.update({
'Hayat': 'life',
'Hayır işi': 'charity',
'Hazır': 'ready',
'Hazır zili': 'readiness bell',
'Hazır ürün': 'finished product',
'Hazırlık listesi': 'prep list',
'Haç': 'cross',
'Haşlamak': 'to boil',
'Hedef / Amaç': 'goal',
'Hediye': 'present',
'Helal': 'halal',
'Hemen değiştireceğiz': 'we will replace it right away',
'Hemen mi sonra mı?': 'now or later?',
'Her ne kadar': 'even though',
'Her zaman': 'always',
'her zaman': 'always',
'Her zamanki gibi': 'as usual',
'Her şey yolunda': 'everything is fine',
'Herkese açık cevap': 'public reply',
'Herkese açık paylaşım': 'public post',
'Hesaba dahil': 'included in the bill',
'Hesabı bölmek': 'to split the bill',
'Hesabı getirin': 'bring the bill',
'Hesabı imzalamak': 'to sign the bill',
'Heves': 'mood',
'Heyecanlanmak / Endişelenmek': 'to worry',
'Hijyen': 'hygiene',
'Hijyen kuralları': 'sanitary rules',
'Hijyen turu': 'sanitary inspection round',
'Hipotez': 'hypothesis',
'Hisse senedi': 'share (stock)',
'Hizmet süresi': 'work experience',
'Hiç kimse': 'nobody',
'Hiçbir şey': 'nothing',
'Hobi': 'hobby',
'Homojen / Pürüzsüz': 'smooth',
'Hoş geldiniz': 'welcome',
'Hoşgörü': 'tolerance',
'Hoşuma gidiyor': 'I like it',
'Hoşuna gitmek': 'to be liked',
'Hoşça kalın': 'goodbye',
'Hukukçu / Avukat': 'lawyer',
'Huy / Mizaç': 'temper',
'Huysuzlanmak': 'to act up',
'Huş dalı demeti': 'birch besom',
'Hâkim / Yargıç': 'judge',
'Hâl hatır sormak': 'to ask how one is doing',
'Hüküm / Karar': 'verdict',
'Hünerli eller': 'golden hands',
'Hız': 'speed',
'Hızlı / Çabuk': 'fast',
'Hızlı sotelemek': 'to sear quickly',
'Hızlı soğutmak': 'to chill quickly',
'Hızlı çıkış': 'fast output',
'ihtimal dışı bırakılamaz': 'one cannot rule out',
'ile (araç hâli)': 'with (instrumental)',
'ile hâli sorusu': 'with whom? with what?',
'Islak': 'wet',
'Islak mendil': 'wet wipes',
'Islatmak': 'to soak',
'Isı': 'warmth',
'Isı korumalı kap': 'thermal container',
'Isınma': 'warming',
'Isıtmak': 'to heat up',
'içeri girmek': 'to come inside',
'Işık': 'light',
'İade': 'return (refund)',
'İade etmek': 'to give back',
'İbadet / Ayin': 'worship',
'İddia etmek': 'to claim',
'İdi / Vardı': 'there was',
'İfade biçimi': 'wording',
'İflas': 'bankruptcy',
'İhlal': 'violation',
'İkamet kaydı': 'residence registration',
'İki': 'two',
'İki kişilik masa': 'table for two',
'İki saat': 'two hours',
'İkilem': 'dilemma',
'İkinci el araba': 'second hand car',
'İklim': 'climate',
'İkna edici': 'convincing',
'İkna edici biçimde': 'convincingly',
'İkna etmek': 'to convince',
'İkona': 'icon',
'İkonostasis': 'iconostasis',
'İkram': 'treat',
'İkram etmek': 'to treat (someone)',
'İlacın muadili': 'generic drug',
'İlahiyat': 'theology',
'İlaç': 'medicine',
'İlaçlar': 'medicines',
'İlgilenmek / Bakmak': 'to take care',
'İlginç': 'interesting',
'İlk / Birinci': 'first',
'İlk mesaj': 'first message',
'İlk yardım/ilaç çantası': 'first aid kit',
'İlkbahar': 'spring',
'İma etmek': 'to hint',
'İmam': 'imam',
'İmge / Tip': 'image',
'İmkân / Olasılık': 'possibility',
'İmza': 'signature',
'İmzalamak': 'to sign',
'İnancın yeniden canlanması': 'revival of faith',
'İnanmak / Güvenmek': 'to believe',
'İnanç': 'faith',
'İnanç / Kanaat': 'conviction',
'İnançlı kişi': 'believer',
'İnce dilimler': 'thin slices',
'İnce ekşilik': 'light acidity',
'İnce ince': 'finely',
'İnce kıymak': 'to mince',
'İncelik': 'subtlety',
'İncik / But': 'shin',
'İndirim': 'discount',
'İndirim kartı': 'discount card',
'İndirim yapmak': 'to give a discount',
'İndirmek': 'to download',
'İnek': 'cow',
'İnternet': 'internet',
'İnşa edilmek': 'to be built',
'İptal etmek': 'to cancel',
'İroni': 'irony',
'İrsaliye': 'waybill',
'İse / Oysa': 'whereas',
'İsim': 'name',
'İstasyon': 'station',
'İstisna': 'exception',
'İtfaiye denetimi': 'fire inspection',
'İtiraz': 'objection',
'İtiraz etmek': 'to appeal',
'İtiraz yazısı': 'complaint letter',
'İyi': 'good',
'İyi akşamlar': 'good evening',
'İyi geceler': 'good night',
'İyi günler': 'have a good day',
'İyi pişmiş': 'well done (steak)',
'İyi şanslar / Hoşça kal': 'good luck and goodbye',
'İyice uyumak': 'to get enough sleep',
'İyileşme / Rehabilitasyon': 'recovery',
'İzlemek / Bakmak': 'to watch',
'İzlenim': 'impression',
'İzleyenler': 'viewers',
'İç dolgu': 'filling',
'İç organlarını çıkarmak': 'to gut',
'İçecekler': 'drinks',
'İçeriği netleştirmek': 'to clarify the ingredients',
'İçinde / -de': 'inside',
'İçindekiler': 'ingredients',
'İçmek': 'to drink',
'İş anlaşmazlığı': 'labour dispute',
'İş birliği': 'cooperation',
'İş görüşmesi / Mülakat': 'job interview',
'İş günleri': 'working days',
'İş tanımı / Brief': 'brief',
'İşlemini yapmak': 'to process (paperwork)',
'İşler': 'things (affairs)',
'İşler nasıl gidiyor': 'how are things at work',
'İştah': 'appetite',
'İşte böyle': 'that is how',
'İşten çıkarma': 'dismissal',
'Jülyen / Çöp şeklinde': 'julienne',
'Jülyen doğramak': 'to cut into julienne',
'Kablo': 'cable',
'Kabuk': 'crust',
'Kaburga': 'ribs',
'Kadeh': 'wine glass',
'Kader': 'fate',
'Kafe': 'cafe',
'Kafiye': 'rhyme',
'Kafkasya': 'the Caucasus',
'Kahraman / Karakter': 'hero',
'Kahvaltı': 'breakfast',
'Kahvaltı dahil': 'breakfast included',
'Kahvaltı etmek': 'to have breakfast',
'kahvaltı etmek': 'to have breakfast',
'Kahve': 'coffee',
'Kahveci / Kafe': 'coffee shop',
'Kalan stok': 'remaining stock',
'Kaldırmak': 'to lift',
'Kalem (tükenmez)': 'pen',
'Kalemi iptal etmek': 'to cancel the item',
'kalkmak': 'to get up',
'Kalkmasına yardım etmek': 'to help someone up',
'Kalori': 'calories',
'Kalp': 'heart',
'Kamera': 'camera',
'Kameralar': 'cameras',
'Kamp ateşi': 'campfire',
'Kanepe': 'sofa',
'Kanun': 'law',
'Kanıt': 'proof',
'Kapak': 'lid',
'Kapanış sorumlusu': 'closing manager',
'Kapatmak': 'to close',
'Kapağını kapatmak (konserve)': 'to seal (a jar)',
'Kapora': 'down payment',
'Kapı': 'door',
'Kapı sesi': 'door knock',
'Kapıda sıra': 'queue at the door',
'Kapılar': 'doors',
'Kapıya bırakmak': 'to leave at the door',
'Kapıyı açmak': 'to open the door',
'Kar': 'snow',
'Kara bulutlar': 'dark clouds',
'Karabuğday': 'buckwheat',
'Karar / Çözüm': 'decision',
'Karar vermek': 'to make a decision',
'Karides': 'shrimp',
'Kart anahtar': 'key card',
'Kartla ödeme': 'card payment',
'Kartopu': 'snowball',
'Kartı okutmak': 'to tap the card',
'Karıncalar': 'ants',
'Karıştırmamak': 'not to mix',
'Karşılama görevlisi': 'hostess',
'Karşılamak (masrafı)': 'to cover (costs)',
'Karşılaşmak / Tanışmak': 'to meet',
'Karşılaştım / Tanıştım': 'I met',
'Karşılıklılık': 'reciprocity',
'Karşıya geçmek': 'to cross',
'Kasa': 'cash desk',
'Kasayı kapatmak': 'to close the till',
'Kasiyer': 'cashier',
'Kat': 'floor',
'Katalog': 'catalogue',
'Katedral / Konsil': 'cathedral',
'katılıyorum': 'I agree',
'Kavanoz': 'jar',
'Kavurma sosu (soğan-havuç)': 'sofrito',
'Kavşak': 'crossroads',
'Kaybetmek': 'to lose',
'Kaydırak': 'slide (playground)',
'Kaygı': 'concern',
'Kaygı / Anksiyete': 'anxiety',
'Kaygılanmak / Dert etmek': 'to be anxious',
'Kaynak': 'source',
'Kaynak bilimi': 'study of sources',
'Kaynamak': 'to come to the boil',
'Kaynatarak azaltmak': 'to reduce (sauce)',
'Kayıp eşya bürosu': 'lost and found',
'Kayıpları azaltmak': 'to cut losses',
'Kaza': 'accident',
'Kazak': 'sweater',
'Kaç / Ne kadar': 'how much',
'Kaç / Ne kadar?': 'how many?',
'Kaç kişi için?': 'for how many people?',
'Kaçırmak / Devamsızlık yapmak': 'to miss',
'Kaşık': 'spoon',
'Kedi': 'cat',
'Kedi (erkek)': 'tomcat',
'Kefaret': 'atonement',
'Kefil': 'guarantor',
'Kefir': 'kefir',
'Kelime oyunu': 'pun',
'kelimeyi unuttum': 'I forgot the word',
'Kendine iyi bak': 'take care of yourself',
'Kentsel dönüşüm': 'urban renewal',
'Kepçe': 'ladle',
'Kesilmek (krema)': 'to curdle',
'Kesinlikle / Aynen': 'exactly',
'Keskin bıçak': 'sharp knife',
'Kesme tahtası': 'chopping board',
'Kez / Defa': 'times',
'Ki / Olan': 'which (relative)',
'Kibarca reddetmek': 'to refuse politely',
'Kilise': 'church',
'Kilise Slavcası': 'Church Slavonic',
'Kilit': 'lock',
'Kilometre': 'mileage',
'Kim': 'who',
'Kim?': 'who?',
'Kimlik': 'identity',
'Kimyon (kimyon tohumu)': 'cumin',
'Kira': 'rent',
'Kira artışı': 'rent increase',
'Kira bedeli': 'rent payment',
'Kira sözleşmesi': 'rental agreement',
'Kiracı': 'tenant',
'Kiraya vermek': 'to rent out',
'Kirli': 'dirty',
'Kirlilik': 'pollution',
'Kitap': 'book',
'Kitap iade etmek': 'to return a book',
'Kitap kulübü': 'book club',
'Kişisel teklif': 'personal offer',
'Klinik': 'clinic',
'Koca / Bütün': 'whole',
'Kod': 'code',
'Kol': 'shoulder',
'Kolhoz': 'collective farm',
'Koli / Paket': 'parcel',
'Koltuklar': 'seats',
'Kombi': 'boiler',
'Kombi fırın': 'combi oven',
'Komi': 'waiter assistant',
'Komik': 'funny',
'Komisyon': 'commission',
'Kompartıman': 'train compartment',
'Komşu': 'neighbour',
'Komşular': 'neighbours',
'Konfit': 'confit',
'Konsepti açıklamak': 'to explain the concept',
'Konser': 'concert',
'Konsolosluk': 'consulate',
'Kontrol raporu': 'inspection report',
'Kontrolör': 'ticket inspector',
'Konu': 'topic',
'Konut kredisi': 'mortgage',
'Konuşma / Sunum': 'presentation',
'Konuşma diline ait': 'colloquial',
'Konuşmak': 'to speak',
'Konuşurken': 'while speaking',
'Koordinatör': 'coordinator',
'Koridor': 'corridor',
'Korkmak': 'to be afraid',
'Korku': 'fear',
'Koro': 'choir',
'Koruma': 'protection',
'Korumak / Saklamak': 'to preserve',
'Koyu / yoğun': 'thick',
'Koyulaşmak': 'to thicken',
'Koşmak (düzenli)': 'to go running',
'Kredi': 'loan',
'Kredi saydırma': 'credit transfer',
'Krema': 'cream',
'Kremalı baz': 'creamy base',
'Kritik gecikme': 'critical delay',
'Kriz': 'crisis',
'Kruton': 'croutons',
'Kuaför': 'hairdresser',
'Kulağına küpe etmek': 'to take note (learn a lesson)',
'Kullanım talimatı': 'instructions',
'Kulvar': 'lane',
'Kum havuzu': 'sandbox',
'Kum kabı': 'litter tray',
'Kumbara': 'piggy bank',
'Kural': 'rule',
'kural olarak / genellikle': 'as a rule',
'Kurallar': 'rules',
'Kurban Bayramı': 'Eid al-Adha',
'Kurdele': 'ribbon',
'Kurt': 'wolf',
'Kurtuluş': 'salvation',
'Kuru temizleme': 'dry cleaning',
'Kurutmak': 'to dry',
'Kurutmamak': 'not to over-dry',
'Kuruyemiş': 'nuts',
'Kurye': 'courier',
'Kurşun kalem': 'pencil',
'Kusurlu': 'defective',
'Kusurlu taraf': 'the party at fault',
'Kutlamak / Tebrik etmek': 'to congratulate',
'Kutlarım': 'congratulations',
'Kutsamak': 'to bless',
'Kutu / Koli': 'box',
'Kutu oyunu': 'board game',
'Kutular': 'boxes',
'Kutuları açmak': 'to unpack the boxes',
'Kuyruk / Sıra': 'queue',
'Kuş': 'bird',
'Kuşak': 'generation',
'kuşkusuz': 'undoubtedly',
'Kâkül': 'fringe',
'Kâr': 'profit',
'Kâr marjı': 'margin',
'Kârlılık': 'profitability',
'Köpek': 'dog',
'Köprü': 'bridge',
'Köpüğünü almak': 'to skim the foam',
'Kötü': 'bad',
'Köy': 'village',
'Köşe': 'corner',
'Küf': 'mould',
'Külah': 'cone',
'Küp doğramak': 'to dice',
'Küp küp': 'into cubes',
'Kütüphane': 'library',
'Küçük': 'small',
'Küçük porsiyon': 'small portion',
'Küçük trafik kazası': 'minor accident',
'Küçük çörek': 'bun',
'Kılçıklar': 'bones',
'Kılçıklı': 'bony',
'Kılıf': 'case',
'Kırgınlık': 'hurt feelings',
'Kırk': 'forty',
'Kırmızı': 'red',
'Kırılır eşya': 'fragile items',
'Kısaltmak': 'to shorten',
'Kısık ateşte pişirmek': 'to stew',
'Kıta': 'stanza',
'Kıtlık / Bulunmayan mal': 'shortage',
'Kıyafet': 'outfit',
'Kıyma': 'minced meat',
'Kız (evlat)': 'daughter',
'Kız kardeş': 'sister',
'Kızartmak': 'to fry',
'Kış': 'winter',
'Lahana turşusu': 'sauerkraut',
'Lahana çorbası': 'shchi (cabbage soup)',
'Lamba': 'lamp',
'Lapa': 'porridge',
'Lavabo': 'sink',
'Leke': 'stain',
'Lezzetli': 'tasty',
'Limit': 'limit',
'Limon dilimi': 'lemon slice',
'Limon suyu': 'lemon juice',
'Lor peyniri': 'cottage cheese',
'Lütfen (kibarca rica)': 'be so kind',
'Lütfen / Rica ederim': 'please',
'Maalesef': 'unfortunately',
'Maaş': 'salary',
'Maaş günü': 'payday',
'Mabet / Tapınak': 'temple',
'Madde': 'clause',
'Maden suyu': 'mineral water',
'Mahalle marketi': 'corner shop',
})
