D.update({
'Dana eti': 'beef',
'Dans etmek': 'to dance',
'Danışman': 'curator',
'Dar': 'tight',
'Dava / Talep': 'lawsuit',
'Davetiye': 'invitation',
'Davetiyeler': 'invitations',
'Davetliler': 'guests',
'de / da (aynı şekilde)': 'also',
'De / Da (olumlu)': 'too',
'Debriyaj': 'clutch',
'Dede': 'grandfather',
'Defne yaprağı': 'bay leaf',
'Defter': 'notebook',
'Deliller': 'evidence',
'demek istediğim': 'I meant to say',
'Demirbaş listesi': 'inventory list',
'Demlik ve çaydanlık': 'teapot',
'Denemek': 'to try on',
'Denetim': 'audit',
'Denetçi': 'inspector',
'Deney': 'experiment',
'Deneyim': 'experience',
'Dengeli': 'balanced',
'Depo': 'warehouse',
'Depozito': 'deposit',
'Derece': 'degree',
'Dereotu': 'dill',
'Derin hüzün / Sıla hasreti': 'deep longing',
'Derin yağda': 'deep fried',
'Derinlik': 'depth',
'Ders': 'lesson',
'Ders kitabı': 'textbook',
'Destek': 'support',
'Destek hattı': 'support line',
'Deterjan': 'detergent',
'Devasa': 'huge',
'Devir hızı': 'turnover rate',
'Devrik söz dizimi': 'inversion',
'Değer': 'value',
'Değerinde olmak': 'to be worth',
'Değerlendirme': 'assessment',
'Değil / -ma': 'not',
'Değişim': 'exchange',
'Değiştirmek': 'to replace',
'Dibi tutmak / Yanmak': 'to burn (stick to the pan)',
'Dijital nezaket': 'digital etiquette',
'Dikkat': 'attention',
'Dikkat çekmek/etmek': 'to draw attention',
'Dikkatli': 'careful',
'Dikmek (bitki)': 'to plant',
'Dikmek (yırtığı)': 'to sew up',
'Dil (organ) / Dil (lisan)': 'language',
'Dil sürçmesi': 'slip of the tongue',
'Dilekçe / Beyan': 'written request',
'Dilemek': 'to wish',
'Din': 'religion',
'Dinlemek': 'to listen',
'Dinlendirmek': 'to let rest',
'Dinlenme': 'rest',
'Dinlenmek': 'to rest',
'dinlenmek': 'to rest',
'Dinlenmek (biraz)': 'to have a rest',
'Dinleyici kitlesi': 'audience',
'Dinî hoşgörü': 'religious tolerance',
'Diploma': 'diploma',
'Diplomat': 'diplomat',
'Direksiyon': 'steering wheel',
'Diriliş': 'resurrection',
'Dizel': 'diesel',
'Diş': 'tooth',
'Diş fırçalamak': 'to brush teeth',
'Diş fırçası': 'toothbrush',
'Diş çekmek': 'to pull a tooth',
'Dişçi': 'dentist',
'Dogma / İnanç esası': 'dogma',
'Doksan': 'ninety',
'Doktor': 'doctor',
'Doktor randevusu': 'doctor appointment',
'Doku': 'texture',
'Dolap': 'wardrobe',
'Dolayısıyla': 'therefore',
'Dolgu': 'filling',
'Dolu / Meşgul': 'busy',
'Dondurma': 'ice cream',
'Dondurmak': 'to freeze',
'Dondurucu': 'freezer',
'Dosya / dava': 'case file',
'Doyurucu': 'filling (food)',
'Doğa': 'nature',
'Doğa koruma alanı': 'nature reserve',
'Doğramak': 'to chop',
'Doğru / Gerçek': 'truth',
'doğru anladıysam': 'if I understood correctly',
'Doğru çözündürmek': 'to defrost properly',
'Doğrulamak': 'to confirm',
'Doğum günü': 'birthday',
'Dua': 'prayer',
'Dudaklar / Ağız (şiirsel)': 'lips',
'Durak': 'bus stop',
'Durumu incelemek': 'to look into the situation',
'Duruşma': 'court hearing',
'Duvar': 'wall',
'Duvar kâğıdı': 'wallpaper',
'Duymak': 'to hear',
'Duyuyor musun': 'can you hear',
'Duş': 'shower',
'Dökmemek': 'not to spill',
'Dönmek': 'to come back',
'Döviz / Para birimi': 'currency',
'Dübel': 'wall plug',
'Dün': 'yesterday',
'Dünya görüşü': 'worldview',
'Dürbün': 'binoculars',
'Düz': 'straight',
'Düğme': 'button',
'Düğün': 'wedding',
'Düğün sunucusu': 'wedding host',
'Düşünmek': 'to think',
'Düşünsene': 'imagine',
'dışarı çıkmak': 'to go outside',
'Dışarıda / Sokakta': 'outside',
'Eczacı': 'pharmacist',
'Eczane': 'pharmacy',
'Edinmek / Satın almak': 'to acquire',
'Ehliyet': 'driving licence',
'Ekip / Takım': 'team',
'Ekipman listesi': 'equipment list',
'Ekipmanı kapatmak': 'to turn off the equipment',
'Ekmek': 'bread',
'Ekmek-tuz': 'bread and salt',
'Ekran': 'screen',
'Ekran değişimi': 'screen replacement',
'Ekran paylaşımı': 'screen sharing',
'Eksper': 'assessor',
'Ekşi krema': 'sour cream',
'Ekşi maya': 'sourdough starter',
'El / Kol': 'hand',
'El bagajı': 'hand luggage',
'El freni': 'handbrake',
'Elbise': 'dress',
'Eldiven': 'gloves',
'Elektrik faturası': 'electricity bill',
'Elektrik kesintisi': 'power cut',
'Elektrik süpürgesi': 'vacuum cleaner',
'Elektrikçi': 'electrician',
'Elemek': 'to sift',
'Eleştirel not': 'critical remark',
'Eleştiri yazısı': 'review',
'Ellerini yıkamak': 'to wash hands',
'Elli': 'fifty',
'Elma': 'apple',
'Emekli aylığı': 'pension',
'eminim ki': 'I am sure that',
'Emlak ofisi': 'real estate agency',
'En (üstünlük)': 'the most',
'En yüksek not': 'top grade',
'Enflasyon': 'inflation',
'Enflasyon artışı': 'indexation',
'Engel olmak / Rahatsız etmek': 'to disturb',
'Erkek kardeş': 'brother',
'Erken': 'early',
'Erken ödeme': 'early payment',
'Ertelemek': 'to postpone',
'Eser': 'work of art',
'Eski / Yaşlı': 'old',
'Eskiden / Daha önce': 'before',
'Esnek çalışma': 'flexible schedule',
'Espresso': 'espresso',
'Et suyu': 'broth',
'Etek': 'skirt',
'Eti kurulamak': 'to pat the meat dry',
'Etik': 'ethics',
'Etiketleme': 'labelling',
'Etkinlik adresi': 'venue address',
'Etsiz': 'without meat',
'Ev bitkisi': 'houseplant',
'Ev partisi': 'house party',
'Ev sahibi': 'landlord',
'Ev yapımı peynir': 'homemade cheese',
'Ev yapımı sos': 'homemade sauce',
'Ev ödevi': 'homework',
'Evcil hayvan': 'pet',
'Evden çıkmak': 'to leave home',
'Evet': 'yes',
'Evrak dosyası': 'paperwork',
'Eylül': 'September',
'Ezbere': 'by heart',
'Ezgi': 'melody',
'Eğer': 'if',
'Eğer …-saydı': 'if only (had)',
'Eğilim': 'tendency',
'Eğitim / Öğrenme': 'training',
'Eğitmen': 'instructor',
'Eğlenceli / Neşeli': 'fun',
'Eş anlamlı': 'synonym',
'Eşdeğer': 'equivalent',
'Eşit / Düzgün': 'even',
'Eşit boyut': 'equal size',
'Eşit paylar': 'equal parts',
'Eşleşme': 'match',
'Eşya listesi': 'list of things',
'Eşya toplama': 'packing',
'Eşyaları yerleştirmek': 'to unpack',
'Faiz oranı': 'interest rate',
'Fakülte': 'faculty',
'Farkındalık': 'mindfulness',
'Farlar': 'headlights',
'Fatura / Hesap': 'bill',
'Faturalar / aidat giderleri': 'utilities',
'Favori masa': 'favourite table',
'Fayans / Karo': 'tiles',
'Fazla bagaj': 'excess luggage',
'Fazla doldurmak': 'to overload',
'Fazla yağ': 'excess fat',
'Fazla yüklü': 'overloaded',
'Fener': 'flashlight',
'Fermantasyon': 'fermentation',
'Fermuar': 'zip',
'Feshetmek': 'to terminate',
'Fide': 'seedling',
'Fileto': 'fillet',
'Film': 'film',
'Final tatlısı': 'final dessert',
'Finansal alışkanlık': 'financial habit',
'Fincan': 'cup',
'Fire raporu': 'waste report',
'Fiyat': 'price',
'Fiyat bindirimi': 'markup',
'Fiyatlar': 'prices',
'Fiş': 'receipt',
'Fişe imza': 'signature on the receipt',
'Food cost': 'food cost',
'Form': 'form',
'Fotoğraf albümü': 'photo album',
'Fotoğraf ebadı': 'photo size',
'Fotoğrafçı': 'photographer',
'Fren': 'brake',
'Frenler': 'brakes',
'Fön / şekillendirme': 'hair styling',
'Füzyon': 'fusion',
'Fıkra': 'joke (anecdote)',
'Fırtına / Gök gürültülü sağanak': 'thunderstorm',
'Fırın': 'oven',
'Fırın havuç': 'roasted carrots',
'Fırın sebzeler': 'roasted vegetables',
'Fırın tepsisi': 'baking tray',
'Fırınlamak': 'to bake',
'Gaf / Isıraksama': 'blunder',
'Ganaj': 'ganache',
'Gar': 'railway station',
'Garanti': 'warranty',
'Garanti kapsamı': 'warranty case',
'Garanti süresi': 'warranty period',
'Garip / Tuhaf': 'strange',
'Garnitür eklemek': 'to add a side dish',
'Garnitürler': 'side dishes',
'Garson': 'waiter',
'Gastronomik vurgu': 'gastronomic accent',
'Gaz': 'gas',
'Gazlı içecek': 'fizzy drink',
'Gazsız': 'still (no bubbles)',
'GB internet': 'gigabytes',
'Gece': 'night',
'Gece çalışma düzeni': 'night mode',
'Gecenin ritmi': 'rhythm of the evening',
'Geciktirmemek': 'not to delay',
'Gelecek ay': 'next month',
'Gelemeyeceğim': 'I cannot come',
'Gelenek': 'tradition',
'Gelir': 'income',
'Gelişme / Gelişim': 'development',
'Genelleme': 'generalisation',
'Genellikle': 'usually',
'Genç adam': 'young man',
'Genç kadın / Kız': 'girl',
'Gereken / Usulüne uygun': 'proper',
'Gerekçe': 'reason (formal)',
'Gerekçelendirme': 'justification',
'Geri bildirim': 'feedback',
'Geri bildirim için teşekkür ederiz': 'thank you for the feedback',
'geri dönmek': 'to return',
'Geri dönüşüm': 'recycling',
'Gerilimi düşürme': 'de-escalation',
'Gerilmek': 'to get nervous',
'Gerçekleştirmek': 'to carry out',
'Gerçekten': 'really',
'Getiri': 'return (profit)',
'Getirmek': 'to bring',
'Gezilecek yer': 'sight',
'Gezmek / Yürümek': 'to go for a walk',
'Geç': 'late',
'Geç kalmak': 'to be late',
'Geç çıkış': 'late check out',
'Geçerli olmak': 'to be valid',
'Geçici belge': 'temporary certificate',
'Geçiş / Aktarma': 'crossing',
'Geçiş hakkı': 'access pass',
'Geçiş üstünlüğü': 'right of way',
'Geçmiş olsun': 'get well soon',
'Gibi / Nasıl': 'like',
'Gider': 'expense',
'Giderken': 'on the way out',
'Giderler': 'expenses',
'Gidip gelmek (yaya)': 'to go on foot (regularly)',
'Girin': 'come in',
'Giriş': 'entrance',
'Giriş anahtarı': 'entrance key',
'Giriş kartı': 'pass card',
'Gitar': 'guitar',
'Gitmek (araçla)': 'to go by transport',
'Gitmek (yaya, şimdi)': 'to go (on foot, now)',
'Gitmem lazım': 'I have to go',
'Gitti': 'he left',
'Giymek': 'to put on',
'Glazür / Sır': 'glaze',
'Gluten': 'gluten',
'Grafik / Çizelge': 'schedule',
'Grup': 'group',
'Gurur duymak': 'to be proud',
'Gökyüzü': 'sky',
'Gölge vardiya': 'shadow shift',
'Gömlek': 'shirt',
'Gönderi': 'postal item',
'Göndermek': 'to send',
'Gönüllülük': 'volunteering',
'Gördü': 'he saw',
'Görev / İş': 'task',
'Görmek güzel': 'good to see',
'görünüşe göre': 'apparently',
'Görüş': 'eyesight',
'Görüşme': 'meeting',
'Görüşmek üzere': 'see you soon',
'Görüşürüz / Hoşça kal': 'bye',
'Gösterin': 'show me',
'Göstermek / övünmek': 'to show off',
'Göz': 'eye',
'Göz muayenesi': 'eye exam',
'Gözlem': 'observation',
'Gözler (şiirsel)': 'eyes (poetic)',
'Gözlük': 'glasses',
'Göçmen kaydı': 'migration registration',
'Gülmek': 'to laugh',
'Gülümseme': 'smile',
'Gümrük': 'customs',
'Gümrük işlemleri': 'customs clearance',
'Gümrük vergisi': 'customs duty',
'Gün / Gündüz': 'day',
'Gün sonu raporu': 'end of day report',
'Günah': 'sin',
'Günaydın': 'good morning',
'Güncellik': 'relevance',
'Gündem': 'agenda',
'Güneş': 'sun',
'Güneş gözlüğü': 'sunglasses',
'Güneş kremi': 'sunscreen',
'Güneşli yer': 'sunny spot',
'Günlük düzen': 'daily routine',
'Günlük kalanlar': 'daily leftovers',
'Günün yemeği': 'dish of the day',
'Günün çorbası': 'soup of the day',
'Gürültü': 'noise',
'Güveni korumak': 'to keep trust',
'Güvenilir': 'reliable',
'Güvenilirlik': 'credibility',
'Güvenli buluşma': 'safe meeting',
'Güvenli tutuş': 'safe grip',
'Güvenli şekilde yeniden kullanmak': 'to reuse safely',
'Güzel (şekilde)': 'beautifully',
'Güzergâh': 'route',
'Güçlü': 'strong',
'Gıda / Erzak': 'groceries',
'Gıda atığı': 'food waste',
})
