# -*- coding: utf-8 -*-
# tr -> en sözlük PARÇA 7 (ekler/fixes)
D.update({
'araçla gidip gelmek': 'to travel back and forth',
'Haber': 'news',
'Haberini yapmak': 'to cover (the news)',
'Hac / Ziyaret': 'pilgrimage',
'Hacı / Ziyaretçi': 'pilgrim',
'Hadi': 'come on',
'Hadi canım / Tabii ki': 'of course',
'Hafif ekşilik': 'slight tang',
'Hafta': 'week',
'Hafta sonu': 'weekend',
'Hafıza': 'memory',
'Hakikat': 'truth',
'Hakkında': 'about',
'hakkında (edat hâli)': 'about (prepositional case)',
'hakkında hâli sorusu': 'about whom? about what?',
'Hakkında konuşmak': 'to talk about',
'Hala / Teyze': 'aunt',
'Halk': 'the people',
'Halk ağzı / Kaba dil': 'colloquial speech',
'Halka ait': 'folk',
'Halka dansı': 'circle dance',
'Halı': 'carpet',
'Hamle / sıra': 'move (in a game)',
'Hamur': 'dough',
'Hamur yoğurmak': 'to knead dough',
'Hangi / Nasıl?': 'which?',
'Harcamaları planlamak': 'to plan expenses',
'Harika / Nefis': 'wonderful',
'Harita': 'map',
'Haritadaki kurye': 'courier on the map',
'Hasar': 'damage',
'Hasar fotoğrafı': 'photos of the damage',
'Hasat': 'harvest',
'Hasta': 'sick',
'Hasta odası': 'hospital ward',
'Hasta olmak / Ağrımak': 'to be ill / to hurt',
'Hastalık (tıbbi)': 'disease',
'Hastalık raporu': 'sick leave note',
'Hastane': 'hospital',
'Hastaneye yatış': 'hospitalisation',
'Hata': 'mistake',
'Hatırlamak': 'to remember',
'Hava': 'air',
'Hava durumu': 'weather',
'Hava kararmadan dönmek': 'to get back before dark',
'Havlu': 'towel',
'Havuz': 'swimming pool',
'Hayal kurmak': 'to daydream',
})
