D.update({
'Aidat': 'maintenance fee',
'Aidat ve altyapı giderleri': 'utilities',
'Almak (teslim)': 'to receive',
'Alışveriş arabası': 'shopping trolley',
'Anahtar': 'key',
'Anaokulu': 'kindergarten',
'Anaokulu öğretmeni': 'kindergarten teacher',
'Anlam / Mana': 'meaning',
'Anlaşmak': 'to agree',
'Anlaşmazlık': 'conflict',
'Aramak (telefonla)': 'to phone',
'Arka fon': 'background',
'Arz / Teklif / Cümle': 'sentence',
'Asitlik (pH)': 'acidity (pH)',
'Asla': 'never',
'Ateş / Sıcaklık': 'temperature',
'Ayakkabı (genel)': 'shoes',
'Ayaz / Dondurucu soğuk': 'frost',
'Ağır ateşte pişirmek': 'to simmer',
'Bank': 'bench',
'Baskı': 'print',
'Battaniye': 'blanket',
'Bay bay / Görüşürüz': 'bye bye',
'Bayram': 'holiday',
'Baş aşçı / şef': 'head chef',
'Başlangıçlar': 'starters',
'Başvuru dilekçesi': 'application',
'Beden': 'size',
'Benzinlik': 'petrol station',
'Beyanname': 'customs declaration',
'Bildiri / Açıklama': 'statement',
'Bitiş tadı': 'aftertaste',
'Borç / Gecikme': 'arrears',
'Boş / Serbest': 'free (vacant)',
'Buluşma': 'date (meeting)',
'Buluşma / Karşılaşma': 'meeting',
'Bölüm': 'chapter',
'Cevaplamak': 'to answer',
'Ceza / Para cezası': 'fine',
'CV': 'CV',
'Dava': 'lawsuit',
'Davet': 'invitation',
'Davet yemeği': 'banquet',
'Dayanak / Gerekçe': 'grounds',
'Denemek (giysi)': 'to try on',
'Dilekçe': 'application form',
'Dilimlemek': 'to slice',
'Diploma / Bitirme tezi': 'degree thesis',
'Diş hekimi': 'dentist',
'Dolaşmak / Gezinmek': 'to stroll',
'Doğa yürüyüşü / Kamp gezisi': 'hiking trip',
'Döviz': 'foreign currency',
'Düz / Dosdoğru': 'straight ahead',
'Elbette': 'of course',
'Eldivenler': 'gloves',
'Elektrikli süpürge': 'vacuum cleaner',
'Endeksleme': 'indexation',
'Envanter sayımı': 'stocktaking',
'Evi görme': 'flat viewing',
'Evraklar': 'documents',
'Faiz / Yüzde': 'interest',
'Gelişim': 'development',
'Geçme notu / Kredi sınavı': 'credit test',
'Gişe': 'service window',
'Göz kontrolü': 'eye check',
'Hamallar': 'porters',
'Hap': 'pill',
'Hasat / Ürün': 'harvest',
'Havale': 'bank transfer',
'Hayır / Yok': 'no',
'Hesap': 'the bill',
'Hesaptan çekim': 'direct debit',
'Işkence / Un': 'flour',
'İfade / başvuru': 'application',
'İmge / Karakter portresi': 'image',
'İnmek / çıkmak': 'to get off',
'İş arkadaşı': 'colleague',
'İş görüşmesi': 'job interview',
'İşlem ücreti': 'transaction fee',
'Kadeh konuşması': 'toast',
'Karar': 'decision',
'Kargo paketi': 'parcel',
'Kart': 'card',
'Karttan çekim': 'card charge',
'Kaynatmak / Haşlamak': 'to boil',
'Kayıt': 'registration',
'Kenara koymak': 'to set aside',
'Kitle / İzleyici': 'audience',
'Konteyner': 'container',
'Konu / Olay örgüsü': 'plot',
'Koşmak': 'to run',
'Kuaför salonu': 'hair salon',
'Kutu': 'box',
'Kutu / koli': 'box',
'Kâr marjı / Fiyat farkı': 'markup',
'Kâğıt': 'paper',
'Kırılacak eşya': 'breakables',
'Kızak tepesi': 'sled hill',
'Kışlık hazırlıklar': 'winter preserves',
'Lapa / Kaşa': 'porridge',
'Lensler': 'lenses',
'Makbuz': 'receipt',
'Makbuz / Ödeme belgesi': 'payment receipt',
'Marinat / Terbiye': 'marinade',
'Masa (kafede)': 'table (at a cafe)',
'Melodi': 'melody',
'Menü': 'menu',
'Metafor / Eğretileme': 'metaphor',
'Meydan': 'square',
'Misafirler': 'guests',
'Modem / router': 'router',
'Mont / Ceket': 'jacket',
'Muayene / Kontrol': 'examination',
'Mülk sahibi': 'property owner',
'Nakil': 'transfer',
'Nakit olarak': 'in cash',
'Nakliyeciler': 'porters',
'Not': 'grade',
'Numara': 'size',
'Oda / muayene odası': 'doctor\'s office',
'Olabilir / ...bilir miyim?': 'may I?',
'Onay': 'confirmation',
'Onay almak': 'to get approval',
'Onur / Meziyet': 'dignity',
'Oran': 'rate',
'Oruç / Perhiz': 'fasting',
'Paket kabı': 'takeaway container',
'Pazar / Çarşı': 'market',
'Pencere': 'window',
'Postane / Posta': 'post office',
'Rahatsız etmek': 'to disturb',
'Resmî itiraz/ihtar': 'formal complaint',
'Resmî yazı': 'official certificate',
'Resmî yazı/belge': 'official certificate',
'Rezerve etmek': 'to book',
'Rota / Güzergâh': 'route',
'Saat (süre)': 'hour',
'Sabah sporu': 'morning exercise',
'Sahne alma / Performans': 'performance',
'Salon / Spor salonu': 'gym',
'Sinema (bina)': 'cinema',
'Siz': 'you (formal)',
'Sohbet / Konuşma': 'talk',
'Sokak / Cadde': 'street',
'Son fermantasyon': 'final proofing',
'Sonunda': 'finally',
'Soğuk (hava)': 'cold (weather)',
'Süpürge': 'broom',
'Süre / Vade / Deadline': 'deadline',
'Sıra': 'queue',
'Sıra / Kuyruk': 'queue',
'Sıra fişi': 'queue ticket',
'Sıvı yağ': 'vegetable oil',
'Tablo': 'painting',
'Tadilat': 'renovation',
'Tadilat / Bakım durumu': 'renovation',
'Tahlil': 'lab test',
'Talep kaydı': 'request ticket',
'Tamir': 'repair',
'Tansiyon': 'blood pressure',
'Tarif / açıklama': 'description',
'Tarife': 'tariff',
'Tarife / Sefer saatleri': 'timetable',
'Tatlı (şekerli)': 'sweet',
'Taviz': 'concession',
'Telafi': 'compensation',
'Teşekkürler': 'thank you',
'Trafik cezası': 'traffic fine',
'Trafik ışığı': 'traffic light',
'Usta': 'craftsman',
'Uygulama': 'app',
'Veri': 'data',
'Yakında / Yanında': 'nearby',
'Yalnız / Bir': 'one',
'Yanında': 'next to',
'Yazlık / Daça': 'dacha',
'Yeni Yıl': 'New Year',
'Yer / Koltuk': 'seat',
'Yorgunum (erkek)': 'I am tired (m)',
'Yoruldum (erkek)': 'I got tired (m)',
'Yüklemek': 'to top up',
'Yılbaşı ağacı': 'New Year tree',
'Zil': 'bell (ring)',
'Zil / Arama': 'phone call',
'Çalar saat': 'alarm clock',
'Çamaşır yıkamak': 'to do the laundry',
'Çaydanlık / Su ısıtıcısı': 'kettle',
'Çağrı hattı': 'hotline',
'Çok sıcak': 'very hot',
'Ön ödeme': 'prepayment',
'Önemli değil / Bir şey değil': 'it is nothing',
'Önermek / Tavsiye etmek': 'to recommend',
'Özel gün': 'special day',
'Öğrenci karnesi/ajandası': 'school diary',
'Üyelik / Abonelik': 'membership',
'Üyelik kartı': 'membership card',
'Şaheser': 'masterpiece',
'Şarj': 'charging',
'Şarj aleti': 'charger',
'Şato / Kilit': 'castle',
'Şifre': 'password',
'Şoför': 'driver',
})
