# -*- coding: utf-8 -*-
# tr -> en sözlük PARÇA 6 (Y...Z, Ç, Ö, Ş, Ü, özel)
D.update({
'Yapraklar': 'leaves',
'Yaptı (tamamlanmış)': 'he did',
'Yapılmış': 'done',
'yapıp bitirmek': 'to complete',
'Yapıştırıcı': 'glue',
'Yara bandı': 'plaster',
'Yardım': 'help',
'Yardım edin': 'help me',
'Yardım etmek': 'to help',
'Yardım sağlamak': 'to provide help',
'Yarı tatlı': 'semi sweet (wine)',
'Yarım saat': 'half an hour',
'Yarın': 'tomorrow',
'Yarın görüşürüz': 'see you tomorrow',
'Yarışma / Müsabaka': 'competition',
'Yasak / Olmaz': 'not allowed',
'Yastık': 'pillow',
'Yatak': 'bed',
'Yatmak': 'to go to bed',
'yatmak': 'to go to bed',
'Yatırım': 'investment',
'Yatırımcı': 'investor',
'Yavaş yavaş': 'little by little',
'Yaz': 'summer',
'Yazar': 'author',
'Yazlık / Bağ evi': 'dacha',
'Yazmak': 'to write',
'yazmak (süreç)': 'to write (process)',
'Yazmak / Yazıp bitirmek': 'to write / to finish writing',
'Yazık': 'what a pity',
'Yazılmış': 'written',
'Yazılı': 'in writing',
'Yazılı cevap': 'written reply',
'yazıp bitirmek': 'to finish writing',
'Yağ oranı': 'fat content',
'Yağlamak / Sürmek': 'to grease',
'Yağmur': 'rain',
'Yağmur yağıyor': 'it is raining',
'Yağsız / Yağsız perhize uygun': 'lean (fasting friendly)',
'Yaş (5+ için)': 'years old',
'Yaşam düzeni': 'way of life',
'Yaşamak': 'to live',
'Yaşlı kişi': 'elderly person',
'Yedek kıyafet': 'change of clothes',
'Yedek parça': 'spare part',
'Yedek takımlar': 'spare cutlery sets',
'Yedi kez ölç': 'measure seven times',
'Yemek / Tabak': 'dish',
'Yemek k. / Çay k.': 'tbsp / tsp',
'Yemek listesi': 'menu',
'Yemek planı': 'meal plan',
'Yemek soğudu': 'the dish got cold',
'Yemek teslimatı': 'food delivery',
'Yemekhane': 'canteen',
'Yemeğin maliyeti': 'cost of the dish',
'Yemeğin temposu': 'pace of the dinner',
'Yeni': 'new',
'Yeni başlayan hataları': "beginner's mistakes",
'Yeniden başlatmak': 'to restart',
'Yeniden doğuş': 'rebirth',
'Yeniden hesaplama': 'recalculation',
'Yeniden paylaşım': 'repost',
'Yeniden yapılandırma': 'restructuring',
'Yeniden yorumlama': 'reinterpretation',
'Yer': 'place',
'Yer fıstığı izi': 'traces of peanuts',
'Yerel ürünler': 'local produce',
'Yerinde / Uygun': 'appropriate',
'Yerindelik': 'appropriateness',
'Yerine bakacak kişi': 'stand in',
'Yetişmek': 'to be on time',
'Yetkili servis': 'service centre',
'Yetmek': 'to be enough',
'Yeşil': 'green',
'Yeşil çay': 'green tea',
'Yeşillik serpmek': 'to sprinkle with herbs',
'Yine bekleriz': 'come again',
'Yine de': 'nevertheless',
'Yirmi': 'twenty',
'Yitirmek': 'to lose',
'Yiğit': 'brave',
'Yok / Hayır': 'no',
'Yoksa / Sahi mi': 'really?',
'Yolculuk / Gezi': 'trip',
'Yorgan': 'blanket',
'Yoruldum': 'I am tired',
'Yorulmak': 'to get tired',
'Yorum': 'interpretation',
'Yoğun (tat)': 'rich (taste)',
'Yoğun kıvam': 'thick consistency',
'Yoğurmak': 'to knead',
'Yukarı': 'upstairs',
'Yumurta': 'egg',
'Yumurtalar': 'eggs',
'Yumuşak iç doku': 'soft crumb',
'Yumuşatmak': 'to soften',
'Yönetici': 'boss (chef)',
'Yönetmen': 'director',
'Yükümlülük': 'obligation',
'yürüyerek ayrılmak': 'to leave (on foot)',
'yürüyerek gelmek': 'to come (on foot)',
'yürüyerek gidip gelmek': 'to go back and forth',
'yürüyerek gitmek (şimdi/tek yön)': 'to be on one\'s way',
'Yürüyüş': 'walk',
'Yürüyüş / doğa gezisi': 'hike',
'Yüz': 'one hundred',
'Yüzde': 'percent',
'Yüzey dezenfeksiyonu': 'surface disinfection',
'Yüzmek': 'to swim',
'Yüzük': 'ring',
'Yüzünü yıkamak': 'to wash one\'s face',
'Yıkamak': 'to wash (clothes)',
'Yıkamak (durulamak)': 'to rinse',
'yıkanmak': 'to wash oneself',
'Yıkım': 'demolition',
'Yıl': 'year',
'Yılbaşı': 'New Year',
'Yılbaşı ağacı / Ladin': 'New Year tree',
'Yıllık izin': 'annual leave',
'Zafer / Galibiyet': 'victory',
'Zam': 'increase (pay)',
'Zaman': 'time',
'Zamanında almak': 'to pick up on time',
'Zar': 'dice',
'Zarar görmek / Yaralanmak': 'to be injured',
'Zarf': 'envelope',
'Zarif kapanış': 'elegant ending',
'Zarif sunum': 'refined plating',
'Zayi kaydı': 'write off',
'Zeki kişi': 'bright mind',
'Zemin / Döşeme': 'floor',
'Zerdeçal': 'turmeric',
'Zeytinyağı': 'olive oil',
'Zincir': 'chain',
'Zinciri bozmamak': 'not to break the chain',
'Ziyaret hediyesi': 'hostess gift',
'Ziyaretiniz için teşekkürler': 'thank you for your visit',
'Zor': 'difficult',
'Zor kişilik': 'difficult personality',
'Zorunlu trafik sigortası': 'compulsory car insurance',
'Zulüm / Baskı': 'persecution',
'Çabalamak': 'to try hard',
'Çadır': 'tent',
'Çalkalamak': 'to rinse out',
'Çalma listesi': 'playlist',
'Çalmaya başladı': 'it started ringing',
'Çalındı': 'it was stolen',
'Çalışan': 'working person',
'Çalışma alanı': 'workstation',
'Çalışma istasyonu': 'work station',
'Çalışmak': 'to work',
'çalışmak': 'to work',
'Çalışmıyor': 'it does not work',
'Çamaşır makinesi': 'washing machine',
'Çan': 'bell',
'Çanta': 'bag',
'Çarparak kapatmak': 'to slam',
'Çarşamba': 'Wednesday',
'Çatal': 'fork',
'Çatal-bıçak takımı': 'cutlery set',
'Çatlak': 'crack',
'Çatışma': 'conflict',
'Çay': 'tea',
'Çay demlemek': 'to brew tea',
'Çağ / Dönem': 'era',
'Çekim': 'filming',
'Çekirdekler / tohumlar': 'sunflower seeds',
'Çekiç': 'hammer',
'Çelişki': 'contradiction',
'Çerçeve': 'frame',
'Çeviri': 'translation',
'Çevre': 'environment',
'Çevreci mutfak': 'eco friendly kitchen',
'Çikolata': 'chocolate',
'Çikolata sosu': 'chocolate sauce',
'Çilecilik': 'asceticism',
'Çilek': 'strawberry',
'Çilingir / Tesisatçı usta': 'plumber locksmith',
'Çizik': 'scratch',
'Çizmeler': 'boots',
'Çiçek': 'flower',
'Çiğ tavuk': 'raw chicken',
'Çocuk': 'child',
'Çocuk kaşığı': 'children\'s spoon',
'Çocuk menüsü': 'children\'s menu',
'Çocuk parkı': 'playground',
'Çocuklar': 'children',
'Çocuklu misafirler': 'guests with children',
'Çocuğu izlemek': 'to watch the child',
'Çok': 'very',
'Çok şükür': 'thank God',
'Çokuluslu': 'multinational',
'Çorap': 'socks',
'Çorba': 'soup',
'Çorbalar': 'soups',
'Çöp': 'rubbish',
'Çöpe atmamak': 'not to throw away',
'Çözmek': 'to solve',
'Çözüm süreci': 'settlement',
'Çözümleme': 'analysis',
'Çünkü': 'because',
'çünkü': 'because',
'Çürük': 'tooth decay',
'Çıkarsızlık': 'selflessness',
'Çıkmak': 'to go out',
'Çıkış': 'exit',
'Çırpmak': 'to whip',
'Çıtır deri': 'crispy skin',
'Çıtır doku': 'crispy texture',
'Çıtır kabuk': 'crispy crust',
'Ödeme': 'payment',
'Ödeme fişi': 'receipt',
'Ödemek': 'to pay',
'Ödemeler dengesi': 'settlements',
'Ödev / Borç': 'debt',
'Ödünç almak': 'to borrow',
'Ödünçleme': 'borrowing',
'Öksürük': 'cough',
'Ölçü': 'measure',
'Ölçü bardağı': 'measuring cup',
'Ölçülü biçimde': 'with restraint',
'Ön hazırlık (mise en place)': 'mise en place',
'Ön hazırlıklar': 'preparations',
'Ön maya / Poolish': 'poolish',
'Ön sipariş': 'pre order',
'Önceden haber vermek': 'to warn in advance',
'Öncelikli sipariş': 'priority order',
'Önem taşımak': 'to matter',
'Önemli değil': 'it is nothing',
'Önlemler': 'measures',
'Örf / Âdet': 'custom',
'Örgü / Tırpan / Kumsal dili': 'braid',
'Örneklem': 'sample',
'örneğin': 'for example',
'Örtü': 'blanket',
'öte yandan': 'on the other hand',
'Övgü': 'praise',
'Övmek': 'to praise',
'Öykü / Hikâye': 'short story',
'Öykünme çeviri': 'calque',
'Özel': 'special',
'Özel istek': 'special request',
'Özel mesaj': 'direct message',
'Özel not': 'special note',
'Özgeçmiş / CV': 'CV',
'Özgünlük / Kendine özgülük': 'originality',
'Özgürlük': 'freedom',
'Özgüven / Emin olma': 'confidence',
'Özlemek': 'to miss',
'Özür dilemek': 'to apologise',
'Özür dilerim': 'I am sorry',
'Öğle molası': 'lunch break',
'Öğle yemeği': 'lunch',
'öğle yemeği yemek': 'to have lunch',
'Öğrenci (okul)': 'pupil',
'Öğrenci dosyası': 'student file',
'öğrenip ezberlemek': 'to learn by heart',
'Öğrenmek / Ezberlemek': 'to learn',
'öğrenmek / çalışmak': 'to learn',
'Öğretmen': 'teacher',
'Öğretmen / bakıcı': 'kindergarten teacher',
'Ücret': 'fee',
'Ücret tarifesi': 'tariff',
'Ücretli': 'for a fee',
'Ücretsiz': 'free of charge',
'Ücretsiz yardım etmek': 'to help for free',
'Ülke': 'country',
'Ümmet': 'ummah',
'Üniversite': 'university',
'Üniversite öğrencisi': 'student',
'Ünlü / Bilinen': 'famous',
'Üretici pazarı': 'farmers market',
'Ürün bitti': 'the product is out of stock',
'Ürün komşuluğu': 'product placement rules',
'Ürün teslimatı': 'produce delivery',
'Ürünü fire yazmak': 'to write off a product',
'Üslup': 'tone',
'Üslup / Stil': 'style',
'Üstelik': 'moreover',
'Üstünde / -de': 'on',
'Ütülemek': 'to iron',
'Üyelik': 'membership',
'Üzerinde (havada)': 'above',
'Üzgün': 'sad',
'Üzgün (hissetmek)': 'to feel sad',
'Üzgünüz': 'we are sorry',
'Şaheser / Başyapıt': 'masterpiece',
'Şampiyona': 'championship',
'Şampuan': 'shampoo',
'Şarabın gövdesi': 'body of the wine',
'Şarj / Şarj aleti': 'charger',
'Şarj cihazları': 'chargers',
'Şarkı': 'song',
'Şart / Koşul': 'condition',
'Şartlar': 'terms',
'Şaşlık / Mangal eti': 'shashlik',
'Şef': 'head chef',
'Şefe sormak': 'to ask the chef',
'Şefe özel yemek': 'chef\'s signature dish',
'Şefkat': 'compassion',
'Şeften ikram': 'compliment from the chef',
'Şehir': 'city',
'Şehir (şiirsel)': 'city (poetic)',
'Şeker': 'sugar',
'Şekerlik': 'sugar bowl',
'Şemsiye': 'umbrella',
'Şeriat': 'sharia',
'Şerit metre': 'tape measure',
'Şifre / Parola': 'password',
'Şiir': 'poem',
'Şiir (sanatı)': 'poetry',
'Şikâyet': 'complaint',
'Şikâyet defteri': 'complaints book',
'Şimdi': 'now',
'şimdi': 'now',
'Şimdi (kitabî)': 'nowadays',
'Şok soğutucu': 'blast chiller',
'şunu düşünüyorum ki': 'I think that',
'Şurup': 'syrup',
'Şüphe': 'doubt',
'Şüpheli': 'suspicious',
'şüphesiz': 'without a doubt',
'… hakkında düşünmek': 'to think about',
'…-den dolayı': 'due to',
'…-den sorumlu olmak': 'to be responsible for',
'…-den vazgeçmek': 'to give up',
'…-e ayrılmış': 'is dedicated to',
'…-e başvurmak': 'to resort to',
'…-e dayanarak': 'on the basis of',
'…-ebilir miyim': 'may I',
'…-iken / yanında': 'while',
'…-in sözlerine göre': 'according to the words of',
'…-sın diye': 'so that',
'…-sın diye (arkaik)': 'so that (archaic)',
'…-ıp -madığı': 'whether',
})
