# -*- coding: utf-8 -*-
# tr -> en sözlük PARÇA 1 (A-D başlangıcı)
D = {
'"Acı!" (düğün nidası)': 'Bitter! (wedding chant)',
'(ben) olacağım': 'I will be',
'-e doğru (datif)': 'towards (dative)',
'-e hâli sorusu': 'to whom? (dative question)',
'-e rağmen': 'in spite of',
'-e rağmen / gerçi': 'although',
'-i hâli sorusu': 'whom? what? (accusative question)',
'-in hâli sorusu': 'whose? (genitive question)',
'-sa / -ardı parçacığı': 'would particle',
'-siz (genitif)': 'without (genitive)',
'... için kullanılır': 'is used for',
'... mı demek istiyorsunuz?': 'do you mean...?',
'... nasıl söylenir?': 'how do you say...?',
'...-den farklı olarak': 'unlike',
'...-e benziyor': 'it looks like',
'24 saat / Gün': '24 hours / a day',
'Abone / Takipçi': 'subscriber',
'Abonelik': 'subscription',
'Abonman kart': 'season ticket',
'Acele işe şeytan karışır': 'haste makes waste',
'Acil': 'emergency',
'Acil hat': 'hotline',
'Acil ilaç': 'urgent medication',
'Acil üçüncü masaya': 'urgent, table three',
'Acilen': 'urgently',
'Acı çorba': 'spicy soup',
'Acısız': 'not spicy',
'Adalet': 'justice',
'Adisyonu kapatmak': 'to close the bill',
'Adisyonu kontrol etmek': 'to check the bill',
'Adlandırılmak': 'to be named',
'Adres': 'address',
'Adım': 'step',
'Adım adım': 'step by step',
'Adımlar': 'steps',
'Adınız?': 'your name?',
'Affedersiniz': 'excuse me',
'Afiyet olsun': 'enjoy your meal',
'Ahlak': 'morality',
'Aidiyet': 'belonging',
'Aile': 'family',
'Aile bütçesi': 'family budget',
'Aile sağlığı merkezi': 'family clinic',
'Akordeon (halk tipi)': 'folk accordion',
'Akrabalar': 'relatives',
'Aksama / Kesinti': 'interruption',
'Aktarma': 'transfer',
'Akıl': 'mind',
'Akım': 'current',
'Akşam': 'evening',
'Akşam yemeği': 'dinner',
'akşam yemeği yemek': 'to have dinner',
'Akşamleyin': 'in the evening',
'Al-götür sipariş': 'takeaway order',
'Alacaklı': 'creditor',
'Alarm': 'alarm clock',
'Alarmı kontrol etmek': 'to check the alarm',
'Alaycılık': 'sarcasm',
'Alerji': 'allergy',
'Algoritma': 'algorithm',
'Alkış': 'applause',
'Almak': 'to take',
'Alo': 'hello (on the phone)',
'Alt kattaki komşular': 'downstairs neighbours',
'Alt metin': 'subtext',
'Altyazılar': 'subtitles',
'Altın renkli': 'golden',
'Altında': 'under',
'Alçakgönüllülük': 'modesty',
'Alıkoymak / Kesmek': 'to withhold',
'Alışkanlık': 'habit',
'Ama': 'but',
'Ambalaj': 'packaging',
'Ambulans': 'ambulance',
'Amca / Dayı': 'uncle',
'Ameliyat': 'surgery',
'Americano': 'americano',
'Amma da …': 'yeah, right...',
'Ampul': 'light bulb',
'Amuse-bouche': 'amuse-bouche',
'An': 'moment',
'Anahtar / düğme': 'switch',
'Anahtar / Pınar': 'key',
'Anahtarlar': 'keys',
'Anaokulu / kreş': 'kindergarten',
'ancak': 'however',
'Anestezi': 'anaesthesia',
'Anlam': 'meaning',
'Anlamlandırma': 'making sense',
'Anlamı aktarmak': 'to convey the meaning',
'Anlamıyorum': 'I do not understand',
'Anlatmak': 'to tell',
'Anlayış / Başsağlığı': 'sympathy',
'Anlayışınız için teşekkürler': 'thank you for your understanding',
'Anlaşma / Mutabakat': 'agreement',
'Anlaştık': 'agreed',
'Anlaşıldı': 'understood',
'Anne': 'mother',
'Antep fıstığı': 'pistachios',
'Antrenman': 'training',
'Antrenör': 'coach',
'Apartman duyurusu': 'building notice',
'Apartman girişi': 'building entrance',
'Apartman yönetim şirketi': 'building management company',
'Ara': 'interval',
'Ara ara karıştırmak': 'to stir occasionally',
'Ara geçiş tabağı': 'transition course',
'Aralık': 'December',
'Arama': 'phone call',
'Aramak': 'to look for',
'Araç dış gövdesi': 'car body',
'Araç içi': 'car interior',
'araçla ayrılmak': 'to drive away',
'araçla gelmek': 'to arrive by car',
'Araçla gidip gelmek': 'to commute by car',
'araçla gitmek (şimdi/tek yön)': 'to go by car (one way)',
'Araştırma': 'research',
'Argüman': 'argument',
'Arka plan': 'background',
'Arkaizm': 'archaism',
'Artan yemekler': 'leftovers',
'Artık / Çoktan': 'already',
'artık / çoktan': 'already',
'Arıza': 'breakdown',
'Arıza servisi': 'breakdown service',
'Arıza tespiti': 'diagnostics',
'Asansör': 'elevator',
'Asidite': 'acidity',
'Asit / Ekşilik': 'acid',
'asla': 'never',
'Asla / Hiçbir zaman': 'never',
'Aslında': 'actually',
'asıl önemli olan': 'the main thing is',
'At': 'horse',
'Atasözü': 'proverb',
'Ateist': 'atheist',
'Ateş': 'fever',
'Ateş / Isı': 'fire',
'Atkı': 'scarf',
'ATM': 'ATM',
'Atıfta bulunmak': 'to refer to',
'Atık / Fire': 'waste',
'Atıştırmalıklar': 'snacks',
'Avangart': 'avant-garde',
'Avans': 'advance payment',
'Avukat': 'lawyer',
'Ay (takvim)': 'month',
'Ayak / Bacak': 'leg',
'Ayakkabı': 'shoes',
'Ayakkabı tamiri': 'shoe repair',
'Ayarlamak': 'to set up',
'Ayarlar': 'settings',
'Ayaz / Don': 'frost',
'Ayaz Dede': 'Father Frost',
'Ayin': 'religious service',
'Aylık ödeme': 'monthly payment',
'Ayna': 'mirror',
'Aynı anda servis etmek': 'to serve simultaneously',
'Ayrı kesme tahtaları': 'separate chopping boards',
'ayrıca': 'as well',
'Ayrıcalık / Muafiyet': 'benefit',
'Ayrılmak / gitmek': 'to leave by transport',
'Ayrılmak / Çekip gitmek': 'to walk away',
'Ayı': 'bear',
'Ayıp / kusur': 'defect',
'Ayırt etmek': 'to distinguish',
'Az pişmiş': 'rare (steak)',
'Aziz / Kutsal': 'saint',
'Aç': 'hungry',
'Açmak': 'to switch on',
'Açmak (merdaneyle)': 'to roll out (dough)',
'Açık hesap': 'open tab',
'Açık pozisyon': 'vacancy',
'açıklığa kavuşturmama izin verin': 'let me clarify',
'açıkça / belli ki': 'obviously',
'Ağaç': 'tree',
'Ağlamak': 'to cry',
'Ağrı': 'pain',
'Ağrı kesici': 'painkiller',
'Ağır': 'heavy',
'Ağır / Uzatılmış': 'dragged out',
'Ağırdan almak': 'to drag ones feet',
'Aşağı': 'down',
'Aşk / Sevgi': 'love',
'Aşçı': 'cook',
'Aşı': 'vaccination',
'Aşı belgesi': 'vaccination certificate',
'Aşırı / Fazla': 'too much',
'Baba': 'father',
'Baba adı': 'patronymic',
'Babaanne / Anneanne': 'grandmother',
'Bagaj': 'luggage',
'Baharat / Çeşni': 'seasoning',
'Baharatlı': 'spicy',
'Bahçe': 'garden',
'Bahşiş': 'tip',
'Bakiye': 'balance',
'Bakiye yüklemek': 'to top up',
'Baksana': 'hey, look',
'Bakteriler': 'bacteria',
'Bakış açısı': 'point of view',
'Bal': 'honey',
'Balalayka': 'balalaika',
'Bale': 'ballet',
'Balon': 'balloon',
'Balzamik sirke': 'balsamic vinegar',
'Balık': 'fish',
'Balıkla eşleşme': 'pairing with fish',
'Bana fark etmez': 'it does not matter to me',
'bana göre': 'in my opinion',
'Banka': 'bank',
'Banka (oturak)': 'bench',
'Banka kartı': 'bank card',
'Banket / davet yemeği': 'banquet',
'Banyo': 'bathroom',
'Bardak': 'glass',
'Bariyer': 'barrier gate',
'Barmen': 'bartender',
'Barış / Dünya': 'peace',
'Basit kaza tutanağı': 'accident report form',
'Batıcılar': 'Westernizers',
'Bayram / Kutlama': 'celebration',
'Bazen': 'sometimes',
'Bağcık': 'shoelaces',
'Bağlam': 'context',
'Bağlanmak': 'to connect',
'Bağlantı / Link': 'link',
'Bağımsız / Kendi başına': 'independent',
'Bağışıklık': 'immunity',
'Baş / Kafa': 'head',
'Baş ağrıyor': 'my head hurts',
'Baş etmek': 'to cope',
'Başarmak (kişisiz)': 'to work out',
'Başarı durumu': 'academic performance',
'başka bir deyişle': 'in other words',
'Başka bir zaman': 'another time',
'Başlangıç': 'beginning',
'Başlatmak / Fırlatmak': 'to launch',
'Başlık / Manşet': 'headline',
'Baştan savma': 'carelessly',
'Baştan yapmak': 'to redo',
'Başvuru': 'application',
'Başvuru gişesi': 'application desk',
'Başvuru numarası': 'application number',
'Bebek arabası': 'stroller',
'Bebek bezi': 'diaper',
'Bebek püresi': 'baby food',
'Beceri': 'skill',
'Beceri değerlendirmesi': 'skills assessment',
'Bekleme': 'waiting',
'Bekleme süresi': 'waiting time',
'Beklemek': 'to wait',
'Beklenmedik giderler': 'unexpected expenses',
'Beklentiler': 'expectations',
'Beklettiğimiz için özür dileriz': 'sorry for the wait',
'Bekleyen masa': 'waiting list table',
'Bekleyin': 'wait',
'Bel': 'back',
'Belediye': 'city hall',
'Belge': 'document',
'Belge / Yazı': 'certificate',
'Belgeler': 'documents',
'Belgeler el altında': 'documents at hand',
'Belgeleri vermek': 'to submit documents',
'belirsizlik için özür dilerim': 'sorry for the confusion',
'Belirtmek gerekir ki': 'it should be noted',
'Belki': 'maybe',
'Ben': 'I',
'Ben ... alayım': 'I will have...',
'bence': 'in my view',
'Benim': 'mine',
'Benim / Senin': 'mine / yours',
'Benim adım': 'my name is',
'Benim hakkımda': 'about me',
'Benzin': 'petrol',
'Benzin istasyonu': 'gas station',
'Bere / Şapka': 'hat',
'Berrak': 'clear',
'Beslemek': 'to feed',
'Beslenme': 'nutrition',
'Beyan': 'declaration',
'Beyaz': 'white',
'Beze': 'meringue',
'Beş': 'five',
'Beş numaralı masa': 'table number five',
'Beşikten mezara öğren': 'live and learn',
'Biber': 'pepper',
'Biberon': 'baby bottle',
'Bildirim': 'notification',
'Bildirim kâğıdı': 'written notice',
'Bildirmek': 'to inform',
'Bile / Hatta': 'even',
'Bilet': 'ticket',
'Bilgelik': 'wisdom',
'Bilgi olarak almak': 'to take note',
'Bilgiyi devretmek': 'to pass on information',
'Bilim insanı': 'scientist',
'Bilinç': 'consciousness',
'Bilirkişi incelemesi': 'expert examination',
'Bilmeden': 'without knowing',
'Bir': 'one',
'Bir dakika bekleyin': 'wait a minute',
'bir dereceye kadar': 'to some extent',
'Bir günlük izin': 'day off',
'Bir kez daha': 'one more time',
'bir yandan': 'on the one hand',
'Bir ölçüde': 'to a certain extent',
'Biraz': 'a little',
'Biraz daha kısa': 'a bit shorter',
'Biraz daha sessiz': 'a bit quieter',
'Biraz daha yavaş': 'a bit slower',
'Birden / Aniden': 'suddenly',
'Birebir / Sözcüğü sözcüğüne': 'word for word',
'Birikim': 'savings',
'Birikim hedefi': 'savings goal',
'Birlikte': 'together',
'Bisiklet': 'bicycle',
'Bitiş / Ağızda kalan tat': 'aftertaste',
'Bitkin düşmek': 'to get exhausted',
'Bitkisel yağ': 'vegetable oil',
'Bitmek / Dinmek': 'to end',
'Biz': 'we',
'Blanşe etmek': 'to blanch',
'Bloke etmek': 'to block',
'Bol şans': 'good luck',
'Bone': 'hair cap',
'Bonfile': 'fillet',
'Bordro': 'payslip',
'Borsa': 'stock exchange',
'Boru': 'pipe',
'Borç': 'debt',
'Borş': 'borscht',
'Boya': 'paint',
'Boyama kâğıdı': 'colouring book',
'Boyatmak': 'to have painted',
'Bozulmak': 'to break down',
'Boş / Müsait': 'free',
'Boş / müsait': 'available',
'Boş gezmek': 'to idle around',
'Boş kontenjan': 'vacant spot',
'Boş saat': 'free time',
'Boşaltma saati': 'unloading time',
'Boşta garson': 'free waiter',
'bu ... demek': 'it means...',
'bu ... olan yer': 'the place where...',
'bu ... olan şey': 'the thing that...',
'bu ... yapan kişi': 'the person who...',
'bu ...-e bağlı': 'it depends on...',
'Bu arada': 'by the way',
'Bu ne demek?': 'what does this mean?',
'Bu yüzden': 'that is why',
'bu yüzden': 'therefore',
'Budizm': 'Buddhism',
'Bugün': 'today',
'Buhar': 'steam',
'Buharda pişirmek': 'to steam',
'Bulaşma': 'infection',
'Bulaşık yıkamak': 'to wash the dishes',
'Bulgur/İrmik türü tane': 'groats',
'Bulmak': 'to find',
'Bulundu': 'it was found',
'Bulutlu': 'cloudy',
'Buluşmak / Görüşmek': 'to meet',
'buna ne deniyor?': 'what is this called?',
'bunun dışında': 'besides',
'Burada': 'here',
'burada': 'here',
'Burs': 'scholarship',
'Buyurun geçin': 'come in',
'Buz': 'ice',
'Buzdolabı': 'fridge',
'Buzlu': 'with ice',
'Buzsuz': 'without ice',
'Buzunu çözmek': 'to defrost',
'Bölüm / Baş(kan)': 'chapter',
'Bölünme / Şizma': 'schism',
'Bütçe': 'budget',
'Büyük': 'big',
'büyük olasılıkla': 'most likely',
'Büyük tadilat': 'major renovation',
'Büyükelçi': 'ambassador',
'Bıçak': 'knife',
'Cam': 'glass',
'Cami': 'mosque',
'Camlar': 'lenses',
'Cankurtaran': 'lifeguard',
'Cappuccino': 'cappuccino',
'Catering': 'catering',
'Ceket / mont': 'jacket',
'Cep': 'pocket',
'Cerrah': 'surgeon',
'Cesur': 'brave',
'Cevap vermek': 'to answer',
'Ceza': 'fine',
'Cheesecake': 'cheesecake',
'Cherry domates': 'cherry tomatoes',
'Cidden mi': 'seriously?',
'Cila': 'wax polish',
'Coşku / Yüce ton': 'pathos',
'Cuma': 'Friday',
'Cumartesi': 'Saturday',
'Cüzdan': 'wallet',
'daha / henüz': 'still',
'Daha az': 'less',
'daha doğrusu': 'rather',
'Daha sessiz': 'quieter',
'Daha yavaş konuşun': 'speak slower',
'Daha çok': 'more',
'Daimi misafir': 'regular guest',
'Daire': 'apartment',
'Daire kiralamak': 'to rent an apartment',
'Daire kiralamak (tutmak)': 'to be renting an apartment',
'Daireyi görmek': 'to view an apartment',
'Dakika': 'minute',
'Dakikalar': 'minutes',
'Dalgalar': 'waves',
'Damak tadına göre': 'to taste',
'Damat / Nişanlı (erkek)': 'groom',
'Damla': 'drop',
}
