# -*- coding: utf-8 -*-
# tr -> en sözlük PARÇA 5 (S-Y başlangıcı)
D.update({
'Sepet': 'basket',
'Serbest meslek mükellefi': 'self employed',
'Serbest çalışma': 'freelance',
'Sergi': 'exhibition',
'Sergi eseri': 'exhibit',
'Sert / Sıkı': 'firm',
'Sert tepe (çırpma kıvamı)': 'stiff peaks',
'Servis / Tabaklama': 'plating',
'Servis arabası': 'trolley',
'Servis etmek': 'to serve',
'Servis hattı': 'plating line',
'Servis penceresi': 'service window',
'Servis sağlayıcı': 'provider',
'Servis servis ilerleme': 'course by course',
'Servis standardı': 'service standard',
'Servisten önce kontrol etmek': 'to check before serving',
'Ses (insan)': 'voice',
'Sesli rehber': 'audio guide',
'Sesli tekrar etmek': 'to repeat out loud',
'Sessiz salon': 'quiet hall',
'Sessizlik': 'silence',
'Sessizlik konusunda anlaşmak': 'to agree on quiet hours',
'Sevinç': 'joy',
'Sevk belgesi': 'referral (document)',
'Sevmek': 'to love',
'Seyirci': 'spectator',
'Seçmek': 'to choose',
'Sibirya': 'Siberia',
'Sigorta': 'insurance',
'Sigorta olayı': 'insured event',
'Sigorta şirketi': 'insurance company',
'Sigortalama': 'insurance (process)',
'SIM kart': 'SIM card',
'Sinagog': 'synagogue',
'Sinek kovucu': 'insect repellent',
'Sinema': 'cinema',
'Sinyal': 'turn signal',
'Sipariş': 'order',
'Sipariş karıştı': 'the order got mixed up',
'Sipariş notu': 'order note',
'Sipariş numarası': 'order number',
'Siparişe hazır mısınız?': 'are you ready to order?',
'Siparişi girmek': 'to enter the order',
'Siparişi puanlamak': 'to rate the order',
'Siparişi tekrar edeyim mi?': 'shall I repeat the order?',
'Sirke': 'vinegar',
'Sis': 'fog',
'Siyah': 'black',
'Siyah çay': 'black tea',
'Siz (resmî)': 'you (formal)',
'Sizin için güvenli mi?': 'is it safe for you?',
'Slavcılar': 'Slavophiles',
'Slayt': 'slide',
'Slaytlar': 'slides',
'SMS bildirimi': 'SMS notification',
'Sofra kurmak': 'to set the table',
'Sofra sohbeti': 'table talk',
'Sohbet': 'conversation',
'Sohbet etmek': 'to have a chat',
'Sokak': 'street',
'Sola': 'to the left',
'Solyanka': 'solyanka',
'Sommelier': 'sommelier',
'Son': 'end',
'Son dokunuş': 'final touch',
'Son kullanma tarihi': 'expiry date',
'Son temizlik': 'final cleaning',
'Sonbahar': 'autumn',
'Sonra': 'then',
'sonra': 'then',
'Sonraki randevu': 'next appointment',
'Sonunda!': 'finally!',
'Sonuç / Çıkarım': 'conclusion',
'sonuç olarak': 'as a result',
'Soru': 'question',
'Sorular': 'questions',
'Sorumlu': 'person in charge',
'Sorumlu garson': 'waiter in charge',
'Sorumluluk': 'responsibility',
'Sorun': 'problem',
'Sorunu kabul etmek': 'to acknowledge the problem',
'Soruşturma': 'investigation',
'Sos': 'sauce',
'Sos ayrı': 'dressing on the side',
'Sos istasyonu': 'sauce station',
'Sosu çektirmek': 'to reduce the sauce',
'Sosyal medya': 'social media',
'Sosyal yardım': 'benefit (welfare)',
'Sous-vide': 'sous vide',
'Sovyet': 'Soviet',
'Soymak / Temizlemek': 'to peel',
'Soyunma odası': 'changing room',
'Soğan / Yay': 'onion',
'Soğansız': 'without onion',
'Soğuk': 'cold (weather)',
'Soğuk algınlığı': 'cold (illness)',
'Soğutmak': 'to cool down',
'Soğutulmuş ürün': 'chilled product',
'Spor': 'sport',
'Spor ayakkabı': 'sneakers',
'Spor salonu': 'gym',
'Stajyer': 'intern',
'Startup / Girişim': 'startup',
'Sterilize etmek': 'to sterilise',
'Stres': 'stress',
'Su': 'water',
'Su baskını': 'flooding',
'Su kaynağı': 'spring (water)',
'Su kesintisi': 'water outage',
'Su stoğu': 'water supply',
'Su sızdırmak': 'to leak',
'Su terazisi': 'spirit level',
'Suda balık gibi': 'like a fish in water',
'Sulama kabı': 'watering can',
'Sulamak': 'to water',
'Sunucunun kadeh konuşması': "toast of the host",
'Sunum / Bildiri': 'presentation (paper)',
'Suyunu içinde mühürlemek': 'to seal in the juices',
'Suçlu': 'guilty',
'Söylenti': 'rumour',
'söz konusu olan': 'what is at stake is',
'Söz vermek': 'to promise',
'Sözleşme': 'contract',
'Sözleşme maddesi': 'contract clause',
'Sözlü': 'orally',
'Sürahi su': 'carafe of water',
'Süre': 'term',
'Süre uzatmak': 'to extend',
'Süreklilik / Devralma': 'continuity',
'Sürmek (zaman)': 'to take (time)',
'Sürpriz': 'surprise',
'Sürücü': 'driver',
'Süs şeridi': 'garland',
'Süsleme': 'decoration',
'Süt': 'milk',
'Süt ayrı': 'milk on the side',
'Süt ürünleri': 'dairy products',
'Süt ürünleri reyonu': 'dairy section',
'Sütsüz': 'without milk',
'Süzmek': 'to strain',
'Sıcak': 'hot weather',
'Sıcak (hava)': 'hot (weather)',
'Sıcak / Ateşli': 'hot',
'Sıcak ana yemekler': 'hot main courses',
'Sıcak karşılama': 'warm welcome',
'Sıcak yemek hazır': 'the hot dish is ready',
'Sıcak çay': 'hot tea',
'Sıcaklık kayıt defteri': 'temperature log',
'Sık sık': 'often',
'Sınama / Onaylanma': 'piloting (testing)',
'Sınav': 'exam',
'Sınav dönemi': 'exam period',
'Sınıf öğretmeni': 'class teacher',
'Sınır dışı etme': 'deportation',
'Sınırlar': 'borders',
'Sıra bileti': 'queue ticket',
'Sırt çantası': 'backpack',
'Sızıntı': 'leak',
'Tabak': 'plate',
'Tabakları almak': 'to clear the plates',
'Taban': 'sole (of a shoe)',
'Tabii ki': 'of course',
'Tablet / Hap': 'tablet',
'Tablo / Resim': 'painting',
'Taburcu / Epikriz': 'discharge summary',
'Tadım kadehi': 'tasting glass',
'Tadım menüsü': 'tasting menu',
'Tahakkuk': 'accrual',
'Tahliye': 'eviction',
'Tahmin': 'forecast',
'tahminen': 'approximately',
'Tahsilat': 'collection (of payment)',
'Takdis / Hayır dua': 'blessing',
'Takip etmek': 'to track',
'Taksi': 'taxi',
'Taksit': 'instalment',
'Takılmak / Sataşmak': 'to tease',
'Talep': 'demand',
'Talep etmek': 'to demand',
'Talepler': 'requirements',
'Tam depo': 'full tank',
'Tam doluluk': 'full house',
'tam olarak katılmıyorum': 'I do not quite agree',
'tam olarak öyle değil': 'not quite so',
'Tam tersine': 'on the contrary',
'Tamam / İyi': 'fine',
'Tamir / Onarım': 'repair',
'Tamir atölyesi': 'repair shop',
'Tamir etmek': 'to fix',
'Tandır': 'tandoor',
'Tanrı': 'God',
'Tansiyon / Basınç': 'pressure',
'Tanıdık': 'acquaintance',
'Tanık': 'witness',
'Tanıtım / Promosyon': 'promotion',
'Tanışma uygulaması': 'dating app',
'Tanışmak': 'to get acquainted',
'Tapu kaydı': 'land registry extract',
'Taraf': 'side (party)',
'Tarak': 'comb',
'Tarif': 'description',
'Tarih': 'date',
'Tarih (gün)': 'date (day of month)',
'Tartışma': 'discussion',
'Tartışmalı': 'debatable',
'Tartışmalı an': 'controversial moment',
'Tartışmamak': 'not to argue',
'Tarçın': 'cinnamon',
'Tasarruf etmek': 'to save money',
'Tasma': 'collar (for a pet)',
'Tasvir etmek': 'to depict',
'Tat / Lezzet': 'taste',
'Tat dengesi': 'balance of taste',
'Tat katmak': 'to add flavour',
'Tatarlar': 'the Tatars',
'Tatil': 'holidays',
'Tatlı': 'sweet',
'Tatlı (yemek)': 'dessert',
'Tatlı / Şirin': 'cute',
'Tatlı menüsü': 'dessert menu',
'Tatlı önermek': 'to recommend a dessert',
'Tatlılar': 'desserts',
'Tatlıyı soğutmak': 'to chill the dessert',
'Tava sıcaklığı': 'pan temperature',
'Tavan': 'ceiling',
'Taviz / Ödün': 'concession',
'Tavsiye': 'recommendation',
'Tavsiye etmek': 'to advise',
'Tavuk fileto': 'chicken fillet',
'Tavuk suyu': 'chicken broth',
'Tayga': 'taiga',
'Taze': 'fresh',
'Taze balık': 'fresh fish',
'Taze ekmek': 'fresh bread',
'Taze hasat': 'fresh harvest',
'Taze sıkılmış meyve suyu': 'freshly squeezed juice',
'Taze yeşillik': 'fresh greens',
'Tazelik': 'freshness',
'Tazmin etmek': 'to compensate',
'Tazminat': 'compensation',
'Taşınma': 'moving house',
'Taşıyıcılar': 'porters',
'Tebrik': 'congratulation',
'Tebrik etmek': 'to congratulate',
'Tedarikçi': 'supplier',
'Tedavi': 'treatment',
'Tehdit': 'threat',
'Tehlikeli': 'dangerous',
'Tekerlek': 'wheel',
'Teklif': 'offer',
'Teknik ara': 'technical break',
'Teknisyen çağırmak': 'to call a technician',
'Tekrar davet etmek': 'to invite again',
'Tekrar edin': 'repeat',
'Tekrar edin lütfen': 'repeat please',
'Tekrar gelmek': 'to come back again',
'Telafi önermek': 'to offer compensation',
'Telefon': 'phone',
'Telefon etmek': 'to call',
'Telefon numarası': 'phone number',
'Telif': 'copyright',
'Temassız': 'contactless',
'Temiz': 'clean',
'Temiz hava': 'fresh air',
'Temiz kesme tahtası': 'clean chopping board',
'Temizlik': 'cleaning',
'Temizlik kontrolü': 'cleanliness check',
'Temmuz': 'July',
'Temperleme': 'tempering (chocolate)',
'Temsilci': 'representative',
'Temyiz': 'appeal (court)',
'Tepsi': 'tray',
'Terazi': 'scales',
'Terbiye etmek': 'to marinate',
'Tercihler': 'preferences',
'Tereyağı': 'butter',
'Tereyağı / Yağ': 'oil',
'Terlik': 'slippers',
'Termos': 'thermos',
'Terroir': 'terroir',
'Terzi / atölye': 'tailor shop',
'Tesadüf / Durum': 'coincidence',
'Tesisatçı': 'plumber',
'Teslim almak': 'to pick up',
'Teslim süreleri': 'deadlines',
'Teslim tarihi': 'deadline',
'Teslimat': 'delivery',
'Teslimat saati': 'delivery time',
'Tevazu / Teslimiyet': 'humility',
'Teyit': 'confirmation',
'Tez': 'dissertation',
'Tez / Ana savı': 'thesis',
'Teşekkür': 'thank you',
'Teşhis': 'diagnosis',
'Tilki': 'fox',
'Tiyatro': 'theatre',
'Tofu': 'tofu',
'Tohumlar': 'seeds',
'Ton / Nüans': 'shade',
'Tonu kontrol etmek': 'to control the tone',
'Topaklar': 'lumps',
'Toplam': 'total',
'Toplamak / Temizlemek': 'to clear away',
'Toplantı': 'meeting',
'Toplantı kaydı': 'meeting recording',
'Toplu servis': 'group serving',
'Topluluk': 'community',
'Topuk': 'heel',
'Tornavida': 'screwdriver',
'Torun (erkek)': 'grandson',
'Tost': 'toast',
'Toz': 'dust',
'Trafik kazası': 'traffic accident',
'Trafik lambası': 'traffic light',
'Trafik levhası': 'road sign',
'Trafik sıkışıklığı': 'traffic jam',
'Tren': 'train',
'Tur / gezi': 'excursion',
'Tur rehberi': 'tour guide',
'Turnike': 'turnstile',
'Tutam': 'pinch',
'Tutanak': 'minutes (protocol)',
'Tuz': 'salt',
'Tuzlama': 'salting',
'Tuzsuz': 'without salt',
'Töreler': 'customs',
'Tükenmişlik': 'burnout',
'Tüketici hakları': 'consumer rights',
'Tüy taramak': 'to brush the fur',
'Ucuz': 'cheap',
'Ulaşmak (yürüyerek)': 'to reach on foot',
'Umami': 'umami',
'Umut': 'hope',
'Un': 'flour',
'Un serpmek': 'to dust with flour',
'Usta / Tamirci': 'craftsman',
'UV ışınları': 'UV rays',
'Uyanmak': 'to wake up',
'uyanmak': 'to wake up',
'Uyarlama': 'adaptation',
'Uyarlamak': 'to adapt',
'Uygulama / App': 'app',
'Uygulamalı eğitim': 'hands on training',
'Uygulamaya geçirme': 'implementation',
'Uygun / Rahat': 'comfortable',
'Uygun gelmek': 'to suit',
'Uyku saati': 'nap time',
'Uyku tulumu': 'sleeping bag',
'Uymadı': 'it did not fit',
'Uymak (kurala)': 'to comply',
'Uyumak': 'to sleep',
'Uyumsuzluk': 'discrepancy',
'Uzak': 'far',
'Uzaktan': 'remotely',
'Uzaktan çalışma': 'remote work',
'Uzlaşma': 'compromise',
'Uzlaşmak': 'to reach agreement',
'Uzun': 'long',
'Uzun süre': 'for a long time',
'Uğramak': 'to drop by',
'Uğraşmak / Çalışmak': 'to be busy with',
'Vaftiz': 'baptism',
'Vagon': 'railway carriage',
'Vahiy': 'revelation',
'Vakayiname': 'chronicle',
'Vakum makinesi': 'vacuum sealer',
'Vanilya': 'vanilla',
'Var': 'there is',
'Vardiya': 'shift',
'Vardiyayı açmak': 'to open the shift',
'Varis': 'heir',
'Varlık / Varoluş': 'being',
'Varlıklar': 'assets',
'Varmak / Gelmek': 'to come',
'Varmak / Gelmek (araçla)': 'to arrive by transport',
'Varsaymak': 'to assume',
'Varyasyon': 'variation',
'Varış zamanı': 'arrival time',
'Vasiyet': 'will (testament)',
'Vegan seçenek': 'vegan option',
'Vejetaryen': 'vegetarian',
'Vejetaryen yemek': 'vegetarian dish',
'Vekâletname': 'power of attorney',
'Veli': 'parent',
'Veli grubu': 'parents chat',
'Veli toplantısı': 'parent teacher meeting',
'Vergi': 'tax',
'Vergi iadesi': 'tax refund',
'Vergi indirimi': 'tax deduction',
'Vergi mukimi': 'tax resident',
'Vergiler': 'taxes',
'Veriler': 'data',
'Verin': 'give me',
'Vermek': 'to give',
'Vestiyer': 'cloakroom',
'Veteriner': 'veterinarian',
'Vezin / Ölçü': 'metre (poetry)',
'Vezne penceresi': 'ticket window',
'Vicdan': 'conscience',
'Vida': 'screw',
'Video toplantı': 'video meeting',
'Vitaminler': 'vitamins',
'Vize': 'visa',
'Vize uzatmak': 'to extend the visa',
'Vurgu': 'stress (accent)',
'Wi-Fi': 'Wi-Fi',
'Wok': 'wok',
'Ya Rabbi': 'oh Lord',
'Yabani ot': 'weed',
'Yakında': 'nearby',
'yalın hâl sorusu': 'who? what?',
'Yan etki': 'side effect',
'Yangın': 'fire',
'Yanılgı': 'misconception',
'Yapabilmek (beceri)': 'to know how',
'Yapay sinir ağı': 'neural network',
'Yapay zekâ': 'artificial intelligence',
'yapmak (süreç)': 'to do (process)',
'Yapmak / Yapıp bitirmek': 'to do / to complete',
'Yaprak': 'leaf',
})
