# -*- coding: utf-8 -*-
# tr -> en sözlük PARÇA 4 (M-S)
D.update({
'Mahkeme': 'court',
'Mahkemeye başvurmak': 'to go to court',
'Makas': 'scissors',
'Makine': 'machine',
'Mal kabul etmek': 'to accept goods',
'Mali fiş': 'fiscal receipt',
'Malik / ev sahibi': 'property owner',
'Maliyet': 'cost price',
'Malzemeler': 'ingredients',
'Mama': 'pet food',
'Mama kabı': 'bowl',
'Mama sandalyesi': 'high chair',
'Manastır': 'monastery',
'Maneviyat': 'spirituality',
'Mantar': 'mushroom',
'Mantar çorbası': 'mushroom soup',
'Manuel indirim': 'manual discount',
'Marine etmek': 'to marinate',
'Marine sosu': 'marinade',
'Marka': 'brand',
'Mart': 'March',
'Marul yaprakları': 'lettuce leaves',
'Masa': 'table',
'Masa (restoranda)': 'table (at a restaurant)',
'Masa ayırtmak': 'to book a table',
'Masa örtüsü': 'tablecloth',
'Masanız hazır': 'your table is ready',
'Masaya bırakmak': 'to leave on the table',
'Masayı taşımak': 'to move the table',
'Matkap': 'drill',
'Mavi (koyu)': 'dark blue',
'Maya': 'yeast',
'Mayalanma / dinlenme': 'proofing (dough)',
'Mayalanıp kabarmak': 'to rise (dough)',
'Mayo': 'swimsuit',
'Mayıs': 'May',
'Mazeret / Haklı çıkarma': 'excuse',
'Mağaza / Dükkân': 'shop',
'Mağazaya şikâyet': 'complaint to the shop',
'Mecazi': 'figurative',
'Mecazi anlam': 'figurative meaning',
'Medovik pastası': 'medovik cake',
'Medrese': 'madrassa',
'Mektup': 'letter',
'Memnun / Sevinçli': 'glad',
'Memnun oldum / Hoş': 'nice to meet you',
'Memnun olmayan misafir': 'unhappy guest',
'Memnuniyetle': 'with pleasure',
'Mentor': 'mentor',
'Menü fiyatı': 'menu price',
'Mercimek': 'lentils',
'Merdiven': 'stairs',
'Merhaba (resmî)': 'hello (formal)',
'Merhamet': 'mercy',
'Merkez': 'centre',
'Mesaj': 'message',
'mesele şu ki': 'the thing is',
'Meslektaş / İş arkadaşı': 'colleague',
'Metafor': 'metaphor',
'Metin': 'story',
'Metodoloji': 'methodology',
'Metrekare': 'square metres',
'Metro': 'metro',
'Mevsim ürünü': 'seasonal product',
'Meyve suyu': 'juice',
'Meyve tabağı': 'fruit plate',
'Meyveler': 'fruits',
'Mezhep / İnanç topluluğu': 'denomination',
'Meziyet': 'merit',
'Meşgul': 'busy',
'Meşgul (e/k)': 'busy (m/f)',
'Midye': 'mussels',
'Mikrofon': 'microphone',
'Minare': 'minaret',
'Miras': 'heritage',
'Misafir': 'guest',
'Misafir istiyor': 'the guest wants',
'Misafir kartı': 'guest card',
'Misafir yorumu': 'guest review',
'Misafirlerden sonra toplamak': 'to tidy up after guests',
'Misafirliğe': 'to visit (somebody)',
'Modem / Router': 'router',
'Mola': 'break',
'Motif / İzlek': 'motif',
'Motivasyon': 'motivation',
'Muafiyet': 'deductible',
'Muayene': 'check up',
'Muayene / Tetkik': 'medical examination',
'Muhalif hoca': 'opponent (academic)',
'muhtemelen / olabilir': 'probably',
'Mum': 'candle',
'Mumlar': 'candles',
'Musluk': 'tap',
'Mutabık kalmak / Onaylatmak': 'to get approval',
'Mutfak': 'kitchen',
'Mutfak bilmeli': 'the kitchen should know',
'Mutfak geleneği': 'culinary tradition',
'Mutfak notu': 'note for the kitchen',
'Mutfak zaman çizelgesi': 'kitchen schedule',
'Mutfakta soracağım': 'I will check with the kitchen',
'Mutfağa fiş basımı': 'printing tickets for the kitchen',
'Mutlu': 'happy',
'Mutluluk': 'happiness',
'Müdür': 'manager',
'Müdür / Amir': 'boss',
'Müftü': 'mufti',
'Mühendis': 'engineer',
'Mühür': 'stamp',
'Mühürlemek / Kızartmak': 'to sear',
'Müsait (e/k)': 'available (m/f)',
'Müslüman (erkek)': 'Muslim',
'Müteahhit': 'developer (construction)',
'Müzakere yürütmek': 'to hold talks',
'Müzakereler': 'negotiations',
'Müze': 'museum',
'Müzik': 'music',
'Müşteri / İş veren': 'client',
'Müşteri destek': 'customer support',
'Nadiren': 'rarely',
'Nakit': 'cash',
'Nakliye aracı': 'delivery vehicle',
'Namaz': 'namaz (prayer)',
'Narin doku': 'delicate texture',
'Nasıl?': 'how?',
'Nasılsın': 'how are you',
'Nasılsın?': 'how are you?',
'Ne': 'what',
'Ne alırsınız?': 'what will you have?',
'Ne gezer': 'no way',
'Ne zaman': 'when',
'Ne zaman geleceksiniz?': 'when will you come?',
'Ne zaman?': 'when?',
'Ne?': 'what?',
'Neden': 'why',
'Neden?': 'why?',
'Nehir': 'river',
'Nerede': 'where',
'Nerede?': 'where?',
'Nereden / Nereli': 'from where',
'Nereden?': 'from where?',
'Nereye?': 'where to?',
'Nezle / Burun akıntısı': 'runny nose',
'Neşeli': 'cheerful',
'Nihayet': 'finally',
'Nikâh dairesi': 'registry office',
'Nostalji': 'nostalgia',
'Not / Dipnot': 'note',
'Not eklemek': 'to add a note',
'Not etmek / Kaydetmek': 'to write down',
'Nota (aroma)': 'note (flavour)',
'Notlar': 'grades',
'Nöbetçi eczane': 'on duty pharmacy',
'Nüktedanlık': 'wit',
'O (eril/dişil)': 'he / she',
'Ocak': 'stove',
'Oda': 'room',
'Oda (otelde)': 'hotel room',
'Oda numarası': 'room number',
'Oda servisi': 'room service',
'Ofis odası': 'office room',
'Okul': 'school',
'Okul günlüğü': 'school diary',
'Okumak': 'to read',
'okumak (süreç)': 'to read (process)',
'Okumak / Okuyup bitirmek': 'to read / to finish reading',
'Okumak / Öğrenim görmek': 'to study',
'Okur / Okuyucu': 'reader',
'Okur kartı': 'library card',
'Okurken / Okuyarak': 'while reading',
'Okuyan': 'the one reading',
'Okuyup': 'having read',
'okuyup bitirmek': 'to finish reading',
'Olay sonrası değerlendirme': 'post incident review',
'Olay örgüsü': 'plot',
'Oldukça': 'quite',
'Olmak / Sonuç vermek': 'to turn out',
'Olur mu? / Mümkün mü?': 'may I?',
'Omlet': 'omelette',
'On': 'ten',
'On bir': 'eleven',
'On dakika gecikmek': 'to be ten minutes late',
'On dakikaya hazır olur': 'it will be ready in ten minutes',
'Onam / Rıza': 'consent',
'Onaylamak': 'to certify',
'Onlar': 'they',
'Online görüşme': 'online call',
'Online hesap': 'online account',
'Online sipariş': 'online order',
'Online ödemek': 'to pay online',
'Operatör': 'operator',
'Optik mağazası': 'optician',
'orada': 'there',
'Orijinal eser': 'original (work)',
'Orman': 'forest',
'Orta pişmiş': 'medium (steak)',
'Oruç (Türkî dillerden)': 'fasting',
'Otantiklik': 'authenticity',
'Otel': 'hotel',
'Otele giriş': 'hotel check in',
'Oto yıkama': 'car wash',
'Otobüs': 'bus',
'Otomatik ödeme': 'autopay',
'Otopark': 'parking',
'Oturma izni': 'residence permit',
'Oturma planı': 'seating plan',
'Oturmak (bir kere)': 'to sit down',
'Oturmak (durum)': 'to be sitting',
'Otuz': 'thirty',
'Oybirliği ile': 'unanimously',
'Oylama': 'voting',
'Oynamak / Çalmak': 'to play',
'Oyun / Gösteri': 'play (theatre)',
'Oyun parkı': 'playground',
'Oyuncak': 'toy',
'Oyunculuk': 'acting',
'Oğul': 'son',
'Paganlık': 'paganism',
'Pahalı': 'expensive',
'Paket / Yanımda götüreceğim': 'to take away',
'Paket kâğıdı': 'paper',
'Paket çatal-bıçak': 'cutlery to go',
'Paketlemek': 'to pack',
'Palto': 'coat',
'Pandispanya': 'sponge cake',
'Panelemek / Galeta': 'breading',
'Pantolon': 'trousers',
'Pantolon paçası yapmak': 'to hem trousers',
'Para': 'money',
'Para ayırmak': 'to set money aside',
'Para iadesi': 'refund',
'Para çekmek': 'to withdraw money',
'Para üstü': 'change',
'Park': 'park',
'Parlayan her şey altın değildir': 'all that glitters is not gold',
'Pasaport': 'passport',
'Pasaport kontrolü': 'passport control',
'Paskalya': 'Easter',
'Paskalya çöreği': 'Easter cake (kulich)',
'Paspas': 'mop',
'Pasta': 'cake',
'Pastacı': 'pastry chef',
'Patates püresi': 'mashed potatoes',
'Patika': 'trail',
'Patlamak / yanmamak': 'to burn out',
'Patlamış mısır': 'popcorn',
'Patrik': 'patriarch',
'Pay': 'share',
'Paylaşmak / Yüklemek': 'to upload',
'Pazar': 'Sunday',
'Pazar / Piyasa': 'market',
'Pazarlık': 'bargaining',
'Pazarlık etmek': 'to bargain',
'Pazartesi': 'Monday',
'pek mümkün değil': 'hardly possible',
'pek olası değil': 'unlikely',
'Pek sanmam': 'I doubt it',
'Peki / Tamam': 'okay',
'Pencere kenarında': 'by the window',
'Pencere önü': 'windowsill',
'Perestroyka': 'perestroika',
'Performans göstergeleri': 'performance indicators',
'Perhiz / Oruç': 'lent (fasting)',
'Peron': 'platform',
'Petekler': 'radiators',
'Peynir': 'cheese',
'Peynir tabağı': 'cheese plate',
'Peçete': 'napkin',
'Peşinat': 'down payment',
'Piknik': 'picnic',
'Pil': 'battery',
'Pilavla servis edilir': 'served with rice',
'PIN kodu': 'PIN code',
'Pipet': 'straw',
'Pirinç': 'rice',
'Piyasa rayici': 'at market rate',
'Piyon': 'game piece',
'Pişme derecesi': 'doneness',
'Plaj': 'beach',
'Plan': 'plan',
'Planlamak': 'to plan',
'Planlar': 'plans',
'Planlı kesinti': 'scheduled outage',
'Plastik': 'plastic',
'Plastik bardak': 'plastic cup',
'Polis (teşkilat)': 'police',
'Polise dilekçe': 'police report',
'Poliçe': 'insurance policy',
'Pompa': 'fuel pump',
'Porsiyon': 'portion',
'Porsiyon gramajı': 'portion weight',
'Porsiyon kapları': 'portion containers',
'Porsiyon kontrolü': 'portion control',
'Porsiyonlama': 'portioning',
'POS cihazı': 'card terminal',
'Postane': 'post office',
'Powerbank': 'power bank',
'Pozisyon / Görev': 'position',
'Poşet': 'plastic bag',
'Prim': 'bonus',
'Primler': 'contributions',
'Priz': 'socket',
'Profil formu': 'questionnaire',
'Program': 'timetable',
'Program broşürü': 'programme booklet',
'Promosyon kodu': 'promo code',
'Prova': 'fitting',
'Puan': 'point',
'Puanlama': 'rating',
'Pudra şekeri': 'powdered sugar',
'Pul': 'postage stamp',
'Püreyi ısıtmak': 'to heat up the puree',
'Raf': 'shelf',
'Rahatlık': 'comfort',
'Rahatsız etmeyen servis': 'unobtrusive service',
'Rahatsız etmeyin': 'do not disturb',
'Rahatsızlık': 'discomfort',
'Rahip': 'priest',
'Rakip': 'rival',
'Ramazan': 'Ramadan',
'Randevu / Kabul saati': 'appointment hours',
'Randevu almak': 'to make an appointment',
'Rapor': 'report',
'Rehber': 'guide',
'Reklam': 'advertisement',
'Rekor': 'record',
'Rendelemek': 'to grate',
'Rengi korumak': 'to keep the colour',
'Renk': 'colour',
'Resepsiyon': 'reception',
'Resim çizmek': 'to draw',
'Resmî': 'official',
'Resmî belge': 'certificate',
'Resmî görüş': 'official position',
'Ressam / Sanatçı': 'artist',
'Restoran': 'restaurant',
'Restoran itibarı': 'restaurant reputation',
'Retorik': 'rhetoric',
'Revizyon': 'revision',
'Revizyonlar': 'edits',
'Rezervasyon': 'booking',
'Rezervasyon yapmak': 'to make a booking',
'Rezervasyonu iptal etmek': 'to cancel the booking',
'Rezervasyonu onaylamak': 'to confirm the booking',
'Reçel': 'jam',
'Reçete': 'prescription',
'Reçete kartı': 'recipe card',
'Rica ederim': 'you are welcome',
'Risk': 'risk',
'Rol oynamak': 'to play a role',
'Roman': 'novel',
'Ruble': 'rouble',
'Ruh / Can': 'soul',
'Ruhsat': 'permit',
'Rus hamamı': 'banya (Russian bath)',
'Rusça öğreniyorum': 'I am learning Russian',
'Rüzgâr': 'wind',
'Saat': 'hour',
'Saat kaça?': 'for what time?',
'Sabah': 'morning',
'Sabah ona kadar': 'until ten in the morning',
'Sabah sisi': 'morning mist',
'Sabit taksit': 'fixed instalment',
'Sabun': 'soap',
'Sabır': 'patience',
'Sadaka': 'alms',
'Safran': 'saffron',
'Sahadaki sorumlu': 'person in charge on site',
'Sahanda yumurta': 'fried eggs',
'Sahne': 'stage',
'Sakin kalmak': 'to stay calm',
'Sakin şekilde': 'calmly',
'Sakinleşmek': 'to calm down',
'Saklama kabı': 'container',
'Saklama sıcaklığı': 'storage temperature',
'Saksı': 'flower pot',
'Saksı değiştirmek': 'to repot',
'Salamura suyu': 'brine',
'Salatalar': 'salads',
'Salatalık': 'cucumber',
'Sallayarak uyutmak': 'to rock to sleep',
'Salon': 'hall',
'Salon müdürü': 'floor manager',
'Salon planı': 'floor plan',
'Salıncak': 'swing',
'Sandalye': 'chair',
'Sandalyeler': 'chairs',
'Sandviç': 'sandwich',
'Sandviç / Tereyağlı ekmek': 'open sandwich',
'Sarı': 'yellow',
'Satın almak': 'to buy',
'satın almak (sonuç)': 'to buy (result)',
'satın almak (süreç/tekrar)': 'to buy (regularly)',
'Satış işlemi': 'deal',
'Sayaç': 'meter',
'Sayaç değeri': 'readings',
'Sayaç göstergesi': 'meter readings',
'Sayesinde': 'thanks to',
'Sayfa': 'page',
'Saygı': 'respect',
'Saygı göstermek': 'to respect',
'Sayım': 'stocktaking',
'Saç kesimi': 'haircut',
'Saçlar': 'hair',
'Sağa': 'to the right',
'Sağlamak / Vermek': 'to provide',
'Sağlık': 'health',
'Sağlıklı': 'healthy',
'Seans': 'screening',
'Sebze bahçesi': 'vegetable garden',
'Sebze garnitürü': 'vegetable side',
'Sebze kırpıntıları': 'vegetable trimmings',
'Sebze suyu': 'vegetable broth',
'Sebzeler': 'vegetables',
'Sek şarap': 'dry wine',
'Sekülerleşme': 'secularisation',
'Selam': 'hi',
'Semaver': 'samovar',
'Sembol': 'symbol',
'Sen': 'you',
'Senin yerinde olsam': 'if I were you',
})
