// DilKoç © 2026 — Bu kaynak kod telif hakkıyla korunur. İzinsiz kopyalama,
// dağıtma ve türev çalışma üretme yasaktır (bkz. LICENSE).
// ============================================================================
// 🛂 VISA & PASSPORT / CITIZENSHIP / MIGRATION PACK — ENGLISH (2/2: units 26-50)
// ============================================================================

import type { UnitModule } from '../../curriculumData';
import { makeCitUnit, type CitWord, type CitSent, type CitLine } from '../citizenship/makeCitUnit';

const U = (
  id: string, n: number, lv: UnitModule['levelGroup'], icon: string,
  title: string, desc: string, cat: string, color: string, grammar: string,
  words: CitWord[], sents: CitSent[], dlg: CitLine[],
): UnitModule => makeCitUnit({ id, unitNumber: n, level: lv, icon, title, desc, category: cat, color, grammar, words, sents, dlg });

const VAT = "Vatandaşlık";
const GOC = "Göç & Uyum";
const DOGUM = "Doğum & Vatandaşlık";
const RESMI = "Resmî İşlemler";

export const EN_CIT_B: UnitModule[] = [
  U("en_cit_26", 625, "B2", "⚖️", "Çift Vatandaşlık",
    "İkinci vatandaşlık: izin, bildirim yükümlülüğü",
    VAT, "#8b5cf6",
    "📌 Kısmi olumsuzluk: \"not in every country\" — her ülkede değil.\nPassive: is allowed — izinli, is prohibited — yasak.",
    [
      ["dual citizenship", "DyUuıl SİTızınship", "çift vatandaşlık", "İki ülkenin vatandaşı olmak."],
      ["second citizenship", "SEkınd SİTızınship", "ikinci vatandaşlık", "Sonradan kazanılır."],
      ["to notify the authorities", "NOWtıfay di oTHORıtiz", "makamlara bildirmek", "Yasal yükümlülüktür."],
      ["obligation", "obliGEYşın", "yükümlülük", "Vatandaşlıkla gelir."],
      ["allowed", "ıLAUd", "izinli/mümkün", "Ülkeye göre değişir."],
      ["prohibited", "prıHİBıtid", "yasak", "Bazı ülkelerde geçerli."],
    ],
    [
      ["Dual citizenship is not allowed in every country.", "Çift vatandaşlık her ülkede mümkün değil."],
      ["You must notify the authorities about a second citizenship.", "İkinci vatandaşlığı makamlara bildirmelisiniz."],
      ["A dual citizen has double rights and obligations.", "Çifte vatandaşın çifte hak ve yükümlülükleri olur."],
    ],
    [
      ["Lawyer", "Do you have a second citizenship?", "du yu HEV ı SEkınd SİTızınship", "İkinci vatandaşlığınız var mı?"],
      ["Client", "Yes, must I notify the authorities?", "YES, mast ay NOWtıfay di oTHORıtiz", "Evet, makamlara bildirmem mi gerekir?"],
      ["Lawyer", "Yes, it's a legal obligation.", "YES, its ı LİIgıl obliGEYşın", "Evet, kanunen bir yükümlülük."],
    ]),

  U("en_cit_27", 626, "B2", "🧑‍⚖️", "Vatandaşlık Hukuku ve Avukat",
    "Mevzuat, avukat, dava ve hukuki yardım",
    VAT, "#8b5cf6",
    "📌 \"specialise IN + alan\" — ...uzmanı olmak.\n\"hear a case/lawsuit\" — davayı görmek.",
    [
      ["legislation", "lecisLEYşın", "mevzuat (kanunlar)", "Tüm yasaların bütünü."],
      ["lawyer", "LOYır", "avukat", "Hukuki temsilcidir."],
      ["legal consultation", "LİIgıl konsılTEYşın", "hukuki danışma", "İlk adım olmalıdır."],
      ["lawsuit", "LOOsuit", "dava", "Mahkemeye taşınır."],
      ["court", "KORT", "mahkeme", "Kararı veren organdır."],
      ["legal aid", "LİIgıl EYD", "hukuki yardım", "Ücretsiz olanı da vardır."],
    ],
    [
      ["The lawyer specialises in citizenship law.", "Avukat vatandaşlık hukuku uzmanıdır."],
      ["The first consultation is free.", "İlk görüşme ücretsizdir."],
      ["The court hears lawsuits against refusals.", "Mahkeme ret davalarını görür."],
    ],
    [
      ["Client", "I need legal aid.", "ay NİID LİIgıl EYD", "Hukuki yardıma ihtiyacım var."],
      ["Lawyer", "Tell me about your situation.", "TEL mi ıBAUT yör siçuEYşın", "Durumunuzu anlatın."],
      ["Client", "My citizenship application was refused.", "may SİTızınship apliKAYşın woz riFYUUzd", "Vatandaşlık başvurum reddedildi."],
    ]),

  U("en_cit_28", 627, "C1", "🔄", "Başvuru Reddi ve İtiraz Süreci",
    "Gerekçeli ret, itiraz yolları ve süreler",
    VAT, "#8b5cf6",
    "📌 Passive modal: \"can be appealed\" — itiraz edilebilir.\nPhrasal verb: \"speed up\" — hızlandırmak.",
    [
      ["to reject an application", "riCEKT ın apliKAYşın", "başvuruyu reddetmek", "Olumsuz karardır."],
      ["reasoned refusal", "Rİİzınd riFYUuzıl", "gerekçeli ret", "Nedeni yazılıdır."],
      ["pre-trial appeal", "PREE-TRAYıl ıPİL", "dava öncesi itiraz", "Önce idareye yapılır."],
      ["deadline", "DEDlayn", "son tarih", "Kaçırılmamalıdır."],
      ["to restore a deadline", "riSTOR ı DEDlayn", "süreyi iade ettirmek", "Mahkeme yoluyla olur."],
      ["supervisory authority", "SUUpırvayzıri oTHORıti", "denetim mercii", "Üst itiraz yeridir."],
    ],
    [
      ["An unreasoned refusal can be appealed.", "Gerekçesiz ret itiraza açıktır."],
      ["A missed deadline can be restored by a court.", "Kaçırılan süre mahkemeyle iade ettirilebilir."],
      ["A pre-trial appeal speeds up the process.", "Dava öncesi itiraz süreci hızlandırır."],
    ],
    [
      ["Lawyer", "Did you receive a reasoned refusal?", "did yu riSİIV ı Rİİzınd riFYUuzıl", "Gerekçeli ret aldınız mı?"],
      ["Applicant", "Yes, the reason is an error in the documents.", "YES, di Rİİzın iz ın Eör in di DOKyuments", "Evet, neden belgelerdeki hata."],
      ["Lawyer", "We'll correct it and file a complaint.", "wil kırEKT it and FAIL ım kımPLEYNT", "Düzeltip şikâyet dilekçesi vereceğiz."],
    ]),

  U("en_cit_29", 628, "A2", "🧳", "Göç ve Göçmen Kelimeleri",
    "Göçmen, yabancı, yerel halk: temel göç kelimeleri",
    GOC, "#f59e0b",
    "📌 \"Where are you from?\" — neredensiniz?\n\"be new here\" — yeni burada olmak.",
    [
      ["immigrant", "IMıgrınt", "göçmen (gelen)", "Ülkeye yerleşmek için gelen."],
      ["emigrant", "EMıgrınt", "göçmen (giden)", "Ülkeden ayrılan kişidir."],
      ["relocation", "reliKEYşın", "taşınma", "Yeni yere yerleşmedir."],
      ["native language", "NEYtiv LENGvic", "ana dili", "Çocuklukta öğrenilen dil."],
      ["foreigner", "FORınır", "yabancı (uyruklu)", "Başka ülke vatandaşıdır."],
      ["local residents", "LOWkıl REZıdınts", "yerel halk", "O bölgede yaşayanlar."],
    ],
    [
      ["He is an immigrant: he came from another country.", "O göçmen: başka bir ülkeden geldi."],
      ["My native language is Turkish.", "Ana dilim Türkçe."],
      ["The local residents are very kind.", "Yerel halk çok iyi kalpli."],
    ],
    [
      ["Neighbour", "Where are you from?", "VEÖR ar yu FROM", "Neredensiniz?"],
      ["Immigrant", "From Turkey. I'm new here.", "from TÖRki. aym NYUU HİİR", "Türkiye'den. Yeni buradayım."],
      ["Neighbour", "Welcome to our city!", "VELkım tu AWİR SİTi", "Şehrimize hoş geldiniz!"],
    ]),

  U("en_cit_30", 629, "B2", "🕊️", "Sığınma Başvurusu",
    "Sığınma isteme, zulüm ve mülakat",
    GOC, "#f59e0b",
    "📌 Passive: \"was persecuted\" — zulüm gördü.\n\"because of + isim\": because of persecution — zulüm nedeniyle.",
    [
      ["asylum", "ıSAYlım", "sığınma", "Korunma hakkıdır."],
      ["to seek asylum", "SİIK ıSAYliм", "sığınma istemek", "Resmî başvurudur."],
      ["persecution", "pösıkYUUşın", "zulüm/takip", "Başvuru nedenidir."],
      ["refugee", "refyuCİİ", "mülteci", "Zorunlu göçmendir."],
      ["humanitarian status", "hyumenTEYriyın STADıs", "insani statü", "Koruma biçimidir."],
      ["interview with an officer", "INtırvyu wid ın OFısır", "memurla görüşme", "Başvurunun ana adımı."],
    ],
    [
      ["He sought asylum because of persecution.", "Zulüm nedeniyle sığınma istedi."],
      ["An asylum application is made at the border or inside the country.", "Sığınma başvurusu sınırda veya ülke içinde yapılır."],
      ["The officer conducts a detailed interview.", "Memur ayrıntılı bir görüşme yapar."],
    ],
    [
      ["Officer", "Why are you seeking asylum?", "WAY ar yu SİIKing ıSAYlım", "Neden sığınma istiyorsunuz?"],
      ["Applicant", "I was persecuted in my homeland.", "ay woz pösıkYUUtid in may HOWMlend", "Vatanımda zulüm gördüm."],
      ["Officer", "Tell me everything in detail.", "TEL mi EVriTHing in Dİİteyl", "Her şeyi ayrıntılı anlatın."],
    ]),

  U("en_cit_31", 630, "B2", "🛡️", "Mülteci Statüsü ve Haklar",
    "Mülteci statüsü: korunma, konut, sağlık ve yardım",
    GOC, "#f59e0b",
    "📌 \"the right TO + fiil/isim\" — ...hakkı.\n\"free for refugees\" — mülteciler için ücretsiz.",
    [
      ["refugee status", "refyuCİİ STADıs", "mülteci statüsü", "Uluslararası korumadır."],
      ["protection", "prıTEKşın", "korunma", "Temel haktır."],
      ["housing", "HAUzing", "konut/barınak", "İlk ihtiyaçtır."],
      ["benefit", "BENifit", "sosyal yardım", "Devlet desteğidir."],
      ["medical care", "MEDıkıl KEÖR", "sağlık yardımı", "Acil durumlarda zorunlu."],
      ["temporary placement", "TEMpıreri PLEYSmınt", "geçici barındırma", "İlk aşamada verilir."],
    ],
    [
      ["Refugee status gives the right to protection.", "Mülteci statüsü korunma hakkı verir."],
      ["The family received housing and benefits.", "Aile konut ve sosyal yardım aldı."],
      ["Medical care is free for refugees.", "Sağlık yardımı mülteciler için ücretsizdir."],
    ],
    [
      ["Social worker", "Here is your temporary placement.", "HİİR iz yör TEMpıreri PLEYSmınt", "İşte geçici barındırmanız."],
      ["Refugee", "Thank you. Can I work?", "tenk YU. KAN ay WÖRK", "Teşekkürler. Çalışabilir miyim?"],
      ["Social worker", "Yes, after you receive status.", "YES, AFtır yu riSİIV STADıs", "Evet, statü aldıktan sonra."],
    ]),

  U("en_cit_32", 631, "C1", "⚖️", "Sınır Dışı ve Yasal Duruş",
    "Sınır dışı etme, giriş yasağı ve hukuki mücadele",
    GOC, "#f59e0b",
    "📌 Passive modal: \"can be appealed\" — itiraz edilebilir.\n\"because of an overstayed visa\" — süresi aşılı vize nedeniyle.",
    [
      ["deportation", "dipörTEYşın", "sınır dışı etme", "Zorla çıkarılmadır."],
      ["removal", "riMUUvıl", "idari sınır dışı", "Mahkeme kararıyla olur."],
      ["entry ban", "ENtri BEN", "giriş yasağı", "Yıllarca sürebilir."],
      ["court decision", "KORT diSIJın", "mahkeme kararı", "İtiraz edilebilir."],
      ["immigration lawyer", "imiGREYşın LOYır", "göç hukuku avukatı", "Uzman desteğidir."],
      ["grounds", "GRAUNDZ", "gerekçeler", "Kararın dayanağıdır."],
    ],
    [
      ["A deportation order can be appealed in court.", "Sınır dışı kararına mahkemede itiraz edilebilir."],
      ["The entry ban lasts five years.", "Giriş yasağı beş yıl sürer."],
      ["The court will examine the grounds for removal.", "Mahkeme sınır dışı gerekçelerini inceleyecek."],
    ],
    [
      ["Lawyer", "Are you facing deportation?", "ar yu FEYsing dipörTEYşın", "Sınır dışı riski mi var?"],
      ["Client", "Yes, because of an overstayed visa.", "YES, bikoz ıv ın OvırSTEYd VİZı", "Evet, süresi aşılı vize nedeniyle."],
      ["Lawyer", "We'll file an appeal.", "wil FAIL ın ıPİL", "İtiraz dilekçesi vereceğiz."],
    ]),

  U("en_cit_33", 632, "A2", "👣", "Yeni Ülkeye İlk Adımlar",
    "Yeni ülkede ilk günler: yol sorma, komşular, market",
    GOC, "#f59e0b",
    "📌 Yönler: go straight — düz gidin, turn right — sağa dönün.\n\"show someone something\" — birine bir şeyi göstermek.",
    [
      ["first steps", "FÖRST STEPS", "ilk adımlar", "Yeni başlangıçtır."],
      ["city", "SİTi", "şehir", "Yeni yaşam alanıdır."],
      ["neighbours", "NEYbırz", "komşular", "İlk tanışılan kişiler."],
      ["groceries", "GROUsıriz", "market/erzak", "Günlük ihtiyaçtır."],
      ["the way", "dı WEY", "yol", "Şehri öğrenmekle başlar."],
      ["to ask the way", "ASK dı WEY", "yol sormak", "Yabancıdan istenir."],
    ],
    [
      ["The first steps in a new country are the hardest.", "Yeni ülkede ilk adımlar en zor olanlardır."],
      ["I asked a passer-by the way.", "Bir yayaya yol sordum."],
      ["My neighbours showed me the grocery store.", "Komşularım bana marketi gösterdi."],
    ],
    [
      ["Newcomer", "Excuse me, where is the grocery store?", "ikSKYUUZ mi, VEÖR iz di GROUsiri STOR", "Affedersiniz, market nerede?"],
      ["Passer-by", "Go straight, then turn right.", "GOW STRAYT, DEN TÖRN RAYT", "Düz gidin, sonra sağa dönün."],
      ["Newcomer", "Thank you very much!", "tenk yu VERi MAÇ", "Çok teşekkür ederim!"],
    ]),

  U("en_cit_34", 633, "B1", "🌉", "Kültür Şoku ve Entegrasyon",
    "Kültür şoku, gelenekler ve uyum süreci",
    GOC, "#f59e0b",
    "📌 \"at first\" — başta (karşıtı: over time — zamanla).\n\"feel like a stranger\" — kendini yabancı hissetmek.",
    [
      ["culture shock", "KALçı ŞOK", "kültür şoku", "Yeni kültürde yaşanır."],
      ["traditions", "trıDIşınz", "gelenekler", "Küçükten öğrenilir."],
      ["customs", "KAStımz", "örf ve adetler", "Toplum kurallarıdır."],
      ["adaptation", "adapTEYşın", "uyum", "Zamanla gerçekleşir."],
      ["to feel like a stranger", "FİL LAYK ı STREYncır", "kendini yabancı hissetmek", "Şokun belirtisidir."],
      ["over time", "Ouvır TAYM", "zamanla", "Her şey düzelir."],
    ],
    [
      ["Culture shock passes over time.", "Kültür şoku zamanla geçer."],
      ["I'm learning local traditions and customs.", "Yerel gelenekleri ve adetleri öğreniyorum."],
      ["At first I felt like a stranger.", "Başta kendimi yabancı hissettim."],
    ],
    [
      ["Friend", "Is it hard for you here?", "iz it HARD for yu HİİR", "Burada zorlanıyor musun?"],
      ["Immigrant", "At first yes, but it's better now.", "at FÖRST YES, bat its BEtır NAU", "Başta evet ama şimdi daha iyi."],
      ["Friend", "Everything will be fine over time.", "EVriTHing wil bi FAYN Ouvır TAYM", "Her şey zamanla iyi olacak."],
    ]),

  U("en_cit_35", 634, "B1", "🗒️", "İlk Günler: Kayıt İşlemleri",
    "Yeni gelenin listesi: kayıt, banka, SIM kart, sigorta",
    GOC, "#f59e0b",
    "📌 \"What's next?\" — sıradaki ne?\nPresent perfect: \"Have you registered yet?\" — kayıt oldunuz mu?",
    [
      ["to register", "REcistır", "kayıt olmak", "İlk resmî adımdır."],
      ["identification number", "aydentifiKEYşın NAMbır", "kimlik numarası", "Vergi/kimlik için verilir."],
      ["to open a bank account", "OWpın ı BENK ıKAUNT", "banka hesabı açmak", "Maaş/ödeme için gerekir."],
      ["SIM card", "SİM KARd", "SIM kart", "İletişim ilk ihtiyaçtır."],
      ["health insurance", "HELTH inŞUırans", "sağlık sigortası", "Devlet veya özel."],
      ["everything is in order", "EVriTHing iz in ORdır", "her şey tamam", "Hazır olma durumudur."],
    ],
    [
      ["First you need to register at your address.", "Önce adresinize kayıt olmanız gerekir."],
      ["I opened a bank account and bought a SIM card.", "Banka hesabı açtım ve SIM kart aldım."],
      ["Now all my documents are in order.", "Artık tüm belgelerim tamam."],
    ],
    [
      ["Adviser", "Have you registered yet?", "hev yu REcistırd YET", "Kayıt oldunuz mu?"],
      ["Newcomer", "Yes, yesterday. What's next?", "YES, YEStırdi. WOTS NEKST", "Evet, dün. Sıradaki ne?"],
      ["Adviser", "Open a bank account and get insurance.", "OWpın ı BENK ıKAUNT and GET inŞUırans", "Banka hesabı açın ve sigorta yaptırın."],
    ]),

  U("en_cit_36", 635, "B1", "🏫", "Dil Kursları ve Uyum Programları",
    "Ücretsiz dil kursları, seviye testi ve dersler",
    GOC, "#f59e0b",
    "📌 \"three times A week\" — haftada üç kez (tekrar kalıbı).\n\"free of charge\" — ücretsiz.",
    [
      ["language courses", "LENGvic KORSız", "dil kursları", "Belediye/devlet verir."],
      ["classes", "KLAAsız", "dersler", "Haftalık programı vardır."],
      ["free of charge", "FRİİ ıv CARC", "ücretsiz", "Uyum kurslarında olur."],
      ["level", "LEvil", "seviye", "A1'den başlar."],
      ["placement test", "PLEYSmınt TEST", "seviye testi", "Kayıt öncesi yapılır."],
      ["practice", "PRAKtis", "pratik/uygulama", "Konuşma geliştirir."],
    ],
    [
      ["The city offers free language courses.", "Belediye ücretsiz dil kursları sunuyor."],
      ["First you take a placement test.", "Önce seviye testine girersiniz."],
      ["Classes are three times a week.", "Dersler haftada üç kez."],
    ],
    [
      ["Administrator", "Would you like to join the courses?", "wud yu LAYK tu COYN di KORSız", "Kurslara katılmak ister misiniz?"],
      ["Student", "Yes. Are there evening classes?", "YES. ar DEÖR İİVning KLAAsız", "Evet. Akşam dersleri var mı?"],
      ["Administrator", "Yes, at seven, free of charge.", "YES, at SEvın, FRİİ ıv CARC", "Evet, yedide, ücretsiz."],
    ]),

  U("en_cit_37", 636, "B2", "👪", "Eş ve Çocuklar için İşlemler",
    "Aile belgeleri: apostil, çeviri, vasilik",
    GOC, "#f59e0b",
    "📌 Passive çoğul: \"are legalised\" — yasallaştırılır.\n\"for each document\" — her belge için.",
    [
      ["marital status", "MERıtıl STEYdıs", "medeni hâl", "Evli/bekâr bilgisidir."],
      ["apostille", "ıPOSİL", "apostil", "Uluslararası onaydır."],
      ["legalisation", "liigılıZEYşın", "yasallaştırma", "Yabancı belge onayı."],
      ["document translation", "DOKyument transLEYşın", "belge çevirisi", "Yetkili çevirmen yapar."],
      ["guardian", "GARdiyın", "vasi", "Çocuk için atanır."],
      ["underage children", "ANdırEYC CHILdrın", "reşit olmayan çocuklar", "18 yaş altıdır."],
    ],
    [
      ["Certificates are legalised through an apostille.", "Belgeler apostille ile yasallaştırılır."],
      ["The notary does document translations.", "Belge çevirisini noter yapar."],
      ["Copies of birth certificates are needed for the children.", "Çocuklar için doğum belgesi kopyaları gerekir."],
    ],
    [
      ["Officer", "Will the children come with you?", "wil di CHILdrın KAM wid yu", "Çocuklar sizinle mi gelecek?"],
      ["Parent", "Yes, here are their documents and translations.", "YES, HİİR ar DEÖR DOKyuments and transLEYşınz", "Evet, işte belgeleri ve çevirileri."],
      ["Officer", "You'll need an apostille for each document.", "yül NİID ın ıPOSİL for İİÇ DOKyument", "Her belge için apostil gerekecek."],
    ]),

  U("en_cit_38", 637, "B2", "💠", "Nitelikli Göçmen ve Mavi Kart",
    "Mavi kart, diploma denkliği ve nitelikli uzmanlık",
    GOC, "#f59e0b",
    "📌 Present perfect passive: \"has been recognised\" — tanındı.\n\"so\" — demek ki (sonuç bağlacı).",
    [
      ["qualified specialist", "KWOLifayd SPESHılıst", "nitelikli uzman", "Meslek sahibi göçmen."],
      ["blue card", "BLUU KARd", "mavi kart", "AB nitelikli göçmen kartı."],
      ["diploma recognition", "diPLOWma rekığNIŞın", "diploma denkliği", "Eşdeğerlik tanınması."],
      ["recognition", "rekığNIŞın", "tanınma/kabul", "Denklik sonucudur."],
      ["profession", "prıFEŞın", "meslek", "Uzmanlık alanıdır."],
      ["salary", "SALıri", "maaş", "Eşik alt sınırı vardır."],
    ],
    [
      ["The blue card is issued to qualified specialists.", "Mavi kart nitelikli uzmanlara verilir."],
      ["The diploma must go through recognition.", "Diplomanın denklik işleminden geçmesi gerekir."],
      ["A high salary is required for the card.", "Kart için yüksek maaş gerekir."],
    ],
    [
      ["Employee", "Has my diploma been recognised?", "haz may diPLOWma bin rekığNAIZd", "Diplomam tanındı mı?"],
      ["Clerk", "Yes, you are a qualified specialist.", "YES, yu ar ı KWOLifayd SPESHılıst", "Evet, nitelikli bir uzmansınız."],
      ["Employee", "So I can get a blue card.", "SO ay KAN GET ı BLUU KARd", "Demek mavi kart alabilirim."],
    ]),

  U("en_cit_39", 638, "B1", "🗺️", "Vatandaşlığa Giden Yol",
    "Yol haritası: aşamalar, sabır ve hedef",
    GOC, "#f59e0b",
    "📌 \"path to\" — ...yolu: path to citizenship.\n\"take + süre\": it takes years — yıllar sürer.",
    [
      ["path", "PAATH", "yol", "Uzun bir süreçtir."],
      ["stage", "STEYC", "aşama", "Her adım bir etaptır."],
      ["step by step", "STEP bay STEP", "adım adım", "Sabırla ilerlemektir."],
      ["preparation", "prepıREYşın", "hazırlık", "Belgelerle başlar."],
      ["patience", "PEYşıns", "sabır", "En gerekli şeydir."],
      ["goal", "GOWL", "hedef", "Vatandaşlıktır."],
    ],
    [
      ["The path to citizenship takes several years.", "Vatandaşlık yolu birkaç yıl sürer."],
      ["Move towards your goal step by step.", "Hedefinize adım adım ilerleyin."],
      ["The keys are patience and preparation.", "Anahtar sabır ve hazırlıktır."],
    ],
    [
      ["Adviser", "What is your goal?", "WOT iz yör GOWL", "Hedefiniz ne?"],
      ["Migrant", "To become a citizen of this country.", "tu biKAM ı SİTızın ıv dıs KANtri", "Bu ülkenin vatandaşı olmak."],
      ["Adviser", "A great goal. Let's start with the residence stage.", "ı GREYT GOWL. lets START wif dı REZıdans STEYC", "Harika bir hedef. İkamet aşamasıyla başlayalım."],
    ]),

  U("en_cit_40", 639, "B2", "⏳", "Uzun Süreli İkamet Yolu",
    "İkamet süresi: kesintisizlik ve yurt dışı çıkışları",
    GOC, "#f59e0b",
    "📌 Present perfect: \"Have you travelled abroad?\" — yurt dışına çıktınız mı?\n\"doesn't interrupt\" — bölemez (III. tekil olumsuz).",
    [
      ["long-term residence", "LONG-törm REZıdans", "uzun süreli ikamet", "Statünün temelidir."],
      ["to count the period", "KAUNT di Pİriyad", "süreyi saymak", "Gün gün hesaplanır."],
      ["absence", "EBsıns", "yokluk/dışarıda kalma", "Süreyi etkileyebilir."],
      ["to interrupt", "inırAPT", "bölmek/kesmek", "Uzun ayrılık yapar."],
      ["long-stay visa", "LONG-stey VİZı", "uzun süreli vize", "İlk adımdır."],
      ["status", "STEYdıs", "statü", "Hakları belirler."],
    ],
    [
      ["Long-term residence gives the right to status.", "Uzun süreli ikamet statü hakkı verir."],
      ["A long absence interrupts the period.", "Uzun süre ülkede olmamak süreyi böler."],
      ["A long-stay visa is the first step.", "Uzun süreli vize ilk adımdır."],
    ],
    [
      ["Inspector", "Have you travelled abroad in the last five years?", "hev yu TRAVıld ıBROD in di LAST FAYF YİRZ", "Son beş yılda yurt dışına çıktınız mı?"],
      ["Applicant", "Yes, for two months.", "YES, for TUU MANTHS", "Evet, iki aylığına."],
      ["Inspector", "That doesn't interrupt the period.", "dat DASınt inırAPT di Pİriyad", "Bu süreyi bölmez."],
    ]),

  U("en_cit_41", 640, "B1", "👶", "Doğum Yoluyla Vatandaşlık",
    "Doğumla vatandaşlık kazanımı ve işleyişi",
    DOGUM, "#ec4899",
    "📌 \"by birth\" — doğum yoluyla (by + yöntem).\nPassive: \"was born\" — doğdu.",
    [
      ["by birth", "bay BYÖRTH", "doğum yoluyla", "Kazanım türüdür."],
      ["newborn", "NYUUborn", "yenidoğan", "Kayıtla başlar."],
      ["to acquire citizenship", "ıkKWAYır SİTızınship", "vatandaşlık kazanmak", "Doğumla otomatiktir."],
      ["automatically", "otımETıkli", "otomatik olarak", "Başvuru gerektirmez."],
      ["parents", "PEÖrınts", "ebeveynler", "Statüyü belirler."],
      ["place of birth", "PLEYS ıv BYÖRTH", "doğum yeri", "Kuralarda önemlidir."],
    ],
    [
      ["A child acquires citizenship by birth.", "Çocuk doğumla vatandaşlık kazanır."],
      ["This right works automatically.", "Bu hak otomatik işler."],
      ["The place of birth affects citizenship.", "Doğum yeri vatandaşlığı etkiler."],
    ],
    [
      ["Parent", "Our child was born here.", "AWİR CHAYLD woz BORN HİİR", "Çocuğumuz burada doğdu."],
      ["Officer", "He or she gets citizenship by birth.", "hi or Şİİ GETS SİTızınship bay BYÖRTH", "Doğum yoluyla vatandaşlık alır."],
      ["Parent", "Which documents are needed?", "wiç DOKyuments ar Nİİdid", "Hangi belgeler gerekiyor?"],
    ]),

  U("en_cit_42", 641, "A2", "📜", "Doğum Belgesi ve Kayıt",
    "Doğum kaydı: hastane belgesi, nüfus müdürlüğü, isim",
    DOGUM, "#ec4899",
    "📌 Passive: \"is registered\" — kaydedilir.\nPresent perfect: \"we've brought\" — getirdik.",
    [
      ["hospital certificate", "HOSpıtıl sırTİFikıt", "hastane doğum belgesi", "Kayıt için gerekir."],
      ["maternity hospital", "mıTÖRnıti HOSpıtıl", "doğum hastanesi", "Belgeyi verir."],
      ["registry office", "REcistri OFis", "nüfus müdürlüğü", "Kayıt burada yapılır."],
      ["first name", "FÖRST NEYM", "ad", "Aile seçer."],
      ["last name", "LAST NEYM", "soyad", "Ebeveynden alınır."],
      ["to register a birth", "REcistır ı BÖRTH", "doğumu kaydetmek", "İlk yasal adımdır."],
    ],
    [
      ["A birth is registered at the registry office.", "Doğum nüfus müdürlüğünde kaydedilir."],
      ["The hospital certificate is needed for registration.", "Kayıt için hastane belgesi gerekir."],
      ["We chose a name for the baby.", "Bebek için bir isim seçtik."],
    ],
    [
      ["Mother", "Where do we register the birth?", "VEÖR du wi REcistır dı BÖRTH", "Doğumu nerede kaydederiz?"],
      ["Clerk", "At our department, take a ticket.", "at AWİR diPARTmınt, TEYK ı TİKit", "Bizim birimde, sıra numarası alın."],
      ["Mother", "Thanks, we've brought the hospital certificate.", "tenks, wiv BROHT di HOSpıtıl sırTİFikıt", "Teşekkürler, hastane belgesini getirdik."],
    ]),

  U("en_cit_43", 642, "B1", "👨‍👩‍👦", "Ana-Baba Vatandaşlığı ve Çocuk",
    "Ebeveyn statüsünün çocuğa etkisi",
    DOGUM, "#ec4899",
    "📌 \"both parents\" — her iki ebeveyn.\n\"through the mother/father\" — anne/baba tarafindan.",
    [
      ["both parents", "BOWTH PEÖrınts", "her iki ebeveyn", "Statü birlikte değerlendirilir."],
      ["through the mother", "THRUU di MADır", "anneden (taraf)", "Kan bağı yoludur."],
      ["through the father", "THRUU di FAADır", "babadan (taraf)", "Diğer kan yoludur."],
      ["parents' citizenship", "PEÖrınts SİTızınship", "ebeveynlerin vatandaşlığı", "Çocuğu belirler."],
      ["supplementary sheet", "SAPliMENTri ŞİIT", "belge ek yaprağı", "Vatandaşlık kanıtıdır."],
      ["official note", "ıFIşıl NOWT", "resmî kayıt (şerh)", "Belgeye işlenir."],
    ],
    [
      ["A child gets citizenship through the mother or the father.", "Çocuk vatandaşlığı anneden veya babadan alır."],
      ["The parents' citizenship is confirmed by passports.", "Ebeveyn vatandaşlığı pasaportlarla kanıtlanır."],
      ["An official note is made in the certificate.", "Belgeye resmî bir kayıt işlenir."],
    ],
    [
      ["Officer", "Who is a citizen — the mother or the father?", "HUİ iz ı SİTızın — dı MADır or dı FAADır", "Vatandaş kim — anne mi baba mı?"],
      ["Father", "Both parents are citizens.", "BOWTH PEÖrınts ar SİTızınz", "Her iki ebeveyn de vatandaş."],
      ["Officer", "Then the child is a citizen by birth.", "DEN dı CHAYLD iz ı SİTızın bay BYÖRTH", "O zaman çocuk doğumla vatandaş."],
    ]),

  U("en_cit_44", 643, "B2", "🌍", "Toprakta Doğma Hakkı (Jus Soli)",
    "Doğum yerine göre vatandaşlık ilkesi",
    DOGUM, "#ec4899",
    "📌 Kısmi olumsuzluk: \"not every state\" — her devlet değil.\n\"mean / means\" — demek olmak.",
    [
      ["jus soli", "cus SOHlay", "toprak hakkı (jus soli)", "Doğum yerine dayanır."],
      ["native-born", "NEYtiv-BORN", "doğumlu (yerli)", "O ülkede doğandır."],
      ["territory", "TERıtıri", "ülke toprağı", "İlkenin kapsamıdır."],
      ["principle", "PRİNsıpıl", "ilke", "Her ülkeninki farklıdır."],
      ["exception", "ikSEPşın", "istisna", "Kurallarda vardır."],
      ["state", "STEYT", "devlet", "İlkeyi belirler."],
    ],
    [
      ["Jus soli means citizenship by place of birth.", "Jus soli, doğum yerine göre vatandaşlık demektir."],
      ["Not every state recognises this principle.", "Her devlet bu ilkeyi tanımaz."],
      ["A native-born person is a citizen of the country.", "Ülkede doğan kişi o ülkenin vatandaşıdır."],
    ],
    [
      ["Student", "What is jus soli?", "WOT iz cus SOHlay", "Jus soli nedir?"],
      ["Teacher", "Citizenship by place of birth — the right of soil.", "SİTızınship bay PLEYS ıv BÖRTH — dı RAYT ıv SOYL", "Doğum yerine göre vatandaşlık — toprak hakkı."],
      ["Student", "Are there exceptions?", "ar DEÖR ikSEPşınz", "İstisnalar var mı?"],
    ]),

  U("en_cit_45", 644, "B2", "🩸", "Kan Bağı Hakkı (Jus Sanguinis)",
    "Soy bağıyla vatandaşlık: köken ve atalar",
    DOGUM, "#ec4899",
    "📌 \"a hundred years ago\" — yüz yıl önce (geçmişte süre).\n\"keep one's roots\" — köklerini korumak.",
    [
      ["jus sanguinis", "cus SAENGvinis", "kan bağı hakkı (jus sanguinis)", "Soyla geçer."],
      ["origin", "ORıcın", "köken/soy", "Belgelerle gösterilir."],
      ["ancestors", "ANsestırz", "atalar", "Aile geçmişidir."],
      ["heritage", "HERıtıc", "miras", "Kültürel bağdır."],
      ["generation", "cenıREYşın", "kuşak", "Soy zinciridir."],
      ["ethnic roots", "ETHnik RUUTS", "etnik kökler", "Köken statüsüdür."],
    ],
    [
      ["Jus sanguinis passes through origin.", "Kan bağı hakkı soyla geçer."],
      ["My ancestors lived here a hundred years ago.", "Atalarım yüz yıl önce burada yaşıyordu."],
      ["Every generation keeps its roots.", "Her kuşak köklerini korur."],
    ],
    [
      ["Applicant", "My ancestors were citizens.", "may ANsestırz wör SİTızınz", "Atalarım vatandaştı."],
      ["Lawyer", "Then the right of blood applies.", "DEN dı RAYT ıv BLAD ıPLAYZ", "O zaman kan bağı hakkı geçerli."],
      ["Applicant", "Which documents prove my origin?", "wiç DOKyuments PRUUV may ORıcın", "Hangi belgeler kökenimi kanıtlar?"],
    ]),

  U("en_cit_46", 645, "B2", "🤝", "Evlat Edinme ve Vatandaşlık",
    "Evlat edinme: mahkeme, çıkarın gözetilmesi, aile",
    DOGUM, "#ec4899",
    "📌 Passive: \"is formalised\" — resmîleştirilir.\nPossessive: the child's interests — çocuğun yararı.",
    [
      ["adoption", "ıDOPşın", "evlat edinme", "Mahkemeyle gerçekleşir."],
      ["adoptive parent", "ıDOPtiv PEÖrınt", "evlat edinen", "Başvuran taraftır."],
      ["foster parents", "FOStır PEÖrınts", "koruyucu ebeveyn", "Çocuğa aile verir."],
      ["court ruling", "KORT RUUling", "mahkeme kararı", "Sürecin sonucudur."],
      ["the child's interests", "dı CHAYLDZ INtırısts", "çocuğun yararı", "En üst unsurdur."],
      ["family", "FAMli", "aile", "Çocuğun hakkıdır."],
    ],
    [
      ["Adoption is formalised through a court.", "Evlat edinme mahkemeyle resmîleştirilir."],
      ["The court protects the child's interests.", "Mahkeme çocuğun yararını korur."],
      ["Foster parents give a child a family.", "Koruyucu ebeveynler çocuğa bir aile verir."],
    ],
    [
      ["Judge", "Do you understand the responsibility of adoption?", "du yu andırSTAND di risponsiBİLıti ıv ıDOPşın", "Evlat edinmenin sorumluluğunu anlıyor musunuz?"],
      ["Foster parent", "Yes, we are ready.", "YES, wi ar REDi", "Evet, hazırız."],
      ["Judge", "The ruling is made in the child's interests.", "dı RUUling iz MEYD in dı CHAYLDZ INtırısts", "Karar çocuğun yararına alındı."],
    ]),

  U("en_cit_47", 646, "B1", "📋", "Resmî Formlar ve Beyan Dili",
    "Form doldurma: alan, imza, zorunlu bölümler",
    RESMI, "#10b981",
    "📌 Emir kipi: fill in — doldurun, indicate — belirtin, add — ekleyin.\n\"marked with a star\" — yıldızla işaretli.",
    [
      ["form", "FORM", "form (kağıdı)", "Resmî evrakın kendisidir."],
      ["field", "FİILD", "form alanı", "Her kutucuk bir alandır."],
      ["to fill in", "FİL İN", "doldurmak", "Blok harflerle yapılır."],
      ["to indicate", "İNdiKEYt", "belirtmek", "Bilgiyi yazmaktır."],
      ["signature", "SIGNıçır", "imza", "Formun sonunda atılır."],
      ["date", "DEYT", "tarih", "Zorunlu alandır."],
    ],
    [
      ["Fill in the form in block letters.", "Formu blok harflerle doldurun."],
      ["Indicate the date and add your signature.", "Tarihi belirtin ve imzanızı ekleyin."],
      ["Fields marked with a star are required.", "Yıldızla işaretli alanlar zorunludur."],
    ],
    [
      ["Officer", "Why is this field empty?", "WAY iz dıs FİILD EMPti", "Bu alan neden boş?"],
      ["Client", "I didn't understand what to write there.", "ay DİDınt andırSTAND WOT tu RAYT DEÖR", "Oraya ne yazacağımı anlamadım."],
      ["Officer", "Indicate your address and the date.", "İNdiKEYt yör ıDRES and di DEYT", "Adresinizi ve tarihi yazın."],
    ]),

  U("en_cit_48", 647, "A2", "☎️", "Randevu, Sıra ve Telefon Görüşmesi",
    "Telefonla randevu: meşgul hat, geri arama",
    RESMI, "#10b981",
    "📌 \"the line was busy\" — hat meşguldü (geçmiş).\nPhrasal verb: \"call back\" — geri aramak.",
    [
      ["to call", "KOL", "telefon etmek", "İlk iletişim yoludur."],
      ["to make an appointment", "MEYK ın ıPOYNtmınt", "randevu almak", "Telefonla yapılır."],
      ["one moment", "WAN MOUmınt", "bir dakika", "Bekletme ifadesidir."],
      ["the line is busy", "dı LAYN iz BİZi", "hat meşgul", "Tekrar aramak gerekir."],
      ["to call back", "KOL BAK", "geri aramak", "Sık yaşanır."],
      ["available time", "ıVEYlıbıl TAYM", "müsait zaman", "Randevu buna alınır."],
    ],
    [
      ["I called the visa centre.", "Başvuru merkezini aradım."],
      ["The line was busy, so I called back.", "Hat meşguldü, bu yüzden geri aradım."],
      ["Book an appointment for an available time.", "Randevuyu müsait bir saate alın."],
    ],
    [
      ["Operator", "Hello, visa application centre.", "helOW, VİZı apliKAYşın SENtır", "Merhaba, vize başvuru merkezi."],
      ["Client", "Hello. I'd like to make an appointment.", "helOW. ayd LAYK tu MEYK ın ıPOYNtmınt", "Merhaba. Randevu almak istiyorum."],
      ["Operator", "One moment... There's a slot on Friday.", "WAN MOUmınt... DEÖRz ı SLOT on FRAYdey", "Bir dakika... Cuma günü uygun var."],
    ]),

  U("en_cit_49", 648, "A2", "📖", "Belge ve Terimler Sözlüğü",
    "Kopya, onay, çeviri, arşiv: resmî terimler",
    RESMI, "#10b981",
    "📌 \"an extract FROM the archive\" — arşivten örneğin -den eki.\nPassive modal: \"must be certified\" — onaylanmalı.",
    [
      ["copy", "KOUpi", "kopya", "Aslın ikizidir."],
      ["to certify", "SÖRtıfay", "onaylatmak", "Noter yapar."],
      ["translator", "transLEYtır", "çevirmen", "Yetkili olmalıdır."],
      ["official extract", "ıFIşıl EKStrakt", "resmî belge örneği", "Kayıttan çıkarılır."],
      ["archive", "ARkayv", "arşiv", "Eski kayıtlar buradadır."],
      ["validity period", "vıLİDıti Pİriyad", "geçerlilik süresi", "Belgede yazar."],
    ],
    [
      ["I need an official extract from the archive.", "Arşivten resmî bir belge örneği gerekiyor."],
      ["The copy must be certified by a notary.", "Kopya noter tarafından onaylanmalı."],
      ["Check the validity period of the document.", "Belgenin geçerlilik süresini kontrol edin."],
    ],
    [
      ["Client", "Can I certify a copy?", "KAN ay SÖRtıfay ı KOUpi", "Kopya onaylatabilir miyim?"],
      ["Notary", "Yes, show me the original.", "YES, ŞOW mi di ırİCınıl", "Evet, aslını gösterin."],
      ["Client", "Here, and check the validity period too.", "HİİR, and ÇEK di vıLİDıti Pİriyad TUU", "İşte, geçerlilik süresini de kontrol edin."],
    ]),

  U("en_cit_50", 649, "C1", "🎓", "Vatandaşlık Yolculuğu: Tüm Süreç",
    "Naturalizasyon: baştan sona tüm süreç bir arada",
    RESMI, "#10b981",
    "📌 \"from start to finish\" — baştan sona.\nGerund özne: \"meeting deadlines\" — sürelere uyum.",
    [
      ["naturalisation", "naçıralıZEYşın", "naturalizasyon", "Vatandaşlığa kabul süreci."],
      ["from start to finish", "from START tu Fİnish", "baştan sona", "Tüm yolculuğu anlatır."],
      ["meeting deadlines", "MİIting DEDlaynz", "sürelere uyum", "Başarının anahtarıdır."],
      ["final stage", "FAYnıl STEYC", "son aşama", "Yemin törenidir."],
      ["long-awaited", "LONG-WEYtid", "uzun zamân beklenen", "Gün sonunda gelir."],
      ["pride", "PRAYD", "gurur", "Yeni vatandaşın hissi."],
    ],
    [
      ["Naturalisation is a journey from start to finish.", "Naturalizasyon baştan sona bir yolculuktur."],
      ["The key to success is meeting deadlines.", "Başarının anahtarı sürelere uymaktır."],
      ["The long-awaited final stage is the oath.", "Uzun beklenen son aşama yemindir."],
    ],
    [
      ["Reporter", "How did you reach the end of the process?", "hau did yu RİİÇ di END ıv di PROUses", "Sürecin sonuna nasıl ulaştınız?"],
      ["Citizen", "Patience, documents and meeting deadlines.", "PEYşıns, DOKyuments and MİIting DEDlaynz", "Sabır, belgeler ve sürelere uyum."],
      ["Reporter", "How do you feel now?", "hau du yu FİL NAU", "Şimdi nasıl hissediyorsunuz?"],
      ["Citizen", "Pride. I'm a citizen now!", "PRAYD. aym ı SİTızın NAU", "Gurur. Artık vatandaşım!"],
    ]),
];
