// DilKoç © 2026 — Bu kaynak kod telif hakkıyla korunur. İzinsiz kopyalama,
// dağıtma ve türev çalışma üretme yasaktır (bkz. LICENSE).
// ============================================================================
// 🛂 CITIZENSHIP PACK — ENGLISH (3/4: units 51-75)
// Interview questions (10) + visa-passport deep dive (8) + migration (7)
// ============================================================================

import type { UnitModule } from '../../curriculumData';
import { makeCitUnit, type CitWord, type CitSent, type CitLine } from '../citizenship/makeCitUnit';

const U = (
  id: string, n: number, lv: UnitModule['levelGroup'], icon: string,
  title: string, desc: string, cat: string, color: string, grammar: string,
  words: CitWord[], sents: CitSent[], dlg: CitLine[],
): UnitModule => makeCitUnit({ id, unitNumber: n, level: lv, icon, title, desc, category: cat, color, grammar, words, sents, dlg });

const MUL = "Vatandaşlık Mülakatı";
const VIZE = "Vize & Pasaport";
const GOC = "Göç & Uyum";

export const EN_CIT_C: UnitModule[] = [
  U("en_cit_51", 650, "B1", "🎤", "Mülakat 1: Kişisel Sorular",
    "Ad, doğum yeri, adres: mülakatın ilk soruları",
    MUL, "#ef4444",
    "📌 \"What is your full name?\" — tam adınız nedir?\n\"I was born in…\" — ...de doğdum (passive geçmiş).",
    [
      ["What is your name?", "WOT iz yör NEYM", "adınız nedir?", "İlk soru her zaman budur."],
      ["surname", "SÖRneym", "soyad", "Resmî olarak sorulur."],
      ["date of birth", "DEYT ıv BÖRTH", "doğum tarihi", "Tam olarak söylenir."],
      ["place of birth", "PLEYS ıv BÖRTH", "doğum yeri", "Şehir/ülke olarak cevaplanır."],
      ["your address", "yör ıDRES", "adresiniz", "Kayıtlı adres sorulur."],
      ["marital status", "MERıtıl STEYdıs", "medeni hâl", "Evli/bekâr/boşanmış."],
    ],
    [
      ["— What is your name? — My name is Ahmet Kaya.", "— Adınız nedir? — Adım Ahmet Kaya."],
      ["— Where were you born? — I was born in Bursa.", "— Nerede doğdunuz? — Bursa'da doğdum."],
      ["— Your address? — 10 Lenin Street.", "— Adresiniz? — Lenin Caddesi 10."],
    ],
    [
      ["Officer", "Hello! What is your full name?", "helOW! WOT iz yör FUL NEYM", "Merhaba! Tam adınız nedir?"],
      ["Candidate", "My name is Ahmet Kaya.", "may NEYM iz Ahyét KAYa", "Adım Ahmet Kaya."],
      ["Officer", "Where and when were you born?", "VEÖR and VEN wör yu BORN", "Nerede ve ne zaman doğdunuz?"],
      ["Candidate", "I was born in Bursa in nineteen ninety-five.", "ay woz BORN in BURSa in nainTİN NİNti-FAYF", "1995'te Bursa'da doğdum."],
    ]),

  U("en_cit_52", 651, "B1", "👨‍👩‍👧", "Mülakat 2: Aile ve Çocuklar",
    "Aile bireyleri, çocuk sayısı, eş mesleği soruları",
    MUL, "#ef4444",
    "📌 \"How many children do you have?\" — kaç çocuğunuz var?\nPossessive: my husband's job — kocamın işi.",
    [
      ["How many children do you have?", "hau MENi CHILdrın du yu HEV", "kaç çocuğunuz var?", "Aile sorusunun merkezidir."],
      ["wife", "WAYF", "eş (karı)", "Erkek için: husband."],
      ["husband's profession", "HAZbındz prıFEŞın", "kocanın mesleği", "Eş bilgisi istenir."],
      ["school-age children", "SKUUL-EYC CHILdrın", "okul çağındaki çocuklar", "Kayıt sorusu yöneltir."],
      ["relatives here", "RElıtivz HİİR", "akrabalar burada", "Aile bağları sorulur."],
      ["grandchildren", "GRANçildrın", "torunlar", "Sorular geniş aileyi kapsar."],
    ],
    [
      ["— How many children do you have? — I have two.", "— Kaç çocuğunuz var? — İkim var."],
      ["My wife also works here.", "Eşim de burada çalışıyor."],
      ["My parents live in Turkey.", "Ailem Türkiye'de yaşıyor."],
    ],
    [
      ["Officer", "Are you married?", "ar yu MERıd", "Evli misiniz?"],
      ["Candidate", "Yes, I have two school-age children.", "YES, ay HEV TUU SKUUL-EYC CHILdrın", "Evet, okul çağında iki çocuğum var."],
      ["Officer", "What does your wife do?", "WOT daz yör WAYF DUU", "Eşiniz ne yapıyor?"],
      ["Candidate", "She is a teacher at a school.", "Şİİ iz ı Tİİçır at ı SKUUL", "O okulda öğretmen."],
    ]),

  U("en_cit_53", 652, "B2", "❓", "Mülakat 3: Neden Vatandaşlık?",
    "«Neden vatandaşlık istiyorsunuz?» sorusuna hazırlık",
    MUL, "#ef4444",
    "📌 \"because + cümle\" — çünkü (neden açıklaması).\n\"want to + fiil\": want to live and work here.",
    [
      ["Why do you want citizenship?", "WAY du yu WANT SİTızınship", "neden vatandaşlık istiyorsunuz?", "Ana sorudur; samimi cevap gerekir."],
      ["to live permanently", "tı LİV PÖRMınıntli", "kalıcı olarak yaşamak", "En kabul görür neden."],
      ["plans for the future", "PLANZ for dı FYUUçı", "gelecek planları", "Soru sonrası gelir."],
      ["to feel at home", "tı FİL at HOWM", "kendini evinde hissetmek", "Güçlü bir ifadedir."],
      ["connection with the country", "kınEKşın wid dı KANtri", "ülkeyle bağ", "Köklülük vurgulanır."],
      ["to contribute", "tı kanTRİByuut", "katkıda bulunmak", "Emek verme anlamındadır."],
    ],
    [
      ["I want to live and work here permanently.", "Kalıcı olarak burada yaşamak ve çalışmak istiyorum."],
      ["This country has become my second home.", "Bu ülke bana ikinci yurdum oldu."],
      ["I have a job, a home and friends here.", "Burada işim, evim ve arkadaşlarım var."],
    ],
    [
      ["Officer", "Why do you want to get citizenship?", "WAY du yu WANT tu GET SİTızınship", "Neden vatandaşlık almak istiyorsunuz?"],
      ["Candidate", "I've lived here for years; my job and family are here.", "ayv LİVD HİİR for YİRZ; may COB and FAMli ar HİİR", "Yıllardır buradayım; işim ve ailem burada."],
      ["Officer", "What are your plans for the future?", "WOT ar yör PLANZ for dı FYUUçı", "Gelecek planlarınız neler?"],
      ["Candidate", "I want to contribute to this country.", "ay WANT tu kanTRİByuut tu dıs KANtri", "Bu ülkeye katkıda bulunmak istiyorum."],
    ]),

  U("en_cit_54", 653, "B2", "💼", "Mülakat 4: İkamet ve Çalışma",
    "Nerede çalışıyorsun, gelirin ne: mali sorular",
    MUL, "#ef4444",
    "📌 \"What do you do (for a living)?\" — geçimini neyle sağlıyorsun?\n\"legally\" — yasal olarak (kayıtlı çalışma vurgusu).",
    [
      ["What do you do for a living?", "WOT du yu DUU for ı LİVing", "ne iş yapıyorsunuz?", "Klasik mülakat sorusu."],
      ["place of work", "PLEYS ıv WÖRK", "iş yeri", "Adresiyle sorulur."],
      ["official income", "ıFIşıl İNkam", "resmî gelir", "Kayıt dışı olmamalı."],
      ["work experience", "WÖRK ikSPIriyıns", "deneyim (kıdem)", "Süreyi kanıtlar."],
      ["to work legally", "WÖRK LİIgıli", "yasal çalışmak", "Önemli şarttır."],
      ["supporting document", "sıPORting DOKyument", "kanıtlama belgesi", "Gelir için istenir."],
    ],
    [
      ["— What do you do? — I'm an engineer at a factory.", "— Ne iş yapıyorsunuz? — Fabrikada mühendisim."],
      ["I've been working legally for five years.", "Beş yıldır yasal olarak çalışıyorum."],
      ["Income is confirmed by a certificate.", "Gelir belgeyle kanıtlanır."],
    ],
    [
      ["Officer", "What do you do for a living?", "WOT du yu DUU for ı LİVing", "Ne iş yapıyorsunuz?"],
      ["Candidate", "I'm an engineer; I work at a factory officially.", "aym ın ENcinir; ay WÖRK at ı FAKtri ıFIşılı", "Mühendisim; fabrikada resmî olarak çalışıyorum."],
      ["Officer", "Is your income confirmed by documents?", "iz yör İNkam kınFÖRmd bay DOKyuments", "Geliriniz belgelerle kanıtlanmış mı?"],
      ["Candidate", "Yes, here is a certificate for the year.", "YES, HİİR iz ı SÖRtıfıkıt for dı YIİR", "Evet, işte yıllık belge."],
    ]),

  U("en_cit_55", 654, "B2", "🏛️", "Mülakat 5: Ülke Bilgisi",
    "Başkent, bayrak, yönetim biçimi: bilgi soruları",
    MUL, "#ef4444",
    "📌 \"What is the capital of…?\" — ...in başkenti nedir?\n\"Who makes the laws?\" — yasaları kim yapar?",
    [
      ["capital", "KAPitıl", "başkent", "En klasik sorudur."],
      ["official language", "ıFIşıl LENGvic", "resmî dil", "Ülkenin dilidir."],
      ["president", "PREzidınt", "cumhurbaşkanı", "Yöneticidir."],
      ["parliament", "PARlımınt", "parlamento", "Yasama organıdır."],
      ["system of government", "SİStım ıv GAVınmınt", "yönetim biçimi", "Devlet yapısıdır."],
      ["population", "popyuLEYşın", "nüfus", "Temel bilgidir."],
    ],
    [
      ["— What is the capital? — The capital is Moscow.", "— Başkent neresi? — Başkent Moskova."],
      ["What is the official language of the country?", "Ülkenin resmî dili nedir?"],
      ["Parliament makes the laws.", "Parlamento yasaları yapar."],
    ],
    [
      ["Examiner", "What is the capital of this country?", "WOT iz di KAPitıl ıv dıs KANtri", "Bu ülkenin başkenti neresi?"],
      ["Candidate", "The capital is Moscow.", "dı KAPitıl iz MOSkow", "Başkent Moskova."],
      ["Examiner", "Who makes the laws?", "HUİ meyks di LOZ", "Yasaları kim yapar?"],
      ["Candidate", "Parliament makes the laws.", "PARlımınt meyks di LOZ", "Parlamento yasaları yapar."],
    ]),

  U("en_cit_56", 655, "B2", "📜", "Mülakat 6: Tarih Soruları",
    "Temel tarih bilgisi ve millî günler",
    MUL, "#ef4444",
    "📌 \"In what year…?\" — hangi yılda…?\n\"celebrate\" — kutlamak (bayramı).",
    [
      ["in what year", "in WOT YIİR", "hangi yılda", "Tarih sorusu kalıbı."],
      ["important event", "imPORtınt iVENT", "önemli olay", "Tarihte dönüm noktası."],
      ["independence", "indiPENdıns", "bağımsızlık", "Millî tarihin ana teması."],
      ["national holiday", "NAŞınıl HOLıdey", "ulusal bayram", "Sorulması olasıdır."],
      ["founder", "FAUNdır", "kurucu", "Tarihî kişiliktir."],
      ["the past", "dı PAST", "geçmiş", "Tarihin kendisidir."],
    ],
    [
      ["— When is the national holiday? — On the ninth of May.", "— Ulusal bayram ne zaman? — Dokuz Mayıs'ta."],
      ["The country gained independence long ago.", "Ülke bağımsızlığına uzun zaman önce kavuştu."],
      ["It was an important event in history.", "Bu tarihte önemli bir olaydı."],
    ],
    [
      ["Examiner", "When is the main national holiday?", "VEN iz di MEYN NAŞınıl HOLıdey", "Ana ulusal bayram ne zaman?"],
      ["Candidate", "On the twelfth of June.", "on di TWELFTH ıv CUUN", "On İki Haziran'da."],
      ["Examiner", "What happened on that day?", "WOT HEpınd on dat DEY", "O gün ne oldu?"],
      ["Candidate", "The country declared independence.", "dı KANtri diKLEÖRD indiPENdıns", "Ülke bağımsızlığını ilan etti."],
    ]),

  U("en_cit_57", 656, "B2", "⚖️", "Mülakat 7: Yasalar ve Yükümlülükler",
    "Vergi, seçme hakkı, yasalara uyum soruları",
    MUL, "#ef4444",
    "📌 \"must + fiil\" — ...meli: Citizens must pay taxes.\n\"the right to vote\" — oy verme hakkı.",
    [
      ["to pay taxes", "PEY TAKsiz", "vergi ödemek", "Vatandaşın birinci görevi."],
      ["to obey the law", "ıBEY dı LO", "yasaya uymak", "Mülakatta vurgulanır."],
      ["the right to vote", "dı RAYT tu VOWT", "oy hakkı", "Seçme hakkıdır."],
      ["military service", "MİLıtiri SÖRvis", "askerlik hizmeti", "Bazı ülkelerde vardır."],
      ["jury duty", "CUUri DYUuti", "jurü görevi", "Yurttaş görevidir."],
      ["civic duty", "Sİvik DYUuti", "yurttaşlık borcu", "Genel kavramdır."],
    ],
    [
      ["Citizens must pay taxes.", "Vatandaşlar vergi ödemek zorundadır."],
      ["Everyone has the right to vote.", "Herkesin oy hakkı vardır."],
      ["Obeying the law is a civic duty.", " yasaya uymak yurttaşlık borcudur."],
    ],
    [
      ["Examiner", "What are the duties of a citizen?", "WOT ar di DYUutiz ıv ı SİTızın", "Vatandaşın görevleri nelerdir?"],
      ["Candidate", "To pay taxes and obey the law.", "tu PEY TAKsiz and ıBEY dı LO", "Vergi ödemek ve yasaya uymak."],
      ["Examiner", "What is the right to vote?", "WOT iz dı RAYT tu VOWT", "Oy hakkı nedir?"],
      ["Candidate", "It's the right to choose the government.", "its dı RAYT tu ÇUUS dı GAVınmınt", "Yönetimi seçme hakkıdır."],
    ]),

  U("en_cit_58", 657, "B1", "👂", "Mülakat 8: Anlamadım, Tekrar Eder misiniz?",
    "Mülakatta yardım isteme kalıpları",
    MUL, "#ef4444",
    "📌 Kibar rica: \"Could you repeat that, please?\" — tekrar eder misiniz?\n\"more slowly\" — daha yavaş (zarf karşılaştırması).",
    [
      ["Could you repeat that, please?", "kud yu riPİIT dat, pliiz", "tekrar eder misiniz, lütfen", "En güvenli kalıptır."],
      ["Could you speak more slowly?", "kud yu SPIIK mor SLOUli", "daha yavaş konuşur musunuz?", "Rica kalıbıdır."],
      ["I didn't understand", "ay DİDınt andırSTAND", "anlamadım", "Durumu bildirir."],
      ["What does it mean?", "WOT daz it MİIN", "bu ne demek?", "Kelime sorma cesareti."],
      ["May I ask a question?", "may ay ASK ı KWESçın", "soru sorabilir miyim?", "İzin isteme kibarlığı."],
      ["How is it pronounced?", "hau iz it prınaUNst", "bu nasıl telaffuz edilir?", "Telaffuz yardımı ister."],
    ],
    [
      ["Could you repeat the question, please?", "Soruyu lütfen tekrar edebilir misiniz?"],
      ["Please speak a little more slowly.", "Lütfen biraz daha yavaş konuşun."],
      ["Sorry, I didn't understand the question.", "Affedersiniz, soruyu anlamadım."],
    ],
    [
      ["Candidate", "Sorry, could you repeat that, please?", "SORi, kud yu riPİIT dat, pliiz", "Affedersiniz, tekrar eder misiniz?"],
      ["Officer", "Of course. Where did you work before?", "ıv KORS. VEÖR did yu WÖRK biFOR", "Elbette. Daha önce nerede çalıştınız?"],
      ["Candidate", "Thank you! I worked in a hospital.", "tenk YU! ay WÖRKT in ı HOSPıtıl", "Teşekkürler! Hastanede çalıştım."],
    ]),

  U("en_cit_59", 658, "B2", "💬", "Mülakat 9: Cevap Kalıpları",
    "Tam cümle cevap verme ve net ifade teknikleri",
    MUL, "#ef4444",
    "📌 Tam cümle: sorudaki fiili cevapta tekrarla.\n\"Yes/No, + kısa açıklama\" — netlik kuralı.",
    [
      ["to answer fully", "ANsır FULi", "tam cevap vermek", "Mülakat tekniğidir."],
      ["confident answer", "KONfidınt ANsır", "kendinden emin cevap", "Ses tonuyla desteklenir."],
      ["short and clear", "ŞORT and KLİİR", "kısa ve net", "Mülakatın altın kuralı."],
      ["not to avoid", "NOT tu ıVOYD", "kaçamak cevap vermemek", "Güven oluşturur."],
      ["a real-life example", "ı RIİL-LAYF igZAMPıl", "yaşamdan örnek", "Cevabı güçlendirir."],
      ["honest answer", "ONıst ANsır", "dürüst cevap", "En doğru strateji."],
    ],
    [
      ["Answer briefly but fully.", "Kısa ama tam cevap verin."],
      ["Don't avoid the question.", "Sorudan kaçmayın."],
      ["An honest answer is better than a long one.", "Dürüst cevap, uzun açıklamadan iyidir."],
    ],
    [
      ["Examiner", "Have you ever broken the law?", "hev yu Eövır BROUkın dı LO", "Hiç yasa ihlali yaptınız mı?"],
      ["Candidate", "No, never. I always follow the rules.", "NOW, NEvır. ay OLVEYZ FOLow dı RUULZ", "Hayır, asla. Kurallara her zaman uyarım."],
      ["Examiner", "Thank you for the honest answer.", "tenk yu for di ONıst ANsır", "Dürüst cevabınız için teşekkürler."],
    ]),

  U("en_cit_60", 659, "B1", "🎭", "Mülakat 10: Tam Simülasyon",
    "Uçtan uca örnek mülakat diyaloğu",
    MUL, "#ef4444",
    "📌 Simülasyonda BÜTÜN kalıplar birlikte kullanılır.\nSıra: selam → kişisel bilgiler → neden → kapanış.",
    [
      ["come in", "KAM İN", "buyurun girin", "Mülakat davetidir."],
      ["have a seat", "HEV ı SİIT", "oturun", "Kibar yönlendirmedir."],
      ["do you have your documents?", "du yu HEV yör DOKyuments", "belgeleriniz yanınızda mı?", "Başlangıç kontrolüdür."],
      ["that's all", "dats OL", "hepsi bu kadar", "Bitiş ifadesidir."],
      ["wait for the decision", "WEYT for di diSIJın", "kararı bekleyin", "Kapanış cümlesidir."],
      ["thank you for your time", "tenk yu for yör TAYM", "zamanınız için teşekkürler", "Nazik vedadır."],
    ],
    [
      ["— Come in, have a seat. — Thank you.", "— Buyurun, oturun. — Teşekkürler."],
      ["Do you have your documents? Show me your passport.", "Belgeleriniz yanınızda mı? Pasaportunuzu gösterin."],
      ["Wait for the decision by mail.", "Kararı postayla bekleyin."],
    ],
    [
      ["Officer", "Hello! Come in and have a seat.", "helOW! KAM İN and HEV ı SİIT", "Merhaba! Buyurun ve oturun."],
      ["Candidate", "Hello! Thank you. I have my documents with me.", "helOW! tenk YU. ay HEV may DOKyuments wid Mİ", "Merhaba! Teşekkürler. Belgelerim yanımda."],
      ["Officer", "What is your name and where do you work?", "WOT iz yör NEYM and VEÖR du yu WÖRK", "Adınız nedir ve nerede çalışıyorsunuz?"],
      ["Candidate", "My name is Ahmet. I work as an engineer.", "may NEYM iz Ahyét. ay WÖRK az ın ENcinir", "Adım Ahmet. Mühendis olarak çalışıyorum."],
      ["Officer", "Thank you for your time. Wait for the decision.", "tenk yu for yör TAYM. WEYT for di diSIJın", "Zamanınız için teşekkürler. Kararı bekleyin."],
    ]),

  U("en_cit_61", 660, "A2", "🛫", "Havalimanı ve Uçuş Kelimeleri",
    "Check-in, kapı, uçuş ve bagaj kelimeleri",
    VIZE, "#0ea5e9",
    "📌 \"check in FOR the flight\" — uçuşa check-in yapmak.\n\"How many hours before\" — kaç saat önce.",
    [
      ["airport", "EÖRport", "havalimanı", "Yolculuğun başlangıcıdır."],
      ["flight", "FLAYT", "uçuş (sefer)", "Biletin kimliğidir."],
      ["boarding pass", "BORding PAS", "biniş kartı", "Check-in'de verilir."],
      ["gate", "GEYT", "kapı (gate)", "Tabela takip edilir."],
      ["boarding", "BORding", "biniş/uçuşa kabul", "Duyurularla başlar."],
      ["hand luggage", "HAND LAGıс", "kabin bagajı", "Sınırlı sayıda olur."],
    ],
    [
      ["Check-in opens two hours before the flight.", "Check-in uçuştan iki saat önce açılır."],
      ["Here is my boarding pass and passport.", "İşte biniş kartım ve pasaportum."],
      ["Boarding is at gate five.", "Biniş beş numaralı kapıda."],
    ],
    [
      ["Staff", "Your passport and ticket, please.", "yör PASport and TİKit, pliiz", "Pasaportunuzu ve biletinizi lütfen."],
      ["Passenger", "Here you are. One piece of hand luggage.", "hiİR yu AR. WAN PIİS ıv HAND LAGıс", "Buyurun. Bir kabin bagajım var."],
      ["Staff", "Here is your boarding pass. Gate five.", "hiİR iz yör BORding PAS. GAYT FAYF", "İşte biniş kartınız. Kapı beş."],
    ]),

  U("en_cit_62", 661, "B1", "💻", "E-Vize ve Online Başvuru",
    "İnternetten vize başvurusu: formül doldurma, yükleme, onay",
    VIZE, "#0ea5e9",
    "📌 \"upload\" — yüklemek (download karşıtı).\n\"confirmation by e-mail\" — e-posta onayı.",
    [
      ["e-visa", "İİ-VİZı", "e-vize", "Başvurusu tamamen onlinedır."],
      ["to fill in the online form", "FİL İN di ONlayn FORM", "online formu doldurmak", "Kağıt yoktur."],
      ["to upload a photo", "APlowd ı FOWtow", "fotoğraf yüklemek", "Formatına dikkat edilir."],
      ["confirmation e-mail", "konfırMEYşın İİ-meyl", "onay e-postası", "Yazılı kanıttır."],
      ["application status", "apliKAYşın STEYdıs", "başvuru durumu", "Siteden takip edilir."],
      ["to print out", "PRİNT AUT", "yazdırmak (çıktı)", "Sınırda istenebilir."],
    ],
    [
      ["I filled in the online form and uploaded a photo.", "Online formu doldurdum ve fotoğrafı yükledim."],
      ["The confirmation came by e-mail.", "Onay e-posta ile geldi."],
      ["You can check the application status online.", "Başvuru durumu internetten kontrol edilebilir."],
    ],
    [
      ["Client", "I've filled in the form. What's next?", "ayv FİLD İN dı FORM. WOTS NEKST", "Formu doldurdum. Sıra ne?"],
      ["Operator", "Upload a photo and pay the fee online.", "APlowd ı FOWtow and PEY dı FİY ONlayn", "Fotoğrafı yükleyin ve ücreti online ödeyin."],
      ["Client", "Done. Will the confirmation come by e-mail?", "DAN. wil di konfırMEYşın KAM bay İİ-meyl", "Tamam. Onay e-posta ile mi gelecek?"],
    ]),

  U("en_cit_63", 662, "B1", "💱", "Vize Ücretleri ve Para Birimleri",
    "Döviz, kur ve ödeme kelimeleri",
    VIZE, "#0ea5e9",
    "📌 \"exchange … for …\" — ...ı ...ye değiştirmek: exchange dollars for rubles.\n\"exchange rate\" — döviz kuru.",
    [
      ["fee in local currency", "FİY in LOWkıl KARınsi", "yerel para cinsinden ücret", "Konsolosluk belirler."],
      ["currency exchange", "KARınsi iksCEYNС", "döviz bozdurma", "Ofisten yapılır."],
      ["exchange rate", "iksCEYNС REYT", "döviz kuru", "Günlük değişir."],
      ["cash", "KAŞ", "nakit", "Bazı yerlerde istenir."],
      ["bank card", "BENK KARd", "banka kartı", "En yaygın ödeme."],
      ["receipt", "riSİYT", "fiş (dekont)", "Ödeme kanıtıdır."],
    ],
    [
      ["The fee is paid in local currency.", "Ücret yerel para birimiyle ödenir."],
      ["I exchanged dollars for rubles.", "Doları rublaya çevirdim."],
      ["Keep the payment receipt.", "Ödeme fişini saklayın."],
    ],
    [
      ["Client", "Can I pay by card?", "KAN ay PEY bay KARd", "Kartla ödeme mümkün mü?"],
      ["Cashier", "No, cash only, in local currency.", "NOW, KAŞ ONli, in LOWkıl KARınsi", "Hayır, yalnız nakit, yerel para ile."],
      ["Client", "OK, I'll exchange some currency first.", "OWKEY, ayl iksCEYNС sam KARınsi FÖRST", "Peki, önce döviz bozduracağım."],
    ]),

  U("en_cit_64", 663, "B2", "⏰", "Vize Süresi Aşımı",
    "Overstay: ceza, çıkış yasağı ve çözümler",
    VIZE, "#0ea5e9",
    "📌 \"overstay a visa\" — vize süresini aşmak.\n\"pay a fine\" — ceza ödemek.",
    [
      ["to overstay a visa", "ouvırSTEY ı VİZı", "vize süresini aşmak", "Ciddi sonuçları vardır."],
      ["fine", "FAYN", "ceza (para)", "Sınırda ödenir."],
      ["entry ban", "ENtri BEN", "giriş yasağı", "Uzun süreli olur."],
      ["to leave voluntarily", "LİİV VOLUNTarıli", "kendi isteğiyle çıkmak", "Cezayı hafifletir."],
      ["valid reason", "VALıd Rİİzın", "haklı neden", "Belgelenirse kabul edilir."],
      ["border service", "BORdır SÖRvis", "sınır idaresi", "Kararı veren makamdır."],
    ],
    [
      ["I overstayed my visa by five days.", "Vize süremi beş gün aştım."],
      ["You must pay a fine for overstaying.", "Süre aşımı için ceza ödemelisiniz."],
      ["He left voluntarily, without a ban.", "Giriş yasağı olmadan kendi isteğiyle çıktı."],
    ],
    [
      ["Officer", "You overstayed your visa by ten days.", "yu ouvırSTEYD yör VİZı bay TEN DEYZ", "Vize sürenizi on gün aştınız."],
      ["Traveller", "I had a valid reason — illness.", "ay HED ı VALıd Rİİzın — İLnıs", "Haklı nedenim vardı — hastalık."],
      ["Officer", "Show a doctor's note and pay the fine.", "ŞOW ı DOKtırz NOWT and PEY dı FAYN", "Doktor belgesini gösterin ve cezayı ödeyin."],
    ]),

  U("en_cit_65", 664, "B1", "🎖️", "Pasaport Türleri",
    "Umuma mahsus, diplomatik ve hizmet pasaportları",
    VIZE, "#0ea5e9",
    "📌 Sıfat tamlaması: DIPLOMATIC passport.\n\"designed for\" — ...için tasarlanmıştır.",
    [
      ["ordinary passport", "ORdıneri PASport", "umuma mahsus pasaport", "Standart pasaporttur."],
      ["diplomatic passport", "diploMEdik PASport", "diplomatik pasaport", "Diplomatlara verilir."],
      ["service passport", "SÖRvis PASport", "hizmet pasaportu", "Görevlilere verilir."],
      ["foreign-travel passport", "FORin-TRAVıl PASport", "yurt dışı pasaportu", "Seyahat belgesidir."],
      ["internal passport", "inTÖRnıl PASport", "iç pasaport (kimlik)", "Ülke içi kimliktir."],
      ["validity period", "vıLİDıti Pİriyad", "geçerlilik süresi", "Tür başına değişir."],
    ],
    [
      ["I have an ordinary foreign-travel passport.", "Umuma mahsus yurt dışı pasaportum var."],
      ["A diplomatic passport gives privileges.", "Diplomatik pasaport ayrıcalık verir."],
      ["The passport is valid for ten years.", "Pasaport on yıl geçerli."],
    ],
    [
      ["Passenger", "Is this an ordinary or a service passport?", "iz dıs ın ORdıneri or ı SÖRvis PASport", "Bu umuma mahsus mu hizmet pasaportu mu?"],
      ["Officer", "Ordinary, for all citizens.", "ORdıneri, for OL SİTızınz", "Umuma mahsus, tüm vatandaşlar için."],
      ["Passenger", "I see, thanks for the explanation.", "ay Sİİ, tenks for di eksplıNEYşın", "Anladım, açıklama için teşekkürler."],
    ]),

  U("en_cit_66", 665, "A2", "🚨", "Pasaport Kaybı ve Çalınma",
    "Kayıp pasaport: polis, tutanak, yeniden çıkarma",
    VIZE, "#0ea5e9",
    "📌 \"My passport was stolen\" — pasaportum çalındı (passive).\n\"report to the police\" — polise bildirmek.",
    [
      ["to lose a passport", "LUUZ ı PASport", "pasaportu kaybetmek", "Hemen bildirilir."],
      ["stolen passport", "STOWlın PASport", "çalınan pasaport", "Polis tutanağı gerekir."],
      ["police report", "pıLİİS riPÖRT", "polis tutanağı", "Kanıt belgesidir."],
      ["theft certificate", "THEFT sırTİFıkıt", "hırsızlık belgesi", "Konsolosluğa verilir."],
      ["embassy / consulate", "EMbısı / KONsulıt", "büyükelçilik / konsolosluk", "Yeni belgeyi verir."],
      ["emergency document", "iMÖRcınsi DOKyument", "acil durum belgesi", "Dönüş için yeterlidir."],
    ],
    [
      ["I lost my passport — what should I do?", "Pasaportumu kaybettim — ne yapmalıyım?"],
      ["First, report it to the police.", "Önce polise bildirin."],
      ["The consulate will issue an emergency document.", "Konsolosluk acil durum belgesi verecek."],
    ],
    [
      ["Tourist", "My passport was stolen!", "may PASport woz STOWlın", "Pasaportum çalındı!"],
      ["Police officer", "File a report — I'll give you a certificate.", "FAIL ı riPÖRT — ayl GİV yu ı sırTİFıkıt", "Tutanak yazın — size belge vereceğim."],
      ["Tourist", "Thank you! Then I'll go to the consulate.", "tenk YU! DEN ayl GOW tu di KONsulıt", "Teşekkürler! Sonra konsolosluğa gideceğim."],
    ]),

  U("en_cit_67", 666, "B1", "🧒", "Çocuklar için Pasaport ve Vize",
    "Çocuk belgeleri: veli izni ve ortak başvuru",
    VIZE, "#0ea5e9",
    "📌 \"parental consent\" — veli onayı (sıfat tamlaması).\n\"apply on behalf of\" — ...adına başvurmak.",
    [
      ["child's passport", "CHAYLDZ PASport", "çocuk pasaportu", "Ayrı belgedir."],
      ["birth certificate", "BYÖRTH sırTİFıkıt", "doğum belgesi", "Her işlemde istenir."],
      ["parental consent", "pıRENtıl kınSENT", "ebeveyn onayı", "Noter onaylıdır."],
      ["to apply on behalf of a child", "ıPLAY on biHALF ıv ı CHAYLD", "çocuk adına başvurmak", "Veli yapar."],
      ["minor", "MAYnır", "reşit olmayan", "Özel kurallara tabidir."],
      ["accompanied by", "ıkAMPınıd bay", "refakatinde", "Yalnız seyahatte kuraldır."],
    ],
    [
      ["A child needs a separate passport.", "Çocuğa ayrı pasaport gerekir."],
      ["The other parent's consent is needed to travel.", "Seyahat için diğer ebeveynin onayı gerekir."],
      ["We completed the documents together.", "Belgeleri birlikte tamamladık."],
    ],
    [
      ["Mother", "How do I get a passport for my child?", "hau du ay GET ı PASport for may CHAYLD", "Çocuğum için pasaport nasıl alırım?"],
      ["Officer", "You need the birth certificate and your consent.", "yu NİID di BYÖRTH sırTİFıkıt and yör kınSENT", "Doğum belgesi ve sizin onayınız gerekli."],
      ["Mother", "OK, we've brought everything.", "OWKEY, wiv BROHT EVriTHing", "Peki, her şeyi getirdik."],
    ]),

  U("en_cit_68", 667, "B2", "👪", "Özel Durumlar: Boşanma ve Velayet",
    "Boşanmış ailelerde çocuk vizesi ve velayet",
    VIZE, "#0ea5e9",
    "📌 \"after the divorce\" — boşanmadan sonra.\n\"custody ruling\" — velayet kararı.",
    [
      ["divorce", "diVORS", "boşanma", "Belgeyle kanıtlanır."],
      ["divorce certificate", "diVORS sırTİFıkıt", "boşanma belgesi", "Dosyada istenir."],
      ["custody", "KASTıdi", "velayet", "Mahkeme verir."],
      ["who the child lives with", "HUİ dı CHAYLD LİVZ wid", "çocuk kimle yaşıyor", "Temel sorudur."],
      ["right to take the child abroad", "RAYT tu TEYK dı CHAYLD ıBROD", "çocuğu yurt dışına çıkarma hakkı", "Onaya bağlıdır."],
      ["court decision", "KORT diSIJın", "mahkeme kararı", "Velayeti belirler."],
    ],
    [
      ["After the divorce, the mother has custody.", "Boşanmadan sonra velayet annede."],
      ["The father's consent is needed for the trip.", "Yolculuk için babanın onayı gerekir."],
      ["The court decision defines custody.", "Mahkeme kararı velayeti belirler."],
    ],
    [
      ["Mother", "I'm divorced; the child lives with me.", "aym diVORST; dı CHAYLD LİVZ wid Mİ", "Boşanmışım; çocuk benimle yaşıyor."],
      ["Officer", "Show the court decision on custody.", "ŞOW di KORT diSIJın on KASTıdi", "Velayet kararını gösterin."],
      ["Mother", "Here it is, and the father's consent to travel.", "HİİR it IZ, and di FAADırz kınSENT tu TRAVıl", "İşte, ve babanın seyahat onayı."],
    ]),

  U("en_cit_69", 668, "A2", "🏠", "Konut Kiralama ve Depozito",
    "Yeni ülkede ev tutma: depozito, komisyon, sözleşme",
    GOC, "#f59e0b",
    "📌 \"rent a flat FROM someone\" — birinden daire kiralamak.\n\"deposit\" — depozito (teminat).",
    [
      ["to rent a flat", "RENT ı FLAT", "daire kiralamak", "İlk ihtiyaçtır."],
      ["deposit", "dıPOZit", "depozito (teminat)", "Genelde bir kira bedelidir."],
      ["agency fee", "EYcınsi FİY", "komisyon (emlak)", "Emlakçıya ödenir."],
      ["tenancy agreement", "TENınsi ıGRİİmınt", "kira sözleşmesi", "İmzalanmadan ödeme yapılmaz."],
      ["utility bills", "yuTİLıti BİLZ", "aidat/faturalar", "Kiraya eklenebilir."],
      ["landlord", "LENDlord", "ev sahibi", "Anlaşmanın diğer tarafı."],
    ],
    [
      ["I rent a flat near my work.", "İş yerimin yakınında daire kiralıyorum."],
      ["The deposit is one month's rent.", "Depozito bir aylık kiradır."],
      ["We signed a one-year tenancy agreement.", "Bir yıllık kira sözleşmesi imzaladık."],
    ],
    [
      ["Tenant", "How much are the deposit and the fee?", "hau MAÇ ar di dıPOZIT and di FİY", "Depozito ve komisyon ne kadar?"],
      ["Agent", "Deposit — one month, fee — half a month.", "dıPOZIT — WAN MANTH, FİY — HAF ı MANTH", "Depozito bir kira, komisyon yarım."],
      ["Tenant", "OK, show me the agreement.", "OWKEY, ŞOW mi di ıGRİİmınt", "Peki, sözleşmeyi gösterin."],
    ]),

  U("en_cit_70", 669, "A2", "🩺", "Aile Hekimi ve Sağlık Sistemi",
    "Sağlık kaydı, aile hekimi ve randevu",
    GOC, "#f59e0b",
    "📌 \"make an appointment WITH a doctor\" — hekimle randevu almak.\n\"insurance policy\" — sigorta poliçesi.",
    [
      ["insurance policy", "inŞUırans POLısi", "sağlık poliçesi", "Devlet sigortasıdır."],
      ["family doctor", "FAMli DOKtır", "aile hekimi", "İlk başvuru noktasıdır."],
      ["to make an appointment", "MEYK ın ıPOYNtmınt", "randevu almak", "Telefonla veya online olur."],
      ["medical record", "MEDıkıl REkırd", "sağlık kartı/dosyası", "Kayıtla açılır."],
      ["referral", "riFÖRıl", "sevk", "Uzman için gereklidir."],
      ["emergency services", "iMÖRcınsi SÖRvisiz", "acil servis", "112 numarasıdır."],
    ],
    [
      ["First, get an insurance policy.", "Önce poliçe alın."],
      ["I made an appointment with the family doctor.", "Aile hekimine randevu aldım."],
      ["A referral is needed for a specialist.", "Uzman için sevk gerekiyor."],
    ],
    [
      ["Patient", "How do I get an insurance policy?", "hau du ay GET ın inŞUırans POLısi", "Poliçe nasıl alınır?"],
      ["Administrator", "With your passport and registration — at the insurance office.", "wid yör PASport and recısTREYşın — at di inŞUırans OFis", "Pasaport ve kayıtla — sigorta ofisinde."],
      ["Patient", "Thanks, I'll go tomorrow.", "tenks, ayl GOW tuMOROW", "Teşekkürler, yarın gideceğim."],
    ]),

  U("en_cit_71", 670, "B1", "🔍", "İş Bulma Yolları",
    "İş arama: ilan, CV, başvuru ve ön görüşme",
    GOC, "#f59e0b",
    "📌 \"apply FOR a job\" — işe başvurmak (for edatına dikkat).\n\"work experience\" — iş deneyimi (kıdem).",
    [
      ["to look for a job", "LUUK for ı COB", "iş aramak", "İlk adımdır."],
      ["to apply for a job", "ıPLAY for ı COB", "işe başvurmak", "Online yapılır."],
      ["CV (resume)", "sİİ-Vİİ", "CV (özgeçmiş)", "Güncel tutulur."],
      ["work experience", "WÖRK ikSPIriyıns", "iş deneyimi", "İlanda şart olarak yazar."],
      ["job interview", "COB INtırvyu", "iş görüşmesi", "Davetle gelir."],
      ["probation period", "prıBEYşın Pİriyad", "deneme süresi", "Genelde 3 aydır."],
    ],
    [
      ["I'm looking for a job in my field.", "Uzmanlık alanımda iş arıyorum."],
      ["Send your CV for this job opening.", "Bu ilana CV'nizi gönderin."],
      ["The probation period is three months.", "Deneme süresi üç ay."],
    ],
    [
      ["Applicant", "I applied for the cook position.", "ay ıPLAYD for di KUK pıZİşın", "Aşçı pozisyonuna başvurdum."],
      ["Employer", "What work experience do you have?", "WOT WÖRK ikSPIriyıns du yu HEV", "Ne kadar deneyiminiz var?"],
      ["Applicant", "Five years in a restaurant.", "FAYF YİRZ in ı REStırant", "Restoranda beş yıl."],
    ]),

  U("en_cit_72", 671, "A2", "🚌", "Toplu Taşıma ve Ulaşım Kartı",
    "Metro, otobüs ve ulaşım kartı dolumu",
    GOC, "#f59e0b",
    "📌 \"top up the card\" — kart yüklemek (phrasal verb).\n\"a single trip\" — tek yolculuk (biniş).",
    [
      ["transport card", "TRANSport KARd", "ulaşım kartı", "Dolumla çalışır."],
      ["to top up the card", "TOP AP di KARd", "kart yüklemek", "Kasada veya uygulamada."],
      ["a single trip", "ı SİNGıl TRİP", "tek yolculuk (biniş)", "Tek biniştir."],
      ["metro", "MEtro", "metro", "En hızlı yoldur."],
      ["bus stop", "BAS STOP", "durak", "Biniş noktasıdır."],
      ["last stop", "LAST STOP", "son durak", "Hattın bitişidir."],
    ],
    [
      ["Top up the card at the desk or in the app.", "Kartı gişede veya uygulamada doldurun."],
      ["A single trip costs fifty rubles.", "Tek yolculuk elli ruble."],
      ["This is not the last stop.", "Bu son durak değil."],
    ],
    [
      ["Passenger", "How do I top up the transport card?", "hau du ay TOP AP di TRANSport KARd", "Ulaşım kartı nasıl yüklenir?"],
      ["Cashier", "At the desk or in the mobile app.", "at di DESK or in di MOUbayl AP", "Gişede veya mobil uygulamada."],
      ["Passenger", "Thanks, I'll top up ten trips.", "tenks, ayl TOP AP TEN TRİPS", "Teşekkürler, on yolculuk yükleyeceğim."],
    ]),

  U("en_cit_73", 672, "B1", "🏫", "Okul ve Çocukların Eğitimi",
    "Okul kaydı, dil desteği ve veli toplantıları",
    GOC, "#f59e0b",
    "📌 \"enrol a child IN a school\" — çocuğu okula kaydettirmek.\n\"parent-teacher meeting\" — veli toplantısı.",
    [
      ["school enrolment", "SKUUL inROLmınt", "okul kaydı", "Belgeyle yapılır."],
      ["required documents", "riKWAYırd DOKyuments", "gerekli belgeler", "Listesi okulda asılıdır."],
      ["adaptation classes", "adapTEYşın KLAAsız", "uyum dersleri", "Yeni gelenler içindir."],
      ["parent-teacher meeting", "PEÖrınt-Tİİçır MİIting", "veli toplantısı", "Düzenli yapılır."],
      ["grades", "GREYDZ", "notlar (karne)", "Dönem sonunda verilir."],
      ["teacher", "Tİİçır", "öğretmen", "İlk iletişim kişisidir."],
    ],
    [
      ["We enrolled our son in the first grade.", "Oğlumuzu birinci sınıfa kaydettirdik."],
      ["Registration documents are needed for enrolment.", "Kayıt için ikamet belgeleri gerekli."],
      ["The parent-teacher meeting is on Thursday.", "Veli toplantısı Perşembe günü."],
    ],
    [
      ["Parent", "How do I enrol my child in school?", "hau du ay inROL may CHAYLD in SKUUL", "Çocuğumu okula nasıl kaydettiririm?"],
      ["Head teacher", "Bring the documents: passport, registration, birth certificate.", "BRING di DOKyuments: PASport, recısTREYşın, BYÖRTH sırTİFıkıt", "Belgeleri getirin: pasaport, kayıt, doğum belgesi."],
      ["Parent", "Thank you, we'll prepare everything.", "tenk YU, wil priPEÖR EVriTHing", "Teşekkürler, her şeyi hazırlayacağız."],
    ]),

  U("en_cit_74", 673, "B1", "🧾", "Vergi Numarası ve Vergiler",
    "Vergi kimlik numarası alma ve temel vergi kelimeleri",
    GOC, "#f59e0b",
    "📌 \"income tax ON salary\" — maaştan gelir vergisi.\n\"file a tax return\" — beyanname vermek.",
    [
      ["tax identification number", "TAKS aydentifiKEYşın NAMbır", "vergi kimlik numarası", "Her işlemde istenir."],
      ["to get a tax number", "GET ı TAKS NAMbır", "vergi numarası almak", "Vergi dairesinden alınır."],
      ["tax", "TAKS", "vergi", "Yurttaş görevidir."],
      ["tax return", "TAKS riTÖRN", "vergi beyannamesi", "Yılda bir verilir."],
      ["tax deduction", "TAKS dıDAKşın", "vergi indirimi", "Bazı giderler için olur."],
      ["income tax", "İNkam TAKS", "gelir vergisi", "Maaştan kesilir."],
    ],
    [
      ["A tax number is needed for work and the bank.", "Vergi numarası iş ve banka için gerekir."],
      ["Income tax is deducted from your salary.", "Gelir vergisi maaştan kesilir."],
      ["The tax return is filed once a year.", "Beyanname yılda bir verilir."],
    ],
    [
      ["Migrant", "Where can I get a tax number?", "VEÖR KAN ay GET ı TAKS NAMbır", "Vergi numarası nereden alınır?"],
      ["Inspector", "At the tax office, with your passport.", "at di TAKS OFis, wid yör PASport", "Vergi dairesinden, pasaportla."],
      ["Migrant", "Thanks, I'll get it tomorrow.", "tenks, ayl GET it tuMOROW", "Teşekkürler, yarın alacağım."],
    ]),

  U("en_cit_75", 674, "A2", "🛒", "Market Alışverişi ve Fiyatlar",
    "Market kelimeleri: fiyat sorusu, ödeme, poşet",
    GOC, "#f59e0b",
    "📌 \"How much is / are…?\" — tekil / çoğul fiyat sorusu.\n\"without a bag\" — poşetsiz (çevre kuralı).",
    [
      ["grocery store", "GROUsiri STOR", "market", "Günlük alışveriş yeridir."],
      ["How much is it?", "hau MAÇ iz it", "ne kadar (fiyat)?", "Temel soru kalıbı."],
      ["discount", "DİSkaunt", "indirim", "Etikette yazılıdır."],
      ["at the checkout", "at di ÇEKaut", "kasada", "Ödeme noktasıdır."],
      ["plastic bag", "PLAStik BAG", "poşet", "Ücretlidir."],
      ["cash or card?", "KAŞ or KARd", "nakit mi kart mı?", "Kasa sorusudur."],
    ],
    [
      ["How much is this cheese?", "Bu peynir ne kadar?"],
      ["At the checkout they asked: cash or card?", "Kasada sordular: nakit mi kart mı?"],
      ["Bags cost extra; without a bag it's free.", "Poşet ücretli; poşetsiz ücretsiz."],
    ],
    [
      ["Shopper", "How much is this bread?", "hau MAÇ iz dıs BRED", "Bu ekmek ne kadar?"],
      ["Seller", "Thirty rubles. That's thirty, please.", "THÖRti RUUblz. dats THÖRti, pliiz", "Otuz ruble. Otuz lütfen."],
      ["Shopper", "I'll pay by card, without a bag.", "ayl PEY bay KARD, wifAUT ı BAG", "Kartla ödeyeceğim, poşet istemiyorum."],
    ]),
];
