import type { CheckpointStory, StoryLine, StoryNewWord } from '../../storyModule/types';

export const EN_STORY_CAST: { name: string; emoji: string; desc: string }[] = [
  { name: 'Claire', emoji: '📋', desc: 'Modern Family: Pritchett-Dunphy ailesini bir arada tutmaya çalışan planlı anne.' },
  { name: 'Phil', emoji: '🏠', desc: 'Modern Family: iyimser baba, emlakçı ve hevesli sihirbaz.' },
  { name: 'Jay', emoji: '🧱', desc: 'Modern Family: sert görünen ama ailesini önemseyen aile büyüğü.' },
  { name: 'Gloria', emoji: '🌟', desc: 'Modern Family: açık sözlü, enerjik ve koruyucu anne.' },
  { name: 'Mitchell & Cameron', emoji: '👨‍👨‍👧', desc: 'Modern Family: farklı karakterleriyle Lily’yi büyüten çift.' },
  { name: 'Ted', emoji: '☂️', desc: 'How I Met Your Mother: aşkı ve anlamı arayan mimar-anlatıcı.' },
  { name: 'Marshall, Lily & Barney', emoji: '🍻', desc: 'How I Met Your Mother: Ted’in hikâyelerini yönlendiren yakın arkadaşları.' },
];

type Level = NonNullable<CheckpointStory['levelId']>;
type Spec = { id:string; kind:CheckpointStory['kind']; checkpoint:number|null; unitFrom:number; unitTo:number; levelId?:Level; nextLevelId?:Level; show:'Modern Family'|'How I Met Your Mother'; episode:string; titleTr:string; frame:string; icon:string; color:string; lines:StoryLine[]; words:StoryNewWord[]; points:{text:string;hint:string;keys:string[][]}[] };
const L=(speaker:string,ru:string,tr:string,narrator=false):StoryLine=>({speaker,ru,reading:ru,tr,...(narrator?{narrator:true}:{})});
const W=(ru:string,tr:string,note:string):StoryNewWord=>({ru,reading:ru,tr,note});
function S(s:Spec):CheckpointStory{return {id:s.id,kind:s.kind,checkpoint:s.checkpoint,unitFrom:s.unitFrom,unitTo:s.unitTo,...(s.levelId?{levelId:s.levelId}:{}),...(s.nextLevelId?{nextLevelId:s.nextLevelId}:{}),titleRu:`${s.show} — ${s.episode}`,titleTr:s.titleTr,framingTr:`${s.show} dizisinin ${s.frame} Bu kısa öğrenme metni bölüm olayından uyarlanmıştır; özgün dizi repliklerini kopyalamaz.`,icon:s.icon,color:s.color,paragraphs:s.lines,newWords:s.words,keyPoints:s.points.map((p,i)=>({id:`${s.id}_k${i+1}`,textTr:p.text,hintTr:p.hint,keywordGroups:p.keys})),misleading:[]};}

export const EN_STORIES: CheckpointStory[] = [
 S({id:'story_lf_a1',kind:'levelFinal',checkpoint:null,unitFrom:1,unitTo:8,levelId:'A1',nextLevelId:'A2',show:'Modern Family',episode:'Pilot (S1E1)',titleTr:'Modern Family — Pilot: Aileyle Tanış',frame:'pilot bölümünden: üç aile kolu kendini tanıtır ve sonunda tek bir geniş aile olduklarını görürüz.',icon:'👨‍👩‍👧‍👦',color:'#22c55e',lines:[
  L('Narrator','This is one family with three homes.','Bu, üç evde yaşayan tek bir ailedir.',true),L('Phil','Hi, I am Phil. Claire is my wife.','Merhaba, ben Phil. Claire benim eşim.'),L('Claire','We have three children: Haley, Alex, and Luke.','Üç çocuğumuz var: Haley, Alex ve Luke.'),L('Gloria','Jay is my husband, and Manny is my son.','Jay benim eşim, Manny de oğlum.'),L('Mitchell','Cameron and I have a daughter. Her name is Lily.','Cameron ve benim bir kızımız var. Adı Lily.'),L('Jay','Different homes, same family.','Farklı evler, aynı aile.')],words:[W('daughter','kız evlat','Aile üyesi.'),W('husband','koca / eş','Erkek eş.'),W('different','farklı','Aynı olmayan.')],points:[{text:'Phil ile Claire üç çocuklarını tanıtır.',hint:'Kaç çocukları var?',keys:[['phil','claire'],['üç','3','çocuk']]},{text:'Mitchell ile Cameron kızları Lily’yi aileye getirir.',hint:'Kızlarının adı ne?',keys:[['mitchell','cameron'],['lily']]},{text:'Üç ayrı evin tek bir geniş aile olduğu anlaşılır.',hint:'Pilotun ana fikri ne?',keys:[['üç','ev'],['tek','aile']]}]}),

 S({id:'story_cp1',kind:'checkpoint',checkpoint:1,unitFrom:1,unitTo:10,show:'Modern Family',episode:'Coal Digger (S1E5)',titleTr:'Modern Family — Coal Digger: Aile Barışı',frame:'Coal Digger bölümünden: aile buluşmasındaki kırıcı bir söz Claire ile Gloria arasında gerilim yaratır.',icon:'🤝',color:'#38bdf8',lines:[L('Claire','I said something rude, and Gloria heard it.','Kaba bir şey söyledim ve Gloria bunu duydu.'),L('Phil','Then apologize without explaining it away.','O zaman bahane üretmeden özür dile.'),L('Claire','Gloria, I judged you before I knew you. I am sorry.','Gloria, seni tanımadan yargıladım. Özür dilerim.'),L('Gloria','I was angry, but I want this family to work.','Kızgındım ama bu ailenin yürümesini istiyorum.'),L('Jay','Good. Now can we finish the game?','Güzel. Şimdi maçı bitirebilir miyiz?')],words:[W('rude','kaba','Kırıcı davranış.'),W('judge','yargılamak','Yeterince tanımadan karar vermek.'),W('apologize','özür dilemek','Hata için af istemek.')],points:[{text:'Claire’in kaba sözü Gloria’yı incitir.',hint:'Gerilim neden çıktı?',keys:[['claire'],['kaba','gloria']]},{text:'Phil, Claire’e bahane üretmeden özür dilemesini söyler.',hint:'Phil’in tavsiyesi ne?',keys:[['phil'],['özür','bahane']]},{text:'Gloria kızgın olsa da ailenin yürümesini istediğini söyler.',hint:'Gloria neyi seçti?',keys:[['gloria'],['aile','barış']]}]}),

 S({id:'story_lf_a2',kind:'levelFinal',checkpoint:null,unitFrom:9,unitTo:16,levelId:'A2',nextLevelId:'B1',show:'Modern Family',episode:'Fizbo (S1E9)',titleTr:'Modern Family — Fizbo: Luke’un Doğum Günü',frame:'Fizbo bölümünden: Luke’un büyük doğum günü planı, palyaço ve aksiliklerle kontrolden çıkar.',icon:'🤡',color:'#f59e0b',lines:[L('Claire','We planned too many activities for one party.','Tek bir parti için çok fazla etkinlik planladık.'),L('Cameron','Fizbo is not an activity. He is an experience.','Fizbo bir etkinlik değil. O bir deneyim.'),L('Phil','I am not afraid of clowns. I just prefer more distance.','Palyaçolardan korkmuyorum. Sadece biraz daha uzak olmayı tercih ediyorum.'),L('Luke','This is the best birthday ever!','Bu şimdiye kadarki en iyi doğum günü!'),L('Claire','Nothing went as planned, but Luke is happy.','Hiçbir şey planlandığı gibi gitmedi ama Luke mutlu.')],words:[W('activity','etkinlik','Partide yapılan şey.'),W('distance','mesafe','İki şey arasındaki uzaklık.'),W('as planned','planlandığı gibi','Plana uygun biçimde.')],points:[{text:'Claire parti için fazla etkinlik planladıklarını fark eder.',hint:'Planın sorunu neydi?',keys:[['claire'],['fazla','etkinlik']]},{text:'Cameron palyaço Fizbo olarak partiye gelir.',hint:'Palyaço kimdi?',keys:[['cameron'],['fizbo','palyaço']]},{text:'Aksiliklere rağmen Luke doğum gününden çok memnun kalır.',hint:'Luke nasıl hissetti?',keys:[['luke'],['mutlu','en iyi']]}]}),

 S({id:'story_cp2',kind:'checkpoint',checkpoint:2,unitFrom:11,unitTo:20,show:'How I Met Your Mother',episode:'Pilot (S1E1)',titleTr:'HIMYM — Pilot: İlk Randevu',frame:'pilot bölümünden: Ted, Robin’le tanışınca geleceği fazla hızlı düşünür; arkadaşları ona anı yaşamasını hatırlatır.',icon:'🍽️',color:'#8b5cf6',lines:[L('Ted','I met Robin at the bar, and I asked her to dinner.','Robin’le barda tanıştım ve onu yemeğe davet ettim.'),L('Marshall','That sounds good. Just do not plan the wedding tonight.','Kulağa iyi geliyor. Yalnız düğünü bu gece planlama.'),L('Robin','I like you, Ted, but we just met.','Senden hoşlandım Ted ama daha yeni tanıştık.'),L('Ted','You are right. I moved too fast.','Haklısın. Çok hızlı davrandım.'),L('Narrator Ted','That night did not end the story. It started a friendship.','O gece hikâyeyi bitirmedi; bir arkadaşlığı başlattı.',true)],words:[W('move too fast','çok hızlı ilerlemek','İlişkide acele etmek.'),W('just met','daha yeni tanıştık','Yeni tanışmayı vurgular.'),W('friendship','arkadaşlık','Dostluk ilişkisi.')],points:[{text:'Ted Robin’le barda tanışıp onu yemeğe davet eder.',hint:'Ted kimi davet etti?',keys:[['ted'],['robin','yemek']]},{text:'Robin daha yeni tanıştıkları için Ted’in yavaşlamasını ister.',hint:'Robin neden temkinli?',keys:[['yeni','tanış'],['yavaş','hızlı']]},{text:'Gece romantik sonuçtan çok bir arkadaşlığın başlangıcı olur.',hint:'Ne başladı?',keys:[['arkadaşlık'],['başlangıç']]}]}),

 S({id:'story_lf_b1',kind:'levelFinal',checkpoint:null,unitFrom:17,unitTo:24,levelId:'B1',nextLevelId:'B2',show:'Modern Family',episode:'Caught in the Act (S2E13)',titleTr:'Modern Family — Caught in the Act: Zamanlama Felaketi',frame:'Caught in the Act bölümünden: çocukların hazırladığı yıldönümü sürprizi son derece uygunsuz bir anda gelir.',icon:'🚪',color:'#ef4444',lines:[L('Haley','We wanted to surprise Mom and Dad with breakfast.','Annemle babama kahvaltıyla sürpriz yapmak istedik.'),L('Alex','Instead, we opened a door we should not have opened.','Onun yerine açmamamız gereken bir kapıyı açtık.'),L('Luke','Can we all agree to forget the last ten seconds?','Son on saniyeyi unutma konusunda anlaşabilir miyiz?'),L('Claire','They are avoiding us. We need to talk normally.','Bizden kaçıyorlar. Normal biçimde konuşmalıyız.'),L('Phil','Or we could move to another country.','Ya da başka bir ülkeye taşınabiliriz.'),L('Narrator','The surprise failed, but honest embarrassment slowly repaired the family routine.','Sürpriz başarısız oldu ama dürüstçe paylaşılan utanç aile düzenini yavaşça onardı.',true)],words:[W('avoid','kaçınmak','Biriyle karşılaşmamaya çalışmak.'),W('embarrassment','utanç','Mahcup olma duygusu.'),W('repair','onarmak','İlişkiyi düzeltmek.')],points:[{text:'Çocuklar yıldönümü kahvaltısı sürprizi hazırlarken uygunsuz bir ana denk gelir.',hint:'Sürpriz neden bozuldu?',keys:[['kahvaltı','sürpriz'],['uygunsuz','kapı']]},{text:'Çocuklar ebeveynlerinden kaçmaya başlar.',hint:'Olaydan sonra ne yaptılar?',keys:[['çocuk'],['kaçın','kaç']]},{text:'Aile utancı dürüstçe kabul ederek normal düzenine dönmeye çalışır.',hint:'Sorun nasıl onarıldı?',keys:[['dürüst'],['utanç','normal']]}]}),

 S({id:'story_cp3',kind:'checkpoint',checkpoint:3,unitFrom:21,unitTo:30,show:'Modern Family',episode:'Dude Ranch (S3E1)',titleTr:'Modern Family — Dude Ranch: Aile Tatili',frame:'Dude Ranch bölümünden: geniş aile bir çiftlik tatilinde korkuları, değişim ve büyümeyle yüzleşir.',icon:'🐎',color:'#f97316',lines:[L('Jay','A family vacation should be relaxing. Why is everyone arguing?','Aile tatili dinlendirici olmalı. Neden herkes tartışıyor?'),L('Gloria','Because a new place does not erase old problems.','Çünkü yeni bir yer eski sorunları silmez.'),L('Dylan','I need to tell Haley that my future may take me far away.','Haley’ye geleceğimin beni uzaklara götürebileceğini söylemeliyim.'),L('Haley','I do not like the news, but I want the truth.','Bu haberi sevmiyorum ama gerçeği istiyorum.'),L('Phil','Maybe adventure means having the difficult conversation.','Belki macera, zor konuşmayı yapabilmektir.')],words:[W('erase','silmek','Bir sorunu yok etmek.'),W('far away','çok uzağa','Uzak mesafe.'),W('difficult conversation','zor konuşma','Duygusal ve ciddi konuşma.')],points:[{text:'Aile tatilinde eski sorunlar yeniden ortaya çıkar.',hint:'Yeni yer sorunları sildi mi?',keys:[['tatil','çiftlik'],['eski','sorun']]},{text:'Dylan geleceğinin onu uzağa götürebileceğini Haley’ye söylemek zorundadır.',hint:'Dylan’ın haberi ne?',keys:[['dylan'],['uzak','gelecek']]},{text:'Phil maceranın bazen zor bir konuşmayı yapmak olduğunu söyler.',hint:'Phil macerayı nasıl tanımlar?',keys:[['phil'],['zor','konuşma']]}]}),

 S({id:'story_lf_b2',kind:'levelFinal',checkpoint:null,unitFrom:25,unitTo:32,levelId:'B2',nextLevelId:'C1/C2',show:'Modern Family',episode:'Disneyland (S3E22)',titleTr:'Modern Family — Disneyland: Beklenti ve Gerçeklik',frame:'Disneyland bölümünden: aile, herkes için kusursuz gün yaratmaya çalışırken farklı ihtiyaçları uzlaştırır.',icon:'🎢',color:'#06b6d4',lines:[L('Claire','If we follow the schedule, everyone can enjoy the day.','Programa uyarsak herkes günün tadını çıkarabilir.'),L('Phil','A perfect schedule cannot predict fear, heat, or tired children.','Kusursuz program korkuyu, sıcağı ya da yorulan çocukları öngöremez.'),L('Jay','I brought better shoes. Experience is not glamorous, but it works.','Daha iyi ayakkabı getirdim. Deneyim gösterişli değildir ama işe yarar.'),L('Gloria','Manny does not need a plan for his feelings. He needs time.','Manny’nin duyguları için plana değil zamana ihtiyacı var.'),L('Claire','Then we change the plan. The goal is the family, not the timetable.','O halde planı değiştiririz. Amaç çizelge değil, ailedir.')],words:[W('predict','öngörmek','Önceden tahmin etmek.'),W('glamorous','gösterişli','Çekici ve etkileyici görünen.'),W('timetable','zaman çizelgesi','Planlanmış saatler bütünü.')],points:[{text:'Claire herkes için ayrıntılı bir program yapar.',hint:'Claire ne hazırladı?',keys:[['claire'],['program','çizelge']]},{text:'Beklenmedik korku, sıcak ve yorgunluk programı bozar.',hint:'Planı ne bozdu?',keys:[['korku','sıcak','yorgun'],['plan']]},{text:'Claire asıl amacın çizelge değil aile olduğunu kabul edip planı değiştirir.',hint:'Öncelik ne oldu?',keys:[['aile'],['plan','değiştir']]}]}),

 S({id:'story_cp4',kind:'checkpoint',checkpoint:4,unitFrom:31,unitTo:40,show:'How I Met Your Mother',episode:'Slap Bet (S2E9)',titleTr:'HIMYM — Slap Bet: Geçmişin Sırrı',frame:'Slap Bet bölümünden: Robin’in geçmişi hakkındaki sır, grubun yanlış varsayımları ve aceleci bahsiyle büyür.',icon:'📼',color:'#a855f7',lines:[L('Barney','Robin has a secret. I am sure my theory is correct.','Robin’in bir sırrı var. Teorimin doğru olduğundan eminim.'),L('Marshall','Then let us make a bet, but the rules must be clear.','O zaman bahis yapalım ama kurallar açık olmalı.'),L('Ted','Maybe we should ask Robin instead of inventing stories.','Belki hikâyeler uydurmak yerine Robin’e sormalıyız.'),L('Robin','I was a teenage pop singer in Canada. That is the secret.','Kanada’da genç bir pop şarkıcısıydım. Sır bu.'),L('Lily','A wrong assumption does not become true because it is funny.','Yanlış bir varsayım komik diye doğru olmaz.')],words:[W('bet','bahis','Sonuca dair iddia.'),W('assumption','varsayım','Kanıtsız kabul.'),W('instead of','yerine','Alternatif belirtir.')],points:[{text:'Barney Robin’in sırrı hakkında kanıtsız bir teori kurar.',hint:'Teoriyi kim kurdu?',keys:[['barney'],['teori','sır']]},{text:'Ted hikâye uydurmak yerine Robin’e sormayı önerir.',hint:'Ted’in çözümü ne?',keys:[['ted'],['robin','sor']]},{text:'Robin geçmişte Kanada’da genç bir pop şarkıcısı olduğunu açıklar.',hint:'Gerçek sır neydi?',keys:[['kanada'],['pop','şarkıcı']]}]}),

 S({id:'story_lf_c1',kind:'levelFinal',checkpoint:null,unitFrom:33,unitTo:48,levelId:'C1/C2',nextLevelId:'C1/C2',show:'Modern Family',episode:'Connection Lost (S6E16)',titleTr:'Modern Family — Connection Lost: Ekrandaki İpuçları',frame:'Connection Lost bölümünden: Claire, havaalanındaki dizüstü bilgisayarından Haley’ye ulaşmaya çalışırken dijital izleri yanlış yorumlar. Bu bölüm dizinin finali değildir.',icon:'💻',color:'#0ea5e9',lines:[L('Claire','Haley is not answering, and every new message seems to confirm my worst fear.','Haley cevap vermiyor ve her yeni mesaj en kötü korkumu doğrular gibi görünüyor.'),L('Phil','A collection of clues is not the same as the full context.','Bir ipucu koleksiyonu bağlamın tamamıyla aynı şey değildir.'),L('Alex','Mom, you are connecting facts that may be unrelated.','Anne, belki de ilgisiz gerçekleri birbirine bağlıyorsun.'),L('Claire','I thought speed gave me certainty. It only gave my anxiety more material.','Hızın bana kesinlik verdiğini sandım. Oysa yalnızca kaygıma daha fazla malzeme verdi.'),L('Haley','I was asleep at home. You could have waited before building a whole disaster.','Evde uyuyordum. Koca bir felaket kurmadan önce bekleyebilirdin.'),L('Narrator','The family reconnects when evidence is placed back into human context.','Kanıt yeniden insani bağlamına yerleştirildiğinde aile tekrar bağ kurar.',true)],words:[W('certainty','kesinlik','Şüphe bulunmaması.'),W('unrelated','ilgisiz','Aralarında bağ olmayan.'),W('context','bağlam','Bilginin anlamını belirleyen çevre.')],points:[{text:'Claire, Haley cevap vermeyince dijital ipuçlarından en kötü sonucu çıkarır.',hint:'Claire neden panikledi?',keys:[['claire'],['haley','cevap','ipucu']]},{text:'Phil ile Alex ipuçlarının tam bağlam olmadığını ve ilgisiz olabileceğini söyler.',hint:'Ailenin uyarısı neydi?',keys:[['phil','alex'],['bağlam','ilgisiz']]},{text:'Haley’nin evde uyuduğu anlaşılır; Claire hızın kesinlik değil kaygı ürettiğini fark eder.',hint:'Gerçekte ne olmuştu?',keys:[['haley'],['ev','uyu']]},{text:'Sonuç, dijital kanıtların insani bağlam içinde değerlendirilmesi gerektiğidir.',hint:'Bölümün ileri seviye fikri ne?',keys:[['dijital','kanıt'],['insan','bağlam']]}]}),
];
