// ============================================================================
// 🇬🇧 İNGİLİZCE MÜFREDATI — C1 + C1/C2 ÜNİTELERİ (33-48)
// ============================================================================

import type { EnRawUnit } from './unitsA';

export const EN_UNITS_C: EnRawUnit[] = [
  // ==========================================================================
  // C1 — ÜNİTE 33-40
  // ==========================================================================
  {
    id: 'en_mod_c1_33',
    unitNumber: 33,
    levelGroup: 'C1',
    title: 'Akademik Yazma & Söylem',
    description: 'Makale dili: bağlaçlar, atıf ve tutarlı argüman kurma',
    category: 'Akademik',
    color: '#0891b2',
    icon: '✍️',
    grammarExplain: `📌 AKADEMİK BAĞLAÇLAR:
1. Ekleme: "Furthermore, ..." / "Moreover, ..." — bir argümanın üzerine koyar.
2. Zıtlık: "Nevertheless, ..." / "However, ..." / "Whereas X is ..., Y is ...".
3. Sonuç: "Thus, ..." / "Consequently, ..." — daha resmi than "so".
4. Atıf: "Smith (2020) argues that..." / "According to recent research, ..." — intihal yapmamak için vazgeçilmez.`,
    words: [
      ['furthermore', 'FERdırmor', 'ayrıca, üstelik', 'Cümle başı + virgül; "and" den çok daha resmi.'],
      ['nevertheless', 'nevırdeLES', 'buna rağmen', '"However"un smokin giymiş hâli.'],
      ['whereas', 'UERez', 'oysa ki', 'İki zıttı tek cümlede karşılaştırır.'],
      ['thus', 'DAS', 'böylece, dolayısıyla', 'Akademik sonucların kısa yolu.'],
      ['cite', 'SAYT', 'atıf yapmak, kaynak göstermek', '"site" (mekân) ile yazımı karıştırma!'],
      ['outline', 'AUTlayn', 'taslak; özetlemek', '"outline your argument" önce taslak çıkar.'],
      ['draft', 'DRAF T', 'taslak yazmak; taslak', '"the first draft" her zaman kötüdür, normaldir.'],
      ['coherent', 'kouHIRınt', 'tutarlı, bağlantılı', 'İyi metnin ölçütü: coherent argument.'],
      ['peer review', 'PIIR riVYU', 'hakem değerlendirmesi', 'Bilimsel yayınların kalite kapısı.'],
      ['empirical', 'emPIRikıl', 'ampirik, gözleme dayalı', '"empirical evidence" = deneysel kanıt.'],
    ],
    sentences: [
      ['The results are limited; nevertheless, they support the hypothesis.', 'Sonuçlar sınırlıdır; buna rağmen hipotezi desteklemektedir.'],
      ['Whereas earlier studies focused on adults, ours includes children.', 'Önceki çalışmalar yetişkinlere odaklanırken, bizimki çocukları da kapsıyor.'],
      ['Furthermore, the data were collected over ten years.', 'Ayrıca veriler on yıl boyunca toplandı.'],
      ['You must cite every source you use.', 'Kullandığın her kaynağı atıfla belirtmelisin.'],
    ],
    sceneTitle: 'The Thesis Supervisor',
    sceneContext: 'Anna, tez danışmanından geri bildirim alıyor.',
    dialogue: [
      ['Supervisor', 'Your draft is coherent, but the argument needs sharper evidence.', 'yor DRAF T İZ kouHIRınt, bat di ARgyumınt NIIDS ŞARPır EVıdıns.', 'Taslağın tutarlı ama argüman daha keskin kanıt istiyor.'],
      ['Anna', 'I plan to add the empirical study from last year.', 'ay PLAN tu ED di emPIRikıl SADı from LAST YIR.', 'Geçen yılki ampirik çalışmayı eklemeyi planlıyorum.'],
      ['Supervisor', 'Good. Furthermore, you should cite the Oxford paper directly.', 'GUD. FERdırmor, yu ŞUD SAYT di OKSfırd PEYpır diREKTli.', 'İyi. Ayrıca Oxford makalesini doğrudan atıflamalısın.'],
      ['Anna', 'I will. Whereas most authors focus on results, I also discuss the limits.', 'ay UİL. UERez MOUST O-tırz FOKUS on riZALTS, ay OSO disKAS di LIMits.', 'Yapacağım. Çoğu yazar sonuçlara odaklanırken ben sınırlandırmaları da tartışacağım.'],
      ['Supervisor', 'Excellent. Send the next draft for peer review, then.', 'EKsılent. SEND di NEKS DRAF T for PIIR riVYU, DEN.', 'Mükemmel. O zaman bir sonraki taslağı hakem değerlendirmesine gönder.'],
    ],
  },
  {
    id: 'en_mod_c1_34',
    unitNumber: 34,
    levelGroup: 'C1',
    title: 'Deyimler (Idioms)',
    description: 'Gerçek İngilizcenin boyası: kalıplaşmış deyimler',
    category: 'İfadeler',
    color: '#f97316',
    icon: '🧩',
    grammarExplain: `📌 DEYİMLER NASIL ÖĞRENİLİR:
1. Deyimler KELİME KELİME çevrilmez: "piece of cake" = pasta parçası DEĞİL, "çok kolay" demektir.
2. Deyimlerde dilbilgisel değişiklik yapılmaz: "kick the bucket" (ölmek) asla "kick the buckets" olmaz.
3. Kayıt seviyesi önemli: bazıları samimi ("hit the books"), bazıları nötr ("a blessing in disguise").`,
    words: [
      ['a piece of cake', 'e PIIS ıv KEYK', 'çok kolay bir iş', '"The exam was a piece of cake!"'],
      ['break the ice', 'BREYK di AYS', 'buzları eritmek', 'Sohbete ilk adımı atmak.'],
      ['hit the books', 'HIT di BUKS', 'ders çalışmaya koyulmak', 'Sınav öncesi klasik tabir.'],
      ['under the weather', 'ANdır di UEDır', 'keyifsiz, hasta gibi', '"I feel under the weather today."'],
      ['once in a blue moon', 'UANS in e BLU MUN', 'çok nadiren', 'Ayda yılda bir yapılan şeyler için.'],
      ['spill the beans', 'SPIL di BIINZ', 'sırışı vermek', 'Planı/makyajı açık etmek.'],
      ['cost an arm and a leg', 'KOST en ARM end e LEG', 'pahalıya patlamak', '"That phone cost an arm and a leg."'],
      ['the ball is in your court', 'de BOL İZ in yor KORT', 'top sende, karar senin', 'Sıra sende mesajı verir.'],
      ['bite the bullet', 'BAYT di BULıt', 'dişini sıkıp katlanmak', 'Zor işi göğüslemek.'],
      ['beat around the bush', 'BIIT eRAUND di BUŞ', 'dolambaçlı konuşmak', 'Konuya girmemek; "Stop beating around the bush!"'],
    ],
    sentences: [
      ['The interview was a piece of cake after all that preparation.', 'Bütün o hazırlıktan sonra görüşme çocuk oyuncağıydı.'],
      ['He beat around the bush for an hour before asking for money.', 'Para istemeden önce bir saat dolandı durdu.'],
      ['I only see my cousins once in a blue moon.', 'Kuzenlerimi çok nadiren görürüm.'],
      ['Stop beating around the bush and tell me the truth.', 'Dolanıp durma ve bana gerçeği söyle.'],
    ],
    sceneTitle: 'Idioms in the Wild',
    sceneContext: 'Mark, Anna\'ya iş görüşmesini anlatırken deyimlere boğuluyor.',
    dialogue: [
      ['Anna', 'How was the interview? You look stressed.', 'Hau UOS di INtırvyu? yu LUK STREST.', 'Görüşme nasıldı? Stresli görünüyorsun.'],
      ['Mark', 'Honestly? I was under the weather, and the questions were not a piece of cake.', 'ONistli? ay UOS ANdır di UEDır, end di KUESçınz UER NOT e PIIS ıv KEYK.', 'Dürüst olayım mı? Keyifsizdim ve sorular çocuk oyuncağı değildi.'],
      ['Anna', 'Come on, stop beating around the bush. Did you get the job?', 'KAM ON, STOP BIITing eRAUND di BUŞ. DID yu GET di CAB?', 'Hadi, dolanıp durma. İşi aldın mı?'],
      ['Mark', 'They said the ball is in my court — I have until Friday to decide.', 'DEY sed de BOL İZ in may KORT — ay HEV ontil FRAYdey tu diSAYD.', 'Top bende dediler — Cuma\'ya kadar karar verme hakkım var.'],
      ['Anna', 'Wow! That promotion must cost an arm and a leg in effort, but it is worth it.', 'UAU! det prımOUşın MAS KOST en ARM end e LEG in EFırt, bat İT İZ UORD İT.', 'Vay! O terfi emek olarak kolunu bacağını mal etmiş olmalı ama buna değer.'],
    ],
  },
  {
    id: 'en_mod_c1_35',
    unitNumber: 35,
    levelGroup: 'C1',
    title: 'Üslup & Nüans (Register)',
    description: 'Resmi ve gündelik eş anlamlılar: doğru kelime, doğru yer',
    category: 'Üslup',
    color: '#8b5cf6',
    icon: '🎩',
    grammarExplain: `📌 KAYIT SEVİYESİ (REGISTER):
1. Aynı anlam, iki kutu: resmi "purchase" ↔ gündelik "buy"; resmi "commence" ↔ gündelik "start".
2. Yanlış kutu kullanmak komik ya da kaba durur: arkadaşına "I require assistance" demek robot gibidir.
3. E-posta/mülakat/yazılı sınav = resmi; arkadaş/parti/mesaj = gündelik.`,
    words: [
      ['purchase', 'PERçıs', 'satın almak (resmi)', 'Gündelik: buy. Sözleşme ve faturalarda.'],
      ['commence', 'kıMENS', 'başlamak (resmi)', 'Gündelik: start. Tören ve resmi metinlerde.'],
      ['assistance', 'eSIStıns', 'yardım (resmi)', 'Gündelik: help. Müşteri hizmetlerinin gözdesi.'],
      ['inquire', 'inkUAYır', 'sormak, sorgulamak (resmi)', 'Gündelik: ask. "Enquire" İngiliz yazımı.'],
      ['terminate', 'TERmıneyt', 'sona erdirmek (resmi)', 'Gündelik: end/finish. Sözleşme dili.'],
      ['endeavour', 'enDEVır', 'çabalamak; çaba (resmi)', 'Gündelik: try. ABD yazımı: endeavor.'],
      ['require', 'rikUAYır', 'gerektirmek, ihtiyaç duymak', 'Gündelik: need. "This job requires patience."'],
      ['inform', 'inFORM', 'bildirmek, haber vermek', 'Gündelik: tell. "Please inform us in advance."'],
      ['prior to', 'PRAYır tu', '-den önce (resmi)', 'Gündelik: before. Hukuk ve yönetmelik dili.'],
      ['subsequently', 'SABsıkuentli', 'ardından, sonradan', 'Gündelik: then/after that. Akademik anlatım.'],
    ],
    sentences: [
      ['The contract will terminate at the end of June.', 'Sözleşme Haziran sonunda sona erecektir.'],
      ['Passengers are requested to inform the staff prior to boarding.', 'Yolcular binmeden önce personeli bilgilendirmekle yükümlüdür.'],
      ['We endeavour to reply within two working days.', 'İki iş günü içinde yanıtlamaya gayret ediyoruz.'],
      ['Subsequently, the committee revised its decision.', 'Ardından komite kararını gözden geçirdi.'],
    ],
    sceneTitle: 'A Formal Email',
    sceneContext: 'Anna, bir şirkete resmi e-posta yazıyor; Mark yumuşatıyor.',
    dialogue: [
      ['Mark', 'You cannot start a business email with "Hey guys".', 'yu KANT START e BİZNİS IIMEYL vid "HEY GAYZ".', 'Bir iş e-postasına "Hey guys" diye başlanmaz.'],
      ['Anna', 'Fine: "Dear Sir or Madam, I am writing to inquire about your services."', 'FAYN: "DİR SER OR MEDım, ay EM RAYting tu inkUAYır eBAUT yor SERvisız."', 'Peki: "Sayın Yetkili, hizmetleriniz hakkında bilgi almak için yazıyorum."'],
      ['Mark', 'Better. And end it with "We look forward to your assistance", not "See ya".', 'BEDır. End END İT vid "ui LUK FORuırd tu yor eSIStıns", NOT "SII YA".', 'Daha iyi. Ve "Görüşürüz" yerine "Yardımınızı bekliyoruz" diye bitir.'],
      ['Anna', 'This formal English costs me an arm and a leg in effort!', 'Dis FORmıl ING-liş KOSTS Mİ en ARM end e LEG in EFırt!', 'Bu resmi İngilizce emek olarak kolumu bacağıma mal oluyor!'],
      ['Mark', 'Welcome to adult life: prior to pressing send, read it twice.', 'UELkım tu eDALT LAYF: PRAYır tu PRESing SEND, RIID İT TUAIS.', 'Yetişkin hayatına hoş geldin: göndermeden önce iki kez oku.'],
    ],
  },
  {
    id: 'en_mod_c1_36',
    unitNumber: 36,
    levelGroup: 'C1',
    title: 'Münazara & Retorik',
    description: 'Argüman kurma, çürütme ve taviz verme dili',
    category: 'Retorik',
    color: '#ef4444',
    icon: '🎙️',
    grammarExplain: `📌 TAVİZ CÜMLELERİ (CONCESSION):
1. "Although + cümle" / "Despite + isim" / "Admittedly, ..." — karşı argümanı önce kabul edip sonra döndürürsün: "Admittedly, the plan is costly. However, it will pay off."
2. "While it is true that..., ..." — rakibin noktasını tanıyıp smashing: en zarif çürütme kalıbı.
3. Zayıf bağırma güçlü argümanı göstermez: "That is a compelling point, and yet..."`,
    words: [
      ['refute', 'riFYUUT', 'çürütmek, reddetmek', '"refute an argument" — düzeltmek değil!'],
      ['concede', 'kınSIID', 'taviz vermek, kabul etmek', '"I concede that the costs are high."'],
      ['premise', 'PREMıs', 'öncül, varsayım', 'Argümanın üzerine kurulduğu taş.'],
      ['fallacy', 'FEELısi', 'yanılgı, safsata', '"a logical fallacy" = mantık hatası.'],
      ['rhetoric', 'RETırık', 'hitabet, retorik', 'Yiğit kelime ama sık "boş laf" iması taşır.'],
      ['advocate', 'EDvıkeyt', 'savunmak; savunucu', '"an advocate for change".'],
      ['undermine', 'ANdırMAYN', 'sarsmak, güvenini zedelemek', '"This data undermines their claim."'],
      ['compelling', 'kımPELing', 'ikna edici, güçlü', '"a compelling argument".'],
      ['scrutiny', 'SKRUUtıni', 'detaylı inceleme', '"under close scrutiny" = sıkı incelemede.'],
      ['rebuttal', 'riBATıl', 'karşı savunma, cevap', 'Münazarada son söz hakkı.'],
    ],
    sentences: [
      ['Admittedly, the plan is expensive; however, it will pay off in five years.', 'Elbette plan pahalı; ama beş yılda kendini amorti edecek.'],
      ['Her rebuttal exposed a fatal fallacy in their premise.', 'Onun karşı savunması, öncüllerindeki ölümcül bir safsatayı ortaya çıkardı.'],
      ['While it is true that costs rose, revenue doubled.', 'Maliyetlerin arttığı doğru ama gelir ikiye katlandı.'],
      ['The evidence survived close scrutiny.', 'Kanıt sıkı incelemeden sağlam çıktı.'],
    ],
    sceneTitle: 'The Debate Final',
    sceneContext: 'Üniversite münazara finali; iki takım karşılıklı.',
    dialogue: [
      ['Debater', 'While it is true that electric cars cost more, their running costs are lower.', 'UAYL İT İZ TRU det iliKtrik KARS KOST MOR, der RANing KOSTS AR LOUır.', 'Elektrikli arabaların daha pahalı olduğu doğru ama işletme maliyetleri daha düşük.'],
      ['Anna', 'Admittedly, that is a compelling point. Yet the batteries undermine your premise.', 'edmITıdli, det İZ e kımPELing POYNT. YET di BEtırız ANdırMAYN yor PREMıs.', 'Elbette bu ikna edici bir nokta. Yine de piller öncülünüzü sarsıyor.'],
      ['Debater', 'Our data refute that claim under close scrutiny.', 'AUR DEYtı riFYUUT det KLEYM ANdır KLOUS SKRUUtıni.', 'Verilerimiz bu iddiayı sıkı incelemede çürütüyor.'],
      ['Anna', 'Then I concede the point — and redirect you to charging infrastructure.', 'DEN ay kınSIID di POYNT — end ridiREKT yu tu CARcing INfrıstrAKçır.', 'O zaman bu noktayı kabul ediyorum — ve sizi şarj altyapısına yönlendiriyorum.'],
      ['Judge', 'A masterful rebuttal. The judges will now deliberate.', 'e MAS-tırful riBATıl. di CACız UİL NAU dilIBıreyt.', 'Ustaca bir karşı savunma. Jüriler şimdi değerlendirecek.'],
    ],
  },
  {
    id: 'en_mod_c1_37',
    unitNumber: 37,
    levelGroup: 'C1',
    title: 'Ekonomi & Küresel Konular',
    description: 'Ekonomi haberciliği ve trend anlatım dili',
    category: 'Ekonomi',
    color: '#10b981',
    icon: '📈',
    grammarExplain: `📌 TREND DİLİ (GRAFİK KONUŞMA):
1. Yukarı: rise, increase, soar (havalanmak), surge (sıçramak).
2. Aşağı: fall, decline, plummet (uçurumdan düşmek).
3. Sabit: remain steady / level off. Kalıplar: "a sharp rise", "a slight decline" — sıfat + isim tamlaması grafik cümlesidir.`,
    words: [
      ['inflation', 'inFLEYşın', 'enflasyon', '"Inflation is falling."'],
      ['recession', 'riSEşın', 'resesyon, durgunluk', '"a deep recession".'],
      ['trade-off', 'TREYDOF', 'ödünleşme, iki arada bir derede kalma', 'Ekonomi derslerinin ilk kelimesi.'],
      ['subsidy', 'SABsıdi', 'sübvansiyon, devlet desteği', 'Çoğulu: subsidies.'],
      ['monopoly', 'mıNOPıli', 'tekel', '"break up a monopoly".'],
      ['sanctions', 'SENKşınz', 'yaptırımlar', '"impose sanctions on a country".'],
      ['austerity', 'osTERıti', 'kemer sıkma politikası', '"austerity measures".'],
      ['emerging market', 'iMERjing MARKıt', 'gelişmekte olan pazar', 'Finans haberlerinin gözdesi.'],
      ['disparity', 'disPERıti', 'eşitsizlik, uçurum', '"wealth disparity" = servet uçurumu.'],
      ['fluctuate', 'FLAKçueyt', 'dalgalanmak', '"Prices fluctuate seasonally."'],
    ],
    sentences: [
      ['Inflation soared last year, then levelled off in spring.', 'Enflasyon geçen yıl havalandı, sonra ilkbaharda düzleşti.'],
      ['The country imposed sanctions on several emerging markets.', 'Ülke birkaç gelişmekte olan pazara yaptırım uyguladı.'],
      ['There is a clear trade-off between growth and equality.', 'Büyüme ve eşitlik arasında net bir ödünleşme var.'],
      ['Wealth disparity has widened for decades.', 'Servet uçurumu on yıllardır açılıyor.'],
    ],
    sceneTitle: 'The Market Report',
    sceneContext: 'Finans analisti canlı yayında piyasaları yorumluyor.',
    dialogue: [
      ['Analyst', 'Inflation fell slightly this quarter, but prices still fluctuate.', 'inFLEYşın FOL SLAYTli Dis KUORtır, bat PRAYSız STIL FLAKçueyt.', 'Enflasyon bu çeyrekte hafifçe düştü ama fiyatlar hâlâ dalgalanıyor.'],
      ['Host', 'Is a recession still on the table?', 'İZ e riSEşın STIL on di TEYbıl?', 'Resesyon hâlâ gündemde mi?'],
      ['Analyst', 'The emerging markets remain steady, which is encouraging.', 'di iMERjing MARKıts riMEYN STEDi, viç İZ inKERıcing.', 'Gelişmekte olan pazarlar istikrarlı, bu cesaret verici.'],
      ['Host', 'And the trade-off between subsidies and austerity?', 'end di TREYDOF bitUİN SABsıdiz end osTERıti?', 'Peki sübvansiyon ve kemer sıkma arasındaki ödünleşme?'],
      ['Analyst', 'A classic dilemma: narrow the disparity, or protect the monopoly holders?', 'e KLA sik dıLEMı: NERou di disPERıti, OR prıTEKT de mıNOPıli HOLDırz?', 'Klasik ikilem: uçurumu daralt mı, tekil sahiplerini koru mu?'],
    ],
  },
  {
    id: 'en_mod_c1_38',
    unitNumber: 38,
    levelGroup: 'C1',
    title: 'Felsefe & Etik',
    description: 'Soyut düşünce dili: ikilemler, paradokslar ve erdem',
    category: 'Felsefe',
    color: '#a78bfa',
    icon: '🤔',
    grammarExplain: `📌 SOYUT İSİMLERLE DÜŞÜNME:
1. Felsefe metinleri isim-yoğundur (nominal-dense): "the pursuit of happiness", "the nature of consciousness".
2. "-ness / -ity / -ism" ekleri soyutluk üretir: aware → awareness, just → justice.
3. Tartışma kalıbı: "This raises the question of whether..." — felsefi soruyu mumla arayan kalıp.`,
    words: [
      ['dilemma', 'dilEMı', 'ikilem', '"a moral dilemma" = ahlaki ikilem.'],
      ['virtue', 'VERçuu', 'erdem, fazilet', '"patience is a virtue".'],
      ['ethics', 'ETiks', 'etik', 'Tekil görünümlü alan adı: "Ethics is...".'],
      ['conscience', 'KONşıns', 'vicdan', 'Okunuşu zordur: KON-şıns.'],
      ['paradox', 'PERıdoks', 'paradoks, çelişki', 'Çoğulu: paradoxes.'],
      ['dogma', 'DOGmı', 'dogma, sorgusuz inanç', '"question the dogma".'],
      ['intrinsic', 'inTRINzik', 'özsel, içten gelen', 'Zıttı: "extrinsic" (dışsal).'],
      ['perception', 'pırSEPşın', 'algı', '"Reality is a matter of perception."'],
      ['moral', 'MORıl', 'ahlaki; ahlak dersi', '"a moral obligation" = ahlaki yükümlülük.'],
      ['existence', 'igZIStıns', 'varoluş, varlık', '"the meaning of existence".'],
    ],
    sentences: [
      ['This raises the question of whether free will truly exists.', 'Bu, özgür iradenin gerçekten var olup olmadığı sorusunu gündeme getiriyor.'],
      ['Kindness is an intrinsic virtue, not a strategy.', 'İyilik özsel bir erdemdir, strateji değil.'],
      ['The paradox of choice makes us less happy.', 'Seçim paradoksu bizi daha az mutlu yapıyor.'],
      ['He followed his conscience, not the dogma.', 'Dogmayı değil vicdanını izledi.'],
    ],
    sceneTitle: 'The Late-Night Debate',
    sceneContext: 'Kütüphane kapanmadan önce felsefe tartışması.',
    dialogue: [
      ['Mark', 'Here is a dilemma: would you lie to save a friend?', 'HİR İZ e dilEMı: UUD yu LAY tu SEYV e FREND?', 'Şöyle bir ikilem: bir arkadaşını kurtarmak için yalan söyler miydin?'],
      ['Anna', 'Kant would say no — lying is intrinsically wrong.', 'KANT UUD SEY NOU — LAYing İZ inTRINzikli RONG.', 'Kant derdi ki hayır — yalan özü itibarıyla yanlıştır.'],
      ['Mark', 'But my conscience would not let me betray a friend.', 'BAT may KONşıns UUD NOT LET Mİ bitREY e FREND.', 'Ama vicdanım bir arkadaşımı ele vermeme izin vermezdi.'],
      ['Anna', 'A true paradox: two moral duties, one choice.', 'e TRU PERıdoks: TU MORıl DYUtiz, UAN ÇOYS.', 'Gerçek bir paradoks: iki ahlaki görev, tek seçim.'],
      ['Mark', 'That is philosophy — every answer raises a new question of existence.', 'det İZ filOSOfi — EVri ANsır REYsız e NYU KUESçın ıv igZIStıns.', 'Felsefe budur işte — her cevap varoluşun yeni bir sorusunu doğurur.'],
    ],
  },
  {
    id: 'en_mod_c1_39',
    unitNumber: 39,
    levelGroup: 'C1',
    title: 'Bilim Keşifleri (İleri)',
    description: 'Büyük bilim söylemi: paradigma, entropi ve anomali',
    category: 'Bilim',
    color: '#0ea5e9',
    icon: '🧪',
    grammarExplain: `📌 BİLİMSEL ÖLÇÜLÜ DİL:
1. Kesinlik merdiveni: "proves" (kanıtlar) > "strongly suggests" (güçlü biçimde gösterir) > "is consistent with" (uyumludur) > "may indicate" (işaret edebilir).
2. "anomaly" — kural dışı veri; genelde büyük keşfin habercisidir.
3. Edilgen + koşul: "Had the anomaly been ignored, the theory would have survived unchanged." — c1 düzeyi ters koşul cümlesi!`,
    words: [
      ['quantum', 'KUONtım', 'kuantum', '"quantum computing" = kuantum bilgisayar.'],
      ['genome', 'CIInoum', 'genom', '"the human genome project".'],
      ['particle', 'PARtikıl', 'parçacık', '"elementary particles".'],
      ['theorem', 'TIYırım', 'teorem', 'Kanıtlanmış matematik önerme.'],
      ['paradigm', 'PERıdaym', 'paradigma', '"a paradigm shift" = paradigma değişimi.'],
      ['entropy', 'ENtırpi', 'entropi', 'Düzensizliğin fiziksel ölçüsü.'],
      ['synthesis', 'SINtisıs', 'sentez, birleştirme', 'Çoğulu: syntheses.'],
      ['cognition', 'kogNİşın', 'biliş, kavrayış', '"human cognition".'],
      ['anomaly', 'eNOMılı', 'anomali, kural dışı durum', 'Çoğulu: anomalies.'],
      ['hypothesize', 'hayPOtisayz', 'hipotez sürmek', 'Fiil hâli — bilim insanı fiili.'],
    ],
    sentences: [
      ['The anomaly in the data triggered a paradigm shift.', 'Verideki anomali bir paradigma değişimini tetikledi.'],
      ['This theorem revolutionized our understanding of entropy.', 'Bu teorem entropi anlayışımızı baştan aşağı değiştirdi.'],
      ['The findings strongly suggest that cognition is embodied.', 'Bulgular bilişin bedensel olduğunu güçlü biçimde gösteriyor.'],
      ['Researchers hypothesize that quantum effects play a role.', 'Araştırmacılar kuantum etkilerinin rol oynadığını öne sürüyor.'],
    ],
    sceneTitle: 'The Discovery',
    sceneContext: 'Bir fizik laboratuvarında beklenmedik bir sonuç.',
    dialogue: [
      ['Researcher', 'The particle behaved strangely — the readings show an anomaly.', 'de PARtikıl biHEYVD STREYNCLi — di RII dings ŞOU en eNOMılı.', 'Parçacık tuhaflaştı — ölçümler bir anomali gösteriyor.'],
      ['Anna', 'Could it be noise, or is the data consistent with the theory?', 'KUD İT Bİ NOYS, OR İZ di DEYtı kınSIStınt vid di TIYıri?', 'Gürültü olabilir mi, yoksa veri teoriyle uyumlu mu?'],
      ['Researcher', 'We hypothesize a new particle. If we are right, this is a paradigm shift.', 'ui hayPOtisayz e NYU PARtikıl. İF ui AR RAYT, Dis İZ e PERıdaym ŞİF T.', 'Yeni bir parçacık öne sürüyoruz. Haklıysak bu bir paradigma değişimi.'],
      ['Anna', 'Had the anomaly been ignored, we would have missed everything.', 'HED di eNOMılı BIIN igNORD, ui UUD HEV MIST EVriting.', 'Anomali göz ardı edilseydi her şeyi kaırırdık.'],
      ['Researcher', 'Exactly. Entropy increases, but so does curiosity!', 'igZEKTli. ENtırpi inKRIISız, BAT SOU DAZ kyuriOSıti!', 'Aynen. Entropi artıyor ama merak da artıyor!'],
    ],
  },
  {
    id: 'en_mod_c1_40',
    unitNumber: 40,
    levelGroup: 'C1',
    title: 'İroni & Yergi',
    description: 'Söylenenle kastedilen arasındaki oyun',
    category: 'Üslup',
    color: '#f43f5e',
    icon: '🎭',
    grammarExplain: `📌 SÖYLENEN ≠ KASTEDİLEN:
1. İroni: tersini kastederek söyleme. "Oh great, another Monday!" — "great" burada tam tersi.
2. Sarcasm (iğneleme): ironinin sivri ucu, genelde kişiye yönelik: "Nice job!" (iş berbat olunca).
3. Metinde ironi sinyalleri: aşırı övgü + ters bağlam, "apparently", "ironically", tırnak işareti etkisi.`,
    words: [
      ['irony', 'AYırıni', 'ironi', '"the irony is that..." kalıbıyla.'],
      ['satire', 'SETAYır', 'yergi, satir', '"political satire" = siyasi yergi.'],
      ['sarcasm', 'SARkezım', 'iğneleme, alay', 'Sarcasm is the lowest form of wit — derler.'],
      ['parody', 'PERıdi', 'parodi, taklit', '"a parody of the president\'s speech".'],
      ['absurd', 'ebSERD', 'saçma, absürt', '"an absurd situation".'],
      ['wit', 'UİT', 'nüktedanlık, zekâ', '"a witty remark" = nükte.'],
      ['cynicism', 'SINısizım', 'kinizm, her şeye kuşkuyla bakma', 'Kötümser şakanın felsefi adı.'],
      ['allegory', 'ELıgori', 'alegori, smbollü anlatı', '"Animal Farm is an allegory."'],
      ['aesthetic', 'esDETik', 'estetik', 'Okunuşu kritik: es-DET-ik!'],
      ['avant-garde', 'aVONGARD', 'avat-garde, öncü', 'Sanatın cephe birliği.'],
    ],
    sentences: [
      ['The irony is that the firewall company got hacked.', 'İroni şu ki, güvenlik duvarı şirketi hacklendi.'],
      ['His speech was a parody of common sense.', 'Konuşması sağduyunun parodisiydi.'],
      ["Oh, wonderful — my flight got cancelled again.", 'Ah harika — uçuşum yine iptal edildi.'],
      ['The novel works as both satire and allegory.', 'Roman hem yergi hem alegori olarak işliyor.'],
    ],
    sceneTitle: 'The Comedy Night',
    sceneContext: 'Bir stand-up gecesinde ironi avı.',
    dialogue: [
      ['Comedian', 'Oh, I just LOVE waiting in airports. Ten hours of pure joy.', 'OU, ay CAST LAV UEYting in ERPOR TS. TEN AUırz ıv PYUUR COY.', 'Ah, havalimanlarında beklemeye bayılıyorum. Dibine saf on saat keyif.'],
      ['Anna', 'Classic irony. He says "love", he means the opposite.', 'KLA sik AYırıni. hi SEZ "LAV", hi MIINZ di OPızit.', 'Klasik ironi. "Bayılıyorum" diyor, tersini kastediyor.'],
      ['Mark', 'And the parliament sketch? Pure satire.', 'end di PARlımınt SKEÇ? PYUUR SETAYır.', 'Peki parlament skeci? Tam bir yergi.'],
      ['Anna', 'An allegory of our times, honestly. Almost absurd.', 'en ELıgori ıv AUR TAYMZ, ONistli. OLmoust ebSERD.', 'Dürüst olmak gerekirse çağımızın alegorisi. Neredeyse absürt.'],
      ['Mark', 'Witty, cynical — and painfully accurate.', 'UITi, SINikıl — end PEYNfuli EKyurıt.', 'Nüktedan, kinik — ve acı derecede isabetli.'],
    ],
  },
  // ==========================================================================
  // C1/C2 — ÜNİTE 41-48 (USTALIK SEVİYESİ)
  // ==========================================================================
  {
    id: 'en_mod_c12_41',
    unitNumber: 41,
    levelGroup: 'C1/C2',
    title: 'Phrasal Verbs (Ustalık)',
    description: 'Kiptri fiiller: ayrılabilir/ayrılamaz, gündelik işlerinin motoru',
    category: 'İfadeler',
    color: '#f59e0b',
    icon: '🔗',
    grammarExplain: `📌 PHRASAL VERB GRAMERİ:
1. Ayrılabilir (separable): "figure the problem out" ✓ / "figure out the problem" ✓ — ama zamir ortadaysa yalnız: "figure IT out".
2. Ayrılamaz (inseparable): "look after the kids" ✓ / "look the kids after" ✗.
3. Üç parçalılar asla bölünmez: "put up with the noise" (katlanmak).`,
    words: [
      ['put up with', 'PUT ap vid', 'katlanmak, tahammül etmek', '"I cannot put up with this noise."'],
      ['carry out', 'KEri AUT', 'gerçekleştirmek, yürütmek', '"carry out a survey" — resmi görev fiili.'],
      ['come across', 'KAM eKROS', 'tesadüfen rastlamak', '"I came across an old letter."'],
      ['turn down', 'TERN DAUN', 'reddetmek; kısmak (sesi)', '"She turned down the offer."'],
      ['figure out', 'FIGır AUT', 'çözmek, anlamak', 'Beyin fırtınasının phrasal halı.'],
      ['break down', 'BREYK DAUN', 'bozulmak; yıkmak; dökülmek', 'Araba bozulur, insan dökülür, kapılar yıkılır.'],
      ['run into', 'RAN INtu', 'tesadüfen karşılaşmak', '"I ran into an old friend."'],
      ['bring about', 'BRING eBAUT', 'meydana getirmek, yol açmak', '"The reform brought about change."'],
      ['get away with', 'GET eUEY vid', 'yakanı sıyırmak', '"He got away with murder."'],
      ['look up to', 'LUK AP tu', 'örnek almak, hayran olmak', '"I look up to my grandmother."'],
    ],
    sentences: [
      ['She turned down the offer without explaining why.', 'Teklifi nedenini açıklamadan reddetti.'],
      ['The survey was carried out in twelve countries.', 'Anket on iki ülkede yürütüldü.'],
      ['I came across this quote and thought of you.', 'Bu alıntıya tesadüfen rastladım ve aklıma sen geldin.'],
      ['They got away with a tiny fine.', 'Ufak bir cezayla yakalarını sıyırdılar.'],
    ],
    sceneTitle: 'The Flatmates',
    sceneContext: 'İki ev arkadaşı rutin bir krizi phrasal verbs\'le yaşıyor.',
    dialogue: [
      ['Anna', 'The washing machine broke down again. I cannot put up with it!', 'de UOŞing maŞIN BROUK DAUN eGEYN. ay KANOT PUT ap vid İT!', 'Çamaşır makinesi yine bozuldu. Katlanamıyorum artık!'],
      ['Mark', 'I will figure out the manual tonight. I came across a repair video.', 'ay UİL FIGır AUT di MENyuel tuNAYT. ay KAM eKROS e riPEIR VIDiyoo.', 'Bu akşam kılavuzu çözerim. Tamir videosuna rastladım.'],
      ['Anna', 'The landlord always gets away with everything, I swear.', 'de LENDlorD OLueyz GETS eUEY vid EVriting, ay SUER.', 'Ev sahibi bence hep bir şekilde yakanı sıyırıyor.'],
      ['Mark', 'I ran into him yesterday and turned down his excuses politely.', 'ay RAN INtu HİM YES-tırdey end TERND DAUN his ikSKYUusız pılAYTli.', 'Dün ona rastladım ve bahanelerini kibarca reddettim.'],
      ['Anna', 'That is why I look up to you, my diplomatic friend.', 'det İZ UAY ay LUK AP tu YU, may diploMETik FREND.', 'İşte bu yüzden sana hayranım, diplomatik dostum.'],
    ],
  },
  {
    id: 'en_mod_c12_42',
    unitNumber: 42,
    levelGroup: 'C1/C2',
    title: 'Eşdizimler (Collocations)',
    description: 'Ana kadar İngilizce: kelimelerin resmi evlilikleri',
    category: 'İfadeler',
    color: '#06b6d4',
    icon: '💞',
    grammarExplain: `📌 EŞDİZİM NEDİR?
1. Kelimeler belirli partnerlerle yaşar: "heavy rain" ✓ / "strong rain" ✗; "make a decision" ✓ / "do a decision" ✗.
2. Türleri: fiil+isim (make progress), sıfat+zarf (bitterly cold), isim+isim (a bar of soap).
3. Ana kadar öğrenilen kelimeler eşdizimlerle native gibi kurulur — bu C2 seviyesinin sırrıdır.`,
    words: [
      ['make progress', 'MEYK PROGres', 'ilerleme kaydetmek', '"do progress" YANLIŞ — her zaman "make"!'],
      ['take a risk', 'TEYK e RISK', 'risk almak', '"make a risk" ✗.'],
      ['heavy rain', 'HEvi REYN', 'şiddetli yağmur', 'Yağmur "heavy", fırtına "strong/severe".'],
      ['highly recommend', 'HAYli rekıMEND', 'şiddetle tavsiye etmek', 'Övgüde standardın üstü.'],
      ['deeply concerned', 'DIIPli kınSERnd', 'derinden endişeli', 'Resmi mektupların klasiği.'],
      ['fully aware', 'FULi eUER', 'tamamen farkında', '"fully aware of the risks".'],
      ['bitterly cold', 'BITırli KOULD', 'keskin soğuk', '"bitterly" soğuğa, "highly" övgüye eşleşir.'],
      ['a bar of soap', 'e BAR ıv SOUP', 'bir kalıp sabun', 'Sayılabilen ünite kalıbı: a bar of, a slice of.'],
      ['pay attention', 'PEY eTENşın', 'dikkat etmek', '"give attention" ✗ — "pay"!'],
      ['meet a deadline', 'MIIT e DEDlayn', 'teslim tarihine yetişmek', '"catch a deadline" ✗.'],
    ],
    sentences: [
      ['You have made remarkable progress this term.', 'Bu dönem kayda değer ilerleme kaydettin.'],
      ['I deeply regret taking that risk.', 'O riski aldığıma derinden pişmanım.'],
      ['We are fully aware of the heavy competition.', 'Yoğun rekabetin tamamen farkındayız.'],
      ['Pay attention — the deadline will not move.', 'Dikkat et — teslim tarihi kaymayacak.'],
    ],
    sceneTitle: 'The Performance Review',
    sceneContext: 'Yıllık performans görüşmesi.',
    dialogue: [
      ['Manager', 'You have made significant progress since January.', 'yu HEV MEYD sigNIfikınt PROGres SINS JANyueri.', 'Ocak ayından bu yana önemli ilerleme kaydettin.'],
      ['Anna', 'Thank you. I am fully aware that I still take too few risks.', 'SENK yu. ay EM FULi eUER det ay STIL TEYK TU FYU RISKS.', 'Teşekkürler. Hâlâ çok az risk aldığımın tamamen farkındayım.'],
      ['Manager', 'Yet you always meet your deadlines — even in bitterly cold Decembers.', 'YET yu OLueyz MIIT yor DEDlaynz — IIV in BITırli KOULD diSEMbırz.', 'Yine de teslim tarihlerini her zaman tutturuyorsun — en keskin soğuk Aralık\'larda bile.'],
      ['Anna', 'I highly recommend giving the new team a chance, by the way.', 'ay HAYli rekıMEND GIVing di NYU TIIM e ÇANS, bay di UAY.', 'Bu arada yeni ekibe şans vermeni şiddetle tavsiye ederim.'],
      ['Manager', 'Noted. Your colleagues are deeply concerned that you never take a day off!', 'NOUtid. yor KOLIIGZ AR DIIPli kınSERnd det yu NEvır TEYK e DEY OF!', 'Not edildi. İş arkadaşların hiç izin yapmadığın için endişeli!'],
    ],
  },
  {
    id: 'en_mod_c12_43',
    unitNumber: 43,
    levelGroup: 'C1/C2',
    title: 'Resmî Yazışma & Diplomasi',
    description: 'Protokol dili: tam da C2 seviyesinin vitrin tabloları',
    category: 'Üslup',
    color: '#64748b',
    icon: '✉️',
    grammarExplain: `📌 RESMİ ZARF CÜMLELERİ:
1. "With regard to / Regarding..." — konuya giriş; "about" ın smokinli hâli.
2. "I would be grateful if you could..." — talep etmenin en kibar hâli.
3. "Please do not hesitate to contact me." — resmi e-postanın evrensel kapanışı.
4. "pursuant to" (uyarınca), "hereby" (işbu) — sözleşme ve diplomatik yazışmanın süsleri.`,
    words: [
      ['with regard to', 'vid rigARD tu', '-e ilişkin, konusunda', 'E-posta konu satırının büyükbabası.'],
      ['pursuant to', 'pırSUınt tu', '-e uygun olarak, uyarınca', 'Hukuk metinlerinin "in accordance with" ı.'],
      ['hereby', 'HİRbay', 'işbu şekilde, bununla', '"I hereby confirm..." — resmi imza dili.'],
      ['cordially', 'KORcılı', 'içtenlikle, saygılarımla', 'Mektup kapanışı: "Yours cordially".'],
      ['enclosed', 'inkLOUZD', 'ekli, iliştirilmiş', '"Please find enclosed..." — ek klasği.'],
      ['kindly', 'KAYNDli', 'kibarca, lütfen', '"Kindly note that..." = lütfen dikkate alın.'],
      ['courtesy', 'KURtısı', 'nezaket; ikram', '"as a courtesy" = nezaket gereği.'],
      ['forthcoming', 'FORSKAMing', 'yaklaşan; hazırda olan', '"the forthcoming meeting".'],
      ['liaison', 'LIYeyzın', 'irtibat, bağlantı görevlisi', 'Okunuşu Fransız kalıntısı: LIY-ey-zın!'],
      ['protocol', 'PROUtokol', 'protokol, usul', 'Diplomasinin trafik kuralları.'],
    ],
    sentences: [
      ['With regard to your request, please find enclosed the signed form.', 'Talebinize ilişkin, ekte imzalı formu bulabilirsiniz.'],
      ['Pursuant to Article 12, the parties shall notify each other.', 'Madde 12 uyarınca taraflar birbirini bilgilendirecektir.'],
      ['I hereby confirm my attendance at the forthcoming session.', 'Yaklaşan oturuma katılımımı işbu yazıyla teyit ederim.'],
      ['Kindly do not hesitate to contact our liaison officer.', 'İrtibat görevlimizle iletişime geçmekten lütfen çekinmeyin.'],
    ],
    sceneTitle: 'The Embassy Letter',
    sceneContext: 'Bir Büyükelçilik yazışması hazırlanıyor.',
    dialogue: [
      ['Anna', 'How should I open the letter to the embassy?', 'hau ŞUD ay OUPın di LEtır tu di EMbısı?', 'Elçiliğe mektuba nasıl başlamalıyım?'],
      ['Mark', '"With regard to your kind invitation of 3 May..." — klasik ve saygılı.', '"vid rigARD tu yor KAYND inviTEYşın ıv TRII MEY..." — KLA sik end sayGILI.', '"3 May tarihli kibar davetinize ilişkin..." — klasik ve saygılı.'],
      ['Anna', 'And the closing? I want to sound diplomatic.', 'end di KLOUSing? ay UANT tu SAUND diploMETik.', 'Peki kapanış? Diplomatik görünmek istiyorum.'],
      ['Mark', '"I hereby confirm my attendance" ve "Yours cordially". Protocol complete!', '"ay HİRbay kınFERM may eTENdıns" ve "YORZ KORcılı". PROUtokol kımPLIT!', '"Katılımımı işbu yazıyla teyit ederim" ve "Saygılarımla". Protokol tamam!'],
      ['Anna', 'Kindly note that this sounds impressively official.', 'KAYNDli NOU det Dis SAUNDZ imPREsivli OFişıl.', 'Şunu kibarca not edeyim: bu etkileyici derecede resmi oldu.'],
    ],
  },
  {
    id: 'en_mod_c12_44',
    unitNumber: 44,
    levelGroup: 'C1/C2',
    title: 'Şiir & Edebiyat Terimleri',
    description: 'Edebiyatın amme dili: sonnet\'ten soliloquy\'ye',
    category: 'Edebiyat',
    color: '#c084fc',
    icon: '🦢',
    grammarExplain: `📌 ŞİİR DİLİNİN GRAMERİ:
1. Şiirde dilbilgisi serbestliği olağandır: "’Twas" (= it was), sıfat-fiil ters dizilişi.
2. Ölçü birimleri: "iambic pentameter" (Shakespeare ölçüsü) — beş çift vuruş.
3. Ses araçları: alliteration (üst üste aynı ünsüz), assonance (ünlü yankısı) — anlamı sesle pekiştirir.`,
    words: [
      ['sonnet', 'SONit', 'sone', '14 satırlık klâsik şiir formu.'],
      ['verse', 'VERS', 'dize, şiir parçası', '"free verse" = serbest şiir.'],
      ['stanza', 'STENzı', 'kıta', 'Şiirin paragrafı.'],
      ['prose', 'PROUZ', 'düz yazı', '"prose and poetry" = düzyazı ve şiir.'],
      ['imagery', 'IMıcri', 'imgeleme, imge dünyası', '"vivid imagery" = canlı imgeler.'],
      ['alliteration', 'elitıREYşın', 'baş ses tekrarı', '"Peter Piper picked..." — P-P-P.'],
      ['soliloquy', 'silILıkui', 'iç konuşma, monolog', 'Hamlet\'in "To be or not to be"si.'],
      ['elegy', 'ELıci', 'ağıt, mersiye', 'Kayıp için yazılan şiir.'],
      ['motif', 'mouTİIF', 'bileşen motif, yinelenen öge', '"a recurring motif" — tekrarlanan tema ögesi.'],
      ['metre', 'MIİtır', 'vezin, ölçü', 'Şiirin kalp ritmi.'],
    ],
    sentences: [
      ['The poem is written in iambic metre with a recurring water motif.', 'Şiir, yinelenen su motifiyle iambik vezinde yazılmış.'],
      ['Her elegy for the fallen city became legendary.', 'O, düşen şehir için yazdığı ağıt efsane oldu.'],
      ['Hamlet\'s soliloquy redefined drama itself.', 'Hamlet\'in monoloğu dramanın ta kendisini yeniden tanımladı.'],
      ['The alliteration in line three is pure music.', 'Üçüncü dizedeki baş ses tekrarı saf müzik.'],
    ],
    sceneTitle: 'The Poetry Reading',
    sceneContext: 'Bir şiir gecesi; sahnede sone okunuyor.',
    dialogue: [
      ['Poet', 'This sonnet took me a year — fourteen lines, endless revisions.', 'Dis SONit TUUK Mİ e YIR — forTIIN LAYNZ, ENDlis riviJınz.', 'Bu sone bana bir yıla mal oldu — on dört satır, sonsuz revizyon.'],
      ['Anna', 'The imagery of the drowned garden stayed with me.', 'di IMıcri ıv de DRAUND GARdın STEYD vid Mİ.', 'Boğulan bahçe imgesi aklımdan çıkmadı.'],
      ['Poet', 'I wanted the metre to feel like a heartbeat.', 'ay UONtid di MIİtır tu FIIL layk e HARDbiit.', 'Veznin kalp atışı gibi hissettirmesini istedim.'],
      ['Mark', 'And the elegy at the end — was it for someone real?', 'end di ELıci et di END — UOZ İT for SAMUAN RIİL?', 'Sondaki ağıt — gerçek birisi için miydi?'],
      ['Poet', 'Every elegy is. That is why each stanza hurts.', 'EVri ELıci İZ. det İZ UAY Iİç STENzı HURTS.', 'Her ağıt öyledir. Bu yüzden her kıta acıtır.'],
    ],
  },
  {
    id: 'en_mod_c12_45',
    unitNumber: 45,
    levelGroup: 'C1/C2',
    title: 'Argo, Lehçe & Dilin Evrimi',
    description: 'Dilbilimin sokak hâli: slângthen etimolojiye',
    category: 'Dilbilim',
    color: '#f97316',
    icon: '🗣️',
    grammarExplain: `📌 DİLİN KATMANLARI:
1. Register merdiveni: jargon (meslek dili) → slang (argo) → dialect (lehçe) → standard English.
2. Dil değişir: neologism (yeni kelime), loanword (ödünç kelime — Türkçeden de: "yoghurt", "kiosk"!).
3. Etimoloji anlamı aydınlatır: "nice" eskiden "cahil" demekti — anlam kayması (semantic shift) yüzünden bugün "nazik".`,
    words: [
      ['slang', 'SLENG', 'argo', '"teenage slang" — her nesil yeniden üretir.'],
      ['dialect', 'DAYılekt', 'lehçe, ağız', 'Yazımın telaffuzdan farklı olduğu yer dili.'],
      ['jargon', 'CARgon', 'meslek dili, içtimaî terminoloji', 'Hukukçunun, yazılımcının şifreli dili.'],
      ['colloquial', 'kıLOUkuiıl', 'konuşma diline ait', '"colloquial English" — kitap dili değil.'],
      ['vernacular', 'vırNEKYulır', 'gündelik halk dili', 'Resmî olmayan ana dil kullanımı.'],
      ['etymology', 'etimOLıci', 'etimoloji, kelime kökeni', 'Kelimenin aile ağacı.'],
      ['neologism', 'niOLıcizım', 'yeni türetilmiş kelime', '"selfie" 2013\'te yıldızdı.'],
      ['loanword', 'LOUNUORD', 'ödünç kelime', '"coffee", "yoghurt" — Türkçe kökenli örnekler bile var.'],
      ['semantic shift', 'sıMENtik ŞİF T', 'anlam kayması', '"awful" eskiden "dolun etkileyici" demekti.'],
      ['orthography', 'orTOGırıfi', 'yazım kuralı bilimi', 'İngilizcenin ünlü kâbusu.'],
    ],
    sentences: [
      ['The etymology of "nice" is a journey through irony.', '"Nice"ın etimolojisi ironilerle dolu bir yolculuk.'],
      ['Every generation coins its own slang.', 'Her nesil kendi argosunu icat eder.'],
      ['English orthography is a museum of old pronunciations.', 'İngilizce yazımı eski telaffuzların müzesidir.'],
      ['"Robot" is a loanword from Czech.', '"Robot" Çekçeden gelme bir ödünç kelime.'],
    ],
    sceneTitle: 'The Linguistics Café',
    sceneContext: 'Dilbilim tartışması bir kafede sürüyor.',
    dialogue: [
      ['Anna', 'Why is "colonel" spelled like that but pronounced "kernel"?', 'UAY İZ "KÖRnıl" SPELT layk det bat prınAUNST "KIRnıl"?', '"Colonel" neden öyle yazılıp "körnıl" diye okunuyor?'],
      ['Mark', 'Blame orthography — and a French loanword that drifted.', 'BLEYM orTOGırıfi — end e FRENÇ LOUNUORD det DRIFtid.', 'Yazım kurallarına suç at — ve yolda kaybolmuş bir Fransız ödünç kelimeye.'],
      ['Anna', 'The etymology is wild: it started as an Italian rank.', 'di etimOLıci İZ UAYLD: İT STARtid ez en Italian RENK.', 'Etimolojisi çılgın: İtalyanca bir rütbe olarak başladı.'],
      ['Mark', 'Semantic shift happens to all of us. Even "silly" once meant "blessed".', 'sıMENtik ŞİF T HEpınz tu OL ıv AS. IIVın "SILi" UANS MENT "BLESıD".', 'Anlam kayması hepimizin başına gelir. "Silly" bile bir zamanlar "kutsanmış" demekti.'],
      ['Anna', 'From blessed to silly — that is a whole biography in one word.', 'from BLESıd tu SILi — det İZ e HOUL bayOGırıfi in UAN UORD.', 'Kutsanmıştan aptala — tek kelimede koca bir biyografi.'],
    ],
  },
  {
    id: 'en_mod_c12_46',
    unitNumber: 46,
    levelGroup: 'C1/C2',
    title: 'Liderlik & Kariyer (Mastery)',
    description: 'Kurumsal dilin zirvesi: strateji konuşmaları',
    category: 'İş Dünyası',
    color: '#6366f1',
    icon: '🚀',
    grammarExplain: `📌 KURUMSAL DİLİN RİTİMİ:
1. Yumuşak kipler ile geri bildirim: "You might want to reconsider..." = aslında "değiştir bunu".
2. "going forward" (bundan böyle), "at this stage" (bu aşamada) — toplantı zaman zarfları.
3. Modal + edilgen kombinasyonu: "The timeline should be revisited." — sorumluluk yumaşatma sanatı.`,
    words: [
      ['leverage', 'LEVıric', 'kaldıraç olarak kullanmak; avantaj', 'Kurumsal İngilizcenin en çok suistimal edilen fiili.'],
      ['streamline', 'STRIMlayn', 'verimli hâle getirmek, yalınlaştırmak', '"streamline the process".'],
      ['stakeholder', 'STEYKHouldır', 'paydaş', 'Sürece dahil herkes.'],
      ['delegate', 'DELıgeyt', 'devretmek, görev dağıtmak', '"delegate tasks" — liderin sanatı.'],
      ['accountability', 'ekaUNTıBILıti', 'hesap verebilirlik', 'Sorumluluk değil, onun şeffaf hâli.'],
      ['benchmark', 'BENCmark', 'kıstas, referans noktası', '"set a benchmark".'],
      ['milestone', 'MAYLstoun', 'kilometre taşı', '"reach a milestone".'],
      ['articulate', 'arTIKYulıyt', 'açık ve etkili ifade etmek', '"articulate a vision".'],
      ['mentorship', 'MENtörşip', 'rehberlik, mentorluk', 'Kariyerin gizli motoru.'],
      ['resilience', 'rizILiyıns', 'dayanıklılık, toparlanma gücü', 'Bireysel kısa andan uzmana en çok sorulan soru.'],
    ],
    sentences: [
      ['We should leverage our brand to streamline operations.', 'Markamızı kullanarak operasyonları yalınlaştırmalıyız.'],
      ['Clear accountability keeps every stakeholder aligned.', 'Net hesap verebilirlik her paydaşı hizada tutar.'],
      ['Reaching this milestone proves the team\'s resilience.', 'Bu kilometre taşına varmak ekibin dayanıklılığını kanıtlıyor.'],
      ['Great leaders delegate; they also articulate the vision.', 'Büyük liderler devreder; vizyonu da etkili biçimde anlatırlar.'],
    ],
    sceneTitle: 'The Boardroom',
    sceneContext: 'Yönetim kurulu toplantısında strateji tartışması.',
    dialogue: [
      ['CEO', 'Going forward, we should leverage our data to streamline logistics.', 'GOuing FORuırd, ui ŞUD LEVıric AUR DEYtı tu STRIMlayn locIStiks.', 'Bundan böyle verimizi kullanarak lojistiği yalınlaştırmalıyız.'],
      ['Anna', 'At this stage, every stakeholder expects a clear benchmark.', 'et Dis STEYC, EVri STEYKHouldır ikSPEKTS e KLIIR BENCmark.', 'Bu aşamada her paydaş net bir kıstas bekliyor.'],
      ['CEO', 'Agreed. Anna, could you articulate the new roadmap?', 'eGRIID. Ae-ne, KUD yu arTIKYulıyt di NYU RODmap?', 'Kabul. Anna, yeni yol haritasını anlatabilir misin?'],
      ['Anna', 'Certainly. But the timeline should be revisited — quality needs mentorship, not just speed.', 'SERtınli. BAT di TAYMlayn ŞUD Bİ riVISItıd — KUOLıti NIIDZ MENtörşip, NOT CAST SPIID.', 'Elbette. Ama zaman çizelgesi gözden geçirilmeli — kalite sadece hız değil, mentorluk ister.'],
      ['CEO', 'Well said. That is the resilience this company is built on.', 'UEL SED. det İZ di rizILiyıns Dis KAMpıni İZ BILT ON.', 'Güzel söylendi. Şirket tam da bu dayanıklılık üzerinde kuruldu.'],
    ],
  },
  {
    id: 'en_mod_c12_47',
    unitNumber: 47,
    levelGroup: 'C1/C2',
    title: 'Kelime Yapımı & Kesinlik',
    description: 'Ön- ve son-eklerle anlam mühendisliği',
    category: 'Dilbilim',
    color: '#0891b2',
    icon: '🧬',
    grammarExplain: `📌 EK KOKU (WORD BUILDING):
1. Olumsuz ön-ekler: un-, in-/im-, dis-, mis-: "understand" → "misunderstand".
2. Derece ön-ekleri: over- (aşırı), under- (eksik): "overestimate" ↔ "underestimate".
3. Son-ekler: -tion (isim), -able (yapılabilir), -less (-sız), -ful (dolu): "care" → careful ↔ careless.`,
    words: [
      ['misunderstanding', 'misındırSTENding', 'yanlış anlama', 'mis- + understand + -ing: iki ek, bir dram.'],
      ['overestimate', 'OUvıresTımeıt', 'abartmak, fazla tahmin etmek', 'Zıttı: underestimate (olduğundan az sanmak).'],
      ['irreversible', 'iriVERsıbıl', 'geri döndürülemez', 'ir- + re- + vers + -ible: dört parça!'],
      ['irrelevant', 'ireLıvınt', 'konu dışı, alakasız', '"That is irrelevant to the discussion."'],
      ['anticipation', 'entisiPEYşın', 'beklenti, öngörü', 'anticipate + -tion.'],
      ['implementation', 'implımınTEYşın', 'uygulama, hayata geçirme', 'Toplantı dilinin vazgeçilmezi.'],
      ['fulfilment', 'fulFILmınt', 'tatmin, yerine getirme', 'İngiliz yazımı: fulfilment (çift l!).'],
      ['thorough', 'TERO', 'eksiksiz, titiz', 'Okunuşu: "TERO" — "thorough" ≠ "through"!'],
      ['meticulous', 'mıTIKYulıs', 'çok titiz, ince eleyen', 'Övgü olarak kullanılan titizlik.'],
      ['ultimately', 'ALTımıtli', 'sonuçta, nihayetinde', 'Sonuç cümlelerinin kraliçesi.'],
    ],
    sentences: [
      ['The misunderstanding arose from an irrelevant detail.', 'Yanlış anlama konu dışı bir ayrıntıdan doğdu.'],
      ['They overestimated the demand and underestimated the costs.', 'Talebi abarttılar, maliyetleri olduğundan az sandılar.'],
      ['The implementation of the plan requires meticulous attention.', 'Planın uygulanması titiz bir dikkat gerektiriyor.'],
      ['Ultimately, thorough preparation beats raw talent.', 'Sonuçta eksiksiz hazırlık, çiğ yeteneği yener.'],
    ],
    sceneTitle: 'The Post-Mortem',
    sceneContext: 'Başarısız bir proje sonrası değerlendirme toplantısı.',
    dialogue: [
      ['Anna', 'The root cause was a simple misunderstanding of the requirements.', 'di RUUT KOZ UOS e SİM pıl misındırSTENding ıv di rikUAYırmınts.', 'Kök neden, gereksinimlerin basit bir yanlış anlaşılmasıydı.'],
      ['Mark', 'We overestimated the timeline and underestimated the scope.', 'ui OUvıresTımeYtid di TAYMlayn end andıresTımeYtid di SKOUP.', 'Zamanı abarttık, kapsamı olduğundan az sandık.'],
      ['Anna', 'The implementation was thorough, but the plan itself was flawed.', 'di implımınTEYşın UOS TERO, bat di PLEN ITSELF UOS FLOD.', 'Uygulama titizdi ama planın kendisi kusurluydu.'],
      ['Mark', 'Irrelevant meetings, irreversible delays...', 'ireLıvınt MIITings, iriVERsıbıl dileyz...', 'Konu dışı toplantılar, geri döndürülemez gecikmeler...'],
      ['Anna', 'Ultimately, this post-mortem is our fulfilment of a promise: to learn.', 'ALTımıtli, Dis POUSTMORtım İZ AUR fulFILmınt ıv e PROMIS: tu LERN.', 'Sonuçta bu değerlendirme, verdiğimiz bir sözün yerine getirilmesi: öğrenmek.'],
    ],
  },
  {
    id: 'en_mod_c12_48',
    unitNumber: 48,
    levelGroup: 'C1/C2',
    title: 'Ustalık Sınavı (Mezuniyet)',
    description: 'C2\'ye veda: sınav dili, çıkarım ve kanıtlı konuşma',
    category: 'Mezuniyet',
    color: '#eab308',
    icon: '🏆',
    grammarExplain: `📌 SINAV DİLİNİN GRAMERİ:
1. Çıkarım soruları: "It can be inferred that..." (Şundan çıkarım yapılabilir ki...).
2. Kontrast: "Whereas the author concedes X, the passage implies Y."
3. Kanıt dili: "cites", "cites evidence", "draws on" — hangi kelime hangi delille gelir?
4. "restate" (yeniden ifade etmek) ≠ "summarise" (özetlemek): sınav tuzağının ta kendisi.`,
    words: [
      ['assess', 'eSES', 'değerlendirmek', '"assess the argument" — ölçüp biçmek.'],
      ['justify', 'CASTıfay', 'gerekçelendirmek', '"Justify your answer."'],
      ['summarise', 'SAMırayz', 'özetlemek', 'ABD yazımı: summarize.'],
      ['contrast', 'KONtrast', 'karşıtlık; karşılaştırmak', 'İsim KONtrast, fiil kınTRAST!'],
      ['imply', 'imPLAY', 'üstü kapamlı söylemek, ima etmek', 'Anlamı yerinde bırakır...'],
      ['infer', 'inFER', 'sonuç çıkarmak', '...okuMAZ bunu, okur İNFER eder!'],
      ['conclude', 'kınKLUUD', 'sonuçlandırmak', '"In conclusion, ..." — resmi bitiş.'],
      ['emphasise', 'EMfısıyz', 'vurgulamak', '"emphasise the contrast".'],
      ['restate', 'riSTEYT', 'yeniden ifade etmek', 'Aynı şeyi başka kelimelerle söylemek.'],
      ['compelling evidence', 'kımPELing EVıdıns', 'ikna edici kanıt', 'Sınavın altın standardı.'],
    ],
    sentences: [
      ['It can be inferred that the author disagrees with the policy.', 'Yazarın politikaya katılmadığı sonucu çıkarılabilir.'],
      ['Summarise the passage, then justify your conclusion.', 'Metni özetle, sonra sonucunu gerekçelendir.'],
      ['The lecturer emphasised the contrast between imply and infer.', 'Öğretim üyesi imply ve infer arasındaki farka vurgu yaptı.'],
      ['Restate your thesis in one compelling sentence.', 'Tezini tek ikna edici cümleyle yeniden ifade et.'],
    ],
    sceneTitle: 'The Final Oral Exam',
    sceneContext: 'Mezuniyet sözlü sınavı; jüri karşısında son soru.',
    dialogue: [
      ['Examiner', 'In one minute, summarise the central thesis of your research.', 'in UAN MİNıt, SAMırayz di SENtırıl TIIsıs ıv yor riSERÇ.', 'Bir dakikada araştırmanızın ana tezini özetleyin.'],
      ['Anna', 'My thesis implies that language shapes perception. I will restate it simply: words build worlds.', 'may TIIsıs imPLAYZ det LENGUİJC ŞEYPS pırSEPşın. ay UİL riSTEYT İT SİM pli: UERDZ BILD UERLDZ.', 'Tezim dilin algıyı şekillendiğini ima ediyor. Basitçe yeniden ifade edeyim: kelimeler dünyaları kurar.'],
      ['Examiner', 'And what may we infer from your compelling evidence?', 'end VAT MEY ui inFER from yor kımPELing EVıdıns?', 'Peki ikna edici kanıtınızdan ne sonuç çıkarabiliriz?'],
      ['Anna', 'That bilingual speakers do not just translate — they transform.', 'det bilingUEL SPIIKırz DU NOT CAST trenSLEYT — DEY trensFORM.', 'İki dilli konuşmacıların sadece çevirmediğini — dönüştürdüğünü.'],
      ['Examiner', 'A compelling answer. In contrast to many, you have learned to conclude with precision. Congratulations!', 'e kımPELing ANsır. in KONtrast tu MENi, yu HEV LERND tu kınKLUUD vid prıSIJın. kınGREcyuLEYşınz!', 'İkna edici bir yanıt. Birçoklarının aksine, kesinlikle sonuç çıkmayı öğrenmişsiniz. Tebrikler!'],
    ],
  },
];
