import type { EnRawUnit } from './unitsA';

export const EN_UNITS_B: EnRawUnit[] = [
  {
    id: 'en_mod_b1_17',
    unitNumber: 17,
    levelGroup: 'B1',
    title: 'Fikir Belirtme & Katılma',
    description: 'Görüş belirtme, katılma/ayrılma ve tartışma dili',
    category: 'İletişim',
    color: '#f59e0b',
    icon: '💬',
    grammarExplain: `📌 FİKİR CÜMLELERİ:
1. "I think (that)..." / "In my opinion, ..." — görüş belirtmenin iki ana yolu.
2. Katılmak: "I (completely) agree with you." — "with" şart! Ayrılmak: "I am afraid I disagree."
3. "actually" = aslında (düzeltme getirir); "of course" = elbette; "on the other hand" = öte yandan — tartışmayı zenginleştiren bağlaçlar.`,
    words: [
      ['in my opinion', 'in may ePINyı-n', 'bence', 'Cümle başında virgülle: "In my opinion, ...".'],
      ['agree', 'eGRII', 'katılmak (aynı fikirde olmak)', '"agree WITH somebody", "agree TO a plan".'],
      ['disagree', 'diseGRII', 'aynı fikirde olmamak', 'Kibar ayrılma: "I disagree, because..."'],
      ['believe', 'biLIIV', 'inanmak', '"I believe you." = sana inanıyorum.'],
      ['on the other hand', 'on di ADır HEND', 'öte yandan', 'İki tarafı karşılaştırırken altın kalıp.'],
      ['actually', 'EKçucli', 'aslında', 'Yaygın hata: "actual" ≠ "güncel"!'],
      ['of course', 'ıv KORS', 'elbette, tabii ki', 'Kibar reddetmede: "Of course not."'],
      ['reason', 'RIIZın', 'neden, sebep', '"for this reason" = bu yüzden.'],
      ['point of view', 'POYNT ıv VYU', 'bakış açısı', '"from my point of view".'],
      ['convince', 'kınVINS', 'ikna etmek', '"convince somebody OF something".'],
    ],
    sentences: [
      ['In my opinion, this film is better than the book.', 'Bence bu film kitaptan daha iyi.'],
      ['I agree with you, but let me add one thing.', 'Sana katılıyorum ama bir şey ekleyeyim.'],
      ['Actually, I believe the opposite.', 'Aslında ben tam tersine inanıyorum.'],
      ['On the other hand, the price is quite reasonable.', 'Öte yandan fiyat gayet makul.'],
    ],
    sceneTitle: 'Film or Book?',
    sceneContext: 'Anna ve Mark bir kitabın film uyarlamasını tartışıyor.',
    dialogue: [
      ['Mark', 'In my opinion, the film was a complete disaster.', 'in may ePINyı-n, de FILM UOS e kımPLIT disAS-tır.', 'Bence film tam bir felaketti.'],
      ['Anna', 'Really? I am afraid I disagree. The acting was brilliant.', 'RII-li? ay EM eFEYRD ay diseGRII. di EKTing UOS BRILyınt.', 'Gerçekten mi? Korkarım katılmıyorum. Oyunculuk harikaydı.'],
      ['Mark', 'Maybe, but they changed the whole story!', 'MEYbi, bat DEY CEYNCID de HOUL STORi!', 'Olabilir ama bütün hikayeyi değiştirmişler!'],
      ['Anna', 'That is true. On the other hand, films can never copy books.', 'det İZ TRU. on di ADır HEND, FILMZ ken NEver KOpi BUKS.', 'Doğru. Öte yandan filmler kitapları asla kopyalayamaz.'],
      ['Mark', 'Good point. So, from your point of view, books always win?', 'GUD POYNT. SOU, from yor POYNT ıv VYU, BUKS OLueyz UIN?', 'Mantıklı. Yani senin bakış açından kitaplar hep kazanıyor?'],
    ],
  },
  {
    id: 'en_mod_b1_18',
    unitNumber: 18,
    levelGroup: 'B1',
    title: 'Eğitim & Üniversite',
    description: 'Eğitim hayatı anlatma ve edilgen çatı (passive voice)',
    category: 'Eğitim',
    color: '#38bdf8',
    icon: '🎓',
    grammarExplain: `📌 EDİLGEN ÇATI (PASSIVE VOICE):
1. "be + fiilin 3. hâli": "This theory is taught in every university." (Bu teori her üniversitede öğretiliyor.)
2. İşin YAPANI önemli değilse veya bilinmiyorsa kullanılır: "The exam was cancelled." (Sınav iptal edildi — kim iptal ettiği önemli değil.)
3. Yapanı belirtmek gerekirse "by": "The novel was written by Orwell."`,
    words: [
      ['university', 'yunıVERSıti', 'üniversite', '"at university" (İngiliz) / "in college" (Amerikan).'],
      ['degree', 'diGRII', 'lisans diploması; derece', '"a degree in economics".'],
      ['subject', 'SABcikt', 'ders, konu, bilgi konusu', '"My favourite subject is history."'],
      ['exam', 'igZEM', 'sınav', '"take an exam" = sınava girmek (give değil!).'],
      ['research', 'riSERÇ', 'araştırma', 'Vurgu sondadır; sayılamaz bir isim.'],
      ['graduate', 'GREcyueyt', 'mezun olmak', '"graduate FROM a university".'],
      ['library', 'LAYbreri', 'kütüphane', 'Okunuşu: LAYbreri (lib-RAIRi ✗).'],
      ['lecture', 'LEKçır', 'ders (konferans tipi)', '"give a lecture" = ders vermek.'],
      ['take notes', 'TEYK NOU TS', 'not almak', 'Derslerde hayatta kalan alışkanlık.'],
      ['professor', 'profESır', 'profesör', 'ABD\'de üniversite öğretim üyesi genel adı.'],
    ],
    sentences: [
      ['She graduated from a famous university.', 'Tanınmış bir üniversiteden mezun oldu.'],
      ['The lecture was given by a visiting professor.', 'Dersi konuk bir profesör verdi.'],
      ['You should take notes during the lesson.', 'Ders sırasında not almalısın.'],
      ['My degree is in computer science.', 'Diplomam bilgisayar bilimi alanında.'],
    ],
    sceneTitle: 'Back to School',
    sceneContext: 'Anna, yüksek lisans düşünmesini Mark\'a anlatıyor.',
    dialogue: [
      ['Mark', 'You look tired. Long day?', 'yu LUK TAYırd. LONG DEY?', 'Yorgun görünüyorsun. Uzun gün müydü?'],
      ['Anna', 'Very. I had three lectures and a research meeting.', 'VERi. ay HED TRII LEKçırz end e riSERÇ MIITing.', 'Çok. Üç dersim ve bir araştırma toplantım vardı.'],
      ['Mark', 'By the way, are you still thinking about a master\'s degree?', 'bay de UAY, AR yu STIL TINKing eBAUT e MAS-tırz diGRII?', 'Bu arada, hâlâ yüksek lisans mı düşünüyorsun?'],
      ['Anna', 'Yes. The programme is taught in English, so I need to study hard.', 'YES. de PROUGREM İZ TOT in ING-liş, sou ay NIID tu SADıdi HARD.', 'Evet. Program İngilizce veriliyor, o yüzden çok çalışmam gerek.'],
      ['Mark', 'You will do great. When do you take the entrance exam?', 'yu UİL DU GREYT. Uen du yu TEYK di ENtrans igZEM?', 'Harika yaparsın. Ne zaman giriş sınavına giriyorsun?'],
    ],
  },
  {
    id: 'en_mod_b1_19',
    unitNumber: 19,
    levelGroup: 'B1',
    title: 'Teknoloji & İnternet',
    description: 'Dijital hayat ve present perfect ("have downloaded")',
    category: 'Teknoloji',
    color: '#8b5cf6',
    icon: '📱',
    grammarExplain: `📌 PRESENT PERFECT (have/has + V3):
1. "I have downloaded the app." — geçmişte oldu, sonucu ŞU AN geçerli. Türkçedeki "-dı" ile birebir örtüşmez!
2. Deneyim: "Have you ever used this software?" (Hiçe kullandın mı?)
3. "for + süre" ve "since + başlangıç": "I have had this phone for two years / since 2023."`,
    words: [
      ['device', 'diVAYS', 'cihaz', 'Telefon, tablet, bilgisayar için genel ad.'],
      ['download', 'DAUNloud', 'indirmek', 'Zıttı: "upload" (yüklemek).'],
      ['account', 'eKAUNT', 'hesap', '"create an account" = hesap açmak.'],
      ['password', 'PAS-uOS', 'şifre', 'Tabu: parolanı kimseyle paylaşma!'],
      ['screen', 'SKRIIN', 'ekran', '"screen time" = ekran süresi.'],
      ['online', 'ONlayn', 'çevrim içi', 'Zıttı: "offline".'],
      ['connection', 'kınEKşın', 'bağlantı', '"The connection is weak."'],
      ['update', 'APdeyt', 'güncelleme; güncellemek', '"Install the update."'],
      ['data', 'DEYtı', 'veri', 'Tekil çoğul ikisi de olur; "datum" nadir.'],
      ['charge', 'CARC', 'şarj etmek; ücret', '"My phone is dead — charge it!"'],
    ],
    sentences: [
      ['I have downloaded the app, but it does not open.', 'Uygulamayı indirdim ama açılmıyor.'],
      ['Have you ever used this software before?', 'Bu yazılımı daha önce hiç kullandın mı?'],
      ['My phone needs charging every evening.', 'Telefonum her akşam şarj istiyor.'],
      ['I have had this laptop for three years.', 'Bu laptop bende üç yıldır var.'],
    ],
    sceneTitle: 'Tech Support Call',
    sceneContext: 'Anna, internet sağlayıcısını arıyor.',
    dialogue: [
      ['Agent', 'Good afternoon, tech support. How can I help you?', 'gud AFtırNUUN, TEK sıpORT. hau ken ay HELP yu?', 'İyi günler, teknik destek. Nasıl yardımcı olabilirim?'],
      ['Anna', 'My internet connection has stopped working since this morning.', 'may IN-tırnet kınEKşın hez STOPD UORKing SINS Dis MORning.', 'İnternet bağlantım bu sabahtan beri çalışmıyor.'],
      ['Agent', 'I see. Have you tried restarting the device?', 'ay SII. HEV yu TRAYD riSTARTing de diVAYS?', 'Anladım. Cihazı yeniden başlatmayı denediniz mi?'],
      ['Anna', 'Yes, I have restarted it twice. The screen shows no signal.', 'YES, ay HEV riSTARtid İT TUAIS. de SKRIIN ŞOUZ NOU SİGnıl.', 'Evet, iki kez yeniden başlattım. Ekranda sinyal yok.'],
      ['Agent', 'Then we will send a technician tomorrow. I have created a ticket for you.', 'DEN ui UİL SEND e tekniŞın tuMOrow. ay HEV kriEYtid e TIKit for yu.', 'O zaman yarın bir teknisyen göndereceğiz. Size bir kayıt açtım.'],
    ],
  },
  {
    id: 'en_mod_b1_20',
    unitNumber: 20,
    levelGroup: 'B1',
    title: 'Medya & Haberler',
    description: 'Haber dili ve dolaylı anlatım (reported speech)',
    category: 'Medya',
    color: '#ef4444',
    icon: '📰',
    grammarExplain: `📌 DOLAYLI ANLATIM:
1. Birinin sözünü aktarırken zaman bir derece geriye kayar: "I am tired." → He said (that) he WAS tired.
2. "will" → "would", "can" → "could", "present" → "past".
3. Gazete dilinde bu yapı her yerde: "The minister said the law would change."`,
    words: [
      ['news', 'NYUUZ', 'haber(ler)', 'Tekil görünümlü çoğul: "The news IS good."'],
      ['article', 'ARtikıl', 'makale, yazı', '"an article about climate".'],
      ['journalist', 'CIRnılist', 'gazeteci', 'Vurgu ilk hecede.'],
      ['report', 'riPORT', 'haber; raporlamak', '"according to the report" = rapora göre.'],
      ['headline', 'HEDlayn', 'manşet', 'Haberin koca harfli başlığı.'],
      ['channel', 'ÇENıl', 'kanal', '"a news channel".'],
      ['broadcast', 'BROADkast', 'yayın; yayınlamak', 'Geçmiş: broadcast → broadcast.'],
      ['social media', 'SOUşıl MIdiâ', 'sosyal medya', 'Tekil bir alan adı gibi kullanılır.'],
      ['fake news', 'FEYK NYUUZ', 'sahte haber', 'Doğrulamadan paylaşmamak gerek.'],
      ['subscribe', 'sabSKRAYB', 'abone olmak', '"subscribe to a channel".'],
    ],
    sentences: [
      ['The journalist said the law would change next year.', 'Gazeteci, kanunun gelecek yıl değişeceğini söyledi.'],
      ['According to the report, prices are rising.', 'Rapora göre fiyatlar yükseliyor.'],
      ['Do not believe every headline you read.', 'Okuduğun her manşete inanma.'],
      ['I subscribe to two daily newspapers.', 'İki günlük gazeteye aboneyim.'],
    ],
    sceneTitle: 'Morning News',
    sceneContext: 'Anna kahvaltıda haberleri okuyor.',
    dialogue: [
      ['Mark', 'Anything interesting in the news today?', 'ENiTHING INtıresting in de NYUUZ tuDEY?', 'Bugün haberlerde ilginç bir şey var mı?'],
      ['Anna', 'This article says the city will build a new metro line.', 'Dis ARtikıl SEZ de SITi UİL BILD e NYU MEtro LAYN.', 'Bu yazı şehrin yeni bir metro hattı yapacağını söylüyor.'],
      ['Mark', 'Again? They promised that before the election, too.', 'eGEYN? DEY PROMist det biFOR di iLEKşın, TU.', 'Yine mi? Seçimden önce de bunu vaat etmişlerdi.'],
      ['Anna', 'The mayor said the project had already started.', 'de MEYır sed de PROCEKT HED OLredi STARTID.', 'Belediye başkanı projenin çoktan başladığını söyledi.'],
      ['Mark', 'I will believe it when I see it. Sounds like fake news!', 'ay UİL biLIIV İT UEN ay SII İT. SAUNDS layk FEYK NYUUZ!', 'Görünce inanacağım. Sahte haber gibi geliyor!'],
    ],
  },
  {
    id: 'en_mod_b1_21',
    unitNumber: 21,
    levelGroup: 'B1',
    title: 'İlişkiler & Duygular',
    description: 'Duygu anlatımı ve geçmiş zamanların anlatıdaki dansı (was doing / did)',
    category: 'İlişkiler',
    color: '#f472b6',
    icon: '❤️',
    grammarExplain: `📌 ANLATI ZAMANLARI:
1. Past continuous (was/were + -ing) = sahneyi kurar: "We were talking quietly."
2. Past simple = sahnedeki olayı patlatır: "Suddenly, she stood up and left."
3. İkisi bir arada hikaye anlatmanın temelidir: "While I was walking home, I met an old friend."`,
    words: [
      ['trust', 'TRAST', 'güven(mek)', '"trust somebody" — ilişkilerin temeli.'],
      ['proud', 'PRAUD', 'gururlu', '"proud OF somebody".'],
      ['jealous', 'CELıs', 'kıskanç', '"jealous OF" — kıskandığın şey "of" ile.'],
      ['disappoint', 'disePOINT', 'hayal kırıklığına uğratmak', '"You disappointed me."'],
      ['support', 'sıpORT', 'desteklemek; destek', 'Hem isim hem fiil.'],
      ['argument', 'ARgyumınt', 'tartışma, kavgalar', '"have an argument WITH somebody".'],
      ['apologize', 'ePOLıcayz', 'özür dilemek', '"apologize TO somebody FOR something".'],
      ['forgive', 'forGIV', 'bağışlamak', 'Düzensiz: forgive → forgave → forgiven.'],
      ['secret', 'SIIKrit', 'sır', '"keep a secret" = sırrı saklamak.'],
      ['listener', 'LISınır', 'dinleyici', 'İyi ilişkinin sırrı: iyi bir dinleyici olmak.'],
    ],
    sentences: [
      ['We were talking quietly when she suddenly stood up.', 'Sakince konuşuyorduk ki o aniden ayağa kalktı.'],
      ['I am so proud of you.', 'Sana çok gurur duyuyorum.'],
      ['He apologized for being late again.', 'Yine geç geldiği için özür diledi.'],
      ['While I was walking home, I met an old friend.', 'Eve yürürken eski bir arkadaşla karşılaştım.'],
    ],
    sceneTitle: 'After the Argument',
    sceneContext: 'Mark, dün geceki tartışmadan sonra Anna\'dan özür diliyor.',
    dialogue: [
      ['Mark', 'About last night... I want to apologize.', 'eBAUT LAST NAYT... ay UANT tu ePOLıcayz.', 'Dün gece hakkında... özür dilemek istiyorum.'],
      ['Anna', 'You were really unfair, you know.', 'yu UER RII-li ANfeYR, yu NOU.', 'Gerçekten haksızdın, biliyorsun.'],
      ['Mark', 'I know. I was tired and I said things I did not mean.', 'ay NOU. ay UOS TAYırd end ay SED TINGZ ay DID NOT MIIN.', 'Biliyorum. Yorgundum ve kastetmediğim şeyler söyledim.'],
      ['Anna', 'While you were shouting, I was just trying to explain.', 'UAYL yu UER ŞAUTing, ay UOS CAST TRAYing tu ikSPLEYN.', 'Sen bağırırken ben sadece açıklamaya çalışıyordum.'],
      ['Mark', 'You are right. Can you forgive me?', 'yu AR RAYT. Ken yu forGIV Mİ?', 'Haklısın. Beni bağışlayabilir misin?'],
    ],
  },
  {
    id: 'en_mod_b1_22',
    unitNumber: 22,
    levelGroup: 'B1',
    title: 'Ulaşım & Trafiğe Çıkma',
    description: 'Trafik dili ve çıkarım kipleri (must be / might be / can\'t be)',
    category: 'Şehir & Seyahat',
    color: '#0ea5e9',
    icon: '🚗',
    grammarExplain: `📌 ÇIKARIM KİPLERİ (deduction):
1. "must be" = kesin böyle olmalı: "He must be stuck in traffic." (Tamamen eminim.)
2. "might/could be" = olabilir: "The road might be closed."
3. "can\'t be" = kesinlikle olamaz: "It can\'t be true — I just saw her."`,
    words: [
      ['traffic', 'TREfik', 'trafik', '"traffic JAM" = trafik sıkışıklığı.'],
      ['highway', 'HAYuey', 'otoyol, karayolu', 'İngilizcede "motorway" de denir.'],
      ['petrol', 'PEtrol', 'benzin', 'ABD\'de "gas / gasoline".'],
      ['drive', 'DRAYV', 'araba kullanmak', '"drive a car" ama "ride a bike/motorbike".'],
      ['passenger', 'PESıncır', 'yolcu', 'Şoför olmayan herkes.'],
      ['roundabout', 'RAUNdeBAUT', 'dönel kavşak', 'İngiliz ulaşımının simgesi!'],
      ['rush hour', 'RAŞ AUır', 'trafiğin en yoğun saati', '"in the rush hour" = yoğun saatte.'],
      ['lane', 'LEYN', 'şerit', '"bus lane" = otobüs şeridi.'],
      ['parking', 'PARking', 'park etme; otopark', '"No parking" = park etmek yasak.'],
      ['fine', 'FAYN', 'ceza; iyiyim', 'Kavga ikilemi: "a parking fine" = park cezası.'],
    ],
    sentences: [
      ['He must be stuck in traffic.', 'Mutlaka trafikte sıkışmıştır.'],
      ['The road might be closed because of the snow.', 'Yol kardan dolayı kapalı olabilir.'],
      ['I got a parking fine in the city centre.', 'Şehir merkezinde park cezası yedim.'],
      ['Avoid the highway during the rush hour.', 'Yoğun saatte otoyoldan uzak dur.'],
    ],
    sceneTitle: 'Stuck in Traffic',
    sceneContext: 'Mark geç kalıyor ve telefonda Anna\'ya durumu anlatıyor.',
    dialogue: [
      ['Anna', 'Where are you? The film starts in ten minutes!', 'UER AR yu? de FILM STARTS in TEN MİNits!', 'Neredesin? Film on dakika içinde başlıyor!'],
      ['Mark', 'I am on the highway, but nothing is moving.', 'ay EM on de HAYuey, bat NAting İZ MUUving.', 'Otoyoldayım ama hiçbir şey hareket etmiyor.'],
      ['Anna', 'There must be an accident. The radio said the road was busy.', 'DER MAS bi en EKSıdınt. de REYdio sed de ROUD UOS BIzi.', 'Mutlaka bir kaza olmalı. Radyo yolu kalabalık demişti.'],
      ['Mark', 'Or it might just be the rush hour. Everyone is leaving work now.', 'OR İT MAYT CAST Bİ di RAŞ AUır. EVriuan İZ LIIving UORK NAU.', 'Ya da sadece yoğun saat. Herkes şimdi işten çıkıyor.'],
      ['Anna', 'You can\'t make it on time. Let us buy tickets for the next show.', 'yu KANT MEYK İT on TAYM. LET as BAY TIKits for de NEKS ŞOU.', 'Zamanında gelemezsin. Bir sonraki seans için bilet alalım.'],
    ],
  },
  {
    id: 'en_mod_b1_23',
    unitNumber: 23,
    levelGroup: 'B1',
    title: 'Kültür & Sanat',
    description: 'Sanat etkinlikleri ve ilgiçli cümleler (relative clauses)',
    category: 'Kültür & Sanat',
    color: '#a78bfa',
    icon: '🎭',
    grammarExplain: `📌 RELATIVE CLAUSES (which / who / where):
1. "which" eşyalar için: "The painting, which was painted in 1890, is priceless."
2. "who" insanlar için: "The artist who made this is only twenty."
3. "where" yerler için: "The gallery where we met is closing down."
4. Tanımlayıcı bilgide virgül YOK; ek açıklamada virgül VAR.`,
    words: [
      ['exhibition', 'eksiBIşın', 'sergi', '"an exhibition of modern art".'],
      ['gallery', 'GELıri', 'galeri', '"art gallery" = sanat galerisi.'],
      ['novel', 'NOVıl', 'roman', 'Uzun kurgu; kısa olan "short story".'],
      ['poet', 'POUıt', 'şair', 'Şiirin kendisi: "poem" — karıştırma!'],
      ['audience', 'ODiyıns', 'seyirci, izleyici', 'Toplu tekil: "The audience WAS amazed."'],
      ['stage', 'STEYC', 'sahne', '"on stage" = sahnedeyken.'],
      ['performance', 'pırFORmıns', 'performans, gösteri', '"a live performance".'],
      ['masterpiece', 'MAS-tırpis', 'başyapıt', 'Master + piece birleşik.'],
      ['critic', 'KRITik', 'eleştirmen', '"art critic" = sanat eleştirmeni.'],
      ['inspiration', 'inspiREYşın', 'ilham', '"a source of inspiration".'],
    ],
    sentences: [
      ['The artist who made this is only twenty.', 'Bunu yapan sanatçı daha yirmi yaşında.'],
      ['The gallery where we met is closing down.', 'Tanıştığımız galeri kapanıyor.'],
      ['Last night\'s performance was breathtaking.', 'Dün geceki performans nefes kesiciydi.'],
      ['This novel is considered a masterpiece.', 'Bu roman başyapıt sayılıyor.'],
    ],
    sceneTitle: 'At the Exhibition',
    sceneContext: 'Anna ve Mark bir modern sanat sergisinde geziyor.',
    dialogue: [
      ['Anna', 'This painting is incredible. Look at the colours!', 'Dis PEYnting İZ inKREDıbıl. LUK et de KAH-lırz!', 'Bu tablo inanılmaz. Şu renklere bak!'],
      ['Mark', 'The artist who made this is only twenty years old.', 'di ARtist hu MEYD Dis İZ ONli TUEnti YIRZ OLD.', 'Bunu yapan sanatçı daha yirmi yaşında.'],
      ['Anna', 'Twenty? Unbelievable. This must be the exhibition everyone is talking about.', 'TUEnti? ANbilihVEYbıl. Dis MAS Bİ di eksiBIşın EVriuan İZ TOKing eBAUT.', 'Yirmi mi? İnanılmaz. Bu, herkesin konuştuğu sergi olmalı.'],
      ['Mark', 'The critic from The Times called it "a modern masterpiece".', 'de KRITik from di TAYMS KOLD İT "e MODırn MAS-tırpis".', 'The Times\'ın eleştirmeni buna "modern bir başyapıt" dedi.'],
      ['Anna', 'Well, it is certainly an inspiration. Let us see the next room!', 'UEL, İT İZ SERtınli en inspiREYşın. LET as SII di NEKS RUUM!', 'Kesinlikle bir ilham kaynağı. Hadi bir sonraki salona bakalım!'],
    ],
  },
  {
    id: 'en_mod_b1_24',
    unitNumber: 24,
    levelGroup: 'B1',
    title: 'Planlar & Gelecek',
    description: 'Gelecek konuşmaları ve 1. tip koşul cümleleri',
    category: 'Gelecek Planları',
    color: '#22c55e',
    icon: '🎯',
    grammarExplain: `📌 GELECEK ve 1. TİP KOŞUL:
1. Plan → "be going to": "I am going to apply for that job." (Kararım hazır.)
2. Anlık karar/tahmin → "will": "I will help you." / "It will rain."
3. 1. Koşul: "IF + present simple, will + fiil": "If I pass the interview, I will move to Berlin." — Türkçedeki "-sa/-irse ... -acak" yapısının birebir karşılığı.`,
    words: [
      ['plan', 'PLEN', 'plan', '"make a plan" / "have a plan".'],
      ['goal', 'GOUL', 'hedef', '"set a goal" = hedef koymak.'],
      ['achieve', 'eÇIIV', 'başarmak, elde etmek', '"achieve a goal" — hedefe ulaşmak.'],
      ['improve', 'imPRUUV', 'geliştirmek', '"improve your English".'],
      ['decide', 'diSAYD', 'karar vermek', '"decide ON something" ya da direkt nesne.'],
      ['look forward to', 'LUK FORuırd tu', 'dört gözle beklemek', 'Sonrası -ing: "looking forward to seeing you".'],
      ['in case', 'in KEYS', '-durumunda, ihtimaline karşı', '"Take an umbrella, in case it rains."'],
      ['apply for', 'ePLAY for', 'başvurmak', 'İş, burs, vize: hepsi için "apply for".'],
      ['opportunity', 'opırTYUUnıti', 'fırsat', '"a great opportunity" kalıbı.'],
      ['ambition', 'emBIŞın', 'hırs, iddialı hedef', '"lifelong ambition" = hayat boyu hayal.'],
    ],
    sentences: [
      ['I am going to apply for that job.', 'O işe başvuracağım.'],
      ['If I pass the interview, I will move to Berlin.', 'Görüşmeyi geçersem Berlin\'e taşınacağım.'],
      ['We are looking forward to seeing you.', 'Seni görmek için dört gözle bekliyoruz.'],
      ['She decided to improve her English this year.', 'Bu yıl İngilizcesini geliştirmeye karar verdi.'],
    ],
    sceneTitle: 'New Year Plans',
    sceneContext: 'Yeni yıl yaklaşıyor; Anna ve Mark planlarını paylaşıyor.',
    dialogue: [
      ['Mark', 'So, what are your plans for the new year?', 'SOU, VAT AR yor PLANZ for de NYU YIR?', 'Peki, yeni yıl için planların neler?'],
      ['Anna', 'I am going to apply for a master\'s programme abroad.', 'ay EM GOUING tu ePLAY for e MAS-tırz PROUGREM eBROD.', 'Yurtdışında bir yüksek lisans programına başvuracağım.'],
      ['Mark', 'That is a big step! What will you do if you get in?', 'det İZ e BIG STEP! VAT UİL yu DU İF yu GET IN?', 'Bu büyük bir adım! Kazanırsan ne yapacaksın?'],
      ['Anna', 'If I get in, I will move in September. I am already looking forward to it.', 'İF ay GET IN, ay UİL MUUV in sepTEMbır. ay EM OLredi LUKing FORuırd tu İT.', 'Kazanırsam Eylülde taşınacağım. Şimdiden dört gözle bekliyorum.'],
      ['Mark', 'Amazing! That was your ambition for years.', 'eMEYzing! det UOS yor emBIŞın for YIRZ.', 'Harika! Bu yıllardır hayalin idi.'],
    ],
  },
  {
    id: 'en_mod_b2_25',
    unitNumber: 25,
    levelGroup: 'B2',
    title: 'İş Dünyası & Müzakere',
    description: 'Anlaşma dili ve 2. tip koşul cümleleri',
    category: 'İş Dünyası',
    color: '#6366f1',
    icon: '🤝',
    grammarExplain: `📌 2. TİP KOŞUL (hipotetik):
1. Yapı: "If + past simple, would + fiil": "If we signed the contract today, we would get a discount."
2. Gerçekçilik az, nezaket yüksek: "If I were you, I would wait." ("was" yerine "were" — kalıp!).
3. Müzakerede muğlaklık: "We might consider..." / "That would depend on the terms." — net evet/hayır yerine diplomasi.`,
    words: [
      ['deal', 'DIIL', 'anlaşma', '"make a deal" = anlaşma yapmak.'],
      ['contract', 'KONtrEKT', 'sözleşme', 'Vurgu: isim KONtrEKT, fiil kınTRAKT.'],
      ['negotiate', 'niGOUSieyt', 'müzakere etmek', '"negotiate with somebody".'],
      ['deadline', 'DEDlayn', 'teslim tarihi', '"meet a deadline" = teslim yetişir (miss = kaçırır).'],
      ['profit', 'PROfit', 'kâr', 'Zıttı: "loss" (zarar).'],
      ['invest', 'inVEST', 'yatırım yapmak', '"invest IN something".'],
      ['partner', 'PARTnır', 'ortak', '"business partner" = iş ortağı.'],
      ['proposal', 'prıPOUzıl', 'teklif, öneri', 'Resmi: "proposal" > "offer".'],
      ['terms', 'TERMZ', 'şartlar', '"on these terms" = bu şartlarla.'],
      ['agreement', 'eGRIImınt', 'anlaşma, mutabakat', '"reach an agreement" = anlaşmaya varmak.'],
    ],
    sentences: [
      ['If we signed the contract today, we would get a discount.', 'Sözleşmeyi bugün imzalasak indirim alırdık.'],
      ['We might consider your proposal next quarter.', 'Teklifinizi gelecek çeyrekte değerlendirebiliriz.'],
      ['The deadline is tight, but the profit is worth it.', 'Teslim tarihi sıkı ama kâr buna değer.'],
      ['If I were you, I would negotiate the terms.', 'Yerinde olsam şartları müzakere ederdim.'],
    ],
    sceneTitle: 'The Negotiation',
    sceneContext: 'Mark, bir tedarikçi ile fiyat müzakeresi yapıyor.',
    dialogue: [
      ['Supplier', 'Our proposal is fifty thousand for the full package.', 'AUR prıPOUzıl İZ FIFti DAUzınd for de FUL PEKıc.', 'Teklifimiz tam paket için elli bin.'],
      ['Mark', 'That is beyond our budget. If we paid that much, we would need a longer deadline.', 'det İZ biYOND aur BADcit. İF ui PED det MAÇ, ui UUD NIID e LONGır DEDlayn.', 'Bu bütçemizi aşıyor. O kadar ödersek daha uzun bir teslim süresine ihtiyacımız olurdu.'],
      ['Supplier', 'We might lower the price if you ordered in bulk.', 'ui MAYT LOUır de PRAYS İF yu ORdırD in BALK.', 'Toplu sipariş verirseniz fiyatı düşürebiliriz.'],
      ['Mark', 'Interesting. What discount would you offer for a two-year partnership?', 'INtıresting. VAT DISkaunt UUD yu OFır for e TU-YIR PARTnırşip?', 'İlginç. İki yıllık bir ortaklık için ne kadar indirim önerirsiniz?'],
      ['Supplier', 'For a loyal partner like you, we could reach an agreement at forty.', 'for e LOYıl PARTnır layk yu, ui KUD RIİç en eGRIImınt et FORti.', 'Sizin gibi sadık bir ortak için kırkta anlaşabiliriz.'],
    ],
  },
  {
    id: 'en_mod_b2_26',
    unitNumber: 26,
    levelGroup: 'B2',
    title: 'Çevre & Doğa',
    description: 'Çevre sorunları ve neden-sonuç bağlaçları',
    category: 'Çevre',
    color: '#10b981',
    icon: '🌍',
    grammarExplain: `📌 NEDEN-SONUÇ BAĞLAÇLARI:
1. Sonuç başta: "Therefore / As a result / Consequently, ..." → cümle başı, virgüllü.
2. Neden başta: "Because of + isim" (çünkü) vs "Due to + isim" (nedeniyle).
3. "Although" (eğer -sa da) ile "Despite" (-e rağmen) ayrımı: Although + cümle, Despite + isim: "Despite the warnings, ..."`,
    words: [
      ['climate change', 'KLAYmit CEYNC', 'iklim değişikliği', 'En büyük çevre sorununun adı.'],
      ['pollution', 'pılUUşın', 'kirlilik', '"air pollution" = hava kirliliği.'],
      ['recycle', 'riSAYKıl', 'geri dönüşüm(e almak)', '"recycle plastic" — fiil de isim de.'],
      ['waste', 'UEYST', 'atık; israf etmek', '"a waste of time" = zaman kaybı.'],
      ['renewable', 'rinyUUebıl', 'yenilenebilir', '"renewable energy" = yenilenebilir enerji.'],
      ['carbon footprint', 'KARbon FUTprint', 'karbon ayak izi', 'Bireysel emisyon ölçüsü.'],
      ['drought', 'DRAUT', 'kuraklık', 'Okunuşu dikkat: "draut".'],
      ['flood', 'FLAD', 'sel, taşkın', 'Zıttı gibi görünen iki afet: drought ↔ flood.'],
      ['ecosystem', 'IYkousistım', 'ekosistem', '"a fragile ecosystem" = kırılgan ekosistem.'],
      ['sustainable', 'sısTEYnıbıl', 'sürdürülebilir', 'Çevre tartışmalarının anahtar kelimesi.'],
    ],
    sentences: [
      ['Because of pollution, the river is dying.', 'Kirlilik yüzünden nehir ölüyor.'],
      ['Therefore, we must switch to renewable energy.', 'Bu yüzden yenilenebilir enerjiye geçmeliyiz.'],
      ['Despite the warnings, emissions kept rising.', 'Uyarılara rağmen emisyonlar artmaya devam etti.'],
      ['Recycling reduces your carbon footprint.', 'Geri dönüşüm karbon ayak izini küçültür.'],
    ],
    sceneTitle: 'The Town Hall Debate',
    sceneContext: 'Belediye binasında çevre tartışması.',
    dialogue: [
      ['Speaker', 'Because of climate change, droughts are becoming more frequent.', 'bikoz ıv KLAYmit CEYNC, DRAUTS AR bikAMing MOR FRIIKuent.', 'İklim değişikliği yüzünden kuraklıklar sıklaşıyor.'],
      ['Anna', 'And floods follow the same pattern. Our ecosystem is fragile.', 'end FLADS FOLou de SEYM PETın. AUR IYkousistım İZ FRAcııl.', 'Seller de aynı örüntü izliyor. Ekosistemimiz kırılgan.'],
      ['Speaker', 'Therefore, the city plans to invest in renewable energy.', 'DERfor, de SITI PLANZ tu inVEST in rinyUUebıl ENıcıti.', 'Bu nedenle şehir yenilenebilir enerjiye yatırım yapmayı planlıyor.'],
      ['Mark', 'What about recycling programmes for households?', 'Vat eBAUT riSAYKling PROUGREMZ for HAUSholds?', 'Haneler için geri dönüşüm programları ne olacak?'],
      ['Speaker', 'Despite our limited budget, we will launch one next month.', 'disPAIT aur LIMıtık BADcit, ui UİL LONÇ UAN NEKS MANT.', 'Sınırlı bütçemize rağmen gelecek ay bir tane başlatacağız.'],
    ],
  },
  {
    id: 'en_mod_b2_27',
    unitNumber: 27,
    levelGroup: 'B2',
    title: 'Bilim & İnovasyon',
    description: 'Bilimsel dil, kesinlik dereceleri (hedging) ve edilgen',
    category: 'Bilim',
    color: '#06b6d4',
    icon: '🔬',
    grammarExplain: `📌 BİLİMSEL TEDİRLİLİK (HEDGING):
1. Bilim insanları asla "This is true" demez; "The data SUGGEST that..." der.
2. Kesinlik sıralaması: will → must → may/might → could → appears to → seems to.
3. Edilgen + geçmiş: "The experiment was conducted twice." (Deney iki kez yapıldı.) — kim yaptığından çok yapılandığı önemlidir.`,
    words: [
      ['experiment', 'ikSPERımınt', 'deney', '"conduct an experiment" = deney yapmak.'],
      ['theory', 'TIYıri', 'kuram, teori', 'Bilimde "teori" = kanıtlanmış açıklama, tahmin değil!'],
      ['evidence', 'EVıdıns', 'kanıt', 'Sayılamaz: "many evidences" ✗, "much evidence" ✓.'],
      ['discovery', 'disKAVıri', 'buluş, keşif', '"a scientific discovery".'],
      ['laboratory', 'lıBORıtıri', 'laboratuvar', 'Konuşma dilinde kısaca "lab".'],
      ['data', 'DEYtı', 'veri', '"The data suggest..." — bilimsel çoğul kullanım.'],
      ['hypothesis', 'hayPOtisıs', 'hipotez', 'Çoğulu: hypotheses.'],
      ['analyze', 'ENılıayz', 'analiz etmek', 'İsim hâli: "analysis".'],
      ['breakthrough', 'BREYKtru', 'büyük atılım', '"a medical breakthrough".'],
      ['researcher', 'riSERçır', 'araştırmacı', 'Bilim insanının günlük unvanı.'],
    ],
    sentences: [
      ['The experiment was conducted twice to confirm the results.', 'Sonuçları doğrulamak için deney iki kez yapıldı.'],
      ['The data suggest a clear connection between diet and health.', 'Veriler, beslenme ve sağlık arasında net bir bağa işaret ediyor.'],
      ['This discovery could be a real breakthrough.', 'Bu keşif gerçek bir atılım olabilir.'],
      ['The evidence appears to support the hypothesis.', 'Kanıt hipotezi destekliyor gibi görünüyor.'],
    ],
    sceneTitle: 'The Research Team',
    sceneContext: 'Bir laboratuvarda araştırma ekibi sonuçları değerlendiriyor.',
    dialogue: [
      ['Researcher', 'We have finished analyzing the data from the experiment.', 'ui HEV FINIŞT ENılıayzing de DEYtı from di ikSPERımınt.', 'Deneyden gelen verilerin analizini bitirdik.'],
      ['Anna', 'Do the results support our hypothesis?', 'Du di riZALTS sıpORT AUR hayPOtisıs?', 'Sonuçlar hipotezimizi destekliyor mu?'],
      ['Researcher', 'The evidence seems to point that way, but we need more tests.', 'di EVıdıns SIIMZ tu POYNT det UEY, bat ui NIID MOR TESTS.', 'Kanıt oraya işaret ediyor gibi, ama daha çok teste ihtiyacımız var.'],
      ['Mark', 'If this is confirmed, it might be a medical breakthrough.', 'İF Dis İZ kınFERMD, İT MAYT Bİ e MEDikıl BREYKtru.', 'Bu doğrulanırsa tıbbi bir atılım olabilir.'],
      ['Researcher', 'Exactly. That is why the study will be conducted again next month.', 'igZEKTli. det İZ UAY de SADı UİL Bİ kınDAKTıd eGEYN NEKS MANT.', 'Aynen öyle. Bu yüzden çalışma gelecek ay tekrar yürütülecek.'],
    ],
  },
  {
    id: 'en_mod_b2_28',
    unitNumber: 28,
    levelGroup: 'B2',
    title: 'Politika & Toplum',
    description: 'Kamuoyu dili ve isim yapımı (nominalization)',
    category: 'Toplum',
    color: '#f43f5e',
    icon: '🏛️',
    grammarExplain: `📌 İSİMLEŞTİRME (NOMINALIZATION):
1. Fiili isme çevirip cümleyi resmileştir: decide → decision, elect → election, govern → government.
2. "They decided quickly." → "Their quick decision..." — resmi metinlerde bu yoğun kullanılır.
3. Seçim dili: "cast a vote" (oy kullanmak), "run for office" (aday olmak), "call an election" (seçim ilan etmek).`,
    words: [
      ['government', 'GAVınment', 'hükümet', 'Vurgu ilk hecede: GAV-ın-mınt.'],
      ['policy', 'POLısi', 'politika, siyasa', '"government policy" = hükümet politikası.'],
      ['election', 'iLEKşın', 'seçim', '"call an election" = seçim ilan etmek.'],
      ['vote', 'VOU T', 'oy; oy vermek', '"cast your vote" = oyunu kullan.'],
      ['rights', 'RAYTS', 'haklar', '"human rights" = insan hakları.'],
      ['freedom', 'FRIIdım', 'özgürlük', '"freedom of speech" = ifade özgürlüğü.'],
      ['tax', 'TEKS', 'vergi', '"income tax" = gelir vergisi.'],
      ['citizen', 'SITizın', 'vatandaş', '"senior citizen" = kıdemli/yaşlı vatandaş.'],
      ['debate', 'diBEYT', 'tartışma; münazara', '"a heated debate" = ateşli tartışma.'],
      ['reform', 'riFORM', 'ıslahat, reform', '"carry out reforms" = reform yapmak.'],
    ],
    sentences: [
      ['The government announced a new tax policy.', 'Hükümet yeni bir vergi politikası duyurdu.'],
      ['Every citizen should cast their vote.', 'Her vatandaş oyunu kullanmalı.'],
      ['The debate over the reform lasted all night.', 'Reform üzerindeki tartışma bütün gece sürdü.'],
      ['Freedom of speech is a fundamental right.', 'İfade özgürlüğü temel bir haktır.'],
    ],
    sceneTitle: 'Election Night',
    sceneContext: 'Seçim gecesi sonuçları televizyon başında izliyorlar.',
    dialogue: [
      ['Mark', 'The results are coming in. The reform party is ahead.', 'di riZALTS AR KAMing IN. di riFORM PARti İZ eHED.', 'Sonuçlar gelmeye başladı. Reform partisi önde.'],
      ['Anna', 'Turnout is high — citizens seem to want change.', 'TERNaut İZ HAY — SITizınz SIIM tu UANT CEYNC.', 'Katılım yüksek — vatandaşlar değişim istiyor anlaşılan.'],
      ['Mark', 'The government will have to rethink its tax policy.', 'de GAVınment UİL HEV tu riTINK its TEKS POLısi.', 'Hükümet vergi politikasını yeniden düşünmek zorunda kalacak.'],
      ['Anna', 'There will be a heated debate in parliament tomorrow.', 'DER UİL Bİ e HIItıd diBEYT in PARlımınt tuMOrow.', 'Yarın parlamentoda ateşli bir tartışma olacak.'],
      ['Mark', 'As long as our rights are protected, I am happy.', 'ez LONG ez aur RAYTS AR prıTEKTıd, ay EM HEPi.', 'Haklarımız korunduğu sürece ben memnunum.'],
    ],
  },
  {
    id: 'en_mod_b2_29',
    unitNumber: 29,
    levelGroup: 'B2',
    title: 'Psikoloji & Davranış',
    description: 'İç dünyayı anlatma ve geçmiş kipler (should have / could have)',
    category: 'Psikoloji',
    color: '#c084fc',
    icon: '🧠',
    grammarExplain: `📌 GEÇMİŞE YÖNELİK KİPLER:
1. "should have + V3" = keşke yapsaydım (eleştiri/pişmanlık): "I should have studied harder."
2. "could have + V3" = yapabilirdim ama yapmadım: "We could have won."
3. "must have + V3" = kesin öyle olmuş olmalı (çıkarım): "She must have forgotten."`,
    words: [
      ['behaviour', 'biHEYvyır', 'davranış', 'ABD yazımı: "behavior".'],
      ['conscious', 'KONşıs', 'bilinçli, farkında', '"conscious decision" = bilinçli karar.'],
      ['anxiety', 'engZAYıti', 'kaygı, endişe', '"suffer from anxiety".'],
      ['habit', 'HEBit', 'alışkanlık', '"break a habit" = alışkanlıktan kurtulmak.'],
      ['motivation', 'moutiVEYşın', 'motivasyon', 'Vurgu sondan bir önceki hecede.'],
      ['therapy', 'TERıpi', 'terapi', '"go to therapy" = terapiye gitmek.'],
      ['attitude', 'ETityud', 'tutum, tavır', '"a positive attitude".'],
      ['personality', 'pırSOnelıti', 'kişilik', '"an outgoing personality" = dışa dönük kişilik.'],
      ['perceive', 'pırSIIV', 'algılamak', 'İsim hâli: "perception".'],
      ['cope with', 'KOUP vid', 'başa çıkmak', '"cope with stress" = stresle başa çıkmak.'],
    ],
    sentences: [
      ['I should have studied psychology years ago.', 'Yıllar önce psikoloji okumalıydım.'],
      ['She must have forgotten the appointment.', 'Randevuyu unutmuş olmalı.'],
      ['Meditation helps you cope with anxiety.', 'Meditasyon kaygıyla başa çıkmaya yardım eder.'],
      ['Old habits are hard to break.', 'Eski alışkanlıklardan kurtulmak zordur.'],
    ],
    sceneTitle: 'A Conversation About Habits',
    sceneContext: 'Anna, yeni yıl kararları ve alışkanlıklar üzerine konuşuyor.',
    dialogue: [
      ['Mark', 'I should have quit smoking years ago. Now it is a real habit.', 'ay ŞUD heV KUIT SMOUking YIRZ eGO. NAU İT İZ e RIİL HEBit.', 'Yıllar önce bırakmalıydım sigarayı. Şimdi gerçek bir alışkanlık oldu.'],
      ['Anna', 'The first step is conscious: you must notice when you smoke.', 'de FERST STEP İZ KONşıs: yu MAS NOtis UEN yu SMOUK.', 'İlk adım bilinçli: ne zaman içtiğini fark etmelisin.'],
      ['Mark', 'My therapist says motivation comes and goes.', 'may TERapist SEZ moutiVEYşın KAMZ end GOUS.', 'Terapistim motivasyonun gelip gittiğini söylüyor.'],
      ['Anna', 'True. I could have given up running many times, but I did not.', 'TRU. ay KUD heV GIVın AP RANing MENi TAYMZ, bat ay DID NOT.', 'Doğru. Koşuyu birçok kez bırakabilirdim ama bırakmadım.'],
      ['Mark', 'That is the attitude! How do you cope with the hard days?', 'det İZ di ETityud! hau du yu KOUP vid di HARD DEYZ?', 'İşte bu tutum! Zor günlerle nasıl başa çıkıyorsun?'],
    ],
  },
  {
    id: 'en_mod_b2_30',
    unitNumber: 30,
    levelGroup: 'B2',
    title: 'Edebiyat & Anlatıcılık',
    description: 'Edebi terimler ve past perfect ile derin anlatı',
    category: 'Edebiyat',
    color: '#f59e0b',
    icon: '📚',
    grammarExplain: `📌 PAST PERFECT (had + V3):
1. Geçmişteki geçmiş: "By the time the police arrived, the thief had already escaped."
2. Anlatıda geriye dönüş (flashback) kurar: "She opened the letter. She had waited for this moment for years."
3. Türkçedeki "-mıştı" zamanının karşılığıdır: kaçmıştı, yazmıştı, gelmişti.`,
    words: [
      ['plot', 'PLOT', 'konu, olay örgüsü', '"the plot thickens" = olaylar karmaşıklaşıyor.'],
      ['character', 'KERıktır', 'karakter, karakter', '"main character" = ana karakter.'],
      ['setting', 'SETing', 'mekân, dekor', 'Hikâyenin nerede geçtiği.'],
      ['metaphor', 'MEtıfor', 'mecaz, metafor', '"Time is money" bir metafordur.'],
      ['narrative', 'NERıtiv', 'anlatı', '"a first-person narrative" = birinci şahıs anlatı.'],
      ['theme', 'TIIM', 'tema, ana fikir', 'Konu değil, ileti: "the theme of loss".'],
      ['chapter', 'ÇEPtır', 'bölüm', '"the final chapter" = son bölüm.'],
      ['quote', 'KOU T', 'alıntı yapmak; alıntı', '"a quote from Shakespeare".'],
      ['fiction', 'FİKşın', 'kurmaca', 'Zıttı: "non-fiction" (kurgu dışı).'],
      ['climax', 'KLAYmeks', 'doruk nokta', 'Hikâyenin gerilimin zirvesi.'],
    ],
    sentences: [
      ['By the time the police arrived, the thief had already escaped.', 'Polis geldiğinde hırsız çoktan kaçmıştı.'],
      ['The novel explores the theme of loneliness.', 'Roman yalnızlık temasını işliyor.'],
      ['She opened the letter she had waited for years.', 'Yıllardır beklediği mektubu açtı.'],
      ['The climax of the story is unforgettable.', 'Hikâyenin doruk noktası unutulmaz.'],
    ],
    sceneTitle: 'The Book Club',
    sceneContext: 'Kitap kulübü toplantısında tartışma.',
    dialogue: [
      ['Anna', 'So, what did you think of the ending?', 'SOU, VAT did yu TINK ıv di ENding?', 'Peki, sonda ne düşündün?'],
      ['Mark', 'Brilliant! By the time the truth came out, the reader had already fallen in love with the villain.', 'BRILyınt! bay de TAYM di TRU KEYM AUT, di RIIdır HED OLredi FOLın in LAV vid di VILın.', 'Brilliant! Gerçek ortaya çıktığında okur kötü karaktere çoktan aşık olmuştu.'],
      ['Anna', 'The whole narrative is a metaphor for grief, in my opinion.', 'de HOUL NERıtiv İZ e MEtıfor for GRIF, in may ePINyı-n.', 'Bence bütün anlatı bir yas metaforu.'],
      ['Mark', 'And the setting — that lonely island! The theme fits perfectly.', 'end di SETing — det LOUNli AYlınd! di TIIM FITS PERfiktli.', 'Bir de mekân — o yalnız ada! Tema mükemmel uyuşuyor.'],
      ['Anna', 'Let us choose the next book before the club closes.', 'LET as ÇUUZ di NEKS BUK biFOR de KLAB KLOUZız.', 'Kulüp kapanmadan bir sonraki kitabı seçelim.'],
    ],
  },
  {
    id: 'en_mod_b2_31',
    unitNumber: 31,
    levelGroup: 'B2',
    title: 'Hukuk & Adalet',
    description: 'Mahkeme dili ve resmi edilgen yapılar',
    category: 'Hukuk',
    color: '#64748b',
    icon: '⚖️',
    grammarExplain: `📌 HUKUK DİLİNDE EDİLGEN:
1. Mahkeme dili neredeyse tamamen edilgendir: "The defendant was found guilty." (Sanık suçlu bulundu.)
2. Resmi kipler: "shall" (yükümlülük), "may" (izin), "must not" (yasak).
3. "charged with" (ile suçlanmak), "accused of" (ile itham edilmek) — edatları ezberle!`,
    words: [
      ['court', 'KORT', 'mahkeme', '"appear in court" = mahkemeye çıkmak.'],
      ['judge', 'CAC', 'yargıç; yargılamak', '"The judge ruled that..."'],
      ['evidence', 'EVıdıns', 'delil, kanıt', '"The evidence was dismissed."'],
      ['lawyer', 'LOYır', 'avukat', '"hire a lawyer" = avukat tutmak.'],
      ['trial', 'TRAYıl', 'duruşma, yargılama', '"a fair trial" = adil yargılama.'],
      ['guilty', 'GILti', 'suçlu', 'Zıttı: "innocent" (masum).'],
      ['sentence', 'SENtıns', 'hüküm; ceza vermek', 'Anlam kayması: cümle ↔ ceza!'],
      ['appeal', 'ePIIL', 'istinaf, temyiz; itiraz etmek', '"appeal against a decision".'],
      ['witness', 'UITnıs', 'tanık', '"a key witness" = kilit tanık.'],
      ['verdict', 'VERdikt', 'hüküm, karar', '"reach a verdict" = karara varmak.'],
    ],
    sentences: [
      ['The defendant was found guilty by the jury.', 'Sanık jüri tarafından suçlu bulundu.'],
      ['The key witness changed her testimony.', 'Kilit tanık ifadesini değiştirdi.'],
      ['His lawyer promised to appeal the verdict.', 'Avukatı karara itiraz edeceğini söyledi.'],
      ['Everyone deserves a fair trial.', 'Herkes adil bir yargılamayı hak eder.'],
    ],
    sceneTitle: 'The Verdict',
    sceneContext: 'Yüksek profilli bir davanın son duruşması.',
    dialogue: [
      ['Reporter', 'The jury has reached a verdict after three days.', 'de CURI hez RIİÇD e VERdikt AFtır TRII DEYZ.', 'Jüri üç gün sonra bir karara vardı.'],
      ['Anna', 'Do you think the defendant will be found guilty?', 'Du yu TINK di difENDınt UİL Bİ FAUND GILti?', 'Sanığın suçlu bulunacağını mı düşünüyorsun?'],
      ['Reporter', 'The evidence was strong, but the defence lawyer was impressive.', 'di EVıdıns UOS STRONG, bat di difENS LOYır UOS imPREsiv.', 'Deliller güçlüydü ama savunma avukatı etkileyiciydi.'],
      ['Mark', 'And if the verdict is guilty, will there be an appeal?', 'End İF di VERdikt İZ GILti, UİL DER Bİ en ePIIL?', 'Peki hüküm suçlu olursa itiraz olacak mı?'],
      ['Reporter', 'Almost certainly. This trial is far from over.', 'OLmost SERtınli. Dis TRAYıl İZ FAR from OUvır.', 'Neredeyse kesin. Bu yargılama daha yeni başlıyor.'],
    ],
  },
  {
    id: 'en_mod_b2_32',
    unitNumber: 32,
    levelGroup: 'B2',
    title: 'Pazarlama & Tüketim',
    description: 'Reklam dili ve fiil + -ing / to-fiil ayrımı',
    category: 'İş Dünyası',
    color: '#ec4899',
    icon: '📣',
    grammarExplain: `📌 GERUND ve INFINITIVE:
1. Bazı fiiller sonrası -ing alır: enjoy, avoid, consider, suggest → "consider buying".
2. Bazıları to-fiil ister: decide, hope, plan, promise → "decide to buy".
3. Anlam değiştirir: "stop smoking" (bırakmak) ≠ "stop to smoke" (içmek için durmak)!`,
    words: [
      ['brand', 'BREND', 'marka', '"brand loyalty" = marka sadakati.'],
      ['advertise', 'EDvırtayz', 'reklamını yapmak', 'İsim: "advertisement" (AD), kısa: "ad".'],
      ['campaign', 'kemPEYN', 'kampanya', '"a marketing campaign".'],
      ['target audience', 'TARgıt ODiyıns', 'hedef kitle', 'Pazarlamanın başladığı nokta.'],
      ['launch', 'LONÇ', 'piyasaya sürmek; lansman', '"launch a product".'],
      ['influence', 'INfluıns', 'etkilemek; etki', 'Influencer = etkileyici kişi.'],
      ['loyalty', 'LOYılti', 'sadakat', '"customer loyalty programme".'],
      ['trend', 'TREND', 'eğilim, trend', '"the latest trend".'],
      ['consume', 'kınSYUUM', 'tüketmek', 'Tüketici: "consumer".'],
      ['competitor', 'kımPETitır', 'rakip', '"a tough competitor".'],
    ],
    sentences: [
      ['The company decided to launch the product in spring.', 'Şirket ürünü ilkbaharda piyasaya sürmeye karar verdi.'],
      ['They are planning a campaign for young consumers.', 'Genç tüketiciler için bir kampanya planlıyorlar.'],
      ['Avoid copying your competitors directly.', 'Rakiplerini doğrudan kopyalamaktan kaçın.'],
      ['Social media influences buying decisions more than TV now.', 'Sosyal medya artık TV\'den daha çok satın alma kararlarını etkiliyor.'],
    ],
    sceneTitle: 'The Pitch Meeting',
    sceneContext: 'Bir pazarlama ekibi yeni kampanyayı sunuyor.',
    dialogue: [
      ['Anna', 'Our target audience is young professionals, so we suggest going digital.', 'AUR TARgıt ODiyıns İZ yang profEŞınılz, sou ui sıcJEST GOuing DİCıtil.', 'Hedef kitlemiz genç profesyoneller, bu yüzden dijitale geçmeyi öneriyoruz.'],
      ['Manager', 'Interesting. Which platforms are you considering?', 'INtıresting. VIÇ PLATformz AR yu kınSIDıring?', 'İlginç. Hangi platformları düşünüyorsunuz?'],
      ['Anna', 'Short videos. They influence trends faster than anything else.', 'ŞORT VIDiyoz. DEY INfluıns TRENDZ FAS-tır den ENiTING ELS.', 'Kısa videolar. Trendleri başka her şeyden daha hızlı etkiliyorlar.'],
      ['Manager', 'And when do you plan to launch the campaign?', 'End UEN du yu PLAN tu LONÇ di kemPEYN?', 'Peki kampanyayı ne zaman başlatmayı planlıyorsunuz?'],
      ['Anna', 'Before the holidays. We hope to beat our biggest competitor.', 'biFOR di HOLıdeyz. ui HOUP tu BIIT aur BIGist kımPETitır.', 'Tatillerden önce. En büyük rakibimizi geçmeyi umuyoruz.'],
    ],
  },
];
