import type { CheckpointStory, StoryLine, StoryNewWord } from './types';
import { isEnglish } from '../content/activeLanguage';
import { EN_STORIES, EN_STORY_CAST } from '../content/en/storyData';

export const STORY_UNITS_PER_CHECKPOINT = 10;

const RU_STORY_CAST = [
  { name: 'Maks', emoji: '👨‍🍳', desc: 'Voronej’den Moskova’ya gelen genç aşçı; yetenekli, aceleci ve Şef’e kendini kanıtlamaya kararlı.' },
  { name: 'Vika', emoji: '📋', desc: '«Клод Моне» restoranının sanat yönetmeni; düzenli, keskin zekâlı ve krizlerde soğukkanlı.' },
  { name: 'Şef Barinov', emoji: '🔥', desc: 'Mutfağın sert ve yaratıcı şefi Viktor Barinov; ekibini bağırarak da olsa korur.' },
  { name: 'Senya', emoji: '🥩', desc: 'Et bölümünün şakacı aşçısı; Fedya ile mutfaktaki her fırsatı küçük bir oyuna çevirir.' },
  { name: 'Fedya', emoji: '🐟', desc: 'Balık ustası; Senya’nın suç ortağı ve mutfak dedikodularının hızlı dağıtıcısı.' },
  { name: 'Nastya', emoji: '🌿', desc: 'İyi kalpli garson; ekibin vicdanı ve krizlerin sakinleştiricisi.' },
  { name: 'Kostya', emoji: '🍸', desc: 'Barmen; salondan mutfağa haber taşıyan, sakin ve güvenilir ekip arkadaşı.' },
] as const;

export const STORY_CAST: { name: string; emoji: string; desc: string }[] =
  isEnglish() ? EN_STORY_CAST : [...RU_STORY_CAST];

type Level = NonNullable<CheckpointStory['levelId']>;
type StorySpec = {
  id: string; kind: CheckpointStory['kind']; checkpoint: number | null;
  unitFrom: number; unitTo: number; levelId?: Level; nextLevelId?: Level;
  episode: string; titleTr: string; framing: string; icon: string; color: string;
  lines: StoryLine[]; words: StoryNewWord[];
  points: { text: string; hint: string; keys: string[][] }[];
};

const L = (speaker: string, ru: string, reading: string, tr: string, narrator = false): StoryLine =>
  ({ speaker, ru, reading, tr, ...(narrator ? { narrator: true } : {}) });
const W = (ru: string, reading: string, tr: string, note: string): StoryNewWord => ({ ru, reading, tr, note });

function story(s: StorySpec): CheckpointStory {
  return {
    id: s.id, kind: s.kind, checkpoint: s.checkpoint, unitFrom: s.unitFrom, unitTo: s.unitTo,
    ...(s.levelId ? { levelId: s.levelId } : {}), ...(s.nextLevelId ? { nextLevelId: s.nextLevelId } : {}),
    titleRu: s.episode, titleTr: s.titleTr,
    framingTr: `«Кухня» dizisinin ${s.framing} Bu metin, bölüm olayından dil öğrenimine uygun biçimde yeniden yazılmış kısa bir uyarlamadır; özgün dizi repliği değildir.`,
    icon: s.icon, color: s.color, paragraphs: s.lines, newWords: s.words,
    keyPoints: s.points.map((p, i) => ({ id: `${s.id}_k${i + 1}`, textTr: p.text, hintTr: p.hint, keywordGroups: p.keys })),
    misleading: [],
  };
}

const RU_STORIES: CheckpointStory[] = [
  story({ id:'story_lf_a1', kind:'levelFinal', checkpoint:null, unitFrom:1, unitTo:11, levelId:'A1', nextLevelId:'A2', episode:'Кухня — Серия 1: Первый день Макса', titleTr:'Kitchen — 1. Bölüm: Maks’ın İlk Günü', framing:'ilk bölümünden: Maks Moskova’ya gelir ve «Клод Моне» mutfağında ilk vardiyasına çıkmaya çalışır.', icon:'🚪', color:'#22c55e',
    lines:[
      L('Anlatıcı','Макс приехал в Москву и нашёл ресторан «Клод Моне».','Maks priyéhal v Maskvú i naşyól ristorán Klod Mané.','Maks Moskova’ya geldi ve Claude Monet restoranını buldu.',true),
      L('Maks','Здравствуйте. Меня зовут Макс. Я повар.','Zdrástvuyte. Minyá zavút Maks. Ya póvar.','Merhaba. Benim adım Maks. Ben aşçıyım.'),
      L('Vika','У нас строгий шеф. Вы готовы работать?','U nas strógiy şef. Vı gatóvı rabótat?','Bizim sert bir şefimiz var. Çalışmaya hazır mısınız?'),
      L('Şef Barinov','На моей кухне сначала слушают, потом готовят!','Na mayéy kúhne snaçála slúşayut, patóm gatóvyat!','Benim mutfağımda önce dinlenir, sonra yemek yapılır!'),
      L('Maks','Я готов. Дайте мне шанс.','Ya gatóf. Dáyti mnye şans.','Hazırım. Bana bir şans verin.'),
    ], words:[W('Шанс','Şans','Şans','дать шанс = şans vermek.'),W('Строгий','Strógiy','Sert / katı','строгий шеф = sert şef.'),W('Сначала','Snaçála','Önce','Sıralama anlatır.')],
    points:[{text:'Maks Moskova’ya gelir ve Claude Monet restoranını bulur.',hint:'Maks nereye geldi?',keys:[['maks'],['moskova','restoran']]},{text:'Şef mutfakta önce dinlemek, sonra yemek yapmak gerektiğini söyler.',hint:'Şefin ilk kuralı ne?',keys:[['önce','dinle'],['sonra','yemek','pişir']]},{text:'Maks çalışmaya hazır olduğunu söyleyip bir şans ister.',hint:'Maks ne istedi?',keys:[['hazır'],['şans']]}] }),

  story({ id:'story_cp1', kind:'checkpoint', checkpoint:1, unitFrom:1, unitTo:10, episode:'Кухня — Серия 2: Новенький на кухне', titleTr:'Kitchen — 2. Bölüm: Mutfaktaki Yeni Çocuk', framing:'ikinci bölüm çizgisinden: Maks ekiple tanışır, Senya ile Fedya da yeni aşçıyı küçük bir sınava sokar.', icon:'🔪', color:'#38bdf8',
    lines:[L('Senya','Новенький, где твой нож?','Nóvinkiy, gdye tvoy noj?','Yeni çocuk, bıçağın nerede?'),L('Maks','Вот нож. А где моё рабочее место?','Vot noj. A gdye mayó rabóçeye mésta?','İşte bıçak. Benim çalışma yerim nerede?'),L('Fedya','Рядом с овощами. Но сначала почисти эту гору лука.','Ryádam s óvaşşami. No snaçála paçísti étu góru lúka.','Sebzelerin yanında. Ama önce şu soğan dağını temizle.'),L('Maks','Это проверка?','Éta pravérka?','Bu bir sınav mı?'),L('Şef Barinov','Это кухня. Здесь каждый доказывает делом.','Éta kúhnya. Zdes kájdıy dakázıvayet délom.','Burası mutfak. Burada herkes kendini yaptığı işle kanıtlar.')],
    words:[W('Новенький','Nóvinkiy','Yeni gelen','Ekibe yeni katılan kişi.'),W('Проверка','Pravérka','Sınav / kontrol','Birini deneme.'),W('Доказывать','Dakázıvat','Kanıtlamak','доказывать делом = işle kanıtlamak.')],
    points:[{text:'Senya ve Fedya yeni gelen Maks’a çalışma yerini gösterip soğan temizletir.',hint:'Ekip Maks’a hangi işi verdi?',keys:[['senya','fedya','ekip'],['soğan','temizle']]},{text:'Maks bunun bir sınav olup olmadığını sorar.',hint:'Maks neyi merak etti?',keys:[['sınav','kontrol']]},{text:'Şef mutfakta herkesin kendini işiyle kanıtladığını söyler.',hint:'Şef ne dedi?',keys:[['iş'],['kanıt']]}] }),

  story({ id:'story_cp2', kind:'checkpoint', checkpoint:2, unitFrom:11, unitTo:20, episode:'Кухня — Серия 3: Проверка шефа', titleTr:'Kitchen — 3. Bölüm: Şefin Sınavı', framing:'üçüncü bölüm atmosferinden: Şef, Maks’ın tat ve hız duygusunu aynı anda ölçer.', icon:'⏱️', color:'#f97316',
    lines:[L('Şef Barinov','У тебя десять минут. Приготовь соус.','U tibyá désit minút. Prigatóf sus.','On dakikan var. Sos hazırla.'),L('Maks','Какой соус?','Kakóy sus?','Hangi sos?'),L('Şef Barinov','Хороший. Гость не будет ждать твои вопросы.','Haróşiy. Gost ni búdit jdat tvaí vaprósı.','İyi bir sos. Misafir senin sorularını beklemez.'),L('Nastya','Спокойно, Макс. Попробуй и исправь соль.','Spakóyna, Maks. Papróbuy i ispráf sol.','Sakin ol Maks. Tadına bak ve tuzu düzelt.'),L('Maks','Готово. Я успел.','Gatóva. Ya uspél.','Hazır. Yetiştim.')],
    words:[W('Успеть','Uspét','Yetişmek','Zamanında bitirmek.'),W('Исправить','İsprávit','Düzeltmek','Hatalı şeyi düzeltmek.'),W('Попробовать','Papróbavat','Tadına bakmak / denemek','Yemek için tadına bakmak.')],
    points:[{text:'Şef Maks’a on dakikada iyi bir sos hazırlama görevi verir.',hint:'Görev ve süre neydi?',keys:[['on','10'],['sos']]},{text:'Nastya Maks’a sakin olup tadına bakmasını ve tuzu düzeltmesini söyler.',hint:'Nastya nasıl yardım etti?',keys:[['nastya','sakin'],['tuz','düzelt','tad']]},{text:'Maks sosu zamanında tamamlar.',hint:'Maks yetişti mi?',keys:[['yetiş','hazır']]}] }),

  story({ id:'story_cp3', kind:'checkpoint', checkpoint:3, unitFrom:21, unitTo:30, episode:'Кухня — Серия 4: Перепутанный заказ', titleTr:'Kitchen — 4. Bölüm: Karışan Sipariş', framing:'dördüncü bölüm tarzından: salonla mutfak arasındaki tek yanlış masa numarası bütün servisi karıştırır.', icon:'🧾', color:'#eab308',
    lines:[L('Nastya','Стол пять заказал рыбу без соли.','Stol pyat zakazál rıbu bez sóli.','Beş numaralı masa tuzsuz balık sipariş etti.'),L('Fedya','Я приготовил рыбу для стола семь.','Ya prigatóvil rıbu dlya stalá sem.','Ben yedi numaralı masa için balık hazırladım.'),L('Maks','Подождите. Мы перепутали номера.','Pad ajdíti. Mı piripútali namirá.','Bekleyin. Numaraları karıştırdık.'),L('Vika','Не спорьте. Переделайте блюдо и извинитесь перед гостем.','Ni spórti. Piridélayti blyúda i izvinítis périt gó stem.','Tartışmayın. Yemeği yeniden yapın ve misafirden özür dileyin.'),L('Maks','Понял. Ошибку исправим сейчас.','Pónyal. Aşípku isprávim siçás.','Anladım. Hatayı şimdi düzelteceğiz.')],
    words:[W('Перепутать','Piripútat','Karıştırmak','İki şeyi yanlış eşleştirmek.'),W('Переделать','Piridélat','Yeniden yapmak','Yanlış işi baştan yapmak.'),W('Извиниться','İzvinítşa','Özür dilemek','перед гостем ile kullanılır.')],
    points:[{text:'Beş ve yedi numaralı masaların balık siparişleri karışır.',hint:'Hangi sipariş karıştı?',keys:[['beş','yedi'],['balık','sipariş']]},{text:'Vika tartışmak yerine yemeğin yeniden yapılmasını ister.',hint:'Vika’nın çözümü neydi?',keys:[['vika'],['yeniden','özür']]},{text:'Maks hatayı hemen düzelteceklerini söyler.',hint:'Maks ne söz verdi?',keys:[['hata'],['düzelt','hemen']]}] }),

  story({ id:'story_cp4', kind:'checkpoint', checkpoint:4, unitFrom:31, unitTo:40, episode:'Кухня — Серия 5: Банкетный вечер', titleTr:'Kitchen — 5. Bölüm: Banket Gecesi', framing:'beşinci bölüm çizgisinden: kalabalık bir davet, eksik sandalyeler ve mutfakta hız yarışı.', icon:'🥂', color:'#ec4899',
    lines:[L('Vika','Сегодня банкет на сорок человек. Всё должно быть идеально.','Sivódnya bankét na só rak çilavyék. Vsyo daljnó bıt idealna.','Bugün kırk kişilik banket var. Her şey kusursuz olmalı.'),L('Kostya','В зале не хватает двух стульев.','V zále ni hvatáyet dvuh stúlyev.','Salonda iki sandalye eksik.'),L('Nastya','Я найду стулья. Кухня готова?','Ya naydú stúlya. Kúhnya gatóva?','Sandalyeleri bulurum. Mutfak hazır mı?'),L('Şef Barinov','Кухня будет готова, если никто не паникует!','Kúhnya búdit gatóva, yesli niktó ni panikúyet!','Kimse paniğe kapılmazsa mutfak hazır olacak!'),L('Maks','Горячее готово. Можно подавать.','Garyáçeye gatóva. Mójna padavát.','Ana sıcak hazır. Servis edilebilir.')],
    words:[W('Банкет','Bankét','Banket / davet','Kalabalık resmî yemek.'),W('Не хватать','Ni hvatát','Eksik olmak','не хватает двух = iki tane eksik.'),W('Паниковать','Panikavát','Paniğe kapılmak','Kriz anında paniklemek.')],
    points:[{text:'Vika kırk kişilik banketin kusursuz olmasını ister.',hint:'Kaç kişilik davet var?',keys:[['kırk','40'],['banket','davet']]},{text:'Salonda iki sandalye eksiktir ve Nastya onları bulmayı üstlenir.',hint:'Ne eksikti?',keys:[['iki'],['sandalye','nastya']]},{text:'Maks sıcak yemeğin servise hazır olduğunu bildirir.',hint:'Servise ne hazırdı?',keys:[['sıcak','yemek'],['hazır','servis']]}] }),

  story({ id:'story_lf_a2', kind:'levelFinal', checkpoint:null, unitFrom:12, unitTo:61, levelId:'A2', nextLevelId:'B1', episode:'Кухня — Серия 6: Ужин для критика', titleTr:'Kitchen — 6. Bölüm: Eleştirmen İçin Akşam Yemeği', framing:'altıncı bölümden esinle: kimliğini gizleyen bir restoran eleştirmeni gelir ve ekip her masadan şüphelenir.', icon:'🕵️', color:'#06b6d4',
    lines:[L('Vika','Сегодня придёт ресторанный критик, но мы не знаем, кто он.','Sivódnya pridyót ristoránnıy krítik, no mı ni znáyem, kto on.','Bugün restoran eleştirmeni gelecek ama kim olduğunu bilmiyoruz.'),L('Senya','Может, это мужчина у окна?','Mójet, éta muşşína u akná?','Belki pencere kenarındaki adamdır?'),L('Fedya','Нет, критик не фотографирует суп десять раз.','Nyet, krítik ni fatagrafíruyet sup désit raz.','Hayır, eleştirmen çorbanın on kez fotoğrafını çekmez.'),L('Şef Barinov','Готовьте хорошо для каждого гостя. Тогда угадывать не придётся.','Gatóvti haraşó dlya kájdava góstya. Tagdá ugádıvat ni pridyótsa.','Her misafir için iyi yemek yapın. O zaman tahmin gerekmez.'),L('Maks','Понял: важен каждый стол.','Pónyal: vájin kájdıy stol.','Anladım: her masa önemlidir.')],
    words:[W('Критик','Krítik','Eleştirmen','Restoranı değerlendiren kişi.'),W('Угадывать','Ugádıvat','Tahmin etmek','Kim olduğunu tahmin etmek.'),W('Каждый','Kájdıy','Her / her biri','каждый гость = her misafir.')],
    points:[{text:'Kimliğini gizleyen bir restoran eleştirmeninin geleceği söylenir.',hint:'Restorana kim geliyor?',keys:[['eleştirmen','kritik'],['gizli','kimliği']]},{text:'Senya ile Fedya salondaki misafirleri tahmin etmeye çalışır.',hint:'Aşçılar ne yaptı?',keys:[['senya','fedya'],['tahmin']]},{text:'Şef her misafire iyi yemek yapılırsa eleştirmeni tahmin etmeye gerek kalmayacağını söyler.',hint:'Şefin dersi ne?',keys:[['her','misafir'],['iyi','yemek']]}] }),

  story({ id:'story_cp5', kind:'checkpoint', checkpoint:5, unitFrom:41, unitTo:50, episode:'Кухня — Серия 7: Секретный ингредиент', titleTr:'Kitchen — 7. Bölüm: Gizli Malzeme', framing:'yedinci bölüm havasından: Şef’in yeni sosundaki malzemeyi bulmaya çalışan ekip yanlış tahminlerde yarışır.', icon:'🫙', color:'#8b5cf6',
    lines:[L('Senya','В соусе есть мёд. Я уверен.','V súse yest myot. Ya uvéren.','Sosta bal var. Eminim.'),L('Fedya','Нет, это горчица.','Nyet, éta garçítsa.','Hayır, bu hardal.'),L('Maks','Сначала сладко, потом остро. Может быть, и мёд, и горчица.','Snaçála slátka, patóm óstra. Mójet bıt, i myot, i garçítsa.','Önce tatlı, sonra acı. Belki hem bal hem hardal.'),L('Şef Barinov','Наконец-то кто-то пробует, а не фантазирует.','Nakanéts-ta kto-ta próbuyet, a ni fantazíruyet.','Sonunda biri hayal kurmak yerine tadına bakıyor.'),L('Maks','Значит, я угадал?','Znáçit, ya ugadál?','Yani doğru mu bildim?')],
    words:[W('Ингредиент','İngr idiyént','Malzeme','Yemeğin bileşeni.'),W('Горчица','Garçítsa','Hardal','Acı sos malzemesi.'),W('Угадать','Ugadát','Doğru tahmin etmek','Sonucu bulmak.')],
    points:[{text:'Senya bal, Fedya ise hardal olduğunu tahmin eder.',hint:'İki tahmin neydi?',keys:[['bal'],['hardal']]},{text:'Maks sosun önce tatlı sonra acı olduğunu fark edip iki malzemeyi birleştirir.',hint:'Maks tadı nasıl çözdü?',keys:[['tatlı'],['acı','iki']]},{text:'Şef, Maks’ın hayal kurmak yerine sosu tattığını över.',hint:'Şef neyi beğendi?',keys:[['tadına','tat'],['maks']]}] }),

  story({ id:'story_cp6', kind:'checkpoint', checkpoint:6, unitFrom:51, unitTo:60, episode:'Кухня — Серия 8: Смена без шефа', titleTr:'Kitchen — 8. Bölüm: Şefsiz Vardiya', framing:'sekizinci bölüm çizgisinden: Barinov kısa süreliğine ayrılır ve mutfak sorumluluğu ekibin üzerinde kalır.', icon:'🧑‍🍳', color:'#14b8a6',
    lines:[L('Şef Barinov','Я уезжаю на два часа. Макс, следи за заказами.','Ya uyezjáyu na dva çasá. Maks, slidí za zakázami.','İki saatliğine gidiyorum. Maks, siparişleri takip et.'),L('Maks','Почему я?','Paçimú ya?','Neden ben?'),L('Vika','Потому что ответственность не спрашивает, готов ли ты.','Patamú şto atvétstvin nast ni spráşivayet, gatóf li tı.','Çünkü sorumluluk hazır olup olmadığını sormaz.'),L('Senya','Первый заказ уже опаздывает.','Pérvıy zakás u jé apázdıvayet.','İlk sipariş şimdiden gecikiyor.'),L('Maks','Работаем по станциям. Никто не кричит, все сообщают время.','Rabótayem pa stántsiyam. Niktó ni kriçít, vse saabşşáyut vrémya.','İstasyonlara göre çalışıyoruz. Kimse bağırmıyor, herkes süreyi bildiriyor.')],
    words:[W('Смена','Smyéna','Vardiya','Çalışma dönemi.'),W('Ответственность','Atvétstvin nast','Sorumluluk','Görevi üstlenme.'),W('Следить за','Slidít za','Takip etmek','Siparişleri izlemek.')],
    points:[{text:'Şef iki saatliğine ayrılır ve Maks’tan siparişleri takip etmesini ister.',hint:'Şef görevi kime verdi?',keys:[['maks'],['sipariş','iki saat']]},{text:'Vika sorumluluğun hazır olup olmadığını sormadığını söyler.',hint:'Vika’nın dersi ne?',keys:[['sorumluluk'],['hazır']]},{text:'Maks ekibi istasyonlara göre düzenleyip sürelerin bildirilmesini ister.',hint:'Maks vardiyayı nasıl düzenledi?',keys:[['istasyon'],['süre','zaman']]}] }),

  story({ id:'story_lf_b1', kind:'levelFinal', checkpoint:null, unitFrom:62, unitTo:126, levelId:'B1', nextLevelId:'B2', episode:'Кухня — Серия 9: Команда «Клод Моне»', titleTr:'Kitchen — 9. Bölüm: Claude Monet Ekibi', framing:'dokuzuncu bölümden uyarlama: mutfakla salon arasındaki suçlama, ancak ekip birlikte hareket edince çözülür.', icon:'🤝', color:'#f59e0b',
    lines:[L('Vika','Гость жалуется, что блюдо холодное.','Gost jáluyetsa, şto blyúda halódnaye.','Misafir yemeğin soğuk olduğundan şikâyet ediyor.'),L('Fedya','Рыба стояла на выдаче семь минут. Это проблема зала.','Rıba stayála na výdaçe sem minút. Éta prabléma zála.','Balık servis penceresinde yedi dakika bekledi. Bu salonun sorunu.'),L('Nastya','А стол ждал гарнир. Это проблема кухни.','A stol jdal garnír. Éta prabléma kúhni.','Masa garnitürü bekliyordu. Bu mutfağın sorunu.'),L('Maks','Это наша общая проблема. Подадим всё заново и одновременно.','Éta náşa óbşşaya prabléma. Padadím vsyo zánava i adnavrém enna.','Bu ortak sorunumuz. Her şeyi yeniden ve aynı anda servis edelim.'),L('Şef Barinov','Вот теперь вы говорите как команда.','Vot tipér vı gavaríti kak kamánda.','İşte şimdi ekip gibi konuşuyorsunuz.')],
    words:[W('Жаловаться','Jálavatşa','Şikâyet etmek','Misafirin sorun bildirmesi.'),W('Одновременно','Adnavrém enna','Aynı anda','Eş zamanlı servis.'),W('Общий','Óbşşiy','Ortak','общая проблема = ortak sorun.')],
    points:[{text:'Misafir soğuk yemek yüzünden şikâyet eder.',hint:'Şikâyet neydi?',keys:[['soğuk'],['şikayet']]},{text:'Mutfak ile salon önce birbirini suçlar.',hint:'Ekip ilk başta ne yaptı?',keys:[['mutfak','salon'],['suçla','sorun']]},{text:'Maks sorunu ortak kabul edip yemekleri yeniden aynı anda servis etmeyi önerir.',hint:'Maks’ın çözümü ne?',keys:[['ortak'],['yeniden','aynı anda']]}] }),

  story({ id:'story_cp7', kind:'checkpoint', checkpoint:7, unitFrom:61, unitTo:70, episode:'Кухня — Серия 10: Ревность и десерт', titleTr:'Kitchen — 10. Bölüm: Kıskançlık ve Tatlı', framing:'onuncu bölüm atmosferinden: Maks’ın Vika için hazırladığı tatlı mutfakta yanlış anlaşılmaya yol açar.', icon:'🍰', color:'#f472b6',
    lines:[L('Nastya','Макс, почему на тарелке написано «для Вики»?','Maks, paçimú na tarélke napísana dlya Víki?','Maks, tabakta neden “Vika için” yazıyor?'),L('Maks','Это просто новый десерт. Она должна оценить подачу.','Éta prósta nóvıy disért. Aná daljná atsinít padaçu.','Bu sadece yeni bir tatlı. Sunumu değerlendirmesi gerekiyor.'),L('Senya','Конечно. Чисто профессиональный шоколад.','Kanéşna. Çísta prafissianálnıy şakalát.','Tabii. Tamamen profesyonel çikolata.'),L('Vika','Если это работа, почему здесь сердце?','Yésli éta rabóta, paçimú zdes sérdtse?','Bu işse burada neden kalp var?'),L('Maks','Потому что... круг не получился.','Patamú şto... kruk ni paluçílsya.','Çünkü... daire olmadı.')],
    words:[W('Ревность','R évnast','Kıskançlık','Duygusal kıskançlık.'),W('Оценить','Atsinít','Değerlendirmek','Sunuma puan vermek.'),W('Получиться','Paluçítşa','Ortaya çıkmak / olmak','не получилось = olmadı.')],
    points:[{text:'Maks Vika için üzerinde yazı olan bir tatlı hazırlar.',hint:'Tatlı kimin içindi?',keys:[['maks'],['vika','tatlı']]},{text:'Senya bunun tamamen profesyonel olduğuyla alay eder.',hint:'Senya nasıl şaka yaptı?',keys:[['senya'],['profesyonel','çikolata']]},{text:'Vika kalp şeklini sorunca Maks daire yapamadığını söyler.',hint:'Maks kalbi nasıl açıkladı?',keys:[['kalp'],['daire','olmadı']]}] }),

  story({ id:'story_cp8', kind:'checkpoint', checkpoint:8, unitFrom:71, unitTo:80, episode:'Кухня — Серия 11: Большой заказ', titleTr:'Kitchen — 11. Bölüm: Büyük Sipariş', framing:'on birinci bölüm tarzından: son dakikada gelen büyük sipariş stok ve zaman yönetimini sınar.', icon:'📦', color:'#0ea5e9',
    lines:[L('Kostya','Заказ на двадцать порций. Через сорок минут.','Zakás na dvátsat pórtsiy. Çérez só rak minút.','Yirmi porsiyonluk sipariş. Kırk dakika içinde.'),L('Fedya','У нас не хватает рыбы.','U nas ni hvatáyet rıbı.','Yeterli balığımız yok.'),L('Maks','Заменим гарнир и предложим два блюда на выбор.','Zaménim garnír i pridlojím dva blyúda na výbar.','Garnitürü değiştirip iki yemek seçeneği sunalım.'),L('Vika','Сначала согласуйте замену с заказчиком.','Snaçála saglasúyti zaménu s zakázçikam.','Önce değişikliği müşteriyle onaylayın.'),L('Şef Barinov','План принят. Теперь работаем без суеты.','Plan prínyat. Tipér rabótayem bez suyetı.','Plan kabul. Şimdi telaş etmeden çalışıyoruz.')],
    words:[W('Порция','Pórtsiya','Porsiyon','Tek kişilik yemek miktarı.'),W('Согласовать','Saglasavát','Onaylatmak / uzlaştırmak','Müşteriyle değişikliği onaylamak.'),W('Суета','Suyetá','Telaş','Düzensiz acele.')],
    points:[{text:'Kırk dakikada yirmi porsiyon hazırlanması gerekir.',hint:'Sipariş ne kadar büyük?',keys:[['yirmi','20'],['kırk','40']]},{text:'Balık eksik olduğu için Maks alternatif yemekler önerir.',hint:'Eksik ürün ve çözüm neydi?',keys:[['balık','eksik'],['iki','seçenek']]},{text:'Vika değişikliğin önce müşteriyle onaylanmasını ister.',hint:'Kimden onay alınmalı?',keys:[['vika'],['müşteri','onay']]}] }),

  story({ id:'story_lf_b2', kind:'levelFinal', checkpoint:null, unitFrom:127, unitTo:181, levelId:'B2', nextLevelId:'C1/C2', episode:'Кухня — Серия 12: Выбор Вики', titleTr:'Kitchen — 12. Bölüm: Vika’nın Seçimi', framing:'on ikinci bölüm çizgisinden: Vika restoranın itibarıyla ekibin hatasını gizlememek arasında zor bir karar verir.', icon:'⚖️', color:'#ef4444',
    lines:[L('Vika','Поставщик привёз продукт без нужного сертификата.','Pastávşşik privyós pradúkt bez nújnava sirtifikáta.','Tedarikçi gerekli sertifikası olmayan ürün getirdi.'),L('Senya','Но продукт свежий. Если вернём, банкет сорвётся.','No pradúkt svéjiy. Yésli virnyóm, bankét sarvyótsa.','Ama ürün taze. İade edersek banket aksar.'),L('Maks','Свежесть не заменяет документ и безопасность.','Svéjest ni zaminyáyet dakumyént i bizapásnast.','Tazelik belge ve güvenliğin yerini tutmaz.'),L('Vika','Возвращаем поставку. Гостям скажем правду и изменим меню.','Vazvraşşáyem pastáfku. Gast yam skájem právdu i iz ménim menyú.','Teslimatı iade ediyoruz. Misafirlere gerçeği söyleyip menüyü değiştireceğiz.'),L('Şef Barinov','Репутация строится именно такими решениями.','R iputátsiya stróitsa íminna takími r işéniyami.','İtibar tam da böyle kararlarla kurulur.')],
    words:[W('Поставщик','Pastávşşik','Tedarikçi','Ürün sağlayan şirket/kişi.'),W('Безопасность','Bizapásnast','Güvenlik','Gıda güvenliği.'),W('Репутация','R iputátsiya','İtibar','Restoran hakkındaki güven.')],
    points:[{text:'Sertifikasız bir ürün teslim edilir.',hint:'Üründeki sorun neydi?',keys:[['sertifika','belge'],['ürün']]},{text:'Maks tazeliğin belge ve güvenliğin yerini tutmayacağını söyler.',hint:'Maks hangi ilkeyi savundu?',keys:[['taze','tazelik'],['güvenlik','belge']]},{text:'Vika teslimatı iade edip menüyü değiştirmeye karar verir.',hint:'Vika ne seçti?',keys:[['iade'],['menü','değiştir','gerçek']]}] }),

  story({ id:'story_lf_c1', kind:'levelFinal', checkpoint:null, unitFrom:182, unitTo:200, levelId:'C1/C2', nextLevelId:'C1/C2', episode:'Кухня — Серия 13: Последний столик сезона', titleTr:'Kitchen — 13. Bölüm: Sezonun Son Masası', framing:'on üçüncü bölümden esinlenen ileri final: zor bir vardiyanın ardından ekip meslek, güven ve birlikte büyümeyi değerlendirir.', icon:'🌙', color:'#a855f7',
    lines:[L('Anlatıcı','После закрытия остался один столик и уставшая команда.','Pósle zakr ıtiya astálsya adín stólik i ustávşaya kamánda.','Kapanıştan sonra bir masa ve yorgun ekip kaldı.',true),L('Maks','Когда я пришёл, я хотел доказать, что уже всё умею.','Kagdá ya prişyól, ya hatél dakazát, şto u jé vsyo uméyu.','Geldiğimde her şeyi bildiğimi kanıtlamak istiyordum.'),L('Vika','А теперь?','A tipér?','Peki şimdi?'),L('Maks','Теперь я знаю: профессионал — не тот, кто не ошибается, а тот, кто отвечает за ошибку.','Tipér ya znáyu: prafissianál — ni tot, kto ni aşibáyetsa, a tot, kto atviçáyet za aşípku.','Şimdi biliyorum: profesyonel hata yapmayan değil, hatasının sorumluluğunu alan kişidir.'),L('Şef Barinov','Неплохо. Завтра докажешь это снова — смена начинается в семь.','Niplóha. Záftra dakájeş éta snóva — smyéna naçináyetsa v sem.','Fena değil. Yarın bunu yeniden kanıtlarsın; vardiya yedide başlıyor.'),L('Anlatıcı','На кухне не бывает окончательных финалов: после каждого ужина приходит новый заказ.','Na kúhne ni bıváyet akançátelnıh finálav: pósle kájdava újina prihódit nóvıy zakás.','Mutfakta kesin finaller yoktur: her akşam yemeğinden sonra yeni bir sipariş gelir.',true)],
    words:[W('Отвечать за','Atviçát za','Sorumluluğunu almak','Bir sonucun sorumluluğunu üstlenmek.'),W('Окончательный','Akançátelnıy','Kesin / nihai','Geri dönüşsüz son.'),W('Профессионал','Prafissianál','Profesyonel','İşini sorumlulukla yapan kişi.')],
    points:[{text:'Maks ilk geldiğinde her şeyi bildiğini kanıtlamak istediğini söyler.',hint:'Maks başlangıçta ne düşünüyordu?',keys:[['maks'],['her şeyi','kanıt']]},{text:'Artık profesyonelliği hata yapmamak değil, hatanın sorumluluğunu almak olarak tanımlar.',hint:'Maks’ın profesyonellik tanımı ne?',keys:[['profesyonel'],['hata','sorumluluk']]},{text:'Şef ertesi gün vardiyanın yedide başladığını hatırlatarak hayatın devam ettiğini gösterir.',hint:'Şef finalde ne dedi?',keys:[['yarın'],['vardiya','yedi']]},{text:'Son mesaj, mutfakta her yemeğin ardından yeni sipariş geldiği için kesin final olmadığıdır.',hint:'Hikâyenin son fikri ne?',keys:[['final','son'],['yeni','sipariş']]}] }),
];

export const STORIES: CheckpointStory[] = isEnglish() ? EN_STORIES : RU_STORIES;
export const STORY_CHECKPOINT_COUNT = STORIES.length;
